### ISSUE TITLE
Improve documentation: Datalogger only

### ISSUE THREAD

**Issue by denniswo** [dsmrreader/dsmr-reader#1002]
If my understanding is correct, I believe the following changes would improve the installation instructions for the _datalogger only_ combined with a _fully installed_ instance of DSMR-reader.

1) On the _datalogger only_ installation:
The installation instruction:
`sudo sh -c 'echo "cd ~/dsmr-reader" >> /home/dsmr/.bashrc'`
appears unnecessary, because this directory is never created. It results is a (harmless) error.

2) On the _fully installed_ installation:
I believe the installation instruction:
`sudo cp /home/dsmr/dsmr-reader/dsmrreader/provisioning/supervisor/dsmr_datalogger.conf /etc/supervisor/conf.d/`
should be omitted, because this instance will not do any data logging.
(In my case the VM I installed it in didn´t even have a USB port, so supervisor kept trying to start this task in vain.)

Background:
I was already forwarding my telegrams from a RPi3 installation to a home server, but the RPi3 installation was a fully installed instance.
As part of my recent upgrade from DSMR-reader v2 to v3, I made the RPi installation a _datalogger only_ instance. I even downgraded the RPi3 to a RPi1 and this is indeed enough to keep up with the data stream from a DSMR 5.0.
This is working very well. Thanks. Big fan.

**Comment by dennissiemensma** [comment]
Thanks, I've clarified the docs in the next release.
