### ISSUE TITLE
Raspberry Pi met SSD

### ISSUE THREAD

**Issue by 87brybry** [dsmrreader/dsmr-reader#1005]
Hoi Dennis, allereerst bedankt voor de heldere uitleg! Binnen no time had ik de basisinstallatie draaiend. 

Ik las het onderdeel over [data-integriteit](https://dsmr-reader.readthedocs.io/en/v3/data_integrity.html). Ik ben helaas ook al eens tegen kapotte SD-kaartjes aan gelopen, maar gelukkig heeft het nog nooit voor echte problemen gezorgd (afkloppen). Toen ik een aantal maanden geleden uit nieuwsgierigheid rond ging zoeken of ik mijn Home Assistant niet op een SSD kon zetten, om het systeem iets sneller te laten werken, ontdekte ik dat SD-kaartjes eigenlijk waardeloos zijn voor dit soort intensief gebruik. 

Nou, lang verhaal kort en wellicht weet je het al, maar je kunt de boel op een Raspberry Pi (grotendeels) op een SSD laten draaien. Voor zover ik begrijp kan het alleen bij een Pi 4 nog niet 100% omdat de USB-controller niet direct aanspreekbaar is, dus de Pi is de eerste twee seconden afhankelijk van een verwijzing op de SD-kaart. Maar dat bespaart in ieder geval een hoop lees- en schrijfbewerkingen op die SD-kaart en het levert ook nog eens een behoorlijke snelheidswinst op; een beetje SSD haalt rustig de 500 MB/s, waar ik een SD-kaartje niet veel sneller van 90 MB/s heb kunnen krijgen. 

Is het ingewikkeld? Nee. Ja. Soms. De meeste uitleg die ik eerder dit jaar kon vinden ging over het aanmaken van nieuwe partities binnen linux en het maken van mounts en dergelijke. Prima voor de ervaren Linux-guru, maar dat ben ik allerminst. 
De volgende manier is een stuk eenvoudiger en werkt al maanden goed op mijn HomeAssistant-installatie op Ubuntu Server. Het is me toen ook gelukt om op deze manier Ubuntu desktop en Raspbian werkend te krijgen. En ook deze DSMR-reader gaat op een zelfde setup draaien. 

1. Download de gewenste image (Ubuntu, Raspbian etc.) en schrijf deze naar het SD-kaartje. 
2. Kloon de hele inhoud van het SD-kaartje naar een lege SSD. Ik gebruik hiervoor een betaalde versie van AOMEI Partition Assitant, maar er zouden ook gratis programma's moeten zijn die dat kunnen.  
3. Verwijder de tweede (achterste) partitie van het SD-kaartje. Dit kan gewoon met Windows schijfbeheer. Binnen Windows is er één leesbare FAT-partitie en en een onleesbare partitie (Ext4). Verwijder die laatste. 

Als in de btcmd.txt iets staat als 'root=LABEL=writable', dan werkt het waarschijnlijk wel. Bij het opstarten kiest de Raspberry voor een partitie met de naam 'writable' (vandaar dat je die andere weg moet gooien). Wordt in dat bestand verwezen naar een PARTUID, dan wordt het een meer ingewikkeld verhaal, maar ook daar zijn oplossingen voor. 

Deze methode gaat uit van een schone installatie; bij de eerste start zullen partities aangemaakt en aangepast worden en de installatie van het OS worden uitgevoerd. Redelijk safe allemaal. 
Ook bestaande installaties kunnen op een soortgelijke manier overgezet worden, maar dat vereist wat meer werk. 

Ik gebruik bij deze twee installaties de ICY BOX IB-248WP-C31 USB-3 case, verkrijgbaar bij o.a. Alternate voor €35,-. De installatie die ik net heb uitgevoerd draait op een Crucial BX500 SSD (slechts €26,-), maar ik denk dat iedere schijf wel zou moeten werken. 

Ik hoop dat het een waardige aanvulling kan zijn aan je uitleg. Nogmaals bedankt voor je DSMR-oplossing. Ik ga verder met de installatie zodra mijn P1-kabel binnen is. 

Groeten, 
Bryan

**Comment by dennissiemensma** [comment]
Bedankt voor je uitleg. Je zou overigens ook nog kunnen kijken naar dit: https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md

Daarmee kun je op sommige Pi's permanent booten zonder SD-kaart, maar ik heb daar zelf geen ervaring mee en er staan ook wat waarschuwingen van de foundation zelf bij. 
Bovenin de pagina staat er verder dat er voor de Pi 4 firmware uitkomt met ingebouwde ondersteuning daarvoor.

En deze kwam van de week voorbij: https://www.tomshardware.com/how-to/boot-raspberry-pi-4-usb
