### ISSUE TITLE
Problemen met sleepknoppen / scrollbalk / controller

### ISSUE THREAD

**Issue by squadramunter** [dsmrreader/dsmr-reader#1017]
- DSMR-reader versie:   v3.10
- Type RaspberryPi or server:   Raspberry Pi
- Standaardinstallatie of Docker:   Standaardinstallatie
- DSMR-protocol slimme meter v4/v5:   Versie 4

---

Allereerst wil ik zeggen dat dit een geweldige toepassing is waardoor ik mijn meterstanden erg goed kan uitlezen. Echter loop ik steeds tegen een vervelend iets aan. Als ik op mijn mobiel zit merk ik dat scrollbalk / controller niet erg fijn reageert. Je moet heel veel moeite doen wil je de balk groter of kleiner kunnen maken. Had graag gezien dat er voor tablets / telefoons of in het algemeen grotere sleep knoppen waren. Zodat ze makkelijk te verplaatsen zijn.

**Comment by dennissiemensma** [comment]
Bedankt voor je input. Weet je toevallig hoe groot je scherm is of wat voor device je gebruikt? 

Ik kan je uiteraard niet beloven dat ik het voor iedereen op alle devices goed werkend kan krijgen, want ik ben immers geen designer/frontender. Maar ik kan zeker even kijken of ik het kan emuleren in mn browser voor een vergelijkbare schermgrootte.

**Comment by dennissiemensma** [comment]
Daarnaast kun je nog even proberen te spelen met de instellingen voor de standaardzoom + de tijdsspanne die initieel getoond wordt. 

Je kunt dit instellen in de admin op `/admin/dsmr_frontend/frontendsettings/` met de bovenste twee widgets onder het kopje 'grafieken'. Wellicht biedt dat nog een verbetering voor je.

**Comment by squadramunter** [comment]
Ha bedankt voor je snelle reactie. 

Ik gebruik momenteel een Samsung Galaxy s9+

2960 x 1440 pixels (Quad HD+)

Ik zal uw tip even uitproberen

**Comment by squadramunter** [comment]
Is die zoom alleen van toepassing op de grafiek of ook voor de balk eronder?

**Comment by dennissiemensma** [comment]
Alleen voor de data in de grafiek, dus dat lost niet je probleem op qua balk, maar wellicht vermindert het de behoefte om te scrollen zodat je er minder tegenaan loopt. 
Zie het dus niet als een oplossing, maar als iets dat simpelweg kan helpen in de tijdsspanne die je het meeste wilt zien.

**Comment by squadramunter** [comment]
Ik heb even lopen spelen met die standaardzoom maar ben erachter gekomen dat het gasverbruik niet mee schaald net als het weer wat eronder staat. Die blijven hetzelfde.

**Comment by dennissiemensma** [comment]
Ik heb nog even voor je gezocht, maar de grafiekentool die ik gebruik lijkt helaas geen optie te hebben voor een grotere scrollbar.

Heb je toevallig ook nog geprobeerd om te zoomen met twee vingers (bijvoorbeeld duim en wijsvinger) op de grafiek zelf? 
Daarnaast kun je ook nog eens sliden (mits ingezoomed) door een vinger op de grafiek te houden en deze naar links en rechts te slepen. 

Bij mij werkt dat laatste zowel in Chrome als Firefox, maar wel het beste in Chrome.
