### ISSUE TITLE
Bij tariefberekening ook vaste dagkosten meenemen

### ISSUE THREAD

**Issue by ridderr** [dsmrreader/dsmr-reader#1020]
Mijn leverancier hanteert naast een kwh tarief ook een dagtarief. Het zou mooi zijn als dit ook ingesteld kan worden en meegenomen in de kosten berekening.

**Comment by dennissiemensma** [comment]
Bedankt voor je suggestie. Het simuleren van alle kosten van leveranciers is een expertise op zichzelf en houd ik bewust buiten het project: https://github.com/dennissiemensma/dsmr-reader/issues/617#issuecomment-632016022
