### ISSUE TITLE
Dag en uur statistieken worden niet meer berekend na meterwissel 

### ISSUE THREAD

**Issue by n9iels** [dsmrreader/dsmr-reader#1026]
Mogge!

Ik heb gisteren helaas een nieuwe meter gekregen van Stedin (het oude ding deed alles prima maar stuurde enkel geen gegevens meer op naar de beheerder...). Echter is deze nieuwe meter niet echt "nieuw", als in: de meterstanden zijn niet 0.

Deze ochtend was ik van plan om de dag/uur statistieken te repareren, echter blijken deze sinds de meterwissel niet meer gegenereerd te worden. Ik krijg wel netjes alle telegrammen binnen (zie onderstaand voor meest recente) en deze zijn zichtbaar op het dashboard.

Na wat zoekwerk kwam ik uit op #742 en volgens mij heb ik hetzelfde probleem. De laatste telegram geeft een foutieve datum aan voor de gasmeter, namelijk `Jan. 1, 1970, 1 a.m.`. In de `/var/log/supervisor/dsmr_backend.log` kom ik ook de volgende notitie tegen:
```
[2020-06-18 08:56:17,595] DEBUG    SP: Running "Generate day and hour statistics" (dsmr_stats.services.run)
[2020-06-18 08:56:17,639] DEBUG    Stats: Waiting for first gas reading on the next day...
[2020-06-18 08:56:17,642] DEBUG    SP: Rescheduled "Generate day and hour statistics" to 2020-06-18 09:01:17.640404+02:00 (ETA 0:04:59.998097)
```
Wat is de beste manier om dit op te lossen? Gewoon bij elk telegram de datum van de gaslezing aanpassen naar de datum van de telegram zelf, en hopen dat dit gefixed wordt? Nu is het uitlezen van gas niet zo heel belangrijk voor mij, maar de electra zou ik toch wel graag weer werkend hebben.

---

Wat gebruik je?
- DSMR-reader versie:  3.10
- Type RaspberryPi or server: Ubuntu 18.04
- Standaardinstallatie of Docker: Docker, telegrammen komen via een remote datalogger binnen
- DSMR-protocol slimme meter: V5

**Laatste telegram**
```
/ISK5\2M550T-1011

1-3:0.2.8(50)
0-0:1.0.0(---)
0-0:96.1.1(-----)
1-0:1.8.1(003670.567*kWh)
1-0:1.8.2(003607.663*kWh)
1-0:2.8.1(000000.106*kWh)
1-0:2.8.2(000016.246*kWh)
0-0:96.14.0(0002)
1-0:1.7.0(00.089*kW)
1-0:2.7.0(00.000*kW)
0-0:96.7.21(00008)
0-0:96.7.9(00002)
1-0:99.97.0()
1-0:32.32.0(00001)
1-0:52.32.0(00000)
1-0:72.32.0(00000)
1-0:32.36.0(00001)
1-0:52.36.0(00001)
1-0:72.36.0(00001)
0-0:96.13.0()
1-0:32.7.0(233.6*V)
1-0:52.7.0(231.9*V)
1-0:72.7.0(234.1*V)
1-0:31.7.0(000*A)
1-0:51.7.0(000*A)
1-0:71.7.0(000*A)
1-0:21.7.0(00.000*kW)
1-0:41.7.0(00.059*kW)
1-0:61.7.0(00.000*kW)
1-0:22.7.0(00.193*kW)
1-0:42.7.0(00.017*kW)
1-0:62.7.0(00.000*kW)
0-1:24.1.0(003)
0-1:96.1.0()
0-1:24.2.1(700101010000W)(00000000)
0-2:24.1.0(003)
0-2:96.1.0()
0-2:24.2.1(700101010000W)(00000000)
!C693
```

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Het lijkt in dit geval ook deels op #818. 

Ik heb daar in 26b8f37bec97cd09efb7d80cf978992a611ed28a een fix gemaakt die ervoor zorgt dat dit probleem zichzelf 24 uur na gebrek aan verdere gasmetingen moet oplossen. Alleen weet ik dus niet of dat helemaal hetzelfde voor jou is.

Denk je dat er inmiddels al 24 uur voorbij zijn?

**Comment by n9iels** [comment]
Ja we zijn inmiddels 24 uur verder, laatste gasmeting was om `June 17, 2020, 9:55 a.m.`

Probleem hier is wellicht dat ik wel gasmetingen door krijg maar de datum compleet fout is? Krijg het idee dat ie daarom eeuwig wacht op "de volgende dag"

Overigens zie ik wel dat de gasmeter gekoppeld is met de slimme meter, alleen geven ze nog geen data door. Vermoedelijk moet de netbeheerder hier nog wat stappen nemen.

**Comment by dennissiemensma** [comment]
Wellicht kun je dan nog even checken wat de melding nu in de logs is. Of het is iets anders, of die fix waar ik naar verwees werkt niet (goed).

Je kunt ook nog even kijken naar de meest recente gasmetingen op basis van ID ipv tijd. Ik weet niet uit mn hoofd of hij die gasmetingen simpelweg overslaat als er teveel tijd tussen 'nu' en de betreffende datum uit de meter zit.

```
sudo su - postgres
psql dsmrreader

select read_at from dsmr_consumption_gasconsumption order by id desc limit 10;
```

**Comment by n9iels** [comment]
De logs geeft nog steeds dezelfde melding (`Stats: Waiting for first gas reading on the next day...`). De laatste 10 recente metingen die zijn opgeslagen zijn van 24 uur terug, dit is de output:

```
 2020-06-17 09:55:04+02
 2020-06-17 09:50:09+02
 2020-06-17 09:45:02+02
 2020-06-17 09:40:05+02
 2020-06-17 09:35:06+02
 2020-06-17 09:30:09+02
 2020-06-17 09:25:02+02
 2020-06-17 09:20:01+02
 2020-06-17 09:15:04+02
 2020-06-17 09:10:04+02
```

Kan het kwaad om in de `dsmr_datalogger_dsmrreading` tabel bij alle rijen die nu een foutieve `extra_device_timestamp` hebben deze gelijk te zetten aan de `timestamp`? Dus enkel waar nu de waarde `1970-01-01 01:00:00+01` is.

**Comment by dennissiemensma** [comment]
Ik zou die afwijkende records voor nu laten voor wat ze zijn, want ze zijn vermoedelijk al verwerkt in de `dsmr_consumption_*` tabel(len).

Wat betreft de dagstatistieken, ik denk dat de eerdere fix niet helemaal goed werkt. Je kunt nog proberen om handmatig de dag van gisteren in te vullen in: `/admin/dsmr_stats/daystatistics/add/`. Mogelijk gaat die daarna wel verder. Ter referentie kun je een dag uit `/admin/dsmr_stats/daystatistics/` bekijken.

Als alternatief kun je wachten op een nieuwe fix, maar dat kan zo een paar dagen of een week duren.

**Comment by n9iels** [comment]
Ik heb dit nu tijdelijk opgelost door in de `dsmr_consumption_gasconsumption` tabel voor elke dag 1 record toe te voegen.

```sql
INSERT INTO dsmr_consumption_gasconsumption (read_at, delivered, currently_delivered) VALUES ('2020-06-19 00:00:01+02', 730.459, 0.000);
```
Dit zorgt ervoor dat de  uur en dag statistieken in ieder geval weer berekend worden omdat de vorige dag is afgesloten :smile:

**Comment by dennissiemensma** [comment]
Je zou kunnen kijken of dat nu nog steeds nodig is voor komende dagen. Ik denk dat die fix niet goed werkt wanneer het midden op de dag gebeurde zonder dagafsluiting.

**Comment by dennissiemensma** [comment]
Heb je inmiddels kunnen proberen of het nog steeds werkt als je niet meer handmatig die gasmeting aanmaakt?

**Comment by n9iels** [comment]
Helaas niet. De volgende dag deed de gasmeter het weer volledig en kreeg ik weer de juiste standen door. Sinds dien geen problemen meer gehad :smile:

**Comment by dennissiemensma** [comment]
Oke bedankt voor je terugkoppeling! In dat geval laat ik het verder voor wat het is. : ]
