### ISSUE TITLE
dsmr_webinterface FATAL Exited too quickly (process log may have details)

### ISSUE THREAD

**Issue by bvansluis** [dsmrreader/dsmr-reader#1031]
I had a short power outage last night and now the web interface isn't working any more. When I run the command sudo supervisorctl status I get the error: 
dsmr_webinterface FATAL Exited too quickly (process log may have details)

What can I do to resolve this error? I have tried the following:
- Restart the services
- Reboot the Raspberry
- Upgrade DSMR to the latest version

I'm not able to access the log files, because I always get an access denied error. With the DSMR user as well as with my own admin user.

**Comment by dennissiemensma** [comment]
Thanks for reporting. You should be able to access the logfiles since you've also installed DSMR-reader and since you're able to run `sudo supervisorctl status`.

Try `sudo -s` when logged in as `pi` user on your Pi to become super user. Or simply add `sudo` to the command you're executing to view the logfiles.

**Comment by bvansluis** [comment]
Not sure what I'm doing wrong or what is wrong with my instance, but I keep getting the access denied error:
![image](https://user-images.githubusercontent.com/46501529/85527697-64c8d400-b60b-11ea-9a19-3f14d77e0d8b.png)
I use this command to open the log files. Is that correct? 

`/var/log/supervisor/dsmr_webinterface.log`

**Comment by dennissiemensma** [comment]
You should prefix the commands with `sudo` (when you're the `pi` user) to indicated superuser privileges. Or type `sudo -s` once to switch to `root` user.

Also, you will need to specify the command for viewing the logfiles. You can use any command line text editor (e.g.: `view`) or use `tail` or `cat`. See https://www.faqforge.com/linux/distributions/debian/linux-how-to-view-log-files-on-the-shell/

**Comment by bvansluis** [comment]
Great, got it! I get this error from the log file: 
Error: Already running on PID 476 (or pid file '/var/tmp/gunicorn--dsmr_webinterface.pid' is stale)

**Comment by dennissiemensma** [comment]
You can check whether the process is still up with:

```
sudo ps faux | grep 476 | grep -v grep
```

If it states something similar (make sure it's not another proces!):
```
dsmr     476  0.0  0.8  24532 16580 ?        S    Jun22   0:23  \_ /home/dsmr/.virtualenvs/dsmrreader/bin/python3 /home/dsmr/.virtualenvs/dsmrreader/bin/gunicorn --timeout 60 --max-requests 500 --bind unix:/var/tmp/gunicorn--dsmr_webinterface.socket --pid /var/tmp/gunicorn--dsmr_webinterface.pid dsmrreader.wsgi
```

If there was no output or it looks like a non-DSMR-reader process, let it be and do **NOT** kill it. You can kill it with:
```
sudo kill -9 476
```



Finally, remove the PID file
```
sudo rm /var/tmp/gunicorn--dsmr_webinterface.pid
```

And try again.

**Comment by bvansluis** [comment]
I get this result after running `sudo ps faux | grep 476 | grep -v grep`

```
root       465  0.1  0.9  22476  9440 ?        Ss   Jun21   4:33 /usr/bin/python2 /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
www-data   476  0.0  0.1  50324  1328 ?        S    Jun21   0:00  \_ nginx: worker process
postgres  7996  1.6  2.0 205664 19476 ?        Ss   12:03   0:01  \_ postgres: 11/main: dsmrreader dsmrreader ::1(48544) idle
```
So I guess I don't kill the process but just remove the PID file and restart the services?

**Comment by dennissiemensma** [comment]
Yeah try the latter.

**Comment by bvansluis** [comment]
Yes! Back online. Thanks a lot Dennis for all the support!

**Comment by dennissiemensma** [comment]
Fijn om te horen!

**Comment by bennybubble** [comment]
Dennis,

Helaas heb ik mijn systeem opnieuw moeten installeren (heb nog wel een database backup) maar ben nu ook op hetzelfde punt aangekomen : 

> pi@piDSMR2:~ $ **sudo supervisorctl status**
dsmr_backend                     RUNNING   pid 1036, uptime 0:04:03
dsmr_datalogger                  RUNNING   pid 1037, uptime 0:04:03
dsmr_webinterface                FATAL     Exited too quickly (process log may have details)

Inhoud logfile:

> pi@piDSMR2:~ $ **tail /var/log/supervisor/dsmr_webinterface.log**
Traceback (most recent call last):
  File "/home/dsmr/dsmr-reader/.venv/bin/gunicorn", line 5, in <module>
    from gunicorn.app.wsgiapp import run
  File "/home/dsmr/dsmr-reader/.venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "/home/dsmr/dsmr-reader/.venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 11, in <module>
    from gunicorn import util
  File "/home/dsmr/dsmr-reader/.venv/lib/python3.13/site-packages/gunicorn/util.py", line 25, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

> pi@piDSMR2:~ $ **lsb_release -a**
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 13 (trixie)
Release:        13
Codename:       trixie
pi@piDSMR2:~ $ **uname -a**
Linux piDSMR2 6.12.62+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.12.62-1+rpt1 (2025-12-18) aarch64 GNU/Linux

Installatie volgens **https://dsmr-reader.readthedocs.io/en/v5/tutorial/installation/step-by-step.html**

**Enig idee wat er hier aan de hand zou kunnen zijn?**

gr. Ben

**Comment by dennissiemensma** [comment]
Ik denk dat DSMR-reader v5 te oud is voor de native installatie op Python 3.13. Je kunt *naast* je huidige herinstallatie proberen of je de container-variant werkend krijgt, dat scheelt je uiteindelijk ook een hoop gedoe als het eenmaal draait. Gebruik dan wel :latest ( = nog v5) ipv :development (= v6). https://dsmr-reader.readthedocs.io/en/development/how-to/upgrade/to-v6/

**Comment by bennybubble** [comment]
Dennis,

Bedankt voor je advies, inmiddels de container variant onder Proxmox werkend gekregen en zowaar de data kunnen importeren.
Uiteindelijk maar 6 dagen data kwijt.

-ben

**Comment by dennissiemensma** [comment]
Fijn om te horen!

**Comment by dennissiemensma** [comment]
Inmiddels is v6 ook beschikbaar als versie in de container. Als je `:6` gebruikt ipv `:development` dan zit je later goed.

**Comment by bennybubble** [comment]
Bedankt voor de update, ik laat het eerst even draaien onder V5.12 en kijk of alles goed blijft werken.

**Comment by dennissiemensma** [comment]
Pas in dat geval je tag aan naar `:5`, want `:latest` wijst nu naar v6

**Comment by bennybubble** [comment]
Zal ik doen, bedankt voor de tip!
