### ISSUE TITLE
Kan niet inloggen op dashboard

### ISSUE THREAD

**Issue by MRL-33** [dsmrreader/dsmr-reader#1032]
Ik typ in: http://<MIJN-IP-ADRES>:7777 maar vind de pagina niet.
Ik heb op mijn RP3B+ (Raspbian Buster) PostgreSQL & DSMR Reader (ingelogd als user: pi) als container in Docker gedaan met:
docker pull postgres
docker run --restart=always --name dsmrdb -e POSTGRES_PASSWORD=XXXX -d postgres
sudo usermod -aG dialout $(whoami)
docker pull xirixiz/dsmr-reader-docker
docker run -d \
  --name dsmr \
  --restart always \
  -p 7777:80 \
  -e DB_HOST=dsmrdb \
  -e DSMR_USER=dsmrreader \
  -e DSMR_PASSWORD=dsmrreader \
  -e DSMR_EMAIL=root@localhost \
  --device /dev/ttyUSB0:/dev/ttyUSB0 \
  xirixiz/dsmr-reader-docker

Bron: https://hub.docker.com/r/xirixiz/dsmr-reader-docker/
Beide containers lopen.
Wat doe ik fout of mis ik nog iets?

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Ik denk dat je dit issue het beste kan aanmaken in het Docker-project: https://github.com/xirixiz/dsmr-reader-docker/issues

Inhoudelijk kan ik je namelijk niet helpen qua Docker-setup.
