### ISSUE TITLE
Migrate settings.py to env vars

### ISSUE THREAD

**Issue by dennissiemensma** [dsmrreader/dsmr-reader#1035]
I found a neat little library for this: https://pypi.org/project/python-decouple/

Seems to work perfectly, allowing me to drop duplicate setting files, the inclusion hell and support env vars by default.

**Comment by dennissiemensma** [comment]
It was quite a ride, but I think it's solid now.

**Comment by LarsVenema95** [comment]
@dennissiemensma I follow the guide and run "cp dsmrreader/provisioning/django/postgresql.py dsmrreader/settings.py" this command, The command line states that the files are missing. However, those two files are not available on the current [repo](https://github.com/dennissiemensma/dsmr-reader/tree/v4/dsmrreader/provisioning/django)?

On the [older repo](https://github.com/dennissiemensma/dsmr-reader/tree/v3/dsmrreader/provisioning/django) postgresql.py is available. Am I doing anything wrong?

**Comment by dennissiemensma** [comment]
@LarsVenema95 I'm not sure what guide you are following. I cannot find a reference to the file in the v4 branch.

These should suffice:
- Upgrading from v3 to v4: https://dsmr-reader.readthedocs.io/en/v4/faq/v4_upgrade.html
- Installing v4 (quick): https://dsmr-reader.readthedocs.io/en/v4/installation/quick.html
- Installing v4 (explained): https://dsmr-reader.readthedocs.io/en/v4/installation/explained.html

**Comment by LarsVenema95** [comment]
@dennissiemensma 
I was following the /latest/ guide: https://dsmr-reader.readthedocs.io/en/latest/installation/explained.html

I will try the v4 guide. That one will probably work. I let you know! :)

**Comment by dennissiemensma** [comment]
@LarsVenema95 thanks for the heads up. For some reason I had to force ReadTheDocs to rebuild 'latest', even though it already pointed to v4. It's updated now.
