### ISSUE TITLE
Totale kosten 

### ISSUE THREAD

**Issue by Webserve** [dsmrreader/dsmr-reader#1042]
Idee: 

Totale kosten tonen bij de contractprijzen. Dus ook het vast recht en eventuele kortingen / belasting korting. 
Hierdoor komt er een totaal plaatje wat je moet betalen.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik heb hier al eerder naar gekeken en het was vrij lastig om dit voor iedereen altijd goed te krijgen met alle constructies en kortingen en alles. Daarom heb ik het gelaten voor wat het is.
