### ISSUE TITLE
Reading in DSMR data from external source

### ISSUE THREAD

**Issue by nmrsmn** [dsmrreader/dsmr-reader#1047]
Is it possible to use the DSMR-reader with telegrams from an external source like another DSMR reader/loggers (like the DSMRLoggerAPI see: https://mrwheel-docs.gitbook.io/dsmrloggerapi/)?

I've tried to find the answer to my question in the documentation but I couldn't find anything except for the "statement" that it should be possible to read data from another DSMR-reader instance, but no guide or whatsoever on how to get this done.

**Comment by dennissiemensma** [comment]
Thanks for asking. DSMR-reader has an API: https://dsmr-reader.readthedocs.io/en/latest/api.html
Unfortunately the API docs are hosted locally in every DSMR-reader installation. 

You can insert data into DSMR-reader by either:
- using the v1 (remote datalogger) API, which only has a single endpoint that accepts the **entire raw telegram**. This will parse and process the data as if DSMR-reader was directly connected to your smart meter. This also prevents you from having to parse the telegram manually at all.
- using the v2 (rest) API, which has an endpoint that accepts the data of the telegram **separately on a per-field basis**. This means you **will** have to parse the telegram yourself and assign the right data to the right field in the API. 

----



- You could load the [Postman-collection/env](https://github.com/dennissiemensma/dsmr-reader/tree/v3/dsmr_frontend/static/dsmr_frontend/postman) for a glance.
- Or check the screenshot of the docs below:

![Screenshot_2020-07-14 ReDoc](https://user-images.githubusercontent.com/16581744/87454634-89a9d900-c604-11ea-86d6-5c53722b9217.png)

**Comment by dennissiemensma** [comment]
Don't hesitate in asking for any futher assistance when needed.
