### ISSUE TITLE
Ondersteuning voor vaste leveringskosten per dag

### ISSUE THREAD

**Issue by bikeymouse** [dsmrreader/dsmr-reader#1048]
Hi, ik heb nog een kleine verbetering voor het tonen van de energiekosten:

Zoals denk ik bij alle energiecontracten, bestaan de kosten bij mijn leverancier uit kosten per Kw of M3 en vaste leveringskosten per dag. Ik kan echter alleen de variabele kosten invoeren. 

Om toch de vaste kosten mee te laten rekenen kijk ik nu hoeveel ik per jaar gebruik om dan de vaste kosten om te slaan in het bedrag per Kw of M3 van de variabele tarieven.

Ik zou het echter leuk vinden het mogelijk zou zijn om ook de vaste leveringskosten per dag voor electra en gas in te stellen. Dan zouden de maand en jaarbedragen nog beter (of zelfs volledig) moeten kloppen met de rekening die ik krijg :-)

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik heb de afgelopen tijd aangegeven dat wat minder wenselijk en makkelijk is: #1042 #1020 #830 #573

Echter, gezien het blijft terugkeren als vraag, zal ik bij een toekomstige release opnieuw onderzoeken wat de mogelijkheden zijn.

**Comment by bikeymouse** [comment]
Oops, ik had niet goed gezocht, had ook je eerdere antwoorden moeten vinden...In ieder geval dank voor je snelle reactie, en hopelijk dat je op een gegeven moment tijd voor vindt om het te realiseren.
Verder niets dan lof over DSMR, zit echt mooi in elkaar!

**Comment by dennissiemensma** [comment]
@bikeymouse 
@Webserve (#1042) 
@ridderr (#1020) 
@quadrophenianl (#830)
@BlackDex (#573)
@poudenes (#573)

Deze staat op de planning voor de v4.3-release. Hieronder een work in progress. **Is dit werkbaar voor jullie?**

(*Ik ben dus niet van plan om voor elke korting en (vast) tariefje een apart veld te maken, om de complete facturatie van leveranciers na te bootsen. Dit is puur een hulpmiddel om het jaartotaal wat beter te benaderen.*)


## Instellen
![Screenshot_2020-08-25 Change Energy supplier price DSMR-reader](https://user-images.githubusercontent.com/16581744/91217783-589ae900-e718-11ea-89b0-da27af02c5ff.png)

## Dashboard
![Screenshot_2020-08-25 Dashboard DSMR Reader](https://user-images.githubusercontent.com/16581744/91217784-59337f80-e718-11ea-81bb-ec38b34c62d3.png)

## Archief
### Dag
![Screenshot_2020-08-25 Archive DSMR Reader](https://user-images.githubusercontent.com/16581744/91217774-5769bc00-e718-11ea-828b-6c14de711a1b.png)
### Maand
![Screenshot_2020-08-25 Archive DSMR Reader(1)](https://user-images.githubusercontent.com/16581744/91217778-58025280-e718-11ea-921d-78cb452b9184.png)
### Jaar
![Screenshot_2020-08-25 Archive DSMR Reader(2)](https://user-images.githubusercontent.com/16581744/91217781-58025280-e718-11ea-9bdb-c2e714e4705a.png)

## Contracten
![Screenshot_2020-08-25 Energy contracts DSMR Reader(1)](https://user-images.githubusercontent.com/16581744/91217785-59cc1600-e718-11ea-8310-bb1db0547c17.png)

**Comment by ridderr** [comment]
Bedankt, dit ziet er perfect uit.

**Comment by BlackDex** [comment]
Ziet er goed uit :).
Thx voor de toevoeging

**Comment by bikeymouse** [comment]
Helemaal prima zo, goed opgelost. Dank!

**Comment by dennissiemensma** [comment]
Dank voor jullie terugkoppeling. Dan neem ik het voor nu in deze vorm mee in de volgende release.

**Comment by Webserve** [comment]
Ziet er goed uit top 👍

**Comment by dennissiemensma** [comment]
Notificaties ook nog bijgewerkt. Het geheel is nu gemerged naar v4.3 release branch.

**Comment by dennissiemensma** [comment]
Uitgebracht in [v4.3](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v4.3.0).

- Voor terugwerkende kracht zie https://dsmr-reader.readthedocs.io/en/v4/faq.html#recalculate-prices-retroactively
