### ISSUE TITLE
Rare fout na verse install

### ISSUE THREAD

**Issue by bartje006** [dsmrreader/dsmr-reader#1051]
Hoi,

Ik had een probleem met DMSR. Dus heb ik alle gedeinstalleerd (instructies gevolgd in de documentatie).
Vervolgens alles opnieuw geinstalleerd. Waarbij die al zei dat de user dsmr en de database al bestonden (dus blijkbaar niet helemaal verwijderd).

Maar ik kon de webinterface niet bereiken (connection refused).

Nu stonden er in de /home twee mappen: dsmr en dmsr. Nu is dmsr denk ik de oude (want daar stond bijna niets in en ik heb toen een typefout gemaakt blijkbaar), die heb ik verwijderd. Maar kon nog steeds niet bij de webinterface. 

Toen wilde ik updaten, maar toen kreeg ik de melding 'Cannot change directory to /home/dmsr' (de oude locatie). 

Hoe kan ik dit het beste oplossen?

Bedankt!

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Als je nog een goede database-backup hebt en/of de database niet verwijderd hebt, kun je in principe de hele homedir/user weggooien en opnieuw proberen.

Je kunt deze stappen volgen: https://dsmr-reader.readthedocs.io/nl/v3/faq/uninstall.html
Let op dat je **stopt na** `sudo userdel dsmr` en de database **niet verwijdert**.

Daarna kun je herinstalleren en het database-gedeelte overslaan (of de fouten van bestaande user/database accepteren).
