### ISSUE TITLE
Archief navigatie via grafiek(en)

### ISSUE THREAD

**Issue by RutgerLubbers** [dsmrreader/dsmr-reader#1054]
Hoi, 

binnen het archief zou het handig zijn als je kan klikken op een specifieke data punt (maand, of dag) en dat je dan springt naar dat detail niveau. 

Zo hoef je niet zelf eerst een ander niveau te selecteren en daarna de gewenste dag / maand ...

Ik kan hier een PR voor maken als je wilt.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek en voorstel. Zie vooral #1053. Als dat eenmaal werkt, dan vermoed ik dat het relatief weinig werk is om te deeplinken vanuit grafieken.

**Comment by RutgerLubbers** [comment]
Voor een voorbeeld: http://dsmr.allowed.org/archive 

Ik zal ook kijken naar deep-linking / URL aanpassen bij navigatie..

**Comment by dennissiemensma** [comment]
@RutgerLubbers heb je hier (of voor #1053) nog een update? Als je er tussendoor niet aan toegekomen bent is dat ook prima hoor, in dat geval zal ik ze dan (voor nu) sluiten.
