### ISSUE TITLE
Grafieken inhoud vraagje

### ISSUE THREAD

**Issue by jorkzijlstra** [dsmrreader/dsmr-reader#1064]
Wat gebruik je?
- DSMR-reader versie:   3.11
- Type RaspberryPi or server:   RockPi 4B
- Standaardinstallatie of Docker:   Docker
- DSMR-protocol slimme meter v4/v5:   V5

---

![image](https://user-images.githubusercontent.com/15804835/89012030-ba328800-d311-11ea-9083-9639c9dc54c4.png)

Zoals je kan zien werkt alles perfect. Ik had alleen een vraag over de inhoud van de grafiek op de live graphs pagina. 

De 2e grafiek toont de per fase waarbij je netjes de + en de - verbruik zit. Klopt het dat de eerste grafiek deze waardes van elkaar lijkt af te trekken en dus het verschil laat zien?

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. De eerste grafiek toont wat je je slimme meter voor het hele huishouden leest als verbruik en/of teruglevering. 

Ik weet niet wat de slimme meter intern doet. Dus of die de waardes van de tweede grafiek gebruikt of dat het losse tellers zijn. In de docs staat het volgende.

## Eerste grafiek
![Selection_001](https://user-images.githubusercontent.com/16581744/89098304-a9a01180-d3e6-11ea-8589-bd324be4b881.png)

## Tweede grafiek
![Selection_002](https://user-images.githubusercontent.com/16581744/89098306-ae64c580-d3e6-11ea-970f-53cf3253084f.png)

**Comment by dennissiemensma** [comment]
Dus voor de duidelijkheid. De waardes worden als het goed is getoond zoals doorgegeven door de slimme meter.

**Comment by jorkzijlstra** [comment]
Zo een vermoeden had ik al. Bedankt voor de info.
