### ISSUE TITLE
Verkeerde waarden in pvoutput

### ISSUE THREAD

**Issue by sideriusj** [dsmrreader/dsmr-reader#1087]
Ik laat dsmrreader de standen naar Pvoutput uploaden. Het vreemde is dat er in Pvoutput andere waarden staan bij import en export. Ik laat ook automatisch de standen van mijn PV installatie naar Pvoutput uploaden, deze kloppen wel. Het zou wel mooi zijn als je de waarden van de opwek, zoals ze in Pvoutput staan in Dsmrreader kan importeren. Dan kan je het echte verbruik berekenen.  Met panelen is je verbruik import plus opwek min export.

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag/verzoek. Ik begrijp de wens en deze is al vaker voorbij gekomen. 

Dit project richt zich echter op alleen het uitlezen van de slimme meter en het plotten/exporteren van die gegevens. De context van verbruik en/of opbrengst is daarbij beperkt tot wat de slimme meter meet. Daarbij zie ik geen rol voor de import van externe gegevens, alleen de andere kant op (export). 
Daarnaast denk ik dat PVOutput 'specialist' is op gebied van PV-systemen en alle bijbehorende gegevens, dus ik denk dat dat sowieso een betere plek is om dergelijke (PV) gegevens te verzamelen.

Het is trouwens wel mogelijk om eea met elkaar te verrekenen in PVOutput. Zie daarvoor issue #9, waarin het oorspronkelijke verzoek staat voor de PVOutput-integratie.
