### ISSUE TITLE
Wachtwoord backend

### ISSUE THREAD

**Issue by pin0tn0ir** [dsmrreader/dsmr-reader#1088]
DSMR-reader is gemaakt om door jezelf te gebruiken en is daarom niet van buitenaf te debuggen. Daarom is het belangrijk dat je eerst deels zelf onderzoek doet en dat hieronder deelt (voor zover nodig). Dit helpt met het oplossen van jouw probleem. 

https://dsmr-reader.readthedocs.io/nl/latest/troubleshooting.html#log-files

Wat gebruik je?
- DSMR-reader versie: 4.2
- Type RaspberryPi or server: 3
- Standaardinstallatie of Docker:   Standaard
- DSMR-protocol slimme meter v4/v5:   V4

---

Na zelf diverse malen de installatie te hebben uitgevoerd, ik snap er zelf niet zoveel van, is het mij enige tijd geleden gelukt en loopt alles nu als een trein. 
Nu heb ik zojuist mijn buurman geholpen, maar waarschijnlijk iets niet goed gedaan. Ik kan met geen mogelijkheid in de backend (admin gedeelte) inloggen, wat ik ook probeer. Ik denk dat er iets fout is gegaan met een wachtwoord. Ik heb al geprobeerd dit op te lossen, maar kom geen steek verder. 
Ps. Ik ben een noob op dit gebied.

**Comment by jeroenpeters1986** [comment]
Hallo @pin0tn0ir,

Het aanmaken van een (nieuwe) admingebruiker is gelukkig redelijk eenvoudig. Ik weet niet wat je al kunt, maar als je het hebt geinstalleerd denk ik dat je er wel uitkomt met deze instructies.

Login op de Raspberry Pi door middel van SSH.
Als je bent ingelogd kun je ingeven: `sudo su - dsmr`, je logt dan in als de DSMR user.
Heb je alle installatie-instructies goed gevolgd dan zou je direct in de geactiveerde Python omgeving moeten komen.
Voer dan het volgende in de 'wizard' te starten die een nieuwe superuser voor je aanmaakt: `./manage.py createsuperuser`.

Als het goed is krijg je wat vragen over een gebruikersnaam, e-mailadres en wachtwoord. Vul de gegevens in en probeer daarna nog eens in te loggen op de admin. 
Ik ben benieuwd of het zo lukt, succes!

**Comment by pin0tn0ir** [comment]
Het is opgelost, weer wat geleerd. 
Bedankt!

**Comment by jeroenpeters1986** [comment]
Ah fijn, goed om te horen!
