### ISSUE TITLE
status page often alerts about 'Generate consumption data'

### ISSUE THREAD

**Issue by helmo** [dsmrreader/dsmr-reader#1093]
Wat gebruik je?
- DSMR-reader versie:   4.x
- Type RaspberryPi of server:  VM
- Standaardinstallatie of Docker:   standaard
- DSMR-protocol slimme meter v4/v5:   v4

---

Het viel me op na de upgrade naar 4.x dat op de status page elke paar seconden een item rood is.
Het gaat om "Generate consumption data".

Ik was opzoek naar een tijdelijke vervanger voor #1086 en hoopte met het matchen op een css class 'alert-danger' wat te hebben.

`/usr/lib/nagios/plugins/check_http -H dsmr.local  --regex="alert-danger" --invert-regex -u http://dsrm.local/status`

Ik heb het idee dat de 'Next run' tijd nog niet is bijgewerkt, waardoor die in het verleden ligt... 

Rood:
```
Last run: a second ago
Next run: now

Last run: 2 seconds ago
Next run: a second ago

Last run: 3 seconds ago
Next run: 2 seconds ago

Last run: 4 seconds ago
Next run: 3 seconds ago
```

Groen:
```
Last run: now
Next run: now
```

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Ik kan me voorstellen dat het wat verwarrend is. De tijden bij `Next run` zijn eigenlijk `Next run planned`. Ik zal dat bij een toekomstige release wat duidelijker maken. En wellicht de kleuren voor die processen neutraler maken.

**Comment by dennissiemensma** [comment]
Ik heb de tekst en kleur aangepast voor de volgende release.

**Comment by dennissiemensma** [comment]
Zojuist uitgebracht in [v4.4](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v4.4)

**Comment by dennissiemensma** [comment]
Dat zeggende hebben, de Status-pagina is op de schop gegaan deze week. Dus bovenstaande gaat uberhaupt niet meer werkend bedenk ik me net.

**Comment by Mixpower** [comment]
> Dat zeggende hebben, de Status-pagina is op de schop gegaan deze week. Dus bovenstaande gaat uberhaupt niet meer werkend bedenk ik me net.

Wat is er gebeurt met de Status pagina? Er word hier nu helemaal niets meer weergegeven, en ook het checken van de versie is verdwenen?

**Comment by dennissiemensma** [comment]
Dit is gewijzigd in #1086, zie daar voor meer informatie. De versie-check zal ik toevoegen aan "About" zodat die weer beschikbaar is.

Edit: Ik bedoelde #1086

**Comment by Mixpower** [comment]
Oké, maar ik denk dat de Status pagina meer geschikt is voor de versie-check.

**Comment by dennissiemensma** [comment]
@Mixpower ter info, voor de aankomende v4.5 release wederom wijzingen: https://github.com/dennissiemensma/dsmr-reader/issues/1086#issuecomment-711391141
