### ISSUE TITLE
Typefoutje

### ISSUE THREAD

**Issue by bduijnhouwer** [dsmrreader/dsmr-reader#1095]
Ik heb nog een heeel klein schoonheidsfoutje gevonden.

Op de configuratiepagina is de titel : " Configuation "
(Er mist een R)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Ik heb het nu aangepast voor de volgende release.

**Comment by dennissiemensma** [comment]
Zojuist uitgebracht in [v4.4](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v4.4)
