### ISSUE TITLE
Suggestie energiekosten berekenen

### ISSUE THREAD

**Issue by gnissahr** [dsmrreader/dsmr-reader#1098]
We hebben hier een all-electric woning met op jaarbasis een overschot aan electra.
Op dit moment heb ik voor te teruggeleverde electriciteit hetzelfde tarief ingevuld als voor de afgenomen electriciteit. Dat geeft een tof resultaat, maar is niet helemaal correct.

![image](https://user-images.githubusercontent.com/65919827/91759583-300c6680-ebd2-11ea-847f-071f147ffd39.png)

In de praktijk (in ieder geval bij Eneco) wordt eerst de teruggeleverde electra in het hoogtarief verrekend tot een netto verbruik van 0. Indien er nog wat resteert zal dat in het laagtarief verrekend worden. Als er dan nog meer overblijft zal dat verrekend worden tegen de terugleververgoeding (lees weinig).

In dit voorbeeld zouden dus de kosten uitkomen op 0 voor hoogtarief, 0 voor laagtarief en circa 930 * terugleververgoeding = circa -56 euro.

De verrekening/saldering is per contractperiode/jaar, dus het is iets wat constant veranderd, maar zou op basis van het weergegeven verbruik prima te berekenen moeten zijn in het overzicht.

Dit zal extra relevant worden als de salderingsregeling afgebouwd gaat worden, dan zal een groter deel van de teruggeleverde electriciteit onder "terugleververgoeding"gaan vallen.

**Comment by dennissiemensma** [comment]
Bedankt voor je suggestie en toelichting! Ik begrijp je wens, echter heb ik een ruime tijd geleden besloten dat DSMR-reader slechts beperkte ondersteuning voor prijsberekening en tarifering doet. 

Het doel van het project is namelijk niet het narekenen van je energierekening, daar zitten veels te veel haken en ogen aan. Daarnaast is de kans groot dat voor elke uitzondering die ik voor de ene gebruiker toevoeg, twee anderen weer een andere afwijkende situatie melden. En je noemt ook het afbouwen van de salderingsregeling, wat het nog complexer maakt.

Dit project is puur bedoeld om je meter uit te lezen en inzicht te krijgen in je verbruik. De tarieven zijn daarbij meer een grove indicatie/gevoel voor jezelf, vooral in de wintermaanden met eventueel gasverbruik, al snap ik de wens voor het exact uit- of narekenen van de kosten. 

Ik denk dat het Energiecontracten-overzicht aan de voorkant het dichtste in de buurt komt van wat je zoekt, al kloppen de kosten dan niet qua teruglevering/saldering.
