### ISSUE TITLE
Save interval

### ISSUE THREAD

**Issue by etiennebz** [dsmrreader/dsmr-reader#1099]
Hallo,
Mooie app moet ik zeggen.
Ik heb het niet kunnen vinden in de app of in de uitgebreide documentatie, dus bij deze een feature request:

Zou het mogelijk zijn om de interval van het opslaan naar een SD kaart aan te passen? Dus bijvoorbeeld de data een paar minuten in het geheugen te houden en dan te saven naar de SD kaart. Dat zou de levensduur van een SD kaartje aanzienlijk kunnen verbeteren.

Bedankt,
Etienne

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Je kunt dit op meerdere manieren voor elkaar krijgen.

- De meest makkelijke manier is om in de configuratie van DSMR-reader de "sleep" tijd van het datalogger-process en het backend-process zo hoog mogelijk te zetten. Voor de datalogger kun je bijvoorbeeld 60 seconden doen, zodat die na elke meting een minuut niets doet (en dus ook niets uitleest!). Voor de backend kun je die ook op 60 seconden of meer zetten. Dat betekent dat alle achtergrond-acties, zoals het groeperen van metingen, telkens een minuut uitgesteld worden. Dus ook bijbehorende writes.

- Een andere workaround is om simpelweg geen SD-kaart te gebruiken. Je kunt DSMR-reader, en dan bedoel ik de database, op een andere HDD/SSD-schijf of zelfs server zetten.
