### ISSUE TITLE
invoervelden wachtwoord wijzigen niet zichtbaar

### ISSUE THREAD

**Issue by MRL-33** [dsmrreader/dsmr-reader#1100]
Wanneer ik op "wachtwoord wijzigen" klik, is de invoer niet zichtbaar op mijn PC-screen. (Chrome)
![not_visible](https://user-images.githubusercontent.com/59490465/91868812-6fd85a00-ec75-11ea-84dd-c4ba63bdda24.png)
Zie je de verticale scrollbar? Ik ben helemaal onderaan de pagina, maar de invoervelden zijn niet zichtbaar.

Solution/workaround: zoom uit totdat de verticale scrollbar verdwijnt. Alleen dan zijn de invoervelden zichtbaar.

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Ik denk niet dat ik het voor je kan oplossen, want deze (nieuwe) pagina komt uit het de meest recente versie van Django, het open-source framework wat ik gebruik.

Dat zeggende hebben kun je nog wel wat proberen, want volgens mij hoort het er niet zo uit te zien en mogelijk zit de cache of iets in de weg:
- Static files wissen en opnieuw kopieren:
```
sudo su - dsmr
./manage.py collectstatic --clear --no-input
./reload.sh
```
- Cache en cookies van je browser weggooien (hoeft uiteraard alleen voor DSMR-reader)

**Comment by dennissiemensma** [comment]
@MRL-33 helpt bovenstaande? In #1103 lijkt het een soortgelijk issue op te lossen.
