### ISSUE TITLE
MQTT wordt altijd uitgeschakeld bij een herstart

### ISSUE THREAD

**Issue by vgdimitri** [dsmrreader/dsmr-reader#1109]
Momenteel is alles geupdate naar 4.3
En de verbinding gebeurd via WiFi. 

Eerst had ik het geprobeerd met de volledige domeinnaam bv. www.mijnserver.be 
Default poort werd gewijzigd van 1883 naar 1884
Dit werkte goed totdat de stroom onderbroken werd. Na het herstarten staat MQTT uitgeschakeld. Omdat : Failed to connect to broken.
Nadien heb ik dit getest door het ip adres te gebruiken ipv de server naam.
Dit werkt ook steeds, totdat het toestel herstart wordt, dan krijg ik onderstaande melding in de logs te zien en dan staat mqtt uitgeschakeld.

Is er een mogelijkheid zodat mqtt ingeschakeld blijft?

Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2020-09-09 11:25:39,871] ERROR    MQTT: Failed to connect to broker (IPADRES:1884), disabling MQTT: [Errno 101] Network is unreachable
[2020-09-09 11:25:39,926] ERROR    Failed to connect to broker
NoneType: None

**Comment by dennissiemensma** [comment]
Bedankt voor je melding! Dit gaat opgelost worden in #1091. Ik raad je aan om dat issue te watchen of in de gaten te houden.
