### ISSUE TITLE
Notification if update is available

### ISSUE THREAD

**Issue by BobPuts** [dsmrreader/dsmr-reader#1116]
Hi There,

Is it possible to send a notification if there is a new update available? Or is it already implemented? Haven't found anything on it.

And maybe select what kind of notifications you want to receive.

**Comment by dennissiemensma** [comment]
Thank you for your suggestion. It's quite a hassle to implement such thing.

If you really would like to receive notifications, I'd suggest subscribing to project-releases on Github: https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/about-notifications

Then you're the first to know.
