### ISSUE TITLE
dsmr mqtt connectie wordt niet hersteld na herstart mqtt server 

### ISSUE THREAD

**Issue by mchangsp** [dsmrreader/dsmr-reader#1118]
Wat gebruik je?
- DSMR-reader versie: v4.3.1
- Type RaspberryPi of server:   RPI 4
- Standaardinstallatie of Docker:   Docker
- DSMR-protocol slimme meter v4/v5:   v4

---
Met v3 wekenlang geen problemen gehad.
Met v4 heb ik nu al een aantal dagen dat de mqtt topics voor electriciteisverbuik plotseling niet meer gepublished worden. De web interface werkt normaal. In "Status" werkt alles.
echter in de backend log staat:
ERROR Client no longer connected.

het lijkt erop dat DSMR op een gegeven moment geen contact meer kan maken met de mqtt server.

ik heb 1x de mqtt server herstart terwijl dsmrreader actief was.
Nadat de herstart van de mqtt server voltooid was, maakten alle andere mqtt clients automatisch weer verbinding. alleen dsmr reader publishte geen nieuwe waardes.

is de code om "opnieuw verbinding te maken met een mqtt server na een disconnect" gewijzigd?

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Zie #1091 en #1109.

**Comment by mchangsp** [comment]
Dank voor het antwoord. Ik had gezocht op "mqtt" en had #1091 en #1109 niet gezien.
