### ISSUE TITLE
Dag statistieken dagelijks uitsturen over MQTT

### ISSUE THREAD

**Issue by poudenes** [dsmrreader/dsmr-reader#1132]
Hoi,

Zou het mogelijk zijn dat de dag statistieken uitgestuurd worden op een opgegeven moment van tijd over MQTT?
Deze MQTT kan ik dan uitlezen in HA en deze dan opslaan in de logger/history. 
Dan hoef ik niet naar de webportal van DSMR en kan de data die in HA zit voor allerlei zaken gebruiken (automations)

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Kan het zijn dat je er overheen gekeken hebt? Als we hetzelfde bedoelen dan zit die functionaliteit er al in onder `(Data source) Day consumption ....` in zowel JSON als split topic.

**Comment by poudenes** [comment]
Die heb ik over het hoofd gezien dank je wel!

**Comment by poudenes** [comment]
Toch een klein vraagje. Het bericht dat dagelijks verzonden wordt (naar mijn pushover) daar staat verbruikers statistieken van de dag ervoor
Electriciteitsverbruik, Gasverbruik en Totale Kosten. Ik bedoel eigenlijk deze informatie. Wordt dat ook via MQTT verzonden al? Want dat kom ik nergens tegen.

**Comment by dennissiemensma** [comment]
Ah op die manier. Bovenstaande gegevens zijn incrementeel waardoor een bericht, met een eindtotalen van een dag, nog niet beschikbaar is. Ik zal het opnemen in  #685 maar onbekend wanneer dat doorgevoerd wordt.
