### ISSUE TITLE
MQTT via Node-Red

### ISSUE THREAD

**Issue by discofris** [dsmrreader/dsmr-reader#1136]
Ik vroeg mij af hoe je kan verbinden via MQTT in een Node-RED flow?
Alles in DSMR staat correct, ik heb een Datasource geactiveerd en de Broker aangezet dat ie naar m'n host met Node-RED erop moet sturen.
In Node-RED ben ik gewoon om te subscriben op een MQTT topic, om te luisteren totdat iemand iets stuurt lukt mij niet in Node-RED. Enig advies?
Wanneer ik de Broker in DSMR deactiveer, dan zie ik outgoing messages ... en terug de Broker activeer om te sturen naar ergens, zijn de messages weg. Dus DSMR-gewijs werkt alles ....

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Ik kan je hier helaas niet mee helpen, ook omdat ik er zelf geen ervaring mee heb.

Ik kan je aanraden je issue te delen op een plek waar velen anderen je kunnen helpen, want hier op Github leest slechts een enkeling mee. Wellicht heb je meer succes op het [Tweakers forum](https://gathering.tweakers.net/forum/list_messages/1876137)?

**Comment by discofris** [comment]
T'is me gelukt. Met een [HiveMQ ](https://www.hivemq.com/downloads/docker/)container ertussen werkt het perfect. In het admin panel van HiveMQ zie ik nu dus 2 clients: 1tje is DSMR-reader en de andere is Node-RED.

### MQTT config in DSMR-reader:
![dva-1353](https://user-images.githubusercontent.com/6281711/94991309-98a88380-0582-11eb-92b8-2334a952325a.png)

### MQTT broker node in Node-RED:
![dva-1354](https://user-images.githubusercontent.com/6281711/94991336-bfff5080-0582-11eb-93ff-05034a7bf826.png)
![dva-1355](https://user-images.githubusercontent.com/6281711/94991345-d0afc680-0582-11eb-8403-d9542f2f15b5.png)

 ### HiveMQ heeft geen instellingen nodig. 
Enkel de container deployen, vanuit DSMR-reader en Node-RED er mee verbinden. Zorg ook dat je 2 **verschillende** client-ids gebruikt:
![dva-1356](https://user-images.githubusercontent.com/6281711/94991381-140a3500-0583-11eb-839d-51eb470e3282.png)
![dva-1357](https://user-images.githubusercontent.com/6281711/94991387-2a17f580-0583-11eb-9ab4-3b37164d7017.png)

![dva-1358](https://user-images.githubusercontent.com/6281711/94991396-3439f400-0583-11eb-892e-2c47d542fbdb.png)

Hopelijk helpt dit nog iemand anders.

**Comment by dennissiemensma** [comment]
Fijn om te horen, dank voor je uitgebreide toelichting!
