### ISSUE TITLE
Django settings instellen via envvars

### ISSUE THREAD

**Issue by dennissiemensma** [dsmrreader/dsmr-reader#1140]
N.a.v. #1080 is er regelmatig vraag naar het override van Django settings via envvars. 

Initieel wilde ik iets maken wat generiek is (met een prefix) om willekeurige settings te overschrijven. Maar dat lijkt niet mogelijk door de verschillende types. Dus ik map wel een hardcoded lijstje.

**Comment by dennissiemensma** [comment]
Uitdaging is nog wel de type mapping. Dan moet ik even goed testen.

**Comment by dennissiemensma** [comment]
Deze voeg ik toe:

```
DJANGO_STATIC_URL=
DJANGO_FORCE_SCRIPT_NAME=
DJANGO_USE_X_FORWARDED_HOST=
DJANGO_USE_X_FORWARDED_PORT=
DJANGO_X_FRAME_OPTIONS=
```

**Comment by dennissiemensma** [comment]
Zojuist uitgebracht in [v4.5](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v4.5.0)

**Comment by discofris** [comment]
Ik bevestig dat dit netjes werkt :) 🥇

**Comment by dennissiemensma** [comment]
Dank voor de terugkoppeling!

**Comment by Wieter** [comment]
werkt ook hier prima, thanks!
