### ISSUE TITLE
Mogelijkheid voor negatieve waarde in Fixed daily costs (€):

### ISSUE THREAD

**Issue by jorkzijlstra** [dsmrreader/dsmr-reader#1148]
Ik zou graag een negatieve waarde in de dagelijkse kosten willen invoeren waardoor ik beter inzicht hebben van de daadwerkelijke kosten per dag. Al moet ik nu alleen maar even wat hoofdrekenen. 

Reden: Vaste leveringskosten (per dag) + netbeheerkosten (per dag) - vermindering energiebelasting (per dag) = een negatieve waarde.

![image](https://user-images.githubusercontent.com/15804835/95505659-056eb400-09af-11eb-8ae6-c87efeeadaf9.png)

Een andere optie is misschien ook het veld "vermindering energie belasting" toe te voegen net als vast kosten, maar dat zal waarschijnlijk meer werk zijn.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Dat lijkt me een prima voorstel zodat je daar zelf vrij in bent. 

Ik heb het voor je doorgevoerd in de volgende release.

**Comment by dennissiemensma** [comment]
Zojuist uitgebracht in [v4.5](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v4.5.0)
