### ISSUE TITLE
Via Mqtt posten van terugwinning

### ISSUE THREAD

**Issue by bartbakels** [dsmrreader/dsmr-reader#1153]
Zou het mogelijkzijn om een waarde terug te koppellen aan dsmr tbv energieterugwinning (zonnepanelen)

Ik heb een aantal zonnepanelen en zou graag de netto terugwinning willen loggen met dsmr. Ik zou bijvoorbeeld de current opbrengts (watts) op een mqtt topic kunnen publishen zodat dsmr deze meeneemt in zijn logging en trending.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik begrijp dat dat een mooie toevoeging zou zijn, maar ik denk dat DSMR-reader daar niet de plek voor is. 

Dit project is puur bedoeld voor het uitlezen van je slimme meter, het plotten van die data en ervoor zorgen dat je die data overal heen kan sturen waar je maar wilt. Ik denk dat je persoonlijk meer geholpen bent met PVOutput, waar ook een hoop omvormers mee gekoppeld kunnen worden. 
Daar kun je dan vervolgens DSMR-reader de bruto-data naar toe laten exporteren, zodat je inzage hebt in beiden. Zie bijvoorbeeld issue #9 voor meer achtergrond.
