### ISSUE TITLE
Vraag mbt oude backup. 

### ISSUE THREAD

**Issue by Diondk** [dsmrreader/dsmr-reader#1154]
<--- COPY OUTPUT AFTER THIS LINE --->

```

DSMR-READER
  Version                                                    v4.4.3
  Database engine/vendor                                 postgresql
  Setting: Backend process sleep                              1.0 s
  Setting: Datalogger process sleep                           0.5 s
  Setting: Retention cleans up after                         None h

SMART METER
  Telegram version (latest reading)                             v50
  Setting: Telegram parser                                        4

DATA
  Stored: Telegram records total                            9423169
                        \_ unprocessed                           61
  Stored: Electricity consumption records                    157510
  Stored: Gas consumption records                             31498

POSTGRESQL SIZE OF LARGEST TABLES (> 1MB)
  public.dsmr_datalogger_dsmrreading                        2311 MB
  public.dsmr_consumption_electricityconsumption              62 MB
  public.dsmr_consumption_gasconsumption                    3296 kB

```

<--- COPY OUTPUT UNTIL THIS LINE --->

---

In maart was mijn dsmr gecrasht en toen heb ik hem verhuisd naar een docker omgeving op unraid. Nu kwam ik net pas weer een backup tegen van mijn dsmr database. Is er nog een manier om deze data terug te krijgen in mijn dsmr? zonder dat ik de database kapot maak en dus helemaal niks meer heb?

**Comment by Diondk** [comment]
Inmiddels deze gevonden dus dat ga ik even proberen: https://github.com/dennissiemensma/dsmr-reader/issues/1145

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Mijn advies is om alleen de uur- en dagstatistieken over te zetten. 

Het andere ticket had je al gevonden, maar als je er zelf niet uitkomt (afhankelijk hoe technisch je bent), dan wil ik evt wel de find-replace voor je doen zodat je de data erbij kan importeren.

**Comment by dennissiemensma** [comment]
_Ongerelateerd aan je vraag: houd er rekening mee dat je met je huidige instellingen (geen dataopschoning + lage datalogger sleep) ontzettend veel data opslaat. Dat kan op den duur uiteindelijk gaan botsen qua performance, afhankelijk van de exacte hardware en opslag die je gebruikt._

**Comment by Diondk** [comment]
Heb alleen de dagstatistieken terug gezet, de uren was me teveel werk :) gelijk ook de dataopschoning ingesteld. Bedankt!
