### ISSUE TITLE
Dropbox access token max lengte vergroten

### ISSUE THREAD

**Issue by HellStorm666** [dsmrreader/dsmr-reader#1157]
Draai versie 4.3.3 in Docker.

Drobbox access token is bij mij 138 tekens, de config (en db) ondersteunen er maar 128.
Dit moet verhoogd worden naar bijv 265.

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Dit was nog niet bij mij bekend. Gezien het een kleine fix is, neem ik het direct mee met de release voor zometeen.

**Comment by dennissiemensma** [comment]
Verhoogd naar 255

**Comment by HellStorm666** [comment]
top, thnx!

**Comment by dennissiemensma** [comment]
Zojuist uitgebracht in [v4.5](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v4.5.0)
