### ISSUE TITLE
Table header latest_timestamp optimaliseren voor mobiele weergave

### ISSUE THREAD

**Issue by knirefel** [dsmrreader/dsmr-reader#1160]
Regelmatig bekijk ik het DSMR Reader Dashboard op een mobiel apparaat. Ik stoor me enigszins aan het feit dat de tabel kolommen continu verspringen omdat de tekst in 'latest_timestamp' wisselt van lengte. Zie hier de verschillen:

![2020-10-21 19_26_30-Dashboard _ DSMR Reader](https://user-images.githubusercontent.com/9083976/96755985-b1fb5d80-13d3-11eb-8eb1-1c45a4cea97a.png)
![2020-10-21 19_26_43-Dashboard _ DSMR Reader](https://user-images.githubusercontent.com/9083976/96755986-b293f400-13d3-11eb-823a-291fa89fe4c0.png)

Het zou prettig zijn als de kolombreedte niet automatisch verspringt op basis van de tekstgrootte.

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Ik zal er in een toekomstige release naar kijken.

**Comment by dennissiemensma** [comment]
Ik heb hier laatst een tijdje naar gekeken, naar ik kreeg het niet helemaal lekker. Wellicht dat ik hiervoor die header met de 'huidige waardes' hiervoor weer los moet trekken, zoals het in vroegere versies van DSMR-reader was. Maar dat is wel wat werk, dus ik laat het voor nu even voor wat het is.

**Comment by dennissiemensma** [comment]
Ik heb hier een mogelijk fix voor. Het variabele stukje tekst staat straks op een losse regel en daarnaast is de header ook losgetrokken, zodat die niet meer de hele tabel beinvloed, mocht het toch weer gebeuren. 


![Selection_008](https://user-images.githubusercontent.com/16581744/110239503-765acd80-7f47-11eb-8402-dc199590ceab.png)

Tot slot zijn er nu geen twee tellers meer naast elkaar voor huidige verbruik/teruglevering, want dat scheelt breedte. Plus dat er gegarandeerd altijd 1 op `0` staat en de andere niet. Dus was het wat logischer om of de een, of de andere te tonen. Teruglevering wordt nog wel groen getoond, met een `-` er voor.

**Comment by dennissiemensma** [comment]
Zojuist uitgebracht in [v4.13](https://github.com/dsmrreader/dsmr-reader/releases/tag/v4.13.0).
