### ISSUE TITLE
DSMR-uitlezing (alleen lezen) om te bekijken

### ISSUE THREAD

**Issue by poudenes** [dsmrreader/dsmr-reader#1166]
Hi ALl,

Misschien niet een bug, maar dacht meld hem wel:

![Schermafbeelding 2020-10-27 om 09 20 24](https://user-images.githubusercontent.com/4399532/97275002-ae356400-1835-11eb-9fa8-ab3b531e5698.png)

Zoals je kunt zien bewaard hij alles op xx:59 en xx:00. Is dit normaal? Lijkt mij dat je of xx:59 of xx:00 alleen bewaard. Maar 2 momenten waar 1 seconde tussen zit, niet echt nuttig?

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Het klopt wat je zegt, echter vanuit DSMR-reader gezien is het gedaan omdat het uurverbruik altijd gebaseerd wordt op de eerste en laatste meting van elk uur. 
Om dat mechanisme te behouden bij eventuele herberekeningen wordt, voor nu, dezelfde data bewaard. Het is in de toekomst altijd vrij makkelijk aan te passen als er nog extra data-opschoning nodig is, ook met terugwerkende kracht. 

Voor nu zit de datagrootte doorgaans in 99% van de ongebruikte telegrammen, dus laat ik het even voor wat het is.
