### ISSUE TITLE
Tijd instellen voor fluvius Belgïe

### ISSUE THREAD

**Issue by modparts** [dsmrreader/dsmr-reader#1167]
Hallo

Mijn Fluvius meter telt de voor een dag i.p.v. 0u00 tot 23u59 van 06u00 tot 5u59 is het en grote moeite om te maken dat ik de tijd wanneer de dag begin en eindigt zelf in te stellen?

Alvast bedankt
Yuri

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. DSMR-reader geeft als het goed is weer wat je meter doorgeeft aan je leverancier, ongeacht het moment van de dag. Het kan natuurlijk wel zijn dat je energieleverancier daar uiteindelijk iets anders mee doet, bijvoorbeeld in haar eigen portaal qua start-eindtijd of met de facturatie. 

Hoewel ik begrijp dat het in jouw situatie wellicht anders werkt dan DSMR-reader het toont, is DSMR-reader vooral bedoeld om jou als gebruiker te laten zien wat je ongeveer verbruikt op een dag. Bijvoorbeeld het effect van boilers of verwarming.
Het nabootsen van de werking van leveranciers (als ik je verhaal goed intepreteer) is daar helaas geen onderdeel van, omdat er tig varianten van zijn.
