### ISSUE TITLE
Vaste kosten negatief

### ISSUE THREAD

**Issue by cloudwalker87** [dsmrreader/dsmr-reader#1170]
Ik zou graag een negatief getal kunnen instellen voor de vaste kosten per dag. Door de vermindering van de energiebelasting van 500+ euro zijn mijn vaste kosten gezakt tot ongeveer €0,25 negatief per dag. Zou mooi zijn als ik dit ook kan instellen ipv op 0 houden. Dank.

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Je specificeert niet welke versie je momenteel gebruikt. De feature is al toegevoegd in [v4.5](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v4.5.0). 

Als dat niet naar behoren werkt, hoor ik het graag.
