### ISSUE TITLE
Succesvolle upgrade!

### ISSUE THREAD

**Issue by RichieB2B** [dsmrreader/dsmr-reader#1176]
Excuses voor de issue-vervuiling. Want is heb helemaal geen issue! Ik upgrade dsmr-reader niet zo vaak (want het werkt altijd prima), dus ik heb net na precies 1 jaar de upgrade gedaan van 2.9 -> 2.15.1 -> 3.12 -> 4.5. En dat ging allemaal vlekkeloos! Prima documentatie, goede scripts en bovenal uitstekend werkende software. Bedankt en ga zo door! 👍

**Comment by dennissiemensma** [comment]
Bedankt voor je terugkoppeling, fijn om te horen!
