### ISSUE TITLE
Upgrade van 3.12.0  naar 4.5.0 No module named 'psycopg2' error

### ISSUE THREAD

**Issue by mstroeve** [dsmrreader/dsmr-reader#1179]
Troubleshooting: https://dsmr-reader.readthedocs.io/nl/latest/troubleshooting.html#log-files

(Heb je DSMR-reader v4.4 of hoger? Zet dan hieronder ook de output van "dsmr_debuginfo") 

--- Nog aanvullen momenteel geen toegang tot unit op locatie

Upgrade instructies zijn zeer duidelijk alles ging prima tot aan de stap Applying database migrations.
Na het uitvoeren van: pip install psycopg2-binary en opnieuw uitvoeren deploy.sh werkt het wel correct.
Mischien kan dit nog verbeterd worden in de upgrade docs?

Hierbij deze error info:

```
 --- Applying database migrations.
Traceback (most recent call last):
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
... 

<lange stacktrace>

...
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.6/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
>>>>> [!] Executing database migrations failed again! <<<<<
        - Running dsmr_sqlsequencereset did not resolve the problem.
        - Create an issue on Github and attach the exeception trace listed above.
[!] Halted. Post-deployment script exited with non-zero code
```

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Zoals je het nu gedaan hebt is de 'oude' manier, die ook prima werkt als fallback.

Werkte het systeembreed installeren van `python3-psycopg2` en daarna de virtualenv opnieuw aanmaken niet?
https://dsmr-reader.readthedocs.io/en/latest/faq/v4_upgrade.html#install-python3-psycopg2

**Comment by mstroeve** [comment]
Zie nu pas dat ik geheel over de uit te voeren regel heb heen gelezen . 
Had niet door dat Postgresql van toepassing was voor mijn installatie en ging direct naar het kopje "Execute the following".

**Comment by dennissiemensma** [comment]
Prima. De door jou gevonden manier werkt dus ook. Dank voor de terugkoppeling!
