### ISSUE TITLE
New image: /bin/bash: /run.sh: No such file or directory

### ISSUE THREAD

**Issue by Xitro01** [dsmrreader/dsmr-reader#1184]
DSMRREADER container is not starting anymore after pulling the latest image.
It used to work before upgrading.

Now it only gives the error "/bin/bash: /run.sh: No such file or directory" in the logs.

**Comment by dennissiemensma** [comment]
I think you might want to recreate your issue at: https://github.com/xirixiz/dsmr-reader-docker/issues

The current project does not support Docker, just the 'native' installation.
