### ISSUE TITLE
Manual fresh install V4

### ISSUE THREAD

**Issue by lubbertkramer** [dsmrreader/dsmr-reader#1187]
Looking into the documentation i want to do a fresh install of V4 because of the active development instead of installing V3 in docker. I see the settings are now stored in the .env file that i use for several dockers. Where can i find more information or a manual on installing V4 and which settings/enviroments are needed in the .ENV file (also the correct naming for example  the secretkey)?

I did found a manual for V3 on -> https://hub.docker.com/r/xirixiz/dsmr-reader-docker/ but the variables mentioned are not mentioning for example the secretkey that is needed.

```
docker run -d \
  --name dsmr \
  --restart always \
  -p 7777:80 \
  -e DB_HOST=x.x.x.x \
  -e DSMR_USER=dsmrreader \
  -e DSMR_PASSWORD=dsmrreader \
  -e DSMR_EMAIL=root@localhost \
  --device /dev/ttyUSB0:/dev/ttyUSB0 \
  xirixiz/dsmr-reader-docker
```

**Comment by dennissiemensma** [comment]
See
- https://dsmr-reader.readthedocs.io/en/v4/installation/explained.html 
- and https://dsmr-reader.readthedocs.io/en/v4/env_settings.html 
- and https://github.com/dsmrreader/dsmr-reader/blob/v4/.env.template

**Comment by dennissiemensma** [comment]
Also, there is a docker version by xirixiz: https://github.com/xirixiz/dsmr-reader-docker

**Comment by lubbertkramer** [comment]
Thanks, have it up and running in Docker with the variables mentioned in the env file above :)
