### ISSUE TITLE
Typo in ondersteuningspagina

### ISSUE THREAD

**Issue by jwveldhuis** [dsmrreader/dsmr-reader#1195]
“veegelstelde”
https://github.com/dsmrreader/dsmr-reader/blob/e9f709c400bded3f1ab1e18a0c49391d46823fa0/dsmrreader/locales/nl/LC_MESSAGES/django.po#L1078

**Comment by dennissiemensma** [comment]
Dank voor je scherpe blik! Ik heb het aangepast voor de volgende release.
