### ISSUE TITLE
Dagstatistieken worden niet gegenereerd na uitschakelen gas

### ISSUE THREAD

**Issue by henkjanwithaar** [dsmrreader/dsmr-reader#1197]
```

DSMR-READER
    App / Python / Database                                                        v4.7 / v3.7.3 / postgresql
    Backend sleep / Datalogger sleep / Retention cleanup                                  1.0s / 0.5s / 4032h
    Telegram latest version read / Parser settings                                               "None" / "3"

DATA
    Telegrams total (est.)                                                                             347632
    Consumption records electricity / gas (est.)                                                94885 / 23810

```

---
Sinds enige tijd (niet zeker sinds welke release) wordt er in het dashboard geen informatie meer getoond met betrekking tot de huidige maand. Op de plaats waar de info in het verleden stond staat nu "The totals for the current month are currently not (yet) available. Check again tomorrow.".

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Worden er wel dagtotalen gegenereerd in het Archief? 

Zo nee, dan kun je kijken of er fouten staan in de log van `dsmr_backend` (https://dsmr-reader.readthedocs.io/en/latest/faq.html#log-files)

**Comment by henkjanwithaar** [comment]
Het archief ziet er als vanouds uit en dagtotalen lijken gewoon gegenereerd te worden:

![Screenshot_20201110-201458-01](https://user-images.githubusercontent.com/36207809/98722848-dd99b400-2391-11eb-8d18-762e2185cb0a.jpeg)

Het logfile bevat wel warnings; die zijn echter PVOutput gerelateerd.

**Comment by dennissiemensma** [comment]
Staan er voor november ook dagen in het Archief of kapt die exact af op eind oktober?

**Comment by henkjanwithaar** [comment]
Het laatste: geen dagen voor november in het archief.

**Comment by dennissiemensma** [comment]
Dan denk ik dat je het beste debug-logging kan inschakelen: https://dsmr-reader.readthedocs.io/en/latest/faq.html#logging-levels
En dan kijken of je in de log van het backendproces meer ziet.

Ik neem aan dat het dashboard en live grafieken verder wel recente metingen laten zien?

**Comment by henkjanwithaar** [comment]
Het dashboard is voor het overige actueel, net als de live grafieken. Ik heb debug logging aangezet de volgende melding komt telkens langs:

`DEBUG    SP: Rescheduled "Generate consumption data" to 2020-11-10 21:58:51.436051+01:00 (ETA 0:00:14.992771)`

**Comment by dennissiemensma** [comment]
Die debug info is heel generiek en weergeeft geen fouten, alleen wat er gebeurt. 

Ik was vergeten te vermelden dat je moet zoeken naar meldingen die beginnen met:

```
Stats: 
```

Zoals:
```
Stats: No data available
Stats: Waiting for day to pass:
Stats: Found unprocessed readings for:
Stats: Missing consumption data for:
Stats: Waiting for first gas reading on the next day
```

Dat zijn allemaal 'afslagen' bij een conditie dat die iets niet kan doen voor het genereren van de dagstatistieken. Het kan 5 minuten tot een uur duren totdat die het weer probeert.

Om dat te omzeilen kun je op de pagina `/admin/dsmr_backend/scheduledprocess/` zoeken naar "Generate day and hour statistics", die aanklikken en dan de 'plandatum/tijd' in het verleden (of 'nu) zetten.

Bij de "Rescheduled" meldingen in de log schuift die een taak even vooruit. Dat varieert per taak en situatie van een paar seconden tot soms zelfs een week. Door hem handmatig te herplannen probeert die het de eerstvolgende backend run opnieuw en zou je iets in de log moeten zien.

**Comment by henkjanwithaar** [comment]
Deze stats: melding blijft iedere vijf minuten terugkomen maar heb gisteren vanuit #1198 gas uitgeschakeld in de backend admin. Voor het overige geen stats: meldingen tot dusver.

`[2020-11-11 09:37:50,285] DEBUG    Stats: Waiting for first gas reading on the next day...`

**Comment by dennissiemensma** [comment]
Dank voor de update, dat verklaart het inderdaad! Ik zal nog een uitzondering toevoegen voor jouw situatie.

Draai je op docker of heb je een handmatige install gedaan?

**Comment by henkjanwithaar** [comment]
> Draai je op docker of heb je een handmatige install gedaan?

Een handmatige install op raspberry pi.

**Comment by dennissiemensma** [comment]
Je kunt dan kijken of dit het voor nu voor je oplost:
```
sudo su - dsmr
git fetch
git checkout -b development origin/development
./deploy.sh
```

Daar zit een voorlopige fix in.

**Comment by henkjanwithaar** [comment]
Gefixed! Dank Dennis.

![Screenshot_20201112-121707-01](https://user-images.githubusercontent.com/36207809/98934038-c4078200-24e1-11eb-8ab7-75515a7b96d8.jpeg)

**Comment by dennissiemensma** [comment]
Oke top! Let op dat nu je wel de testversie gebruikt, wat voor nu prima is. Maar bij de volgende release wil je weer switchen naar de hoofd-versie, waar deze fix tzt dan ook in zit.

Alvast het command voor dan:
```
sudo su - dsmr
git checkout v4
./deploy.sh
```

**Comment by dennissiemensma** [comment]
Uitgebracht in [v4.8](https://github.com/dsmrreader/dsmr-reader/releases/tag/v4.8.0). Je kunt dit nu uitvoeren om terug te wisselen naar de hoofdbranch: https://github.com/dsmrreader/dsmr-reader/issues/1197#issuecomment-726290999
