### ISSUE TITLE
Gebruik postgresql triggers en functies voor vullen django_admin_log

### ISSUE THREAD

**Issue by gotiniens** [dsmrreader/dsmr-reader#1203]
Ik moet zeggen dat het ook voor mij nieuw is, maar ik ontdekte van de week dat je met de PostgreSQL functies Triggers en Functions op database niveau een change history kan bijhouden. De database zorgt er dan zelf voor dat bij het uitvoeren van een query er een tabel gevuld wordt met deze informatie, precies zoals nu in de django_admin_log gedaan wordt.

Als je dit geïmplementeerd hebt hoef je de volgende melding in de history bij de admin pagina niet meer te tonen:

`This object doesn’t have a change history. It probably wasn’t added via this admin site.`

Het voordeel van deze methode is dat je history niet inconsistent wordt als je wijzigingen doet buiten de applicatie om, en dat een bug in je applicatie ook niet voor inconsistentie kan zorgen.

Ik vond deze stackoverflow post met een mooi voorbeeld: https://stackoverflow.com/questions/55875237/use-a-postgres-trigger-to-record-the-json-of-only-the-modified-fields

**Comment by dennissiemensma** [comment]
Bedankt voor suggestie! Het gebruik van triggers is doorgaans een goede toevoeging op dat gebied.

Het is goed om te weten dat:
- Dit project Django gebruikt en dat die logging standaardfunctionaliteit is dat erbij zit (en niet bewust is aangezet).
- Ondanks dat alleen PostgreSQL 'officieel' ondersteund wordt, dit project ook gebruikt (en getest wordt) in andere soorten databases. Dat maakt het al stukken complexer.
- Ik dit project echt zie als iets voor hobbyisten thuis. In de praktijk denk ik dat die hele admin logging voor DSMR-reader uberhaupt niet nodig is.

Ik kan je zeker aanraden om persoonlijk wat verder in triggers te verdiepen, wellicht kun je het ergens toepassen. Maar voor dit project laat ik het buiten beschouwing.
