### ISSUE TITLE
DSMR webinterface werkt niet

### ISSUE THREAD

**Issue by marco2152** [dsmrreader/dsmr-reader#1214]
De DSMR webinterface werkt niet. Ik heb de volgende acties uitgevoerd (zonder resultaat tot nu toe):
1. DSMR update uitgevoerd
2. Zachte DSMR reload uitgevoerd (./reload.sh)
3. Harde DSMR reload uitgevoerd (sudo supervisorctl restart all)

Foutmelding na laatste commando: 
* Reloading process: dsmr_webinterface (Gunicorn)kill: (589): Operation not permitted

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Wat is de output van:

```
sudo supervisorctl status
```

**Comment by dennissiemensma** [comment]
Houd er trouwens rekening mee dat je `sudo` command **niet als `dsmr`** gebruiker kan uitvoeren. Zowel je derde commando als die van mij net.

Je zult dan even een gebruiker hoger (meestal `pi` of `root`) moeten zijn. Dat kan meestal met `logout` of CTRL+D, er vanuitgaande dat je eerst "van boven naar beneden" bent ingelogd met `sudo su - dsmr`.

**Comment by marco2152** [comment]
Hi Dennis - ja, beide commando's uitgevoerd als pi user. Hier de output:
[image: image.png]
Groeten,
Marco

**Comment by dennissiemensma** [comment]
Bedankt voor je reactie. Afbeeldingen uploaden naar Github per e-mail werkt niet altijd, dus je kunt het beste even inloggen en opnieuw proberen.

**Comment by marco2152** [comment]
![Uploading image.png…]()

**Comment by dennissiemensma** [comment]
Ik denk dat je iets te snel bent geweest. Er staat nu letterlijk: `Uploading image.png…`

Je kunt voordat je op 'Comment' klikt even de preview van je bericht doen hier of die goed is geupload. Soms duurt het een paar tellen en dan zie je in je bericht zoiets verschijnen:

```
![Selection_011](https://user-images.githubusercontent.com/16581744/100152659-507f5080-2ea3-11eb-8159-42c557ca105e.png)
```

**Comment by marco2152** [comment]
Blijft moeilijk dit, poging 5
![image](https://user-images.githubusercontent.com/54395975/100152871-a5bb6200-2ea3-11eb-99f5-60746ca32005.png)

**Comment by dennissiemensma** [comment]
Ah helder. Ik denk dat je het beste even in de logfile kunt kijken wat de fout is. Met:
```
sudo tail /var/log/supervisor/dsmr_webinterface.log -n 30
```

Wat is de output?

**Comment by dennissiemensma** [comment]
Het zou namelijk zomaar kunnen dat je zoiets ziet: `Error: Already running on PID 1234 (or pid file '/var/tmp/gunicorn--dsmr_webinterface.pid' is stale)`

**Comment by marco2152** [comment]
Ja, klopt helemaal. In mijn geval is PID 589.

Groeten,
Marco

**Comment by dennissiemensma** [comment]
In dat geval zul je de pidfile moeten weggooien en dan opnieuw het webinterface proces proberen te herstarten:

```
sudo rm /var/tmp/gunicorn--dsmr_webinterface.pid
sudo supervisorctl restart dsmr_webinterface
```

**Comment by marco2152** [comment]
En opgelost! Bedankt Dennis, heel fijn dat je zo laat nog me kon helpen.

Groeten,
Marco

**Comment by dennissiemensma** [comment]
Fijn om te horen, dank voor je snelle reactie.
