### ISSUE TITLE
Geen dagstatistieken meer sinds 1 okt. Wel live metingen zichtbaar. Retentie?

### ISSUE THREAD

**Issue by BjornB2** [dsmrreader/dsmr-reader#1218]
Hey! 
Ik zie zojuist dat sinds 1 oktober kennelijk geen metingen/dagstatistieken meer worden opgeslagen. Al zoekende kwam ik er achter dat ik geen retentie ingesteld had en dat er dus niks verwijderd werd. Ik gebruik DSMR al een aantal jaren, dus ik gok dat de DB volgelopen is. Ik heb nu wel een retentie ingesteld. Worden de gegevens nu vanzelf opgeschoond of moet ik iets handmatig doen om dit te forceren?

Ik heb overigens net probleemloos mijn docker container kunnen updaten van 3.8 naar de laatste 4.x. zonder extra CLI stappen. Toppertje :)

**Comment by BjornB2** [comment]
<img width="1155" alt="Schermafbeelding 2020-11-27 om 13 38 43" src="https://user-images.githubusercontent.com/3328086/100450439-ebe80f80-30b5-11eb-9fc5-040e8c606f26.png">

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Zijn er nog andere waarschuwingen? Je kunt denk ik het beste even in #1208 kijken voor wat queries om te kijken hoever de retentie is. En het is ook handig om een infodump toe te voegen hier: https://dsmr-reader.readthedocs.io/en/latest/faq.html#debug-info-dump-for-github-issues

**Comment by BjornB2** [comment]
Hey Dennis, 

Dank voor je bericht. Ik denk dat mijn nieuwe retentieinstelling inmiddels 'verwerkt' is. Ik zie opeens weer data, ook voor de periode tussen 1 oktober en nu. Top!
Thanks voor deze super tool 😊 

Björn

**Comment by dennissiemensma** [comment]
Top, fijn om te horen!
