### ISSUE TITLE
nieuwe installatie alles werkt maar geen frames in website

### ISSUE THREAD

**Issue by frenk64** [dsmrreader/dsmr-reader#1220]
Net een nieuwe installatie gedaan kan in de website komen maar zie dat alleen text zonder de frames en kleuren

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Het handigste is om even een screenshot te maken en te kijken of je foutmeldingen ziet in je browser console (F12).

**Comment by frenk64** [comment]
Bij deze dan ik zie fouten voor het laden van de scripts met F12
![DSMR condole](https://user-images.githubusercontent.com/75210444/100585891-95194a80-32ee-11eb-9b6c-2b1305a92a8b.jpg)

**Comment by frenk64** [comment]
Op basis van de f12 info even verder gezocht

Wat ik nu zie dat de benodigde script en images in /home/dsmr......... staan
de NGINX error.log error is not found : /var/www/dsrmr.... en die directory bestaat niet

Denk dat er ergens een link moet zijn klopt dat?

**Comment by frenk64** [comment]
Ik heb option 2 gebruikt voor de installatie, omdat ik nu via de f12 melding erachter kwam dat NGINX dus de "templates"" niet kon vinden verder gezocht en zag in optie 1 dat de directory /var/www/dsmrreader gemaakt wordt die dus bij optie 2 kennelijk niet gemaakt wordt. Verder staat erbij dat dan de bestanden later daar geplaatst worden.

Dus het is opgelost de directory gemaakt en de bestanden daarheen gekopieerd 
F5 in de browser en voila ziet er mooi uit, het is nu ff wachten op het kabeltje

**Comment by dennissiemensma** [comment]
Bedankt voor je update. Ik weet niet hoe je de bestanden hebt gekopieerd, maar je hoeft dat niet handmatig te doen. Ook omdat je wellicht dan met toekomstige updates in de war komt.

Als het goed is heb je deze stappen uitgevoerd: https://dsmr-reader.readthedocs.io/en/latest/installation.html#webserver-nginx-part-1
```
sudo mkdir -p /var/www/dsmrreader/static
sudo chown -R dsmr:dsmr /var/www/dsmrreader/
```

Daarna: https://dsmr-reader.readthedocs.io/en/latest/installation.html#bootstrapping

```
sudo su - dsmr
./manage.py collectstatic --noinput
```

Dat zou afdoende moeten zijn,

**Comment by frenk64** [comment]
Dag Dennis bedankt voor de melding, ik miste inderdaad nog de frames als ik naar het configuratie sub scherm ging.

Maar inderdaad dit is de volledige oplossing, 
Na het uitvoeren ./manage.. werken de andere schermen nu ook.

de eerste drie sudo opdrachten had ik gisteren al gedaan voor het handmatig  kopiëren, maar dat is duidelijk niet voldoende. 

btw ook CU geïnstalleerd om straks de poort even te checken, wat ik destijds al eens gedaan voor een collega
