### ISSUE TITLE
Enkel tarief problemen

### ISSUE THREAD

**Issue by dgreebe** [dsmrreader/dsmr-reader#1232]
De data van de remote datalogger lijkt wel te kloppen als het gaat om de GAS stand. Electra klopt ook, maar bij enkel tarrief klopt te prijs niet. De prijs blijft hangen als HOOG tarief start. 
Verbruik word wel goed gemeten maar de prijs klopt niet.

**Comment by dennissiemensma** [comment]
Bedankt voor je bericht. Ik denk dat je het beste een screenshot en een telegram kan delen om te verduidelijken wat je exact bedoelt.

**Comment by dennissiemensma** [comment]
@dgreebe heb je aanvullende informatie, zodat ik je beter kan helpen?

**Comment by dgreebe** [comment]
mijn energie leverancier biedt enkel tarief aan, maar mijn meter is voor dubbel.
In de DSMR heb ik nu bij beide tarieven hetzelfde bedrag staat en dat is nu opgelost. 
Tevens heb ik ook de datalogger die remote draait geupdate. (nu krijg ik alleen geen gas metingen meer binnen)....

**Comment by dgreebe** [comment]
issue kan dicht. probleem met enkel tarief is niet meer van toepassing.
