### ISSUE TITLE
3.11 upgrade

### ISSUE THREAD

**Issue by dennis071nl** [dsmrreader/dsmr-reader#1236]
Hoi mannen, 

Ik probeer mn 3.11 installatie te upgraden maar bij stap 1 loop ik al vast. Ik werk op basis van docker, dsmr en dsmrdb draaien in principe an sich wel. 

de guide (https://dsmr-reader.readthedocs.io/nl/v4/faq.html#how-to-upgrade) loop ik al vast bij stap 1...:-(

De foutmelding die ik krijg is: 

 --- You are currently running version: 
3.11

 --- Checking Python version.
Running Python 3.8.3 (default, Jun  3 2020, 19:49:40) 
[GCC 9.3.0]

 --- Pulling remote repository for new commits...
./deploy.sh: line 30: git: command not found

 --- Merging/updating checkout.
./deploy.sh: line 36: git: command not found

 >>> Running post-deployment script. <<<

 --- Checking whether VirtualEnv is activated.
     [i] ----- Activating 'dsmrreader' VirtualEnv...
./post-deploy.sh: line 10: /root/.virtualenvs/dsmrreader/bin/activate: No such file or directory
     [!] FAILED to switch to 'dsmrreader' VirtualEnv (is it installed?)
[!] Halted. Post-deployment script exited with non-zero code

Hoop dat jullie me een beetje in de goeie richting kunnen duwen!

Thanks in advance, D

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Vermoedelijk hoef je bij docker alleen de dsmreader app container te updaten naar de laatste versie. Alle technische wijzigingen zouden al in de nieuwe container zelf gedaan moeten zijn. Bij de deploy wordt dan je bestaande database container bijgewerkt zodat die compatibel is met de nieuwere versie. @xirixiz nog aanvullingen?

**Comment by dennis071nl** [comment]
Dennis, ik heb nu als image in mn docker-compose " xirixiz/dsmr-reader-docker:latest ", zou dit niet afdoende moeten zijn dan?

**Comment by dennissiemensma** [comment]
Ik ben zelf helaas niet zo bedreven met docker. Ik ken het oppervlakkig, helemaal voor dsmr reader. Wellicht wordt je image nog gecached of iets?

**Comment by xirixiz** [comment]
Heren, wellicht kan je deze stappen volgen 😉 

https://github.com/xirixiz/dsmr-reader-docker#upgrade-the-postgres-container-to-a-newer-release

Het upgrade meganisme kan je niet "standaard" uitvoeren.

**Comment by xirixiz** [comment]
Ach, ik lees het nog verkeerd ook. Je kan inderdaad gewoon naar de laatste versie van de Docker image en dan gaat het upgraden vanzelf. Voor de zekerheid zou ik wel eerst een database dump maken zodat je iig een backup hebt voordat je upgrade.

https://github.com/xirixiz/dsmr-reader-docker#backup-and-restore-mechanism-1
https://github.com/xirixiz/dsmr-reader-docker#backup-and-restore-mechanism-2

**Comment by dennissiemensma** [comment]
@dennis071nl zie bovenstaande tips, is het inmiddels gelukt?

**Comment by dennis071nl** [comment]
Dennis,

Ik heb alle data weggegooid en helemaal fris opnieuw begonnen... inmiddels
draai ik met 4.9!

Dank voor jullie hulp!

Op di 22 dec. 2020 om 20:13 schreef Dennis Siemensma <
notifications@github.com>:

**Comment by dennissiemensma** [comment]
Oke, mocht je nog je oude data ergens hebben, je kunt de dag- en uurstatistieken vrij makkelijk overzetten hoor!
