### ISSUE TITLE
Electricity grouping type

### ISSUE THREAD

**Issue by rogierlommers** [dsmrreader/dsmr-reader#1249]
Misschien stomme vraag, maar wat moet ik nu precies invullen bij `Electricity grouping type`? Een clean install geeft me dit:

![Screenshot 2021-01-08 at 15 06 00](https://user-images.githubusercontent.com/3907131/104024208-0e943a80-51c3-11eb-955b-60b94f869f95.png)

Ofwel, per minuut. Echter achter value `By reader` staat default. Dit is nu dus niet het geval? Hoe bepaal ik nu waarop ik deze value moet zetten? En welke impact heeft dit?

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Het kan zijn dat die logica niet helemaal lekker is of afhankelijk van je meterversie.

De keuze hangt er vanaf hoeveel meetpunten in je de live grafieken wil. Voor het meten van het gebruik maakt het verder niet uit omdat daarvoor altijd het begin en einde van een uur of dag genomen wordt. Groeperen zorgt dus voor wat minder data.

Voor DSMR v4 meters zijn er 6 metingen per minuut. Voor DSMR v5 meters 60, dus vandaar de optie om die 6 of 60 te groeperen om het wat leesbaarder te maken.

**Comment by rogierlommers** [comment]
Thanks.

**Comment by dennissiemensma** [comment]
In de volgende release zal ik het verduidelijken in de admin.
