### ISSUE TITLE
  Dagstatistieken lopen achter.

### ISSUE THREAD

**Issue by iepmaatje** [dsmrreader/dsmr-reader#1251]
Hallo Allemaal, Ik draai DSMR met een aparte datalogger. Tot gisteren liep alles gesmeerd, maar vanochtend zag ik ineens de melding "   Dagstatistieken lopen achter   (1 dag, 12 uur geleden)"  Er is niets verandert door mij. Waar komt deze melding vandaag ? Ik heb nog steeds ' Live' data, alleen geen dagstatistiek van gisteren...

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Je kunt het beste eerst #1230 lezen en https://github.com/dsmrreader/dsmr-reader/issues/1197#issuecomment-724968648 proberen. Ik hoor graag of je daar iets kan vinden.

**Comment by iepmaatje** [comment]
Hallo Dennis, ik lees de volgende Error in de backend log file:
" ERROR    HTTPSConnectionPool(host='data.buienradar.nl', port=443): Max retries exceeded with url: /2.0/feed/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f70d630b250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Traceback (most recent call last):"

Is het niet kunnen bereiken van Buienradar de oorzaak van het ontbreken van de dagstatistiek ?

**Comment by dennissiemensma** [comment]
Bedankt voor de update. Je zult denk ik debug logging moeten aanzetten en zoeken naar de meldingen in de gelinkte comment in #1197 om de oorzaak te achterhalen. De buienradar error is ongerelateerd. En ik neem aan dat je geen andere meldingen hebt in de About pagina?

**Comment by iepmaatje** [comment]
Hallo Dennis, Ik zie in de DEBUG dat de gas gegevens niet meer doorkomen.. dit zal de oorzaak zijn. 

2021-01-13 10:33:10,460] DEBUG    SP: Running "Generate day and hour statistics" (dsmr_stats.services.run)
[2021-01-13 10:33:10,486] DEBUG    Stats: Waiting for first gas reading on the next day...
[2021-01-13 10:33:10,488] DEBUG    SP: Rescheduled "Generate day and hour statistics" to 2021-01-13 10:38:10.486698+01:00 (ETA 0:04:59.998217)

Ik heb 'gas' uitgeschakeld in de backend en nu komen de dagstatistieken weer door :-)
Wil natuurlijk wel gas bijven monitoren, enig idee wat ik nu moet doen ? Sorry voor al mijn vragen...

**Comment by iepmaatje** [comment]
Hallo Dennis, Na wat meer speurwerk zie ik dat mijn slimme meter geen gasgegevens ontvangt.. Ligt dus niet aan DSMR.
Tijdelijk uitzetten van de gasgegevens in de backend heeft vootlopig de oplossing gebracht. Thanks voor je support !

**Comment by dennissiemensma** [comment]
Fijn dat je het gevonden hebt. Mocht je later nog andere issues hebben, koppel het gerust weer terug!
