### ISSUE TITLE
MQTT: Nieuwe DSMR-reader releases

### ISSUE THREAD

**Issue by poudenes** [dsmrreader/dsmr-reader#1255]
Hoi Allen,

Ik open regelmatig de DSMR pagina om te kijken of er een update is.
Het zou mooi zijn als er een MQTT meegezonden wordt wanneer er een nieuwe versie beschikbaar is.

Systeem checkt oude versie gelijk aan nieuwe versie dan is MQTT Update "false"
oude versie anders dan nieuwe  versie dan is MQTT Update "true"

Zo kan ik in HA bijvoorbeeld een automation maken. Een notificatie sturen als er een update beschikbaar is

:)

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Wellicht dat ik het meeneem zodra er nieuwe MQTT-features komen, maar voorlopig laat ik het even voor wat het is.

**Comment by Thuurke** [comment]
Ik los dit nu op door de notifications pagina van de installatie uit te lezen. Als hier There is a newer version of..dan wordt de counter meer dan 1. Opslaan in een json en die laten uitlezen. werkt naar behoren.

```
import datetime as dt
from urllib.request import urlopen
import json

now = dt.datetime.now()
now_formatted = now.strftime("%d-%m-%Y %H:%M:%S")

url = "http://x.x.x.x/notifications"
page = urlopen(url)
html = page.read().decode("utf-8")
text_to_find = "There is a newer version of DSMR-reader available."
text_index = html.find(text_to_find)

count = html.count(text_to_find)

if count == 0: 
   status="Uit"
else:
   status="Aan"

datastore = []
datastore = {
             'status':     status,
             'count':     count,
             'last_checked': now_formatted,
             }

json.dumps(datastore)

with open("dsmr_update.json", "a") as outfile:
    json.dump(datastore, outfile)
    outfile.write('\n')    
```

**Comment by dennissiemensma** [comment]
@Thuurke je kunt nog overwegen om simpelweg de XHR-request te doen die de About-pagina ook doet:

```
GET /about/xhr/update-check
```

```
{"is_latest_version": true}
```

Wellicht versimpelt dat je check.

**Comment by Thuurke** [comment]
@dennissiemensma  Oke dat zou inderdaad wat code regels schelen :)

**Comment by skank01** [comment]
+1 voor update mqtt

**Comment by dataegg** [comment]
> @Thuurke je kunt nog overwegen om simpelweg de XHR-request te doen die de About-pagina ook doet:
> 
> ```
> GET /about/xhr/update-check
> ```
> 
> ```
> {"is_latest_version": true}
> ```
> 
> Wellicht versimpelt dat je check.

Met deze info kun je hier prima een binary sensor voor maken in HA

**Comment by dennissiemensma** [comment]
Ik heb hier opnieuw naar gekeken, maar het is relatief veel werk om dit via MQTT te realiseren, dus ik laat het voor wat het is. Dan besteed ik liever mijn beschikbare tijd aan features zoals #1291.

Ook omdat er alternatieve methodes zijn. 
- `GET /about/xhr/update-check`
- https://api.github.com/repos/dsmrreader/dsmr-reader/tags
