### ISSUE TITLE
Samenvatting energiecontracten verbeteren

### ISSUE THREAD

**Issue by PhyxionNL** [dsmrreader/dsmr-reader#1257]
Een aantal vragen/opmerkingen over energiecontracten.

1. **Totaal** staat onder het gas, dit is niet heel logisch omdat gas en stroom verschillende eenheden zijn. Eigenlijk zou je het zo willen: 
![image](https://user-images.githubusercontent.com/7643972/104811371-3efb5a80-57fb-11eb-870d-348ecc0d78e6.png) 
Eventueel aangevuld met **Totaal** kWh net als de tarieven erboven.

2. Ik heb mijn retentieconfiguratie op "Uitgeschakeld" staan, dit wil ik graag op één jaar zetten, maar wat voor impact heeft dit op de energiecontracten? Er staat alleen:
_De volgende gegevens worden nooit opgeschoond:_
    Dagtotalen/statistieken (zoals weergegeven in het Archief).
    Uurtotalen/statistieken (zoals weergegeven in het Archief).
    De eerste meting van elk uur.
    De laatste meting van elk uur.

3. "Daarnaast wordt teruggeleverde energie niet verrekend in de kosten. De teruggeleverde kWh wordt hier alleen voor de volledigheid getoond.". Dat klopt niet want dit wordt wel meegerekend (wat overigens klopt want de opbrengst van de opgeleverde energie kan je uiteraard aftrekken van de totale kosten van je energiecontract).

**Comment by dennissiemensma** [comment]
Bedankt voor je vragen. Hierbij per stuk een toelichting:

1. De huidige opzet is inderdaad niet ideaal, maar was meer om het compact te houden (vooral op kleinere schermen). Ik wil best wel een keer voor je kijken of ik er nog een regel tussen kan drukken, als dat het duidelijker maakt.

2. De [totalen van de energiecontracten](https://github.com/dsmrreader/dsmr-reader/blob/2c1ce8550b1ea9fd6e5ff769538b1cde85fa267e/dsmr_consumption/services.py#L500-L504) komen uit [dezelfde bron](https://github.com/dsmrreader/dsmr-reader/blob/2c1ce8550b1ea9fd6e5ff769538b1cde85fa267e/dsmr_stats/services.py#L280-L297) als het Archief, dus automatisch opschonen heeft daar **geen** invloed op. Eigenlijk werkt het hetzelfde als [het Archief](https://github.com/dsmrreader/dsmr-reader/blob/2c1ce8550b1ea9fd6e5ff769538b1cde85fa267e/dsmr_stats/services.py#L253-L277) in jaar-niveau, alleen zijn de start- en einddatums gebaseerd op de contractdatums (tenzij iemand toevallig ook contracten heeft van 1 jan - 31 dec).

3. Het is mij niet helemaal duidelijk wat je bedoelt. Heb je misschien een screenshot van je eigen situatie? Ik heb zelf geen teruglevering, dus ik kan hier niet makkelijk simuleren wat je bedoelt.

**Comment by PhyxionNL** [comment]
Zie onderstaand 😊
1. Op zich hoeft dat niet eens, alleen het totaal één regel omhoog (evt. met kWh erachter) zoals op mijn screenshot is genoeg. Nu staat die onderaan en is het net alsof het gas er ook bij hoort.
2. Prima, dan pas ik dat aan.
3. In de omschrijving staat die tekst: 
![image](https://user-images.githubusercontent.com/7643972/104815944-23eb1380-5818-11eb-9eb8-d7f00a0cd3f2.png) 
DSMR reader doet dat wel, en dat is ook correct (de oplevering gaat van het verbruik af, want dat kost je natuurlijk ook niks), alleen die tekst klopt dus niet. 

![image](https://user-images.githubusercontent.com/7643972/104816008-99ef7a80-5818-11eb-8781-4741f21ab35d.png)

**Comment by dennissiemensma** [comment]
Aah helder, dank voor de toelichting. Ik zal de tekst voor teruglevering wat aanpassen. Het ging mij er destijds vooral om dat DSMR-reader geen rekening houdt qua kosten met salderen (vooral bij afwijkende saldering). 

Wat betreft de totalen, ik weet dan niet of dat dan helemaal lekker gaat. Het was de bedoeling dat die totaalregel qua prijs het totaal van alles is en niet alleen van elektra. Vandaar dat er dan mogelijk een extra regel bij moet.

**Comment by PhyxionNL** [comment]
> Wat betreft de totalen, ik weet dan niet of dat dan helemaal lekker gaat. Het was de bedoeling dat die totaalregel qua prijs het totaal van alles is en niet alleen van elektra. Vandaar dat er dan mogelijk een extra regel bij moet.

Dat lijkt mij ook handig inderdaad, maar een totaal van verschillende eenheden (zoals dat nu het geval is) is in ieder geval niet erg nuttig.

**Comment by dennissiemensma** [comment]
Ik heb losgetrokken voor de volgende release:

![Selection_001](https://user-images.githubusercontent.com/16581744/104845462-efd62800-58d5-11eb-9ad5-a74345db8d4b.png)


![Selection_002](https://user-images.githubusercontent.com/16581744/104845463-f06ebe80-58d5-11eb-931c-0bf0ae14ec24.png)

**Comment by dennissiemensma** [comment]
De tekst bovenin is straks ook aangepast en wat generieker gemaakt.

**Comment by dennissiemensma** [comment]
Onderdeel van [v4.12](https://github.com/dsmrreader/dsmr-reader/releases/tag/v4.12.0)

**Comment by martijnb92** [comment]
Het lijkt mij persoonlijk handig om deze nieuwe layout ook toe te passen op de dashboard pagina ipv alleen op de energiecontracten pagina :smiley:

**Comment by dennissiemensma** [comment]
Ik zal het meenemen voor de release van aankomende week. Dashboard is daar namelijk sowieso al wat aangepast:

![Screenshot_2021-03-07 Dashboard DSMR Reader(1)](https://user-images.githubusercontent.com/16581744/110256333-9bc3f780-7f98-11eb-84be-c737f72806a0.png)
