### ISSUE TITLE
InfluxDB: Field type conflict: input field “returned_2” is type float, already exists as integer

### ISSUE THREAD

**Issue by SanderGit** [dsmrreader/dsmr-reader#1261]
DSMR-reader: 4.10 in Docker

Ik heb deze aan InfluxDB gekoppeld. Er komt wel data in terecht maar het gaat niet goed. Als ik de data handmatig wil synchroniseren komt er een foutmelding.

Debug info:
```
DSMR-READER
    App / Python / Database                                                       v4.10 / v3.9.1 / postgresql
    BE sleep / DL sleep / Retention / Override                                     1.0s / 5.0s / 672h / False
    Latest telegram version read / Parser settings                                                 "50" / "4"

DATA
    Telegrams total (est.)                                                                              24097
    Consumption records electricity / gas (est.)                                                   2609 / 309

```
Foutmelding:

```
raise InfluxDBClientError(err_msg, response.status_code)                                           
influxdb.exceptions.InfluxDBClientError: 400: {"error":"partial write: field type conflict: input field \"returned_2\" on measurement \"electricity_positions\" is type float, already exists as type integer 
dropped=200"}                                                                     

```
Het weggooien en opnieuw aanmaken van de InfluxDB database helpt niet.

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Voor de duidelijkheid: Krijg je ook een fout in de automatische synchronisatie? 
Of alleen bij het uitvoeren van `./manage.py dsmr_influxdb_export_all_readings`?

**Comment by SanderGit** [comment]
> Bedankt voor je melding. Voor de duidelijkheid: Krijg je ook een fout in de automatische synchronisatie?
> Of alleen bij het uitvoeren van `./manage.py dsmr_influxdb_export_all_readings`?

Bij het configureren van de automatische sync krijg ik geen melding. Als er een issue met de verbinding is gaat het vinkje ‘enabled’ uit. Een foutmelding heb ik niet gezien. De pagina ‘Influxdb measurements’ is leeg sinds de koppeling er in principe wel is.

Er wordt volgens mij wel data in geschreven, alleen krijg ik het er in Grafana nog niet uit met dit dashboard:
https://github.com/iotassistant/iotassistant.io/blob/master/grafana-dashboard.json

Edit: ik denk dat die json ook niet klopt met wat er de database in gaat dus die moet ik aanpassen.

**Comment by dennissiemensma** [comment]
De pagina `Influxdb measurements` in DSMR-reader weergeeft alleen gegevens die wachten op verzending. Als er geen achterstand is, zul je daar inderdaad niet vaak gegevens zien.

Krijg je dezelfde fout als je dit probeert?
```
./manage.py dsmr_influxdb_export_all_readings --to-influx-database testje
```

**Comment by SanderGit** [comment]
Dan doet ie het zonder foutmelding.
Edit: als ik delivered_2 uitcommentarieer valt hij vervolgens over current_l1
Als ik die ook uitcommentarieer, idem voor current_l2 en current_l3, kan ik wel importeren.
Daarna heb ik ze weer aangezet.

**Comment by dennissiemensma** [comment]
Je kunt nog proberen om het eerst te exporteren naar een aparte InfluxDB-database, met bovenstaand commando (totdat alles over is). En daarna ook de automatische export te wisselen naar die database.

**Comment by SanderGit** [comment]
Het is nog weinig data dus ik vind het wel goed zo. Ik zal dit issue sluiten. Bedankt voor het meedenken!

Wel ben ik benieuwd of er ergens een lijst met variabelen/velden is die ik naar InfluxDB kan sturen, ik vind in de MQTT-documentatie wel wat dingen maar heb nog geen compleet overzicht gezien.
Power failures, sags e.d. zie ik er in de standaardconfiguratie niet standaard bij staan bijvoorbeeld.

**Comment by dennissiemensma** [comment]
Top! Wat betreft gegegevens, zie issue #1250. De InfluxDB-export is alleen bedoeld voor metingen. Daarmee kan iemand zelf aggregraties doen (dat doet DSMR-reader immers ook, op een eigen manier).

Het kan nog wel zijn dat ik de integratie ooit nog wat dichter bij de metingen maak, voor de meterstatistieken. Want om te voorkomen dat er tig reccords zijn met dezelfde meterstatistieken, scheidt  DSMR-reader ze nu. Daarom staan die niet bij de "metingen", als bijeffect van die scheiding.

Het is namelijk te veel werk om ondersteuning voor elk extern type database of protocol te maken, voor elk type gegeven in DSMR-reader. 
Daarom houd ik het doorgaans bij een REST API voor het pullen van data en MQTT voor het pushen van data. Voor MQTT komt er nog wel een uitbreiding in de toekomst, want daar is momenteel nog niet alles in beschikbaar.
