### ISSUE TITLE
Vaste dagkosten via MQTT naar HA

### ISSUE THREAD

**Issue by skank01** [dsmrreader/dsmr-reader#1289]
Ik kijk er vermoedelijk over, maar het zou handig zijn mochten de vaste kosten per dag/maand/jaar ook via mqtt doorgaan naar HA

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Dit is denk ik nog niet gedocumenteerd. Je kunt dit gebruiken in de MQTT-mapping van de dagtotalen:

```
# JSON-variant
fixed_cost = dsmr/day-consumption/fixed_cost
```

```
# Per-topic
fixed_cost = fixed_cost
```

Ik zal dit in de volgende release opnemen in de admin-pagina.

**Comment by dennissiemensma** [comment]
Voor maand/jaar totalen neem ik dat mee in #989

**Comment by dennissiemensma** [comment]
Onderdeel van [v4.12](https://github.com/dsmrreader/dsmr-reader/releases/tag/v4.12.0)
