### ISSUE TITLE
Digitale Meter België, verkeerd inlezen

### ISSUE THREAD

**Issue by HansG130** [dsmrreader/dsmr-reader#1290]
Ik het een Belgische digitale meter aangesloten op de p1 poort.
Ik merk op dat hij de tarieven omgewisseld heeft. Overdag neemt hij Laag en 's nachts Hoog tarief.

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Dit kun je zelf in DSMR-reader oplossen door de tarieven in de frontend-configuratie te hernoemen (om te draaien).

Voor meer achtergrond zie:
- #750
- #858
- #856
