### ISSUE TITLE
Feature request: Totaal verbruik archive screen & doorlinken naar dag view

### ISSUE THREAD

**Issue by Koal4** [dsmrreader/dsmr-reader#1293]
Is het misschien mogelijk om totaal verbruik ook te vermelden onder de 'mouse hoover' in archive screen?

![image](https://user-images.githubusercontent.com/10795027/107865575-17ce9200-6e68-11eb-8c81-9443b4e13d06.png)

Ik begrijp dat je dit ook aflezen vanuit de grafiek maar daar kan ik niet de onderscheid maken of het no 7 of 8 is.,

Tevens kwam ik ook meteen op het idee of het mogelijk is om op een dag (onder maand view) te kunnen kunnen klikken zodat je meteen naar de de daily view gaat?

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik zal er ooit opnieuw naar kijken, maar ik weet wel dat het niet heel triviaal is om werkend te krijgen. Hier heeft ook iemand eerder naar gekeken.

**Comment by dennissiemensma** [comment]
Ik heb hier nogmaals naar gekeken en het is inderdaad helaas niet heel triviaal. Dus ik laat dit voor nu voor wat het is.
