### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by corchat** [dsmrreader/dsmr-reader#1295]
Het lijkt erop dat de buienradar plugin 1 keer per uur update.
De data van buienradar update elke 10 minuten.
Kan er een gebruikerskeuze worden ingebouwd voor de update interval zodat je kan kiezen hoe vaak de data wordt opgehaald.

Groet Cornelis

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. De huidige weergegevens in DSMR-reader zijn puur bedoeld als indicatie, zodat later terug te zien is of de temperatuur bijvoorbeeld veel hoger of later was dan een voorgaand jaar.

Daarom laat ik de interval voor wat het is, ook omdat het naar verwachting weinig invloed heeft qua daggemiddelde en de hoogste/laagste temperatuur.
