### ISSUE TITLE
Supervisor-processen verplaatsen van /var/tmp/ naar /tmp/

### ISSUE THREAD

**Issue by dennissiemensma** [dsmrreader/dsmr-reader#1297]
Uitzoeken of de PID-files van de Supervisor-processen in `/tmp/` kunnen, ipv `/var/tmp/`. Dit zodat ze na een (onvoorziene) reboot automatisch verwijderd worden.

Deployscript moet dan ook aangepast worden.

**Comment by GieltjE** [comment]
Is /run hier niet beter voor? Minder problemen met systemd i.c.m. b.v. apache reverse proxy, en deze word normaliter ook opnieuw opgebouwd.

**Comment by dennissiemensma** [comment]
De run-mappen zijn idd beter, alleen weet ik niet of ik daar tegen permissies aan ga lopen omdat de processen niet als root draaien. Ik zal het tzt even proberen.

**Comment by GieltjE** [comment]
Nadat ik wisselde naar systemd (alsin compleet init systeem), waren er juist issues met /tmp, /var mocht apache daarintegen wel bij.
Wel even het volgende toevoegen aan het webinterface .service bestand zodat systemd automatisch /run/dsmr aanmaakt:
```
[System]
RuntimeDirectory=dsmr
```

**Comment by dennissiemensma** [comment]
Bedoel je dat je uberhaupt geen Supervisor gebruikt? Want dan ga je denk ik ook geen last hebben van deze wijziging. Het gaat vooral om de PID-file van Gunicorn namelijk, die in de huidige versie een reboot overleeft.

**Comment by GieltjE** [comment]
Inderdaad helemaal geen supervisor(d), was ik vergeten te vermelden.

**Comment by dennissiemensma** [comment]
Hier nog wat achtergrond: https://wiki.debian.org/ReleaseGoals/RunDirectory

`/run` is een tmpfs, wat perfect is. Alleen zit ik dan nog met de permissies en dat lijkt wat lastiger, omdat die bij elke reboot hersteld moeten worden. Dus ik denk dat het uiteindelijk alsnog uitkomt op iets in `/tmp/`
