### ISSUE TITLE
Rework documentation structure

### ISSUE THREAD

**Issue by dennissiemensma** [dsmrreader/dsmr-reader#1315]
Momenteel is de documentatie redelijk uitgewerkt. Echter, ik merk dat het moeilijk is om er een goede structuur in te maken. Het is namelijk deels promotie van features, deels FAQ/zelfhulp, deels handleidingen en ik merk dat het soms wat lastig is om daar een natuurlijke indeling in te maken.

Een tijdje terug kwam ik deze tegen en dat is superinteressant, namelijk gewoon de documentatie splitsen in vier categorieen:
https://documentation.divio.com/

- Tutorials
- How-to
- Explanation
- Reference

Moeite waard om wat tijd in te steken. Ik denk dat het uiteindelijk de gebruikers goed kan helpen.

**Comment by jeroenpeters1986** [comment]
Zeker de moeite waard, ik gebruik dat veel voor DjangoCMS en als
gebruiker/lezer is dat heel erg fijn!
-- 
Groeten,

Jeroen Peters

**Comment by dennissiemensma** [comment]
Eerste opzet staat. Zal wel wat iteraties nodig hebben voordat het optimaal is.
