### ISSUE TITLE
Cannot login to admin interface

### ISSUE THREAD

**Issue by ualex73** [dsmrreader/dsmr-reader#1323]
I tried to login today to my admin interface, but it doesn't let me in. I used the procedure:
`./manage.py changepassword admin`
To change it, but that doesn't work either ... any other option to reset to troubleshoot this?

**Comment by ualex73** [comment]
found it ;-)

**Comment by Jhack159** [comment]
> found it ;-)

Hello, 
What is the solution ? I 'm also looking for.

Tnx

Jack

**Comment by dennissiemensma** [comment]
@Jhack159 https://dsmr-reader.readthedocs.io/en/v5/how-to/admin/set-username-password.html
