### ISSUE TITLE
Error in upgrade van 4.12 naar 4.13 tijdens de-installatie van six

### ISSUE THREAD

**Issue by reboot1983** [dsmrreader/dsmr-reader#1326]
Hi,

Tijdens de upgrade van .12 naar .13 kreeg ik onderstaande foutmelding in de console. Ik ben niet helemaal zeker of het 'critial' is, want na de upgrade lijkt dsmr-reader wel gewoon prima te functioneren.

![image](https://user-images.githubusercontent.com/20405704/111875388-d31fa480-8999-11eb-92d2-f3643932a0c9.png)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Gaat het script wel door en krijg je aan het eind iets als `>>> Deployment complete. <<<`?

Zo ja dan voorzie ik verder geen problemen, helemaal als DSMR-reader lijkt te werken. De foutmelding gebeurt namelijk tijdens het installeren van externe libraries.

**Comment by reboot1983** [comment]
Sorry, dat had ik er best ff bij kunnen vermelden inderdaad.
Ja, het script is netjes doorgegaan en aan het einde gaf hij aan klaar te zijn en de nieuwe versie is nu 4.13.

**Comment by dennissiemensma** [comment]
Oke prima! Ik zal voor de zekerheid een extra check toevoegen aan het deplyscript voor een volgende release. Dank voor je melding!
