### ISSUE TITLE
Enter historical data

### ISSUE THREAD

**Issue by Systemedic** [dsmrreader/dsmr-reader#1330]
On March 1st I switched from energy supplier. I just started with DSMR-Reader and it would be nice to have a option to read out the data from the 1st of March or enter it manually (I can get the data from Oxxio). Is there an option for that?

**Comment by dennissiemensma** [comment]
You can manually enter day totals per date on: `/admin/dsmr_stats/daystatistics/add/`
It will be displayed in the Archive accordingly.

**Comment by Systemedic** [comment]
Awesome! I could have find that myself.. Didn't know where to start.
