### ISSUE TITLE
Upgrade to eCharts 5

### ISSUE THREAD

**Issue by dennissiemensma** [dsmrreader/dsmr-reader#1331]
https://echarts.apache.org/en/tutorial.html#New%20features%20in%20ECharts%205

Los van de update zelf kan dit interessant zijn:
> Time Axis
> Apache ECharts 5 brings a time axis suitable for expressing timestamp scales.

Verder ziet het er iets gelikter uit, subtiele verschillen in rendering, tooltips, etc voor wat ik zo 1-2-3 even zie.

**Comment by dennissiemensma** [comment]
Inmiddels goed werkend.

**Comment by AbelLykens** [comment]
Tof. Die negatieve grafieken zijn fijn. Enige onhandige is dat voltagegrafiek y op 0 begint dus dat je schommeling minder ziet :)

**Comment by dennissiemensma** [comment]
@AbelLykens bedankt voor je terugkoppeling. 

De voltages worden gefixt in de volgende release. Je kunt het tot die tijd evt handmatig fixen met: https://github.com/dsmrreader/dsmr-reader/issues/1349#issuecomment-812889240
