### ISSUE TITLE
⚠️ pyyaml==5.4.1 / ModuleNotFoundError: No module named 'setuptools._distutils' / KeyError: 'pyyaml'

### ISSUE THREAD

**Issue by tctr74** [dsmrreader/dsmr-reader#1334]
Ik krijg een error tijdens de upgrade van v4.13 naar v4.14. Zo te zien in het post-deploy script. De foutmelding is bijgevoegd
[deploy.log](https://github.com/dsmrreader/dsmr-reader/files/6201082/deploy.log)

Na het handmatig starten lijkt de webinterface ook niet goed meer te werken. Het huidige verbruik en de live grafieken worden niet weergegeven, maar de logging lijkt verder wel goed te gaan.
![image](https://user-images.githubusercontent.com/81334581/112396904-583fec00-8d01-11eb-9f7a-f21ab31f0f91.png)
![image](https://user-images.githubusercontent.com/81334581/112397222-f338c600-8d01-11eb-8e09-7df41be1960a.png)

Debug info dump:
```

DSMR-READER
    App / Python / Database                                                       v4.14 / v3.7.3 / postgresql
    BE sleep / DL sleep / Retention / Override                                    1.0s / 5.0s / 2016h / False
    Latest telegram version read / Parser settings                                                 "50" / "4"
    (!) Database migrations pending                                                                     4 (!)

DATA
    Telegrams total (est.)                                                                            1228300
    Consumption records electricity / gas (est.)                                               135735 / 35497

POSTGRESQL SIZE OF LARGEST TABLES (> 500 MB)
    public.dsmr_datalogger_dsmrreading                                                                 502 MB

```

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. **Wat voor OS gebruik je?**


De fout lijkt:
```
ModuleNotFoundError: No module named 'setuptools._distutils'
```

Dit is een tijdje terug ook gemeld in #1307. Je zou die tip kunnen proberen:

```
sudo su - dsmr
export SETUPTOOLS_USE_DISTUTILS=stdlib
./deploy.sh
```

Lost dat het issue voor je op?

**Comment by tctr74** [comment]
Hoi,

sudo su - dsmr
export SETUPTOOLS_USE_DISTUTILS=stdlib
./deploy.sh

werkt inderdaad!

Mijn OS is Raspbian 10 op een Pi 3B+.

Thanks!

**Comment by dennissiemensma** [comment]
Fijn om te horen, dank voor de terugkoppeling!
