### ISSUE TITLE
Teruglevering verbergen op Statistieken-pagina

### ISSUE THREAD

**Issue by reboot1983** [dsmrreader/dsmr-reader#1337]
When going to the statistics page I see the usage in "HOOGTE- EN LAAGTE RECORDS", but it is stating 'hoogste teruglevering', but we are not returning power to the net. We only take the power. I think there is a wrong label here? It should state 'hoogste verbruik' (per fase). The lowest usage is correct.

Version is the current latest: 4.14
![image](https://user-images.githubusercontent.com/20405704/112684865-f5229680-8e73-11eb-9328-4d64911b0ed0.png)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Ik heb zelf dezelfde situatie thuis (geen teruglevering) en had er eerder geen verklaring voor. Ik kan me vaag herinneren dat ik het ook echt zo zag staan in de geschiedenis, hoewel dat niet het ruwe telegram was.

![Screenshot_2021-03-26 Statistics DSMR Reader](https://user-images.githubusercontent.com/16581744/112697816-acc1a380-8e88-11eb-94c2-ec006eaff438.png)

Ik heb het al een paar keer gereset, maar het blijft willekeurig terugkomen, dus ik heb het maar gelaten voor wat het was.

----

Afhankelijk van of en hoever je automatische dataopschoning aan hebt staan, kun je zelf kijken of je nog het betreffende (geparste) telegram van 5 maart kan terugvinden op deze URL:

```
/admin/dsmr_datalogger/dsmrreading/?timestamp__range__gte_0=2021-03-05&timestamp__range__gte_1=14%3A54%3A00&timestamp__range__lte_0=2021-03-05&timestamp__range__lte_1=14%3A55%3A00
```

En dan kijken wat er staat bij:
```
Electricity currently returned:
0.000
Current electricity returned in kW
```

----

Voor echt goed onderzoek bij mezelf zou ik eigenlijk al mijn ruwe telegrammen ergens moeten opslaan en dan hopen dat het komende maanden weer een keertje voor komt, maar vond het zelf wat veel werk om dat te doen.

**Comment by reboot1983** [comment]
![image](https://user-images.githubusercontent.com/20405704/112719352-dca88f80-8ef8-11eb-96c2-964ed4c6bf7e.png)
![image](https://user-images.githubusercontent.com/20405704/112719355-e3cf9d80-8ef8-11eb-8146-c397a4eec9a0.png)

Dit is wat ik heb staan als ik jouw link volg. En Tevens heb ik nog gisteren er even bij gezet. Ik zie overal bij 'returned' 0,000 staan. 
Ik heb ook steekproeven gehouden en alles in de tussenliggende periode (het zijn nogal wat bladzijden, vandaar steekproeven) staat returned op 0,000.

Ik kan me niet herinneren dat ik het eerder heb gezien. Ik heb nog wel een screenshot gevonden dat ik op 13-02-2021 heb gemaakt. Daar zie ik dat de labels wel goed staan (zie hieronder). Mij kennende zat ik toen op de dan recentst uitgebrachte versie.

![image](https://user-images.githubusercontent.com/20405704/112719548-be8f5f00-8ef9-11eb-8a74-1de5f79da16e.png)

En als ik van die periode kijk, dan is de data al niet meer zo uitgebreid en kom ik op onderstaande.

![image](https://user-images.githubusercontent.com/20405704/112719636-1cbc4200-8efa-11eb-9f69-58ce2dfc05c0.png)

En in het kader van informatieverstrekking. Deze optie heb ik geactiveerd, maar lijkt verder geen invloed te hebben op de huidige weergave. Zowel geactiveerd als gedeactiveerd wordt in de statistiekenpagina het verkeerde label getoond.

![image](https://user-images.githubusercontent.com/20405704/112719790-ff3ba800-8efa-11eb-9222-231c88ebee67.png)

**Comment by reboot1983** [comment]
Overigens nog een kleine sidenote van deze pagina: de kolomkoppen staan hier in het Engels i.p.v. NL

**Comment by dennissiemensma** [comment]
Bedankt voor je aanvulling. De Statistieken-pagina is wel aangepast bij de laatste release, dus ik heb [de template even opnieuw voor je gecheckt](https://github.com/dsmrreader/dsmr-reader/blob/v4.14.0/dsmr_frontend/templates/dsmr_frontend/statistics.html#L227-L271). De mapping lijkt daar wel goed. Als in dat deze velden gebruikt worden:
```
highest_return_l1_value
highest_return_l2_value
highest_return_l3_value
```

Je kunt ze even checken in de database:
```
sudo su - postgres
psql dsmrreader
\x on

select * from dsmr_stats_electricitystatistics;
```

Dan krijg je zoiets:
```
-[ RECORD 1 ]---------------+-----------------------
id                          | 1
highest_usage_l1_timestamp  | 2019-06-09 17:02:20+01
highest_usage_l2_timestamp  | 2019-10-05 11:34:16+01
highest_usage_l3_timestamp  | 2020-12-28 11:57:37+00
highest_return_l1_timestamp | 2020-08-06 20:56:25+01
highest_return_l2_timestamp | 2020-12-02 10:54:02+00
highest_return_l3_timestamp | 2021-02-07 10:48:57+00
highest_usage_l1_value      | 4.301
highest_usage_l2_value      | 6.224
highest_usage_l3_value      | 3.728
highest_return_l1_value     | 0.163
highest_return_l2_value     | 0.095
highest_return_l3_value     | 2.630
lowest_usage_l1_timestamp   | 2019-03-29 16:36:25+00
lowest_usage_l1_value       | 0.006
lowest_usage_l2_timestamp   | 2021-02-19 10:39:13+00
lowest_usage_l2_value       | 0.008
lowest_usage_l3_timestamp   | 2018-11-14 09:30:38+00
lowest_usage_l3_value       | 0.001
```

----

Als de eerdere zoekopdracht via de GUI geen resultaten toont, kun je het snelste via de database checken welke metingen uberhaupt een teruglevering hadden.

Ik zie nu trouwens ook dat de statistieken een ander veld gebruiken, [die van de fasen en niet 'currently returned'](https://github.com/dsmrreader/dsmr-reader/blob/v4.14.0/dsmr_stats/services.py#L367-L377).
```
sudo su - postgres
psql dsmrreader
\x on

select id, timestamp, electricity_currently_returned, phase_currently_returned_l1, phase_currently_returned_l2, phase_currently_returned_l3 from dsmr_datalogger_dsmrreading where phase_currently_returned_l1 > 0 or phase_currently_returned_l2 > 0 or phase_currently_returned_l3 > 0 limit 10;
```

Ik zie nu zelf ook een resultaat op **L3**:
```
-[ RECORD 1 ]------------------+-----------------------
id                             | 13369127
timestamp                      | 2020-04-12 19:00:07+01
electricity_currently_returned | 0.000
phase_currently_returned_l1    | 0.000
phase_currently_returned_l2    | 0.000
phase_currently_returned_l3    | 0.001

```


----

Hoe dan ook is het denk ik goed dat ik het in een volgende release dan maar hardcoded ga verbergen. Op de meeste plekken toont DSMR-reader teruglevering op basis van checks, maar op deze pagina nog niet, zoals je al hebt geprobeerd.

**Comment by reboot1983** [comment]
Eerste query:
![image](https://user-images.githubusercontent.com/20405704/112749253-720f5680-8fc1-11eb-87bf-a3e6ef044cc4.png)

Tweede query:
![image](https://user-images.githubusercontent.com/20405704/112749277-92d7ac00-8fc1-11eb-8855-525ae61604e0.png)

**Comment by dennissiemensma** [comment]
Dank voor de update. Ik zie het al, het is de NL-vertaling. Die klopt niet. In je intiele screenshot staan de kleuren er niet bij, dus valt het me nu pas op. Klopt het dat de kleuren bij teruglevering bij jou **rood** zijn?

**Comment by dennissiemensma** [comment]
~Aah nvm, in je tweede screenshot staan ze erbij en daar zijn ze idd rood.~ Ik zal de vertaling fixen, maar hoe dan ook de teruglevering verbergen als die er niet is.

**Comment by dennissiemensma** [comment]
Hier kun je het goed zien, ze staan dubbel.

![Selection_002](https://user-images.githubusercontent.com/16581744/112749514-ff9f7600-8fc2-11eb-95bc-09ef0de63a70.png)

**Comment by dennissiemensma** [comment]
Gefixt en aangepast voor volgende release.

**Comment by dennissiemensma** [comment]
Onderdeel van de nieuwe [v4.15 release](https://github.com/dsmrreader/dsmr-reader/releases/tag/v4.15.0).

**Comment by reboot1983** [comment]
Fix confirmed. Zowel teruglevering is nu dynamisch verborgen als de labels zijn nu correct :) (Y)
