### ISSUE TITLE
Https support

### ISSUE THREAD

**Issue by Deefnl** [dsmrreader/dsmr-reader#1338]
Hi,

Is it possible to get https support. Integrated with let's encrypt for example? Right now it's impossible to integrate the web page into a https home assistant iframe.

Regards,

Dave Jacobs

**Comment by fverpoest** [comment]
My installation is running without any problem on https with the help of Certbot.

Follow these instructions: https://certbot.eff.org/lets-encrypt/debianbuster-nginx

**Comment by jeroenpeters1986** [comment]
Yes, DSMR-Reader works perfectly on HTTPS if you have that configured. This is the part where you will need to configure your webserver to server DMSR-reader over HTTPS with a valid certificate. This kinda falls outside the DSMR-Reader scope I think, but running it over HTTPS is working fine

**Comment by dennissiemensma** [comment]
Thanks guys, I'll add a reference to the website above in the docs

**Comment by dennissiemensma** [comment]
Added to docs for next release.

**Comment by dennissiemensma** [comment]
Onderdeel van de nieuwe [v4.15 release](https://github.com/dsmrreader/dsmr-reader/releases/tag/v4.15.0).
