### ISSUE TITLE
Datepicker is out-of-date

### ISSUE THREAD

**Issue by reboot1983** [dsmrreader/dsmr-reader#1339]
![image](https://user-images.githubusercontent.com/20405704/112719657-3d849780-8efa-11eb-8f80-f2fab5150201.png)

Kijkende naar de datepicker op `/admin/dsmr_datalogger/dsmrreading`. Als je hier iets wilt selecteren ben je je een ongeluk aan het klikken naar het huidige jaar. :)
Kan de ingevulde datum hier worden preselected?

DSMR-Reader 4.14; Windows 10 met Chrome up2date

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Kun je eens kijken of het ook gebeurt als je gewoon `/admin/dsmr_datalogger/dsmrreading/` opent?

Ik kan het namelijk alleen reproduceren als ik de pagina benader via een URL met een voorgedefinieerde zoekopdracht. Daar lijkt die minder goed mee om te gaan en dat is mij niet eerder opgevallen. Hoe dan ook [is dit een externe plugin](https://github.com/silentsokolov/django-admin-rangefilter), dus ik kan maar beperkt wijzigingen hier omheen doen.

**Comment by reboot1983** [comment]
Dan ziet hij er inderdaad wel goed uit

**Comment by dennissiemensma** [comment]
Dank voor het proberen! In dat geval laat ik het voor nu voor wat het is, gezien ik vermoed dat vrij weinig gebruikers deze specifeke situatie meemaken.
