### ISSUE TITLE
Timestamp from DSMR5 meter is misinterpreted

### ISSUE THREAD

**Issue by ghost** [dsmrreader/dsmr-reader#1342]
/Ene5\T210-D ESMR5.0

1-3:0.2.8(50)
0-0:1.0.0(210329232030S)
...
ID:
1
Timestamp:
30 maart 2021 01:20
Moment waarop de meting is gedaan

The above is a copy-paste from the meter statistics admin page. There's a 2 hour discrepancy between the timestamp from the telegram and how it is interpreted. Runs in Docker with the - DJANGO_TIME_ZONE=Europe/Amsterdam flag. What can clarify this?

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Grote kans dat je van het volgende last hebt: #1282

Probeer deze mount/volume te verwijderen:
```
/etc/localtime:/etc/localtime:ro
```

**Comment by ghost** [comment]
Dat was inderdaad de fix, dank. Geen idee hoe die er is gekomen, in de laatste versie van het docker compose voorbeeld staat-ie er ook niet.

**Comment by dennissiemensma** [comment]
Fijn! En klopt, dat is ook pas vrij recent gewijzigd: https://github.com/xirixiz/dsmr-reader-docker/commit/d23758baf4f0a59b1e9d9fc58ed2ec13f9653fc7 . Verder zijn er meerdere manieren om dit issue te fixen, maar dit is de makkelijkste.
