### ISSUE TITLE
DSMR reader en homey

### ISSUE THREAD

**Issue by lukevredeveld** [dsmrreader/dsmr-reader#1345]
Misschien geen 'issue', maar ik kom niet veel verder met mijn zoektocht op internet, of ik begrijp niet wat er omschreven wordt. Ik ben helemaal dik tevreden met DSMR-reader en wil dit vooral blijven gebruiken. Ik zoek alleen nog een manier om de data naar homey te krijgen. Dat blijkt te werken met http-get requests, maar ik krijg het niet verder in mijn homey systeem om het daadwerkelijk ergens te tonen. Wellicht dat hier iemand rondloopt die mij dit verder wil leggen, want ik ben al avonden bezig en nog geen steek opgeschoten helaas :-(

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Ik denk dat je het beste je situatie en wens kan voorleggen op een forum, zoals Tweakers. Ook omdat ik zelf nul verstand heb van Homey. Hier op Github lezen namelijk maar heel weinig mensen mee.

Ik zie in dit topic iets voorbij komen, al staat er niet in detail in **hoe** die gebruiker dat voor elkaar heeft gekregen: https://gathering.tweakers.net/forum/list_message/58443032#58443032
