### ISSUE TITLE
4.15 voltage grafiek autoscaling in live grafieken

### ISSUE THREAD

**Issue by reboot1983** [dsmrreader/dsmr-reader#1349]
Sinds versie 4.15 zijn de grafieken in de live-grafieken-pagina herzien. Er zijn mooie opties bijgekomen die in de meeste grafieken heel mooi uitwerken. Echter het voltage gedeelte is nu niet langer inzichtelijk (eigenlijk: nauwkeurig genoeg weergegeven). Dit komt omdat de grafiek niet langer auto-scaled, maar nu tussen de 0 en 250v wordt weergegeven. Hierdoor is het wisselende voltage niet langer duidelijk zichtbaar. Op mijn aansluiting wisselt het voltage soms met +/- 10v en met de huidige schaal is dit niet langer zichtbaar of op te merken.

Versie <4.15
![image](https://user-images.githubusercontent.com/20405704/113483455-c3c54e80-94a3-11eb-910f-db48a4a43cbd.png)

Versie 4.15
![image](https://user-images.githubusercontent.com/20405704/113483470-d770b500-94a3-11eb-96d3-1fe0e3fed9be.png)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding! Dat is helaas een bijeffect geweest van de grote refactoring, dus ik zal het meenemen in de volgende release.

Tot die tijd kun je evt handmatig de fix doorvoeren: 9ff735cc6ca15b3b5ce9790e362c206d8a1481a6

Let op dat je de fix dan doorvoert op deze file hieronder en **niet** die uit de repo in `/home/dsmr/dsmr-reader/...`:
```
/var/www/dsmrreader/static/dsmr_frontend/js/dsmr-reader/live/voltage.js
```

Na een harde refresh in je browser zou het dan gefixt moeten zijn, totdat je ooit weer `deploy.sh` draait (die overschrijft de file als het goed is).

**Comment by dennissiemensma** [comment]
Fix uitgebracht in [v4.15.1](https://github.com/dsmrreader/dsmr-reader/releases/tag/v4.15.1)
