### ISSUE TITLE
Energiekosten rariteit.

### ISSUE THREAD

**Issue by cmderks93** [dsmrreader/dsmr-reader#1350]
Ik ben benieuwd hoe deze rekensom tot stand komt, er lijkt iets niet te kloppen.

**Comment by cmderks93** [comment]
![Screenshot_20210403-193423__01](https://user-images.githubusercontent.com/13498377/113486662-4d7d1800-94b4-11eb-865a-30f57031cb68.jpg)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Het is mij niet duidelijk wat je bedoelt. Kun je aangeven wat er precies mis gaat en wat de verwachte uitkomst is? 

Verder kun je op de pagina met energiecontract-totalen beter zien welke prijzen er ingesteld zijn.

**Comment by cmderks93** [comment]
Nu ik het uitschrijf, zie ik dat ik een fout maak...
Ik kan ofwel niet tellen, ofwel niet goed kijken....
Deze mag dicht. Sorry!

**Comment by dennissiemensma** [comment]
Bedankt voor de opheldering. Meld het vooral als je alsnog ergens een foute berekning ziet hoor.

**Comment by dennissiemensma** [comment]
Ik zal voor de volgende release de (sub)totalen lichtjes highlighten, zodat wat duidelijker is dat het totalen zijn. Ik vermoed dat o.a. daar je verwarring door ontstond.

![Screenshot_2021-04-03 Dashboard DSMR Reader](https://user-images.githubusercontent.com/16581744/113488459-9c2faf80-94be-11eb-8130-284f8525082f.png)
