### ISSUE TITLE
Dsmr addon voor home assistant: geen updates? 

### ISSUE THREAD

**Issue by gobartos** [dsmrreader/dsmr-reader#1353]
Ik gebruik dsmr reader als addon via home assistant supervisor. Al 1 keer heb ik via die weg een update kunnen doen, maar intussen zijn er recent 2 updates geweest op de software en die zijn blijkbaar niet doorgekomen tot als addon bij home assistant. Of doe ik iets verkeerd?

**Comment by niekniek89** [comment]
@gobartos ik denk dat je [hier](https://community.home-assistant.io/t/dsmr-reader-add-on-for-home-assistant/279087) moet zijn voor o.a. updates.

echter, zie ik dat 16 uur geleden de addon is bijgewerkt naar:

**2021-04-06: 0.4.1 Update to DSMR-reader v4.15.1**

**Comment by gobartos** [comment]
Ja maar geen update hier in Home Assistant...

![Screenshot 2021-04-07 at 14 20 31](https://user-images.githubusercontent.com/49399526/113865607-91219b80-97ac-11eb-9c07-483cce501c0a.jpg)

![Screenshot 2021-04-07 at 14 22 11](https://user-images.githubusercontent.com/49399526/113865704-b31b1e00-97ac-11eb-8cd7-eea1de565eb3.jpg)

**Comment by donnie-dominguez** [comment]
Home Assistant kijkt periodiek (denk eens per 24 uur) of er updates zijn. Dus het kan even duren. Wellicht helpt het om HA opnieuw te starten om een check te forceren. Maar dat is inderdaad meer iets voor de HA community

**Comment by jeroenpeters1986** [comment]
Eens met wat @donnie-dominguez  en @niekniek89 aangegeven hadden, dit is iets voor de HA community.

**Comment by gobartos** [comment]
Ik wil nog graag weten of de add-on door dezelfde persoon gemaakt wordt of iets 'achteraf gefabriceerd' is.

**Comment by niekniek89** [comment]
DSMR Addon is door iemand anders gemaakt, en wordt door die gene onderhouden (zie aangegeven [HA community link](https://community.home-assistant.io/t/dsmr-reader-add-on-for-home-assistant/279087)). Helemaal bovenaan staat de maker van de addon.
![HA Addon](https://user-images.githubusercontent.com/48858098/113868439-f7f48400-97af-11eb-86c7-4a1f1b6327da.jpg)

**Comment by dennissiemensma** [comment]
@gobartos ik kan me voorstellen dat het wat verwarrend is. Voor de duidelijkheid:

- DSMR-reader applicatie zelf: https://github.com/dsmrreader/dsmr-reader (huidig project)
- Docker-versie van DSMR-reader: https://github.com/xirixiz/dsmr-reader-docker (door xirixiz)
- HA add-on met DSMR-reader: https://github.com/sanderdw/hassio-addons (door sanderdw)
