### ISSUE TITLE
Live grafiek (specifiek terug levering)

### ISSUE THREAD

**Issue by niekniek89** [dsmrreader/dsmr-reader#1354]
Goedemiddag,

Ik heb zojuist een upgrade uitgevoerd van 4.14 naar 4.15.1.
Als ik dan in het dashboard links naar "Live grafiek" ga, zie ik opeens dat het gedeelte "terug levering"  een soort van 
ondersteboven is.
Wellicht hoort dit zo (sinds de nieuwe updates), maar is nooit zo geweest.

![live grafiek](https://user-images.githubusercontent.com/48858098/113863023-6f72e500-97a9-11eb-9b9e-5b83e207f7e7.jpg)

Ik zie dat dit ook geldt voor "Recent fase vermogen":

![live grafiek](https://user-images.githubusercontent.com/48858098/113863202-b06af980-97a9-11eb-9dbc-14eaeb4988a1.jpg)

**Comment by donnie-dominguez** [comment]
Is inderdaad nieuw sinds de laatste update (v4.15.1)
![image](https://user-images.githubusercontent.com/59409550/113866221-5835f680-97ad-11eb-8652-417fbebba955.png)

**Comment by dennissiemensma** [comment]
@niekniek89 dit is inderdaad zoals bedoeld. Ik kan me voorstellen dat het even wennen is.

Voor gebruikers die simultaan verbruiken en terugleveren zijn deze grafieken waarschijnlijk stukken duidelijker. De oude situatie ging er vanuit dat altijd ofwel verbruik ofwel teruglevering mogelijk was, maar dat bleek in de praktijk niet altijd zo te zijn.

Verder verduidelijkt dit ook de per-fasen-grafiek, waar in sommige situaties de Y-as 6x gebruikt werd, waardoor het er allemaal niet duidelijker werd. Nu is dat versimpeld naar tweemaal 3x.
