### ISSUE TITLE
Influx DB

### ISSUE THREAD

**Issue by iepmaatje** [dsmrreader/dsmr-reader#1355]
Hallo Allen,
Ik probeer te begrijpen hoe ik InfluxDB kan gaan gebruiken om met Grafana m'n eigen dashboards te maken.
Echter, ik snap niet wat ik moet doen :-(
Ik begrijp dat ik een vinkje kan zetten bij integratie, maar wat dan ? Wat is er nodig om dit werkend te krijgen ?
Ik kan geen enkele documentatie hierover vinden.
Zou iemand mij in een aantal stappen willen beschrijven hoe ik een InfluxDb integratie kan opzetten ?
Erwin

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Ik denk dat je het beste deze topics kunt doorlezen:

- #857
- #1055

Het is bewust een wat oppervlakkige integratie geweest.
