### ISSUE TITLE
Maandbedrag toevoegen aan contract

### ISSUE THREAD

**Issue by supershadow** [dsmrreader/dsmr-reader#1356]
hallo,
Als eerst wil ik zeggen dat ik er tevreden ben met met het programma.
is het ook mogelijk om het vaste maandbedrag dat je betaalt aan je energieleverancier toe te voegen aan je contract. en dat je dit weer kunt terug kun zien in een grafiek of tabel om te zien of je maandelijkse bedrag genoeg is wat je betaald.
en dit dan ook weer met het mqtt mee te versturen.

Met vriendelijke groet

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek! De kosten in DSMR-reader zijn puur bedoeld ter indicatie wat een dag kost tov een andere dag. 

Voor een exacte berekening van wat je daadwerkelijk betaalt aan je leverancier zijn ook allemaal extra berekeningen nodig zoals de kosten van de netbeheerder, belastingen, eventuele saldering en andere kortingen of andere kosten. Het is vrijwel onmogelijk om dat voor iedereen bij elke leverancier goed te krijgen, dus daarom ondersteunt DSMR-reader alleen de huidige opzet.

En om te voorkomen dat er verkeerde aannames of verrassingen achteraf komen, denk ik ook dat het daarom niet handig is om zaken zoals het maandbedrag hierbij op te nemen. Het is immers nooit de waarheid.

Overigens zie ik ook steeds meer leveranciers die zelf pro-actief maandelijkse overzichten sturen van de kosten die maand, het voorschot en een voorspelling of het afdoende is voor het jaar. Ik denk persoonlijk ook dat het meer een service daar zou moeten zijn, ook omdat zij exact weten wat ze je in rekening gaan brengen.
