### ISSUE TITLE
Idee: Opbrengst zonnepanelen meenemen in stats?

### ISSUE THREAD

**Issue by E020** [dsmrreader/dsmr-reader#1365]
Het zou handig zijn als je de productie van zonnepanelen zelf ook als add-on op de een of andere manier kan worden toegevoegd, bijvoorbeeld als die entiteit zelf al in Home Assistant zit. Dat maakt de DSMR stats een stuk rijker voor zonnepaneelbezitters omdat eigen gebruik (van hetgeen de zonnepanelen opleveren) dan ook mee kunt nemen in de stats. Of is dit op de een of andere manier al mogelijk?

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag! Zie dit comment voor meer toelichting en verwijzingen: https://github.com/dsmrreader/dsmr-reader/issues/1296#issuecomment-807547632
