### ISSUE TITLE
Remote datalogger leest gas verbruik niet met Belgische meters

### ISSUE THREAD

**Issue by jimmyd-be** [dsmrreader/dsmr-reader#1370]
Gas waardes worden niet meegenomen met een remote datalogger setup.
Als ik de reader volledig op de remote zet en ik kies als DSMR versie 'Belgium - Fluvius (gas meter fix) werkt het wel. Maar als ik mijn setup aanpas naar een remote datalogger en een docker omgeving voor de webinterface dan komt deze value niet door.

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Werkt het ook niet in combinatie met de remote datalogger en dan in DSMR-reader de DSMR-versie Fluvius?

**Comment by jimmyd-be** [comment]
Dat heeft het inderdaad opgelost. Ik krijg nu de gaswaardes binnen. Bedankt.

**Comment by dennissiemensma** [comment]
Fijn om te horen!
