### ISSUE TITLE
dsmr_backend herstart elke seconde

### ISSUE THREAD

**Issue by fonta** [dsmrreader/dsmr-reader#1371]
Het viel mij op dat de backend continue opnieuw opstart.
Hoort dit te gebeuren? Of is er iets aan de hand?
De webinterface werkt voor zover ik kan zien naar behoren.
Versie is 4.15.1.

![image](https://user-images.githubusercontent.com/6190791/115224458-26a61f00-a10d-11eb-9bc5-b5f85bf8d90e.png)

**Comment by fonta** [comment]
MQTT verbinding werkte niet. Na fixen blijft de backend gewoon draaien.

**Comment by dennissiemensma** [comment]
Fijn om te horen dat je het zelf zo snel hebt gevonden!
