### ISSUE TITLE
Problems when chaing datalogger port

### ISSUE THREAD

**Issue by hemant5400z** [dsmrreader/dsmr-reader#1372]
Hi,

In change port and ip of my datalogger and restarted all.

But datalogger keeps crashing. Any ideas.

Port works fine when running telnet i can see the smartreader messages.

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Een goede eerste plek om te kijken zijn de logs: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/logfiles.html

**Comment by hemant5400z** [comment]
Sorry deze kan dicht aangezien het om de docker variant gaat.


Hemant
