### ISSUE TITLE
Het vermelden van piekvermogen

### ISSUE THREAD

**Issue by jeroomdm** [dsmrreader/dsmr-reader#1377]
Vanaf 2022 zal er in België een tarief zijn op basis van het piekvermogen. De grootste piek die 15min duurde nemen ze dan voor de hele maand.
Is het mogelijk dit ook te voorzien in DSMR-Reader?
Als ik inlog bij de netbeheerder zie ik het volgende:
![image](https://user-images.githubusercontent.com/5408131/116599545-87610300-a928-11eb-8bfe-32d8b28b1900.png)

Alvast bedankt!

**Comment by dennissiemensma** [comment]
@jeroomdm bedankt voor je verzoek. Er komt hier waarschijnlijk eind dit jaar ondersteuning voor in DSMR-reader, al houd ik nog een slag om de arm.

Een eerder gemeld issue kun je hier vinden: #1084 _(deze stond niet meer op de voorpagina)_
Je kunt het beste dat issue volgen.
