### ISSUE TITLE
Freature request: auto reconnect MQTT broker

### ISSUE THREAD

**Issue by t-liu93** [dsmrreader/dsmr-reader#1384]
Is it possible to let the backend reconnect to MQTT broker if it detect too many MQTT message is in the queue?

I've been used dsmr-reader for more than a year now. In my environment, my dsmr reader occasionally disconnect from MQTT broker spontaneously, roughly once a few days. Currently if I see it I have to go to the WebUI and reconnect the MQTT broker. So I have an idea, I'm wondering if the backend can detect it and try to reconnect? Or simply when it complaints 'too many MQTT message queued', then it tries to reconnect.

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Je kunt overwegen om te upgraden naar v4.16 (als je dat al niet gedaan hebt) en dan in de broker instellingen Quality of Service level 2 te gebruiken. Die is sinds die release wat robuuster.

Ik ben ook toevallig nog bezig met fix release daarvoor (v4.16.1) met een bugfix en het verbeteren van de connectiviteit. Want precies het probleem dat je beschrijft, wordt nog niet helemaal goed afgehandeld. Ook niet in v4.16, maar vermoedelijk straks wel bij de patch release.

Mogelijk lost dat alle je problemen straks op.

**Comment by dennissiemensma** [comment]
Onderdeel van [v4.16.1](https://github.com/dsmrreader/dsmr-reader/releases/tag/v4.16.1). Probeer of die release je problemen oplost.
