### ISSUE TITLE
Herinstallatie packages 

### ISSUE THREAD

**Issue by reboot1983** [dsmrreader/dsmr-reader#1386]
Onderstaande viel mij vanmorgen toevallig op bij de update van 4.15.2 naar 4.16.1. Het lijkt erop alsof het ./deploy.sh script niet (correct) de huidige versies detecteert. Het verwijderd de betreffende installatie van deze twee packages om vervolgens dezelfde versie weer te installeren.

![image](https://user-images.githubusercontent.com/20405704/117944281-637cc480-b30d-11eb-8c8f-cfbc2b42b22c.png)

Daarnaast een vraag over de outdated PIP melding. Is dit iets wat we veilig kunnen uitvoeren? Ik vind er niets over in de handleiding en weet ook niet of deze melding door DSMR-Reader wordt gegeven of gewoon een standaard melding is?
Misschien is het een optie om het deploy script dit ook te laten managen en bij iedere update op de juiste versie te zetten?

**Comment by dennissiemensma** [comment]
Bedankt voor je melding! Ik zie echter niet helemaal wat je bedoelt. Dropbox 11.7 wordt weggehaald en vervangen door 11.8 onderaan. Idem voor Auto-pep 1.5.6, naar 1.5.7. Bedoel je dat?

Pip is zelf wat speciaal en niet perse onderdeel van DSMR-reader. Je kunt die echter gerust updaten met:
```
sudo su - dsmr
pip install --upgrade pip
```

**Comment by reboot1983** [comment]
Wauw.. Sorry daarvoor. Ik had beter moeten/mogen kijken.
