### ISSUE TITLE
"archief" gem. temperatuur weergave

### ISSUE THREAD

**Issue by newtech2015** [dsmrreader/dsmr-reader#1389]
hallo,

het valt mij op, dat als ik maanden van dit jaar het verbuik wil vergelijken tov bv vorig jaar, ik er niet de temperatuur bij heb.

dit lijkt me wel handig als dit zou zijn, dat ik bv 20% meer gas in een maand heb verbruik tov dezelfde maand 1 jaar geleden, is leuk... maar wat was de temperatuur dan?

gr ron

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Dat was ook van oorsprong de reden om de temperatuur te meten door DSMR-reader. Het bleek echter vrij snel niet afdoende en betrouwbaar genoeg, omdat hiervoor eigenlijk zogenaamde "graaddagen" bedoeld zijn. 
En het is een behoorlijke klus om die te integreren en onderhouden. Daarom laat ik dat liever aan tools of partijen over die zich daarop focussen, eigenlijk vergelijkbaar waarom ik voor de upload van omvormers niet het wiel opnieuw ga uitvinden, want bijvoorbeeld PVOutput.org richt zich helemaal op die functionaliteit.

Je kunt overwegen om je gasstanden dagelijks door DSMR-reader te exporteren naar MinderGas. Die kunnen (dacht ik) een betere vergelijking per maand of jaar maken en nemen graaddagen daarin mee. Zij hebben ook wat meer toelichting: https://www.mindergas.nl/degree_days/explanation

Mochten er nog andere tools of partijen zijn die zoiets (beter) aanbieden, dan zal ik ooit een koppeling overwegen. Want ik zie daar wel een mogelijke rol in binnen DSMR-reader, afhankelijk van de voordelen.
