### ISSUE TITLE
Pie charts in trends-pagina vervangen door bar/line chart

### ISSUE THREAD

**Issue by johannienhuis** [dsmrreader/dsmr-reader#1390]
De pi-charts op de trends-pagina zijn onoverzichtelijk. Daarbij zijn de verschillende uren moeilijk onderling vergelijkbaar (vooral voor de delen van een pie die niet naast elkaar liggen).

Is het mogelijk om de pie chart te vervangen door een normale grafiek zoals op de archive-pagina getoond wordt? Hierdoor zijn alle uren van een dag in 1 oogopslag goed vergelijkbaar. Bovendien kan de gebruiker dan eenvoudig tussen bar/line chart kiezen.

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Zou je een screenshot willen maken van je eigen situatie? Dit diagram is momenteel druk, dus het is sowieso een uitdaging om hem in alle sitauties leesbaar te maken. 
Het is momenteel bewust een variant op een pie-chart, die de onderlinge verschillen juist wat meer zou moeten benadrukken. Ik zou een keer kunnen kijken voor een tweede variant, echter wil ik liever zo min mogelijk variaties en het liefste maar 1 of 2 die voor iedereen leesbaar zijn. Ongeacht in welke vorm dat dan uiteindelijk is.

**Comment by johannienhuis** [comment]
Dank voor je reactie. Zie bijgaand voorbeeld zoals deze bij mij zichtbaar is. [Trends  DSMR Reader.pdf](https://github.com/dsmrreader/dsmr-reader/files/6489288/Trends.DSMR.Reader.pdf)

**Comment by johannienhuis** [comment]
Overigens ben ik zelf niet zo'n voorstander van het gebruik van Pie charts. Veel data visualisatie guru's adviseren om deze niet te gebruiken simpelweg omdat er bijna altijd betere alternatieven zijn. (Google maar eens op 'stephen few pie charts'). Ken je https://chart.guide/? Ook hier zie je dat de pie chart afgeraden wordt.

En zeg nou zelf, dit diagram is veel overzichtelijker :-)
![image](https://user-images.githubusercontent.com/76614702/118399096-bfbc4d00-b65b-11eb-89a3-6f7c0350ae65.png)
(afkomstig uit de archive-pagina / dag-niveau)

**Comment by dennissiemensma** [comment]
Bedankt voor je aanvullingen. Wat betreft je eigen screenshots snap ik goed wat je bedoelt. De eerste pie is wel zoals het bedoeld is en is om duidelijk aan te geven welk uur of uren dominant zijn. 
Echter, de situatie in je tweede en derde pie heb ik zelf nog niet eerder gezien en dat maakt het inderdaad niet duidelijk. Ter vergelijking, ik heb wel behoorlijk wat rare situaties gehad en de meeste kunnen fixen met een een workaround, maar zo heb ik het meestal gezien:

![Screenshot_2021-05-17 Trends DSMR Reader](https://user-images.githubusercontent.com/16581744/118548961-296f5080-b75b-11eb-8360-ad152082f21e.png)
En hoewel je natuurlijk nog kan discussiëren over of dat de ideale weergave is, vond ik het wel werkbaar.

Ik heb ook nog even gezocht naar je tips over de pie's, maar dat gaat vermoedelijk vooral op voor normale pie's met vele stukken, zoals [deze](https://echarts.apache.org/examples/en/editor.html?c=pie-legend). Dat was ook de reden dat ik bewust gekozen had voor de [rose-variant](https://echarts.apache.org/examples/en/editor.html?c=pie-roseType-simple), die schaalt naar mate van de dominantie.

Verder heb ik ook [deze variant](https://echarts.apache.org/examples/en/editor.html?c=scatter-single-axis) nog overwogen, maar die is denk ik alleen duidelijk als het echt veel datapunten heeft, zoals die in het voorbeeld. 
Ik zal iig voor je kijken of een staafdiagram het duidelijker maakt, wellicht evt gesorteerd van hoog naar laag zoals [deze](https://echarts.apache.org/examples/en/editor.html?c=bar-race) (zonder animatie dan). En eventueel later nog samengevoegd met een andere variant oid in deze [opties](https://echarts.apache.org/examples/en/index.html#chart-type-bar).

**Comment by johannienhuis** [comment]
Bedankt voor je inhoudelijke reactie! Hierbij weer een aanvulling van mijn kant.

Het voorbeeld dat jij meestuurt ziet er qua structuur wel beter uit. Maar ik blijf een taart diagram nadelig vinden omdat de oppervlakte-maat in een circel moeilijker te vergelijken is dan de hoogte-maat van staafdiagram. 

Als je een chart wil gebruiken waarbij je oppervlakte als maatvoering gebruikt dan vind ik persoonlijk alleen vierkante vormen geschikt. (Bijvoorbeeld Treemap of een Marimekko chart maken ook gebruik van oppervlakte als visualisatie-hulp. Treemap en Marimekko vind je hier: https://chart.guide/charts/part-to-whole-or-composition/ (in de 3e rij). Dit even ter illustratie hoe je (naar mijn mening) met oppervlakte kunt werken in charts echter deze charts zijn denk ik niet inzetbaar voor de trends-pagina).

Je hebt in je reactie ook nog een hele interessante aanvulling: https://echarts.apache.org/examples/en/editor.html?c=scatter-single-axis. Wat ik hier echt super interessant aan vind is de onderverdeling naar dagen en uren zodat je beter zicht krijgt op wekelijkse patronen. Alleen de oppervlakte vergelijking in circels vind ik dus minder sterk in dit voorbeeld... ;-) 

Zou je als alternatief op de dagen/uren visualisatie de horizon-chart eens willen overwegen? (Zie rechtsonder in deze link https://chart.guide/charts/time-or-trend/). Dit zou denk ik een heel sterk alternatief zijn, vraag is natuurlijk altijd of dit te realiseren is ;-)

Nogmaals dank voor je reactie. Ik denk graag met je mee. Zoals je merkt heb ik een eigen mening over data visualisaties maar voel je vrij om daar wel of niet iets mee te doen.

**Comment by dennissiemensma** [comment]
Ik heb nog deze variant geprobeerd, maar rekt te veel uit:

![Screenshot from 2022-07-06 20-56-43](https://user-images.githubusercontent.com/16581744/177629572-afa6053f-48e8-475b-8828-89ecb032d473.png)

---

Vanaf DSMR_reader v5.4 wordt het zoiets:

![Screenshot from 2022-07-06 21-32-09](https://user-images.githubusercontent.com/16581744/177629644-9ece988f-10cc-4e26-ad86-c6b95075a0f7.png)

De onderste pie heb ik zoo gehouden, omdat het prima verhouding geeft tussen twee (doorgaans relatief gelijk aan elkaar) vlakken

**Comment by dennissiemensma** [comment]
Release van v5.4 staat voor **morgenavond** op de planning, mits er niets uit de 24-uurstest komt.
