### ISSUE TITLE
MQTT: Fix QoS 0

### ISSUE THREAD

**Issue by dennissiemensma** [dsmrreader/dsmr-reader#1393]
- #1391
- #1387

**Comment by dennissiemensma** [comment]
- Onderzoeken of de eerste `client.loop()` zonder return-check gedaan kan worden. Voor QoS 1/2 is de `is_published()` check er namelijk alsnog daaronder.
- MQTT client timeout flink verlagen.

**Comment by bockelaar** [comment]
ik heb ook last van deze bug. na verloop van tijd (paar uur) stopt de verwerking. een sudo supervisorctl restart all maakt dat alle achterstallige telegrams etc weer verwerkt worden.
Als je info/logs e.d. nodig hebt laat het me maar weten

**Comment by dennissiemensma** [comment]
@bockelaar bedankt voor je melding. Voor nu kun je het beste QoS 2 gebruiken. Dat zou het ook moeten oplossen.

**Comment by bockelaar** [comment]
ik las het, het het een uurtje geleden ingesteld :)

**Comment by dennissiemensma** [comment]
Ik zal ervoor zorgen dat DSMR-reader voor nu alleen QoS 2 gebruikt. Ook automatisch voor iedereen die nog 0 of 1 gebruikt.

Dan is het ook geen variabele instelling meer en kan er minder stuk gaan. Ik heb ook tot nu toe nog geen meldingen gehad dat QoS 2 niet goed werkt.

Ik zal het eerst hardcoden en de instelling verbergen in een patch release. Dan gooi ik het er later wel helemaal uit.
