### ISSUE TITLE
Onverwerkte telegrammen na upgrade

### ISSUE THREAD

**Issue by reboot1983** [dsmrreader/dsmr-reader#1402]
Sinds de upgrade van een uur geleden van 4.16.2 naar de laatste versie (4.16.3) krijg ik een dsmr reader melding dat hij onverwerkte telegrammen heeft. En dat getal loopt op, de grafieken staan stil, maar het actuele verbruik lijkt wel gewoon te kloppen.

hoe krijg ik dsmr reader weer aan de praat dat ie de onverwerkte telegrammen weer gaat verwerken? Het betreft een dedicated install op Debian conform de v4 handleiding, gekoppeld aan de p1reader (ethernet versie) van Zuidwijk.com. 

“supervisorctl restart all” helpt niet. Postgresql opnieuw starten helpt niet. System reboot helpt niet. Wat kan ik nog meer proberen?

Ik kan in de changelog of handleidingen hier ook geen stappenplan voor vinden lijkt het?

Alvast bedankt voor de tips/tricks.

![9915E736-8A2B-4320-8926-4FB1B5B1BEAC](https://user-images.githubusercontent.com/20405704/120390707-55c7c700-c32e-11eb-841f-1d1f5f447294.jpeg)

**Comment by dennissiemensma** [comment]
Je kunt het beste eerst zoeken in de logfile naar de oorzaak: https://github.com/dsmrreader/dsmr-reader/issues/1387#issuecomment-839932356

**Comment by reboot1983** [comment]
Ik zie in de dsmr_backend log dat er issues waren om te verbinden met postgresql.
Maar die issues bleven ook nadat postgresql herstart was en weer gewoon up en running en beschikbaar was.

Ik snap alleen niet waarom dit niet automatisch is opgelost met een supervisor restart all. Ik heb nu specifiek en alleen de datalogger herstart en daarmee heeft ie alles in een paar tellen verwerkt en nu draait ie weer goed. 

Hieronder wat ik tegen kom in de dsmr_backend.log

```
2021-06-01 22:59:45,180 ERROR    mixins       run_once                        101 | dsmr_backend.management.commands.dsmr_backend: [!] Exception raised. Traceback (most recent call last):
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: terminating connection due to administrator command
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dsmr/dsmr-reader/dsmr_backend/mixins.py", line 90, in run_once
    self.run(data=self.data, **options)
  File "/home/dsmr/dsmr-reader/dsmr_backend/management/commands/dsmr_backend.py", line 33, in run
    dsmr_backend.services.schedule.execute_scheduled_processes()
  File "/home/dsmr/dsmr-reader/dsmr_backend/services/schedule.py", line 28, in execute_scheduled_processes
    logger.debug('SP: %s backend service(s) ready to run', len(calls))
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: terminating connection due to administrator command
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

**Comment by the1rig** [comment]
Ik merk hetzelfde, zelfde foutmelding ook. Alleen lost het opnieuw opstarten van het dsmr_datalogger niet op. Een volledige reboot van de machine waar dsmr draait lost de queue op.

**Comment by dennissiemensma** [comment]
@reboot1983 bedankt voor de aanvulling. Werkt het inmiddels nu wel goed?

Het lijkt erop dat deze fouten specifiek komen door het herstarten van de database:
```
terminating connection due to administrator command
```

- Waren deze fouten er eerder ook al, voordat je de database herstart hebt?
- En gebruik je toevallig MQTT in DSMR-reader? Want de patch update die je gedaan hebt had alleen invloed op MQTT dacht ik.

**Comment by dennissiemensma** [comment]
@the1rig welke foutmelding krijg je? En wat zeggen de logs? Wellicht is het sowieso handig om even een los issue aan te maken hier. Je kunt de huidige uiteraard watchen.

**Comment by the1rig** [comment]
@dennissiemensma het probleem lijkt vanzelf verholpen te zijn, ik had overigens dezelfde foutmelding als @reboot1983, maar na een nacht is hij weer helemaal bij en blijft hij bij :)

**Comment by dennissiemensma** [comment]
Oke dank voor de update. Ik zou zeggen houd het voor nu even in de gaten of het vaker voor komt. 
De laatste patch-update betreft namelijk vooral MQTT en *zou* geen andere zaken moeten raken.

**Comment by reboot1983** [comment]
> @reboot1983 bedankt voor de aanvulling. Werkt het inmiddels nu wel goed?
> 
> Het lijkt erop dat deze fouten specifiek komen door het herstarten van de database:
> 
> ```
> terminating connection due to administrator command
> ```
> 
> * Waren deze fouten er eerder ook al, voordat je de database herstart hebt?
> * En gebruik je toevallig MQTT in DSMR-reader? Want de patch update die je gedaan hebt had alleen invloed op MQTT dacht ik.

Sorry voor de late reactie.

Nee, ik gebruik geen MQTT. Ik moest eerlijk gezegd ook even opzoeken wat het was. 😉 
Na het herstarten van de datalogger werkte het bij mij weer inderdaad. Ik heb voor de herstart van de database (achteraf betrof het een apt upgrade) geen fouten gezien.

Ik zie wel dat de logs vol staan met dezelfde meldingen: 
`Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html
`

Dit komt in zowel de backend (paar entries: 99x) als de datalogger (vele entries: 5552x) logfiles veelvuldig voor.
Maar voor de rest is het een oase van rust 😉 

Dankjewel voor de support.

---edit:

Kleine aanvulling misschien nog. Is het wellicht mogelijk om bovenstaande logentries in de pagina: 'about' op te nemen? Hier heb je al een stukje debug en 'status' opgenomen natuurlijk. Wellicht kun je bovenstaande entry uit de log halen en op deze pagina als ondersteuning plaatsen?

**Comment by dennissiemensma** [comment]
Bedankt voor de aanvulling. Die `Current logging level set to "ERROR"...` is bedoeld om te laten zien dat de logging werkt, maar ook een hint de huidige instellingen alleen foutmeldingen loggen en geen DEBUG. Als het goed is komt de melding 1x voorbij bij (her)start van een proces. Dit alles om het aantal schrijfacties te beperken.
Als je die 5000x in de datalogger-log ziet, is het wellicht nog de moeite waard om te kijken of dat proces wellicht veel crasht, of dat dat puur een periode was waarin het proces zichzelf steeds herstarte.

Qua logging in de About-pagina, dat is wat lastig omdat strikt gezien DSMR-reader niet perse altijd bij die logs kan. Voor een standaardinstallatie wel, maar het staat iedereen vrij om andere loglocaties te definieren en dat kan buiten DSMR-reader om.
