### ISSUE TITLE
[FR] Button/link to recalculate costs after update prices instead of sudo command instruction

### ISSUE THREAD

**Issue by E020** [dsmrreader/dsmr-reader#1410]
Yes, there's a sudo command to update prices retroactively. But would be nice to have a button somewhere that executes this command for user with less terminal/sudo experience.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Hoewel ik me zeker kan vinden in je suggestie, vraag ik me wel af in hoeverre het de moeite waard is om dit op die manier te maken. Helemaal tov hoevaak iemand het wellicht nodig heeft.

Want het is niet alleen een kwestie van een knop toevoegen, ik moet er dan ook voor zorgen dat het blijft werken als het langer dan 60 seconden duurt, gezien DSMR-reader standaard een timeout hanteert van 60 seconden. Een hoop (fix)scripts gaan nu bewust via de commandline, bijvoorbeeld ook het updaten, zodat ze geen last hebben van timeouts en andere bijeffecten.

Als het onduidelijk is hoe iets uitgevoerd moet worden, werk ik liever de documentatie bij, want voor sommige zaken zoals een DB-restore zou iemand toch echt naar de commandline moeten. Dit project vereist doorgaans geen diepe kennis van commandline, maar wel de basis van verbinden en commands uitvoeren.
