### ISSUE TITLE
ik loop vast bij stap 10 (supervisor) tijdens de installatie

### ISSUE THREAD

**Issue by scannie67** [dsmrreader/dsmr-reader#1412]
> 🇳🇱 Lees eerst [deze info](https://github.com/dsmrreader/dsmr-reader/blob/v4/CONTRIBUTING.md) om jezelf te helpen.
> 
> 🇬🇧 First read [this info](https://github.com/dsmrreader/dsmr-reader/blob/v4/CONTRIBUTING.md) for self-service.

**Comment by scannie67** [comment]
Op dit punt krijg ik een foutmelding tijdens de installatie:
sudo cp /home/dsmr/dsmr-reader/dsmrreader/provisioning/supervisor/dsmr_datalogger.conf /etc/supervisor/conf.d/

de foutmelding:
cp: cannot stat '/home/dsmr/dsmr-reader/dsmrreader/provisioning/supervisor/dsmr_datalogger.conf': No such file or directory

Iemand tips waar het mis gaat?

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. In een van de eerdere stappen heb je als het goed is een kopie van dsmr-reader in /home/dsmr/dsmr-reader/ gezet. Bestaat die map wel?
