### ISSUE TITLE
Allow graph 'stack' option for live graphs

### ISSUE THREAD

**Issue by skinkie** [dsmrreader/dsmr-reader#1420]
![image](https://user-images.githubusercontent.com/502394/125177240-6cd5c080-e1da-11eb-9324-cc78fb6aac77.png)

Gezien er nagenoeg geen apparaten zijn die gelijktijdig twee (of drie) fases gebruiken, is het wat betreft visualisatie (veel) handiger om een lijn grafiek te zien voor het gebruik per fase zonder dat deze is opgeteld. Je wilt immers kunnen zien welke fase wordt belast, want het cummulatieve gebruik is al af te lezen in recent electricity usage.

**Comment by dennissiemensma** [comment]
Bedankt voor je suggestie! Het probleem is meer dat iedereen zijn eigen voorkeur heeft voor de eigen situaties. 

Wat voor jou handig is, werkt voor een andere gebruiker weer niet. Voor een deel kan ik dat oplossen met instelbare grafiekopties, maar ook dat houdt op een gegeven moment op.
Wat ik nog wel overweeg is om de bestaande checkbox voor wel/niet stapelen in het Archief door te trekken naar de Live grafieken, zodat dat ook daar te wisselen is. 

Of nog beter, nu ik er over nadenk, een manier aanbieden waarbij jullie de grafiekenconfig zelf kunnen overschrijven om te bereiken wat je wil. Dat betreft zowel grafiekstijl als stapelen en zelfs opties qua assen. Ik kan dan tzt wel assisteren met wat voorbeelden, want je bent absoluut niet de enige die grafieken net iets anders wil en waar het blijft zoeken naar een compromis.

**Comment by dennissiemensma** [comment]
Ik zal voor de volgende release de "stack" optie ook toepassen op de fases en stroomsterktes bij Live grafieken.

Mocht dat toch teveel ongewenste effecten hebben bij andere gebruikers, dan zal ik het weer terugdraaien.

**Comment by dennissiemensma** [comment]
## Beide varianten met fictieve/nepdata, grafieken 4 en 6

## Stacked
![Screenshot 2022-07-10 at 21-18-44 Live graphs DSMR-reader](https://user-images.githubusercontent.com/16581744/178158960-3550d751-8ad2-4897-aabc-24225ab6b69c.png)


---

## Unstacked

![Screenshot 2022-07-10 at 21-18-59 Live graphs DSMR-reader](https://user-images.githubusercontent.com/16581744/178158962-6f5d3065-6402-40a0-bd12-31b89b41b6c2.png)

**Comment by dennissiemensma** [comment]
Uitgebracht in [v5.5](https://github.com/dsmrreader/dsmr-reader/releases/tag/v5.5.0)
