### ISSUE TITLE
Feature Request: add counters to CSV export/ archive view

### ISSUE THREAD

**Issue by Ferao** [dsmrreader/dsmr-reader#1424]
> 🇳🇱 Lees eerst [deze info](https://github.com/dsmrreader/dsmr-reader/blob/v4/CONTRIBUTING.md) om jezelf te helpen.
> 
> 🇬🇧 First read [this info](https://github.com/dsmrreader/dsmr-reader/blob/v4/CONTRIBUTING.md) for self-service.

Is it possible to add the counter of the meter in the CSV export?
or/and see the counters in the archive -> data view section?

**Comment by dennissiemensma** [comment]
Hi thanks for your suggestion. I'll add the counters to the CSV export, as it should be easy. 

And maybe in a later release to the Archive as well.

**Comment by Ferao** [comment]
Perfect thanks

**Comment by dennissiemensma** [comment]
Added for 4.17 release

**Comment by dennissiemensma** [comment]
Added in [v4.17](https://github.com/dsmrreader/dsmr-reader/releases/tag/v4.17.0)
