### ISSUE TITLE
Feature request: Temperatuur toevoegen aan pvoutput

### ISSUE THREAD

**Issue by duiffie** [dsmrreader/dsmr-reader#1439]
Aangezien het via de pvoutput api niet mogelijk is om alleen de temperatuur te updaten zonder daarbij ook v1, v2, v3 of v4 te specificeren lijkt het me handig om, wellicht met een checkbox, de mogelijkheid te hebben om bij de 'add status' call de temperatuur mee te sturen.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. DSMR-reader houdt het qua ondersteunde features bij gegevens die uit de meter komen. De weergegevens die er nu inzitten, hadden er achteraf gezien nooit in gemoeten. Zie oa #1344 / #1389.

----

Dat zeggende hebben zijn er nog wel andere mogelijkheden die je kunt proberen. Ik zie dat PVOutput hun complete docs op de schop heeft gegooid (goede verbetering) en nu valt deze feature mij op:
- https://pvoutput.org/help/auto_uploader.html

Want eigenlijk is de feature die je zoekt heel generiek en staat dat ook los van DSMR-gegevens. Je kunt kijken of dat een werkbare oplossing voor je is, bijvoorbeeld met een provider zoals deze:

> This weather device downloads weather data from an OpenWeatherMap city. It does not require a personal weather station. The following information is required from OpenWeatherMap

- https://pvoutput.org/help/auto_uploader.html#openweathermap
