### ISSUE TITLE
Please check your datalogger

### ISSUE THREAD

**Issue by onsmam** [dsmrreader/dsmr-reader#1443]
Hi,

sinds 2 dagen krijg ik elke 3 uur een melding over telegram; 
`It has been over 60 minutes since the last reading received. Please check your datalogger.` 
Als ik in de GUI kijk zie ik dat alles gewoon doorloopt, althans dat lijkt er wel op... ik zie de grafieken gevuld worden en het archief lijkt ook gewoon gevuld. ook op de ondersteuningspagina staat een groene balk welke aangeeft dat alles goed draait.

ik heb al geprobeerd om de 3 services te herstarten, reboot van de pi, deploy.sh uitgevoerd, maar ik blijf deze meldingen krijgen.

in de log file van de backend zie ik wel een fout, welke er volgens mij niet zo veel mee te maken heeft...:

```
2021-08-25 14:33:39,472 ERROR    mixins       run_once                        101 | dsmr_backend.management.commands.dsmr_backend: [!] Exception raised. Traceback (most recent call$
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: terminating connection due to administrator command
SSL connection has been closed unexpectedly
```

de debug info dump ziet er als volgt uit:

```

DSMR-READER
    App / Python / Database                                                     v4.16.3 / v3.7.3 / postgresql
    BE sleep / DL sleep / Retention / Override                                    1.0s / 10.0s / 168h / False
    Latest telegram version read / Parser settings                                                 "50" / "4"

DATA
    Telegrams total (est.)                                                                              89321
    Consumption records electricity / gas (est.)                                                 45522 / 3447

```

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Deze zal wat lastig zijn om te achterhalen. Die fout die je aangeeft is denk ik alleen relevant als die heel vaak terugkomt, want dat kan de datalogger wel in de weg zitten.

- Heb je 2 dagen geleden nog iets aan de setup verandert wat je je kunt herinneren? Bijvoorbeeld OS-update, DSMR-reader update, etc.

Niet heel lang geleden was de limiet 12 uur, maar sinds #1240 is dat 60 minuten geworden. Mijn eerste ingeving is te kijken of de systeemtijd op de Pi overeen komt. Je kunt dat simpelweg doen met:
```
date
```

Voor de rest doet DSMR-reader niet veel bijzonders. [Het checkt of de laatste meting binnen het uur is, zo ja dan doet die de check 5 minuten later nogmaals](https://github.com/dsmrreader/dsmr-reader/blob/v4/dsmr_notification/services.py#L219-L226). 

Je zou debuglogging kunnen inschakelen en kijken wat er gebeurt:
- https://dsmr-reader.readthedocs.io/nl/latest/how-to/troubleshooting/enabling-debug-logging.html

Verder kun je nog kijken of je gaten ziet in de tijdstippen van de datalogger metingen, rond de momenten dat je de notificatie kreeg:
- `/admin/dsmr_datalogger/dsmrreading/`

Check ook even of de tijdstippen van de telegrammen wel overeenkomen met de lokale tijd. Soms doen meters wat rare dingen, maar dan had ik al wel verwacht dat je in het dashboard ook al afwijkende tijden zou zien.

**Comment by onsmam** [comment]
> Bedankt voor je melding. Deze zal wat lastig zijn om te achterhalen. Die fout die je aangeeft is denk ik alleen relevant als die heel vaak terugkomt, want dat kan de datalogger wel in de weg zitten.
> 
> * Heb je 2 dagen geleden nog iets aan de setup verandert wat je je kunt herinneren? Bijvoorbeeld OS-update, DSMR-reader update, etc.

nee, althans... niet dat ik me herinner.. hij draait op de zelfde PI als mijn domotica, waar ik wel eens mee bezig kan zijn..

> Niet heel lang geleden was de limiet 12 uur, maar sinds #1240 is dat 60 minuten geworden. Mijn eerste ingeving is te kijken of de systeemtijd op de Pi overeen komt. Je kunt dat simpelweg doen met:
> 
> ```
> date
> ```

Tijd staat goed.

> Voor de rest doet DSMR-reader niet veel bijzonders. [Het checkt of de laatste meting binnen het uur is, zo ja dan doet die de check 5 minuten later nogmaals](https://github.com/dsmrreader/dsmr-reader/blob/v4/dsmr_notification/services.py#L219-L226).
> 
> Je zou debuglogging kunnen inschakelen en kijken wat er gebeurt:
> 
> * https://dsmr-reader.readthedocs.io/nl/latest/how-to/troubleshooting/enabling-debug-logging.html

Deze draait nu.. en verzameld data, even afwachten

> Verder kun je nog kijken of je gaten ziet in de tijdstippen van de datalogger metingen, rond de momenten dat je de notificatie kreeg:
> 
> * `/admin/dsmr_datalogger/dsmrreading/`
> 
> Check ook even of de tijdstippen van de telegrammen wel overeenkomen met de lokale tijd. Soms doen meters wat rare dingen, maar dan had ik al wel verwacht dat je in het dashboard ook al afwijkende tijden zou zien.

ik zie niks missen rond de tijd van de meldingen, ook alleen maar groene vinkjes.. tijd van de telegram klopt ook..

wat ik vreemd vind is dat hij exact 3 uur tussen de meldingen zit, ik zou zeggen dat dit een timeout is ofzo..
bij de Statusnotificatie-configuratie pagina zie ik dat hij gewoon netjes elke 5 minuten opschuift.

ik zal even kijken wat de debug zegt..

**Comment by dennissiemensma** [comment]
Je zou ook nog kunnen spelen met de interne waarde van die `60` minuten check.

- Als je **onderaan** in `dsmrreader/settings.py` (er staat als het goed is standaard alleen een `import` regel in) dit toevoegt:

```
DSMRREADER_STATUS_READING_OFFSET_MINUTES=90
```
_(er is geen envvar voor)_

- en **het backend process herstart**, dan kun je kijken of het wat uit maakt als je die bijvoorbeeld op `90` of `150` zet.

```
sudo su - dsmr
./reload.sh
```
(of direct in Supervisor herstart)

Dan zou die die waarde moeten pakken.

**Comment by onsmam** [comment]
Goedemorgen,

ik heb de logfiles even door gekeken, enigste wat ik zie is:

```
2021-08-27 08:29:37,273 WARNING  datalogger   telegram_to_reading              81 | Rejected telegram: Invalid telegram CRC. The calculated checksum '41976' (A3F8) does not match the telegram checksum '7992' (1F38)
```

1 a 2 minuten later krijg ik het telegram bericht. attached mijn log files. ik heb hem gisteravond even aangezet, en vrijwel meteen uitgezet en vanochtend net voor het bericht weer aangezet.

ik zal nog even met bovenstaande suggesties aan de gang gaan!

bedankt voor je hulp in ieder geval.


[dsmr_datalogger-stderr---supervisor-1wZl84.log](https://github.com/dsmrreader/dsmr-reader/files/7065471/dsmr_datalogger-stderr---supervisor-1wZl84.log)
[backend.log](https://github.com/dsmrreader/dsmr-reader/files/7065477/backend.log)

**Comment by dennissiemensma** [comment]
De tijd van de telegrammen uit je meter lijken iig wel goed:
```
2021-08-27 08:34:01,472 DEBUG    datalogger   telegram_to_reading              74 | Received telegram:
/ISK5\

1-3:0.2.8(50)
0-0:1.0.0(210827083347S)
```

`2021-08-27 08:34:01,472` vs `21-08-27 08:33:47 S` (~15 seconden verschil is niets vreemds)

---

Je zou ook nog kunnen kijken of de tijdstippen van de telegrammen goed in de DB komen:

```
sudo su - postgres
psql dsmrreader -c 'set timezone="europe/amsterdam"; select timestamp from dsmr_datalogger_dsmrreading order by timestamp desc limit 5;'
```

Je ziet dan de meeste recent 5, in onze tijdzone.

**Comment by onsmam** [comment]
> Je zou ook nog kunnen kijken of de tijdstippen van de telegrammen goed in de DB komen:
> 
> ```
> sudo su - postgres
> psql dsmrreader -c 'set timezone="europe/amsterdam"; select timestamp from dsmr_datalogger_dsmrreading order by timestamp desc limit 5;'
> ```
> 
> Je ziet dan de meeste recent 5, in onze tijdzone.

hi,

bedankt voor je reactie. 

dat lijkt ook goed te gaan. ik heb het command om 20:22:40 uitgevoerd

```
postgres@raspberrypi:~$ psql dsmrreader -c 'set timezone="europe/amsterdam"; select timestamp from dsmr_datalogger_dsmrreading order by timestamp desc limit 5;'
       timestamp        
------------------------
 2021-08-27 20:22:19+02
 2021-08-27 20:22:08+02
 2021-08-27 20:21:57+02
 2021-08-27 20:21:46+02
 2021-08-27 20:21:35+02
(5 rows)
```

als de tijdlijn zich doorzet zou ik over ca 7 minuten weer een melding moeten krijgen, ik heb
```DSMRREADER_STATUS_READING_OFFSET_MINUTES=90```
nu op 150 staan, 90 maakte geen verschil

edit: 150 maakt ook geen verschil.

ik heb nog even in het log gekeken maar daar zie ik helemaal niks verschillend in... ergens lijkt dus iets te hangen, al zou je verwachten dat dat na een restart wel over is... ik zal eens een clean install proberen... wellicht helpt dat...

**Comment by onsmam** [comment]
hoe spontaan het begon, is het spontaan ook weer gestopt... verder niets gedaan...
wellicht dat de laatste keer restart toch gewerkt heeft op een of andere manier... in ieder geval bedankt voor de hulp.

**Comment by dennissiemensma** [comment]
Oke desondanks fijn om te horen!
