### ISSUE TITLE
Support of Energy contract that uses hourly market prices

### ISSUE THREAD

**Issue by Ferao** [dsmrreader/dsmr-reader#1444]
> 🇳🇱 Lees eerst [deze info](https://github.com/dsmrreader/dsmr-reader/blob/v4/CONTRIBUTING.md) om jezelf te helpen.
> 
> 🇬🇧 First read [this info](https://github.com/dsmrreader/dsmr-reader/blob/v4/CONTRIBUTING.md) for self-service.

Hi, 

Can you please add support for hourly energy prices?

I see a 2 options (maybe even more)
1. get the market prices from web using for example Nordpool.
   (https://www.nordpoolgroup.com/Market-data1/Dayahead/Area-Prices/nl/hourly/?view=table)
   there is a Home-Assistant custom component that is using the Nordpool API.
   (https://github.com/custom-components/nordpool)
2. read the current engery price from a MQTT topic (and store it in the database for archive purposes)

Alvast bedankt,

**Comment by dennissiemensma** [comment]
Bedankt voor je suggestie! De prijzen/kosten in DSMR-reader zijn puur ter indicatie en alleen op dagbasis. Als je een nauwkeurige of diepe analyze wilt van de kosten, denk ik dat je het beter in een timeseries database of iets kan doen. 

DSMR-reader is namelijk in de basis alleen voor het uitlezen van de slimme meter en kan daar "een" visualisatie van maken en/of data doorsturen. 
Ik zie de feature die jij voor je ziet, eigenlijk in hetzelfde straatje als bijvoorbeeld opwekking zonnepanelen, analyse gas en temperatuur. Daar zijn gehele projecten op zichzelf voor te maken (bijvoorbeeld PVOutput, MinderGas, etc).
