### ISSUE TITLE
Archief verbruik per week inzien

### ISSUE THREAD

**Issue by niekniek89** [dsmrreader/dsmr-reader#1446]
Goedemiddag,

Een vraag (en geen idee of dit gewenst/mogelijk is):
Momenteel kan je het archief gebruiken voor dag/maand/jaarverbruik.
Is het ook mogelijk om het weekverbruik in te zien in het archief?

Het zou wellicht een "leuke" toevoeging zijn, maar zoals hierboven.. geen idee of dit gewenst/mogelijk is.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik zal het op de lijst van _mogelijke_ toekomstige features zetten. Het is namelijk helaas niet heel triviaal om in te bouwen, gezien de gebruikte datepicker geen weekselectie ondersteunt.

**Comment by dennissiemensma** [comment]
Het is behoorlijk wat werk en ik denk dat het het niet waard is, tov andere tools die mogelijk hetzelfde (en allerlei soorten intervals) makkelijker kunnen bieden. Meer toelichting in soortgelijk verzoek: https://github.com/dsmrreader/dsmr-reader/issues/1348#issuecomment-923339346
