### ISSUE TITLE
Gemiddelden gas in trends verdwijnen door kleine waarden

### ISSUE THREAD

**Issue by FredericMa** [dsmrreader/dsmr-reader#1453]
Ik gebruik DSMR-reader sinds 23 juni.
Gezien wij zonneboiler hebben, hebben we sindsdien weinig gas verbruikt.
Het is me opgevallen dat op gegeven momenten bijvoorbeeld 6 stukken op de piechart zichtbaar zijn en een paar dagen/weken erna plotseling maar 4. Zie hieronder:
Van 23 juni tot 11 september:
![image](https://user-images.githubusercontent.com/7840263/134971642-3d0ee606-97a5-440c-8ca9-ef0d0cba2dbe.png)
Van 23 juni tot 26 september:
![image](https://user-images.githubusercontent.com/7840263/134971742-e4f3f8e7-435d-45c1-9685-76e9b2373563.png)

Ik heb gemerkt dat de gemiddelden die via de API worden doorgestuurd een kleine waarde hebben nl 0.02 en 0.01.
We hebben in totaal 6.178 m³ gas verbruikt in de totale periode van ongeveer 100 dagen.
Als ik het goed heb, worden bij de berekening van de gemiddelden ook de uren met een verbruik van 0 m³ meegeteld. Dit zorgt ervoor dat het gemiddelde naar beneden getrokken wordt waardoor het na verloop van tijd onder 0.01 duikt en dus op 0 valt waardoor het ook verdwijnt uit de grafiek.
Als oplossing kan je de uren met waarde 0 negeren bij het berekenen van het gemiddelde. Anderzijds kan het ook een oplossing zijn om het aantal decimalen te verhogen zodat de waarde in de API niet op 0 valt.

Laat me gerust weten als deze uitleg niet duidelijk is of als je meer gegevens nodig hebt.

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Ik kan helaas beperkt wat voor je doen, omdat de meterstanden tot 3 decimalen doorgegeven worden.

Ik heb voor v4.18 de afronding naar de webinterface aangepast naar 5 decimalen. Mogelijk helpt dat in jouw edge-case. Als je handig bent met code, kun je het eventueel ook tijdelijk lokaal doorvoeren, om te kijken of dat het oplost: 2bb82d98d1456e7171297b426407fbeffe8a8aca

**Comment by FredericMa** [comment]
Thanks! I'll test later today.

**Comment by FredericMa** [comment]
Ik heb het getest en het geeft een veel beter resultaat. Bedankt!
![image](https://user-images.githubusercontent.com/7840263/135157468-0a20b4fd-49c2-491d-aa01-246e1b4d8cf8.png)

Is het een idee om de records met een verbruik of teruglevering van 0 eruit te filteren voor de berekening van de trends?
Dit zou een nog acuurater resultaat geven met veel kleinere afrondingsfouten.

**Comment by dennissiemensma** [comment]
Fijn om te horen!

Ik weet niet of het veel uit gaat maken als ik 0 eruit filter, omdat het effectief het gemiddelde (percentage) in alle uren evenredig aantast. Als het absolute gemiddelde in kWh/m3 weergegeven zou worden, zou het wel noodzakelijk zijn denk ik.

**Comment by dennissiemensma** [comment]
Uitgebracht in [v4.18](https://github.com/dsmrreader/dsmr-reader/discussions/1456)
