### ISSUE TITLE
💡Vergelijken: Temperatuur toevoegen

### ISSUE THREAD

**Issue by FutureCow** [dsmrreader/dsmr-reader#1506]
### Feature

Als je naar het archief gaat, kun je mooi de min/max/gem temperaturen zien van de dag/maand/jaar. 
Het zou ook mooi zijn als die bij het vergelijken mogelijk is, dan kun je het gasverbruik van verschillende dagen/maanden beter vergelijken. 
Wellicht zelf een kolommetje met: m³ / (18 - gem temp).
Ik weet dat de koppeling met gasmeter dit mogelijk maakt, maar dit is natuurlijk simpel toe te voegen als je alle gegevens als hebt :).

**Comment by FutureCow** [comment]
Zie nu dat dit al vaker is gevraagd en dat dit nooit de bedoeling is geweest om toe te voegen, helaas!

**Comment by dennissiemensma** [comment]
Dank voor je verzoek en fijn dat je zelf al antwoord had gevonden. Ik denk dat als je iets wilt doen met temperatuur en gas (en vooral ook graaddagen) je naar een dienst als MinderGas kan kijken (wellicht zijn er tegenwoordig ook andere).

Het is namelijk absoluut niet triviaal om een goede en eerlijke vergelijking te kunnen maken (kwam ik later achter). Vandaar deze keuze.
