### ISSUE TITLE
Dubbel gas telwerk

### ISSUE THREAD

**Issue by Wikkevogel** [dsmrreader/dsmr-reader#1511]
### Description

Hoi, op mijn slimme meter zitten twee telwerken voor het gas. Het eerste telwerk staat stil. Op het tweede telwerk wordt wel het gasverbruik bijgehouden. In Home Assistant zie ik nu alleen mijn electricteitsverbruik. Bij het gas wordt niets geregistreerd. Hoe kan dit verholpen worden? Ik gebruik een P1 kabel en een Raspberry Pi.
mvg, Frank

### DSMR-reader version

Laatste versie v

### DSMR-reader platform

Other

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Ik denk dat je het beste even een dump van een telegram uit je meter kan maken. Ben je daar bekend mee?

**Comment by Wikkevogel** [comment]
Dank voor je reactie. Nee, nooit eerder iets met een telegram gedaan.

**Comment by dennissiemensma** [comment]
Je kunt in je eigen DSMR-reader naar deze URL gaan, daar staat het telegram van je meter: `/admin/dsmr_datalogger/meterstatistics/`

**Comment by Wikkevogel** [comment]
Bedankt Dennis. Ik zie dat de netbeheerder inmiddels de eerste meter heeft verwijderd (ik had ze erover gebeld) en dat er nu wel data binnenkomt. De cijfers kloppen nu nog niet maar misschien moet ik even geduld hebben. Ik kom er op terug als ik er niet uitkom en dan zal ik een telegram bijvoegen. Tot zover dank!

**Comment by dennissiemensma** [comment]
Bedankt voor je aanvulling. Is je gasmeter toevallig vervangen? Want dat kan verkeerde standen verklaren. Dsmrreader fixt meterwissel niet automatisch, dat kun je het beste morgen handmatig eenmalig doen, mits het dus een meterwissel was.

**Comment by dennissiemensma** [comment]
@Wikkevogel https://github.com/dsmrreader/dsmr-reader/issues/1511#issuecomment-964429437

**Comment by Wikkevogel** [comment]
Nee, het betrof geen meterwissel. Bedankt voor je hulp.
