### ISSUE TITLE
🚨Raspberry Pi OS - Bullseye 

### ISSUE THREAD

**Issue by ghost** [dsmrreader/dsmr-reader#1512]
### Description

Aangezien vandaag [Raspberry Pi OS - Bullseye](https://www.raspberrypi.com/news/raspberry-pi-os-debian-bullseye/) is uitgekomen.
Kon ik het als pseudo Tweakers niet laten om Raspberry Pi OS - Bullseye eens te testen met dsmr-reader.
dsmr-reader lijkt allemaal naar behoren te werken op Bullseye. 

Ondernomen stappen:
- Manuele, volledige back-up gemaakt van de dsmr databank.
- Verse installatie Raspberry Pi OS - Bullseye op het micro-sd kaartje gezet.
- De dsmr  'Installatie: Stapsgewijs' uitgevoerd inclusief 'Optioneel: Database back-up terugzetten'.

Ik heb nog een volledige systeemback-up mocht e.e.a. achteraf toch niet helemaal lekker werken.

Excuses voor het eventuele ongemak dat ik dit hier plaats. 
Ik had van dit onderwerp graag een discussie gestart. Maar ik kon geen discussie openen. 

### DSMR-reader version

4.19

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
Bedankt voor je probeersel en fijn dat het goed lijkt te werken! Ik zou zeggen kijk het even een weekje aan of je toch niets vreemds ziet. In principe zou een OS-upgrade hooguit issues kunnen geven bij het installeren van packages.

Welke Python-versie komt nu trouwens standaard mee met Bullseye? Al zou het niet uit moeten maken gezien t/m Python 3.9 en zelfs 3.10 goed zou moeten werken met DSMR-reader.
