### ISSUE TITLE
Vergelijken geeft visueel verkeerde kleur bij negatief verschil

### ISSUE THREAD

**Issue by D1StrX** [dsmrreader/dsmr-reader#1517]
### Description

![Screenshot_20211121-121812](https://user-images.githubusercontent.com/40062371/142759971-4d926e1b-487d-43ee-b09a-4c12048e5fa3.jpg)

Bij het vergelijken van, in dit geval dagen, geeft dsmr het elektriciteit percentage verschil negatief aan, terwijl dit positief moet zijn. Zie voorbeeld screenshot.
Een minor visuele bug, maar toch net als die de juiste kleur aangeeft. (Icoon is juist)

### DSMR-reader version

4.19

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding! Ik zal het meenemen in een volgende release.

**Comment by dennissiemensma** [comment]
Wordt opgelost in v5.1. Kwam alleen voor bij het samenvoegen van hoog/laag tarief

**Comment by dennissiemensma** [comment]
Uitgebracht in https://github.com/dsmrreader/dsmr-reader/releases/tag/v5.1.0
