### ISSUE TITLE
🚨 Geen grafiek "Verhouding tarieven" als 100% nachtverbruik.

### ISSUE THREAD

**Issue by FredericMa** [dsmrreader/dsmr-reader#1523]
### Description

Hier in België is gedurende het hele weekend nachttarief van toepassing.
Ik wou mijn verbruik van vorig weekend bekijken en merkte dat de grafiek voor de verhouding van de tarieven niet getoond wordt. Hoewel deze grafiek weinig zou zeggen aangezien deze 100% nachttarief zou aangeven, veronderstel ik wel dat deze zou moeten verschijnen? Ik vermoed dat dit voor 100% dagtarief ook het geval zal zijn maar dat ga ik alvast niet snel te zien krijgen 😃 
![image](https://user-images.githubusercontent.com/7840263/143787790-466e6a66-2ae9-474d-b1dd-08dd4fbceac4.png)

### DSMR-reader version

4.19

**Comment by dennissiemensma** [comment]
Bedankt voor je melding, dit is een bug die mij nog niet bekend was. Mocht je bedreven zijn in je browser qua debuggen van netwerkverkeer, dan zie je dat de XHR-call faalt:
```

Server Error
Sorry, something unexpected happened.
Exception:

AttributeError: 'NoneType' object has no attribute 'items'

Traceback:

  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)

  File "/home/dsmr/dsmr-reader/dsmr_frontend/mixins.py", line 11, in dispatch
    return super().dispatch(request, *args, **kwargs)

  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)

  File "/home/dsmr/dsmr-reader/dsmr_frontend/views/trends.py", line 111, in get
    end=form.cleaned_data['end_date'],
```

Ik zal kijken of ik dit in een 5.1 of 5.2 release kan fixen.

**Comment by FredericMa** [comment]
Geen probleem, jij bedankt voor deze geweldige tool!

**Comment by dennissiemensma** [comment]
Gefixt in aankomende v4.20

**Comment by FredericMa** [comment]
Hi Dennis,

Hoewel de visualisatie nu wel een pie toont, is deze wel leeg bij 100% nachtverbruik. Ik had verwacht dat deze een pie weergeeft met 1 element namelijk 100% nachttarief.
Is het de bedoeling dat de chart leeg is?
![image](https://user-images.githubusercontent.com/7840263/154243380-8daa5ddc-646d-49c4-8ff5-81f7168a9907.png)

Edit: ik zit intussen op V5.0.

**Comment by dennissiemensma** [comment]
Bedankt voor je aanvulling. Er zit denk ik nog een bugje in, ik zie deze fout:
```
Uncaught TypeError: data is undefined
    update_trends_tariffs http://rpi4.siemensma.net/static/dsmr_frontend/js/dsmr-reader/trends/tariff.js?r=v5.1:74
    
```

**Comment by dennissiemensma** [comment]
Wat verbeteringen klaargezet voor v5.1

**Comment by dennissiemensma** [comment]
Uitgebracht in https://github.com/dsmrreader/dsmr-reader/releases/tag/v5.1.0

**Comment by FredericMa** [comment]
Werkt zoals verwacht nu, thanks!
