### ISSUE TITLE
Totaalverbruik toevoegen bij "Vergelijk"

### ISSUE THREAD

**Issue by QuadNL** [dsmrreader/dsmr-reader#1527]
### Description

Bij het vergelijken deel is het verbruik en teruglevering enkel hoog en laagtarief zichtbaar, opgeteld totaalverbruik/teruglevering is niet te zien. Wel in archief en dashboard.
![image](https://user-images.githubusercontent.com/66387274/144140857-b969a11b-7ca1-4cb2-aac8-3394617c6350.png)

Hier een voorbeeld van uit het archiefgedeelte:
![image](https://user-images.githubusercontent.com/66387274/144141091-49e35096-04f8-4a72-b3ab-959048925c30.png)

### DSMR-reader version

4.18

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
Bedankt voor je feedback. Ik zal er in de toekomst nog een keer wat dieper naar kijken. Puur het optellen zou nog wel toe te voegen zijn.

Overigens kun je voor het vergelijken van achtereenvolgende dagen ook nog de maandweergave in het Archief gebruiken. Dan zie je in 1 oogopslag de verhoudingen tussen alle dagen.

**Comment by dennissiemensma** [comment]
In de komende v5.4 release zijn de totalen toegevoegd.

![Screenshot from 2022-06-17 12-37-11](https://user-images.githubusercontent.com/16581744/174283663-e4a3e0fd-a22b-47ac-bd9a-8be43249ed96.png)

![Screenshot from 2022-06-17 12-37-24](https://user-images.githubusercontent.com/16581744/174283667-3efc5b87-9e74-4d99-ba24-98c881a227cb.png)

**Comment by QuadNL** [comment]
Hoi Dennis,

Wat goed, dank!
Ik zie uit naar update 5.4. 😊

Fijn weekend!

Elbert

**Comment by dennissiemensma** [comment]
Release van v5.4 staat voor **morgenavond** op de planning, mits er niets uit de 24-uurstest komt.
