### ISSUE TITLE
🚨Periode energiecontracten mist laatste dag

### ISSUE THREAD

**Issue by thijskuijpers** [dsmrreader/dsmr-reader#1534]
### Description

De berekening van totalen over de contractperiode lijkt de laatste dag te missen. De einddatum kan niet als begindatum van de volgende periode worden gebruikt, dus ik verwacht "van <datum> t/m <datum>" i.p.v. "van <datum> tot <datum>".
Zie screenshot, waarin ik 2 dagen verwacht maar alleen de eerste dag wordt meegenomen in de berekening. 
![2021-12-08 22_58_34-Energiecontracten _ DSMR Reader](https://user-images.githubusercontent.com/81739716/145292594-a729963b-c5e0-4f72-bc7a-b45cf77b6be0.png)

### DSMR-reader version

4.19

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Ik zal hier later wat dieper naar kijken. Deze bug was mij nog niet bekend.

**Comment by hv92** [comment]
Hier hetzelfde probleem. Duidelijk te zien dat maandag 3 januari (hoogtarief) niet mee wordt gerekend.

![image](https://user-images.githubusercontent.com/22493928/149205171-f45d0230-e87d-411b-ab65-9ebc378274ab.png)

**Comment by dennissiemensma** [comment]
Ik heb de oorzaak in ieder geval al gevonden:

https://github.com/dsmrreader/dsmr-reader/blob/c037848e0f96028fb500415b9289df40f81bc14f/dsmr_stats/services.py#L270

- `day__gte=start` = Groter dan of gelijk aan startdatum
- `day__lt=end` = Kleiner dan einddatum

Subtiel en is nooit opgevallen, het moet dus `day__lte=end` zijn zodat de einddatum ook meetelt. Ik neem het mee in een release.

**Comment by hv92** [comment]
Bedankt voor je snelle fix @dennissiemensma. Ik heb de bovenstaande regel aangepast, helaas ontstaat er weer een nieuwe bug. Het probleem is te zien als je naar Archief gaat en dan 1 dag selecteert. In het archief wordt blijkbaar van dezelfde functie gebruik gemaakt en is één dag blijkbaar huidige dag + volgende dag (en dan werkt kleiner dan wel correct).

2 dagen en hoogtarief voor zondag (van de maandag)
![image](https://user-images.githubusercontent.com/22493928/149999849-20e388a5-19c8-4b23-8e9c-453d4205a2bb.png)

**Comment by dennissiemensma** [comment]
Oh ik bedoelde ook niet dat die regel aangepast moest worden, maar het herleidt wel naar hoe het komt. De uiteindelijke fix is om de plek die dat aanroept aan te passen zodat die altijd +1 dag doet. Want bovenstaande query wordt inderdaad ook door andere features gebruikt.

**Comment by dennissiemensma** [comment]
Dit is de plek waar het vermoedelijk gefixt mag worden: https://github.com/dsmrreader/dsmr-reader/blob/c037848e0f96028fb500415b9289df40f81bc14f/dsmr_consumption/services.py#L512-L515

Naar zoiets:
```
        end_date = current.end or timezone.now().date()
        summary = dsmr_stats.services.range_statistics(
            start=current.start,
            end=end_date + timezone.timedelta(days=1)
        )
```

Ik kan het nu niet makkelijk testen, omdat ik qua ontwikkelomgeving nog midden in de voorbereidingen voor v5 zit.

**Comment by hv92** [comment]
Thanks! Ik had nav je vorig bericht ook al die regel gevonden en aangepast. Ik zal terugkoppelen of die wijziging de fix is.

Edit: het werkt. Ik heb wel de volgende regel staan, want het tweede deel wordt gebruikt als er geen einddatum is opgegeven:
end=current.end + timezone.timedelta(days=1) or timezone.now().date()

**Comment by dennissiemensma** [comment]
Ik neem het mee in v4.20. Fix via 53dfa85f1a129efe24234fc29bcdf45884bd7393.
