### ISSUE TITLE
🙋Na het upgraden van postgres naar v14 krijg ik een error van de automatische backup.

### ISSUE THREAD

**Issue by Diondk** [dsmrreader/dsmr-reader#1541]
### Description

Elke ochtend als ik inlog op mijn server is mijn dsmr reader container gestopt. Dit is eigenlijk al zo sinds de laatste update, gisteren heb ik mijn externe postgres geupgrade naar versie 14 omdat ik meerdere containers heb die daar van gebruik maken.

Nu heb ik de volgende errors:

```
2021-12-21 08:53:43,795 ERROR schedule execute_scheduled_processes 37 | (AttributeError) dsmr_backup.services.backup.run errored: 'NoneType' object has no attribute 'read'

could not find a "pg_dump" to execute
pg_dump: error: server version: 14.1 (Debian 14.1-1.pgdg110+1); pg_dump version: 13.5

pg_dump: error: aborting because of server version mismatch

2021-12-21 08:54:13,811 ERROR schedule execute_scheduled_processes 37 | (AttributeError) dsmr_backup.services.backup.run errored: 'NoneType' object has no attribute 'read'
```
Moet ik nu terug naar een oudere versie van postgres om deze error op te lossen?

### DSMR-reader version

4.19

### DSMR-reader platform

Docker (e.g. Xirixiz)

### Debug info dump

```shell
DSMR-READER
    App / Python / Database                                                      v4.19 / v3.10.0 / postgresql
    BE sleep / DL sleep / Retention / Override                                     1.0s / 5.0s / 168h / False
    Latest telegram version read / Parser settings                                                 "50" / "4"

DATA
    Telegrams total (est.)                                                                             426229
    Consumption records electricity / gas (est.)                                                32361 / 26594
```

**Comment by Diondk** [comment]
De error is weg nadat ik de backup heb uitgeschakeld, aangezien mijn postgres extern draait en daar een backup van wordt gemaakt. Ben ik dus wel veilig. Dan kan deze dicht, en zal ik morgen is kijken of hij nog crasht. mocht dat zijn dan maak ik een nieuw issue aan.

**Comment by dennissiemensma** [comment]
@Diondk bedankt voor je melding. Ik denk dat dit komt doordat de DB-client (`pg_dump`) een oudere versie is.

```
pg_dump version: 13.5
server version: 14.1
```

Je kunt het ook oplossen door de DB-client te upgraden naar versie 14, alleen is dat wellicht minder triviaal via een Docker image.
