### ISSUE TITLE
🙋 Geen hoog tarief meer?

### ISSUE THREAD

**Issue by BurgerhoutJ** [dsmrreader/dsmr-reader#1546]
### Description

Sinds vandaag zie ik alleen maar laag tarief terug in de monitoring. 
Is dit een klein jaarwisseling bugje?
![Screenshot_20220101-153028](https://user-images.githubusercontent.com/25769575/147852893-365e1fe4-f8b2-41e5-a199-b3be4f6603b6.jpg)

### DSMR-reader version

4.19

### DSMR-reader platform

Native (e.g. manual installation)

### Debug info dump

```shell
DSMR-READER
    App / Python / Database                                                       v4.19 / v3.9.2 / postgresql
    BE sleep / DL sleep / Retention / Override                                     1.0s / 5.0s / 672h / False
    Latest telegram version read / Parser settings                                                 "42" / "4"

DATA
    Telegrams total (est.)                                                                              34389
    Consumption records electricity / gas (est.)                                                    5603 / 51
```

**Comment by dennissiemensma** [comment]
Als het goed is draait er in de weekenden of op feestdagen geen hoogtarief. Of bedoel je dat niet?

**Comment by BurgerhoutJ** [comment]
Oh ja... Het is zaterdag. Sorry. 😏
