### ISSUE TITLE
🤔 DSMR reader compatible with 64bits Raspbian OS?

### ISSUE THREAD

**Issue by mkruiver** [dsmrreader/dsmr-reader#1562]
### Your question

Is DSMR reader eigenlijk compatible met 64 bits Raspbian?

https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-11-08/

of zouden misschien zelfs de Python packages etc nog niet beschikbaar zijn voor 64bits?

**Comment by mkruiver** [comment]
@dennissiemensma al eens geprobeerd?

**Comment by mkruiver** [comment]
Raspbian 64 lijkt iig met Python 3.9 voor ARM64 te komen.
Postgres is ook ARM64 compatible.

**Comment by mkruiver** [comment]
Werkt gewoon! :)

**Comment by dennissiemensma** [comment]
@mkruiver bedankt voor de check! Ik dacht dat alles inmiddels al 64 bit was, maar fijn dat het werkt!

**Comment by mkruiver** [comment]
Hoppa, Raspbian 64bits OS is officieel uit en DSMRReader draait al op 64bits ;)

https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/
