### ISSUE TITLE
OpenAPI specs wijken qua formaat af van de bestandsextensie (YAML ipv JSON)

### ISSUE THREAD

**Issue by mvaneijken** [dsmrreader/dsmr-reader#1563]
### Description

Als ik en DSMR-Reader de /api/v2/openapi.json download, dan bevat deze de specificatie in yaml formaat ipv json. Nu weet ik dat yaml en json op zich uitwisselbaar zijn, maar de extensie suggereert dat het om json gaat.

### DSMR-reader version

4.19

### DSMR-reader platform

Docker (e.g. Xirixiz)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding! Dit is niet bewust en ook niet bedoeld. Blijkbaar kan ReDoc met beide formaten overweg, want zo is niet mijn insteek. Ik zal de extensie aanpassen in DSMR-reader v5.x

**Comment by dennissiemensma** [comment]
@mvaneijken het was wat uitzoekwerk hoe het onderwater zit in dat API-framework. Bij jezelf er JSON uit te trekken kun je dit er achter zetten `?format=openapi-json`:
```
GET /api/v2/openapi.json?format=openapi-json
```

In DSMR-reader v5 zal ik de bestandsextensie weghalen. Gezien het dynamisch is.

**Comment by dennissiemensma** [comment]
Aangepast in 904e41400d59a3992f4ce7d840ec697840705a7d

**Comment by mvaneijken** [comment]
Dankje voor je reactie en uitzoeken! Ik ga het proberen met de genoemde parameter.
