### ISSUE TITLE
🚨 upgrade van 4.x naar 5.x  nginx 502 bad gateway

### ISSUE THREAD

**Issue by neverstoppedaskingwhy** [dsmrreader/dsmr-reader#1572]
### Description

De stappen in het plan https://dsmr-reader.readthedocs.io/nl/v5/tutorial/upgrading/to-v5.html op een raspberry pi met success alle gevolgd: Deployed version 5.0rc2

Iets is er toch nog niet juist (gedaan) - 502 Bad Gateway

Heb ik iets overzien? Of wat kan de oorzaak zijn?

### DSMR-reader version

5.0rc2

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
Wat is de output van:
```
sudo supervisorctl status
```

Verder kun je deze twee bekijken voor fouten van de webinterface:
```
sudo tail -f /var/log/supervisor/dsmr_webinterface.log
sudo tail -f /var/log/nginx/*.log
```

**Comment by neverstoppedaskingwhy** [comment]
bedankt voor de tips, het lijkt er op dat de dsmr_backend steeds opnieuw start

dsmr_backend                     RUNNING   pid 4618, uptime 0:00:09
dsmr_datalogger                  RUNNING   pid 4383, uptime 0:03:23
dsmr_webinterface                RUNNING   pid 4382, uptime 0:03:23

morgen maar even verder naar kijken


DSMR-READER
    App / Python / Database                                                     v5.0rc2 / v3.9.9 / postgresql
    BE sleep / DL sleep / Retention / Override                                     1.0s / 5.0s / 168h / False
    Latest telegram version read / Parser settings                                                 "50" / "4"

DATA
    Telegrams total (est.)                                                                             149605
    Consumption records electricity / gas (est.)                                                59494 / 51021

**Comment by dennissiemensma** [comment]
In dat geval kun je morgen in `sudo tail -f /var/log/supervisor/dsmr_backend.log` kijken. En anders debug logging inschakelen.

Als de datalogger verder wel draait, vermoed ik dat er iig metingen binnenkomen. Die worden dan later wel verwerkt. Je kunt het dubbelchecken qua recente metingen in de DB met:
```
sudo sudo -u postgres psql dsmrreader -c 'select id, timestamp from dsmr_datalogger_dsmrreading order by timestamp desc limit 10'
```

**Comment by dennissiemensma** [comment]
Of als je interface verder goed draait gewoon op het dashboard of er recente metingen binnenkomt. Ze worden alleen nog niet verwerkt.

**Comment by neverstoppedaskingwhy** [comment]
Metingen komen binnen in de DB. 

In de dsmr_backend.log staan komen meldingen dat de MQTT client geen verbinding krijgt met de broker. Nu heb ik wel eens gespeeld met de MQTT client, maar was de mening dat deze niet meer actief was. In ieder geval heb ik de MQTT broker ook niet meer actief. 

Waar en hoe kan de MQTT client in de configuratiebestanden handmatig worden uitgeschakeld? Web interface en admin interface zijn niet beschikbaar.

**Comment by neverstoppedaskingwhy** [comment]
ok, de mqtt settings heb ik inmiddels via psql gewist uit de tabel dsmr_mqtt_mqttbrokersettings. De foutmelding mbt. de verbinding tot de broker komt nu niet meer in dsmr_backend.log. 

dsmr_backend start nu ook niet steeds opnieuw, maar in dsmr_backend.log komt nog wel volgende melding:

```
2022-02-03 19:42:59,283 ERROR    mixins       run_once                        103 | dsmr_backend.management.commands.dsmr_backend: [!] Exception raised. Traceback (most recent call last):
  File "/home/dsmr/dsmr-reader/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.AdminShutdown: terminating connection due to administrator command
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dsmr/dsmr-reader/dsmr_backend/mixins.py", line 92, in run_once
    self.run(data=self.data, **options)
  File "/home/dsmr/dsmr-reader/dsmr_backend/management/commands/dsmr_backend.py", line 33, in run
    dsmr_backend.services.schedule.execute_scheduled_processes()
  File "/home/dsmr/dsmr-reader/dsmr_backend/services/schedule.py", line 29, in execute_scheduled_processes
    logger.debug('SP: %s backend service(s) ready to run', len(calls))
  File "/home/dsmr/dsmr-reader/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/dsmr/dsmr-reader/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/dsmr/dsmr-reader/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/dsmr/dsmr-reader/.venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/dsmr/dsmr-reader/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/dsmr/dsmr-reader/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/dsmr/dsmr-reader/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/dsmr/dsmr-reader/.venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/dsmr/dsmr-reader/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: terminating connection due to administrator command
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

web interface werkt nog niet

in de nginx/error.log: 

```
2022/02/03 19:44:53 [crit] 568#568: *2 connect() to unix:///var/tmp/gunicorn--dsmr_webinterface.socket failed (2: No such file or directory) while connecting to upstream, client: 192.168.178.40, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:///var/tmp/gunicorn--dsmr_webinterface.socket:/", host: "192.168.178.31"
```

**Comment by neverstoppedaskingwhy** [comment]
De exception schijnt eenmalig geweest te zijn. Een log met debug actief gemaakt. 

ergens gaat iets niet goed bij nginx - gunicorn - django

[supervisord.log](https://github.com/dsmrreader/dsmr-reader/files/7997849/supervisord.log)
[access.log](https://github.com/dsmrreader/dsmr-reader/files/7997850/access.log)
[dsmr_backend.log](https://github.com/dsmrreader/dsmr-reader/files/7997851/dsmr_backend.log)
[dsmr_webinterface.log](https://github.com/dsmrreader/dsmr-reader/files/7997852/dsmr_webinterface.log)
[error.log](https://github.com/dsmrreader/dsmr-reader/files/7997853/error.log)

**Comment by neverstoppedaskingwhy** [comment]
OK; opgelost

sudo ln -s **-f** /etc/nginx/sites-available/dsmr-webinterface /etc/nginx/sites-enabled/

**Comment by dennissiemensma** [comment]
Bedankt voor je update! Ik was niet in de gelegenheid om te reageren, fijn dat je het zelf als hebt gevonden. Ik zal de upgrade-guide aanpassen zodat die symlink erbij komt.

**Comment by dennissiemensma** [comment]
Docs worden zo bijgewerkt
