### ISSUE TITLE
🚨Foutje in de v4 installatie documentatie?

### ISSUE THREAD

**Issue by Calimerorulez** [dsmrreader/dsmr-reader#1573]
### Description

Hi Dennis,

Ik ben op een nieuwe server vanaf een schone Debian installatie de installatie van DSMR-reader aan het uitvoeren volgens:
https://dsmr-reader.readthedocs.io/nl/v5/tutorial/installation/step-by-step.html

Echter, bij de laatste stap, als ik de status van supervisor wil controleren, krijg ik onderstaande error:

```
dsmr_backend                     BACKOFF   can't find command '/home/dsmr/.virtualenvs/dsmrreader/bin/python3'
dsmr_datalogger                  BACKOFF   can't find command '/home/dsmr/.virtualenvs/dsmrreader/bin/python3'
dsmr_webinterface                FATAL     can't find command '/home/dsmr/.virtualenvs/dsmrreader/bin/gunicorn' 
```

Ik vermoed dat dat te maken heeft met dat in de scripts `.virtualenvs` gebruikt wordt, maar in de documentatie `.venv` in het pad. Klopt dat?

Groeten,
Patrick

### DSMR-reader version

4.19

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Dit komt omdat de v5 docs nog niet officieel zijn en de standaard Git branch nog `v4` is. Ik zal het aanpassen zodat voortaant bij de `git clone` expliciet de branch wordt opgegeven bij de docs.

Voor nu kun je het beste proberen om simpelweg de codebase te wisselen naar v5 en te kijken of dat (een deel) oplost. Het hangt er ook vanaf of je wel of niet een .venv hebt aangemaakt (ik vermoed van wel) of de vorige .virtualenvs variant van v4.

- Wissel
```
sudo su - dsmr
git checkout -b v5 origin/v5
```

- Check met `git branch` of je nu op v5 zit. 

- Nu nog nginx en supervisor configs van v5 kopieren:

```
logout

sudo cp /home/dsmr/dsmr-reader/dsmrreader/provisioning/nginx/dsmr-webinterface /etc/nginx/sites-available/
sudo ln -s -f /etc/nginx/sites-available/dsmr-webinterface /etc/nginx/sites-enabled/
sudo nginx -t
sudo systemctl reload nginx.service

sudo cp /home/dsmr/dsmr-reader/dsmrreader/provisioning/supervisor/dsmr_datalogger.conf /etc/supervisor/conf.d/
sudo cp /home/dsmr/dsmr-reader/dsmrreader/provisioning/supervisor/dsmr_backend.conf /etc/supervisor/conf.d/
sudo cp /home/dsmr/dsmr-reader/dsmrreader/provisioning/supervisor/dsmr_webinterface.conf /etc/supervisor/conf.d/
sudo supervisorctl reread
```

- Daarna kun je proberen of `./deploy.sh` het wel doet. Als je alleen PID fouten krijgt aan het einde, is het OK
```
sudo su - dsmr
/deploy.sh
```

- Probeer nu nogmaals alles te starten:
 ```
logout
sudo supervisorctl start all
```

**Comment by dennissiemensma** [comment]
Ik zal mn comment nog even bijwerken, want je moet nog wel wat andere configs kopieren nadat je op v5 zit bedenk ik me

**Comment by Calimerorulez** [comment]
Dank je voor je snelle en uitgebreide antwoord, ik heb de stappen gevolgd (en dacht de v4 docu gebruikt te hebben), en alles start nu 👍

**Comment by dennissiemensma** [comment]
Oke fijn om te horen!
