### ISSUE TITLE
🚨v5 upgrade ModuleNotFoundError: No module named 'MySQLdb'

### ISSUE THREAD

**Issue by GieltjE** [dsmrreader/dsmr-reader#1576]
### Description

When upgrading to v5 using MariaDB/MySQL the following error occurs:

```
Traceback (most recent call last):
  File "/home/dsmr/dsmr-reader/.venv/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
ModuleNotFoundError: No module named 'MySQLdb'
```

Easily fixed by running:
```
pip install mysqlclient
```

### DSMR-reader version

5.0

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
Bedankt voor de heads up! Dit "klopt" in de zin dat MySQL-support onofficieel is en ongedocumenteerd. Wel fijn dat je het al voor jezelf gefixt hebt. In principe ondersteun ik alleen PostgreSQL. 

Dat zeggende hebben probeer ik wel zoveel mogelijk gebruik te maken van het ORM in Django, waardoor de DB opslag meestal niet uit maakt, gezien DSMR-reader weinig spannends gebruikt qua queries. Daarom draai ik de tests nog steeds tegen 3 soorten DB's: https://github.com/dsmrreader/dsmr-reader/blob/v5/.github/workflows/automated-tests.yml#L80-L109

Zolang dat goed gaat en het mij niet veel extra moeite kost, blijf ik het "ondersteunen".

**Comment by GieltjE** [comment]
Ik weet dat het niet ondersteund word (heb alleen persoonlijk geen zin om database nr. 3 te draaien).
Is daarintegen wel even goed om het gedocumenteerd te hebben hier of misschien zelfs kort te vermelden in de normale documentatie.
