### ISSUE TITLE
🚨 Foutje in de V5 datalogger documentatie

### ISSUE THREAD

**Issue by Calimerorulez** [dsmrreader/dsmr-reader#1587]
### Description

Hoi Dennis,

Ik heb nog een klein foutje gevonden in de documentatie voor de alleen-datalogger-installatie (https://dsmr-reader.readthedocs.io/nl/v5/how-to/installation/remote-datalogger.html)

Onder het kopje "[Apparaat met remote datalogger](https://dsmr-reader.readthedocs.io/nl/v5/how-to/installation/remote-datalogger.html#id2)" moet bij # Requirements komen te staan:

`sudo -u dsmr /home/dsmr/.virtualenvs/dsmrreader/bin/pip3 install pyserial==3.5 requests==2.26.0 python-decouple==3.5`

In de commando's ervóór wordt `.virtualenvs` gebruikt namelijk, en geen `.venv`, en het pad (locatie 'dsmr-reader' met minteken i.p.v. zonder) klopt eigenlijk ook niet :)

### DSMR-reader version

v5

**Comment by dennissiemensma** [comment]
Bedankt voor je oplettendheid! Ik zal het bijwerken.

**Comment by dennissiemensma** [comment]
Ik heb het bijgewerkt in a2dd27495fc5c4fa3322a912f3f11879d7daca7b, over 5 a 10 mins zijn de docs wel bijgewerkt.
