### ISSUE TITLE
P1/DSMR-reader naar puls🤔

### ISSUE THREAD

**Issue by MIDieter** [dsmrreader/dsmr-reader#1588]
### Your question

Is het mogelijk om met DSMR-reader pulsen te creëren?

Er is al een bestaande meet-installatie en dsmr-reader zou kunnen functioneren als een gateway tussen de bestaande installatie en de nieuwe digitale meters. De bestaande installatie werkt via puls telling.
bv:  via een Raspberry PI op de gpio pinnen
- import elektriciteit: 1 puls per 0.1KWh
- export elektriciteit: 1 puls per 0.1KWh
- gas: 1 puls per 0.1m³

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek! Ik denk dat dat heel lastig gaat worden, vooral omdat er geen meterstanden zijn of DSMR-protocol is.

Dit project is gebaseerd op het uitlezen van de slimme meter via DSMR-telegrammen. En hoewel je een telegram wel kan simuleren via een script, blijf je dan zitten met de meterstanden die er dan niet zijn.
