### ISSUE TITLE
🙋DSMR = live consumption/returing values frozen

### ISSUE THREAD

**Issue by q144** [dsmrreader/dsmr-reader#1591]
### Description

hi,
i recently clean reinstalled my pi2B with bullseye image and 5.0 release
all works fine except live consumption/return values are frozen. 
i do have historic data being filled in without delay.nothing wrong in logs, even with debug.
deploy works fine.no indication in support tab there is something wrong...
![dsmr stuck](https://user-images.githubusercontent.com/59310412/155887371-59b66c94-7b19-44d7-8142-7379e8363348.JPG)

i think this info is generated via live-header-include.html but thats as far as i got.
any suggestions? 

### DSMR-reader version

5.0

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
I suspect there is one future reading causing this, as dsmrreader uses the latest one for these data. Do you see any future readings in the admin in: /admin/dsmr_datalogger/dsmrreading/

**Comment by q144** [comment]
no,

most recent are from today

**Comment by dennissiemensma** [comment]
What does this output?

```
sudo su - postgres
psql dsmrreader

# Edited:
SELECT id, timestamp, electricity_currently_delivered, electricity_currently_returned FROM dsmr_datalogger_dsmrreading ORDER BY timestamp DESC LIMIT 10;
```

**Comment by q144** [comment]
id    |       timestamp        | electricity_delivered_1
----------+------------------------+-------------------------
  49115537 | 2022-02-28 09:03:53+01 |                3888.367
  49115536 | 2022-02-28 09:03:48+01 |                3888.364
  49115535 | 2022-02-28 09:03:42+01 |                3888.361
  49115534 | 2022-02-28 09:03:37+01 |                3888.358
  49115533 | 2022-02-28 09:03:31+01 |                3888.355
  49115532 | 2022-02-28 09:03:26+01 |                3888.352
  49115531 | 2022-02-28 09:03:20+01 |                3888.349
  49115530 | 2022-02-28 09:03:15+01 |                3888.346
  49115529 | 2022-02-28 09:03:09+01 |                3888.342
  49115528 | 2022-02-28 09:03:03+01 |                3888.339

**Comment by digiater** [comment]
I've got exactly the same issue in v5.0:

```
dsmrreader=# SELECT id, timestamp, electricity_currently_delivered, electricity_currently_returned FROM dsmr_datalogger_dsmrreading ORDER BY timestamp DESC LIMIT 10;
   id    |       timestamp        | electricity_currently_delivered | electricity_currently_returned
---------+------------------------+---------------------------------+--------------------------------
 4394568 | 2022-02-28 15:07:02+01 |                           0.000 |                          2.245
 4394567 | 2022-02-28 15:06:47+01 |                           0.000 |                          2.176
 4394566 | 2022-02-28 15:06:35+01 |                           0.000 |                          2.225
 4394565 | 2022-02-28 15:06:22+01 |                           0.000 |                          2.161
 4394564 | 2022-02-28 15:06:10+01 |                           0.000 |                          2.221
 4394563 | 2022-02-28 15:05:54+01 |                           0.000 |                          2.321
 4394562 | 2022-02-28 15:05:42+01 |                           0.000 |                          2.218
 4394561 | 2022-02-28 15:05:31+01 |                           0.000 |                          2.168
 4394560 | 2022-02-28 15:05:20+01 |                           0.000 |                          2.269
 4394559 | 2022-02-28 15:05:07+01 |                           0.000 |                          2.252
(10 rows)
```

This is an old installation recently upgraded to v5.0. I just noticed this today as my consumption is frozen on 2070 and returning on 1111. The graphs seem to be okay.

**Comment by q144** [comment]
i did try to fool/force the live update by upgrading a record and restart services but no change 
(eg:update dsmr_datalogger_dsmrreading set timestamp='2-2-2023 18:01:14+01' where id =49121125;)

**Comment by dennissiemensma** [comment]
@q144 what does the updated query return?

```
SELECT id, timestamp, electricity_currently_delivered, electricity_currently_returned FROM dsmr_datalogger_dsmrreading ORDER BY timestamp DESC LIMIT 10;
```

**Comment by q144** [comment]
id    |       timestamp        | electricity_currently_delivered | 
electricity_currently_returned
----------+------------------------+---------------------------------+--------------------------------
  49121127 | 2023-02-02 18:01:14+01 | 0.388 |                          0.000
  49121645 | 2022-02-28 18:49:31+01 | 0.490 |                          0.000
  49121644 | 2022-02-28 18:49:26+01 | 0.490 |                          0.000
  49121643 | 2022-02-28 18:49:20+01 | 0.494 |                          0.000
  49121642 | 2022-02-28 18:49:15+01 | 0.487 |                          0.000
  49121641 | 2022-02-28 18:49:09+01 | 0.499 |                          0.000
  49121640 | 2022-02-28 18:49:04+01 | 0.509 |                          0.000
  49121639 | 2022-02-28 18:48:58+01 | 0.500 |                          0.000
  49121638 | 2022-02-28 18:48:53+01 | 0.497 |                          0.000
  49121637 | 2022-02-28 18:48:47+01 | 0.497 |                          0.000

**Comment by dennissiemensma** [comment]
@q144 @digiater can you press F12 while viewing the page and 

- check whether the `header` calls succeed in the **network** tab?
- and if so, view the response of them?

![Screenshot from 2022-02-28 18-49-09](https://user-images.githubusercontent.com/16581744/156032883-e3f4e580-4c2e-415f-ace9-9be2f91a6a17.png)

----

![Screenshot from 2022-02-28 18-48-34](https://user-images.githubusercontent.com/16581744/156033013-58b907d6-9912-40ab-bec3-80be133397de.png)

**Comment by q144** [comment]
found it.
i disabled and re enabled tracking protection and now its fine.
i believe the live data was marked as "cached".
this action probably reset/deleted my cache for this site

thanks :)

/feels like looking for a needle in a haystack while you're sitting on it...

**Comment by dennissiemensma** [comment]
Thanks for sharing! I'll add some no-caching header in the next release. Maybe that will solve it by default.

**Comment by dennissiemensma** [comment]
Current release:

![Screenshot from 2022-02-28 19-58-15](https://user-images.githubusercontent.com/16581744/156042260-75f9b903-232b-45d5-8625-c511359ba4f1.png)

----


Next release:

![Screenshot from 2022-02-28 19-58-04](https://user-images.githubusercontent.com/16581744/156042322-6a537e84-edb1-4f3f-9539-b077aa864ad7.png)

---

Hopefully it will prevent browser caching or whatever.

**Comment by digiater** [comment]
![ccache](https://user-images.githubusercontent.com/68736110/156053353-430272bb-4568-4872-885d-83be160f35fd.png)

The response is indeed cached. But I do not seem te get rid of it, restarting the browser, disabling/enabling enhanced protection, clearing the browser cache, restarting the webserver on the dsmr system all do not help.

**Comment by dennissiemensma** [comment]
DSMR-reader v5.1 is scheduled for tomorrow anyway, so it may be fixed shortly

**Comment by dennissiemensma** [comment]
Released in https://github.com/dsmrreader/dsmr-reader/releases/tag/v5.1.0

**Comment by digiater** [comment]
I upgraded to 5.1, upgraded the underlaying linux mint installation, rebooted, restarted browser, cleared browser cache and the problem is still there (firefox 97.0.1). It works fine on google chrome.

**Comment by dennissiemensma** [comment]
Can you check in the network tab whether the Expires/Cache-Control response headers are sent? 
And are there any other errors on the console tab? 

It works fine for me in Firefox 97 on Ubuntu, but it already did on previous DSMR-reader versions as well. So it quite hard for me to replicate the issue.

![Screenshot from 2022-03-02 18-15-38](https://user-images.githubusercontent.com/16581744/156413324-7bfb5a0e-148c-4643-900a-5981e87a795b.png)

**Comment by digiater** [comment]
It's not there. Notice the date in the response header, it's old. (the clock on the system has the correct time).

![image](https://user-images.githubusercontent.com/68736110/156415652-c0f4d35c-1001-423f-b3f6-d64365e68ac5.png)

**Comment by digiater** [comment]
If I create a network trace I can see the correct response, but it does not show up in the browser trace. I guess this is a firefox thing as other systems and browsers seem to be ok. I will dig a bit deeper.

**Comment by digiater** [comment]
There's a little button in the debug pane that says 'disable cache' and that did the trick. After that the entries will be fetched again from the server. This appears to be a browser issue.

![image](https://user-images.githubusercontent.com/68736110/156443496-d4a0f3ee-dab3-4b10-9e85-e28da739f25c.png)

**Comment by dennissiemensma** [comment]
Great, hopefully it'll fix the problem forever
