### ISSUE TITLE
FAQ link op pagina "Add Energy supplier (price)" wijst naar v4 documentatie🚨

### ISSUE THREAD

**Issue by mvaneijken** [dsmrreader/dsmr-reader#1595]
### Description

FAQ link op pagina "Add Energy supplier (price)" wijst naar de v4 ipv de v5 documentatie: "Updating prices for (past) days already stored in the Archive does not affect them. In order to reapply price changes retroactively [see the FAQ](https://dsmr-reader.readthedocs.io/en/v4/faq.html) for a how-to."

Betreft pagina met link: "/admin/dsmr_consumption/energysupplierprice/add/".

### DSMR-reader version

5.1

### DSMR-reader platform

Docker (e.g. Xirixiz)

**Comment by mvaneijken** [comment]
Is ook het geval voor de mindergas config: "Detailed instructions for configuring MinderGas.nl can be found here: [Documentation](https://dsmr-reader.readthedocs.io/nl/v4/how-to/admin/mindergas.html)". Pagina: "/admin/dsmr_notification/notificationsetting/"

En voor Notification config: "Detailed instructions for configuring MinderGas.nl can be found here: [Documentation](https://dsmr-reader.readthedocs.io/nl/v4/how-to/admin/mindergas.html)". Pagina: "/admin/dsmr_mindergas/mindergassettings/"

**Comment by dennissiemensma** [comment]
Gaat mee met v5.2

**Comment by dennissiemensma** [comment]
Bedankt voor het melden! Ik neem het mee voor de volgende versie.
