### ISSUE TITLE
Database Vacuum vraagje

### ISSUE THREAD

**Issue by niek1992** [dsmrreader/dsmr-reader#1598]
### Description

Hoi,

Onlangs geupgraded van v1.28 (ualex73) naar v5.0.0 (xirixiz). Had wat voeten in aarde, wilde namelijk mijn historie bewaren (wat uiteindelijk gelukt is met wat trial & error). Documentatie is niet helemaal 100% waardoor bepaalde commando's niet gingen werken bij mij.

Ik draai dus DSMR-Reader in:

- Docker;
- Ubuntu VM met 4gb RAM; 4 cores, 80gb SSD storage;
- ESXi host.

Nu is mijn Postgres database 16gb groot. Ruimte heb ik zat, maar vroeg me af of het uberhaubt nut heeft om dataretentie in te stellen. Performance is voor mij geen issue, maar volgens mij kan ik in de huidige webinterface toch niet zo gedetailleerd de data inzien. Het wordt per uur gegroepeerd als ik het juist heb. 

Dan is mijn conclusie ook dat het bewaren van deze data nutteloos is tenzij ik zelf een dashboardje ontwikkel die wel deze data gedetailleerd weergeeft, correct?

Ook had ik de Dropbox integratie ingesteld maar deze heeft nooit echt gewerkt. Weet dat deze vraag in een andere repo moet (namelijk die van Xirixiz of Ualex73) want dit had (voor zover ik kon ontdekken) te maken met verkeerde rechten op de database folder. Hij maakte wel netjes elke dag een backup naar Dropbox van 1kB, dus de integratie werkte.

### DSMR-reader version

V5.0.0

### DSMR-reader platform

Docker (e.g. Xirixiz)

**Comment by dennissiemensma** [comment]
Als het goed is is je v1.28 database automatisch te upgraden door v5.x naar de laatste versie. Voor de rest verwacht ik dat je geen issues zou hebben als je het via Docker draait, omdat alle wijzigingen tussen major versies bijna altijd te maken hebben met upgrades van Python e.d. Dat is voor Docker-gebruikers geen werk, los van je docker-compose config e.d.

Qua opslag win je het meeste door simpelweg een datalogger sleep in te stellen, als je niet elke seconde een versie waarde nodig hebt. 
Retentie of het roteren van gegevens is wel aan te raden zodat je DB-backups stukken kleiner worden. Je hebt gelijk dat je in principe op een niet-rPi + SSD minder last hebt van performance issues, alleen schaalt DSMR-reader niet oneindig door en als je de gegevens niet nodig hebt, zou ik ze lekker laten opschonen.

De dropbox-integratie is in v5.x op de kop gegaan, dus die kun je nu makkelijker koppelen als het goed is via een officiele Dropbox App (key) voor DSMR-reader. Daarna zou je gewoon de backups daar terug moeten zien, ook de grotere.
