### ISSUE TITLE
💡 Datalogger berichten bufferen in geval van verbindings probleem

### ISSUE THREAD

**Issue by HighTide** [dsmrreader/dsmr-reader#1610]
### Feature

De mogelijkheid voor de datalogger om lokaal een buffer bij te houden in het geval van een verbroken verbinding.

Ik draai een setup waarbij ik een raspberry pi als datalogger in de meterkast heb liggen. Het is nu me nu al een paar keer overkomen dat de raspberry pi zijn verbinding verliest, en aangezien ik het niet actief in de gate hou, ik er een maand later pas achter kom dat de datalogger niks heeft doorgegeven.

Nu zou het voor mij ideaal zijn als op het moment dat ik de internet verbinding van de datalogger herstel, alle data die niet is doorgegeven alsnog wordt doorgegeven.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik denk dat je het beste ervoor kunt zorgen dat je setup robuust is.

Je kunt dit op meerdere manieren doen, zoals:
- Simpelweg push notificaties instellen. Indien ingesteld geeft DSMR-reader een notificatie als er een tijd geen meting binnen is gekomen.
- Je datalogger Pi met een cron (dagelijks) herstarten. Dit is een wat agressievere methode, maar het forceert dat je Pi weer helemaal opnieuw alles opzet. Een lichtere variant zou een cron zijn die alleen het netwerk op de Pi + datalogger herstart.
- Simpelweg monitoring zetten op DSMR-reader via de eigen API. Er is een endpoint dat dezelfde informatie teruggeeft als de pagina in DSMR-reader bij problemen. Zie #1086.

De remote datalogger is puur gemaakt als proxy voor wanneer DSMR-reader ergens anders draait en niet als dataopslag of buffer. In principe vervult DSMR-reader die laatste rol, want die is zowel als proxy of eindount te gebruiken, afhankelijk van je behoeftes.
