### ISSUE TITLE
Remote DataLogger via Rest API🙋

### ISSUE THREAD

**Issue by rkops-bd** [dsmrreader/dsmr-reader#1611]
### Description

I have a P1 meter with full api support. How can I configure DSMR-reader to get data from this device.
https://mrwheel-docs.gitbook.io/dsmrloggerapi/

### DSMR-reader version

5.1

### DSMR-reader platform

Docker (e.g. Xirixiz)

**Comment by rkops-bd** [comment]
It also support telegram messages. I configured it in the DataLogger configuration with the specified IPaddress and port 80. But no data is captured in the DSMR reader application

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. DSMR-reader zelf ondersteunt alleen de directe verbinding naar je meter. Dat is ofwel serieel via een kabel ofwel via een netwerksocket zoals via `ser2net` ofwel via de remote datalogger van DSMR-reader. De remote datalogger leest overigens gewoon de seriele poort uit en forward het telegram naar de DSMR-reader API, maar zit dus wel direct op de meter.

De software die je beschrijft en nu gebruikt, leest zelf al de slimme meter uit. Als je die software ergens anders ook voor gebruikt, kun je overwegen om het te forwarden naar DSMR-reader, maar voor zover ik weet zijn daar (nog) geen scripts voor. Zie ook #1047 voor een eerdere vraag over dezelfde software.

Mijn advies is om `ser2net` te gebruiken met bijvoorbeeld onderstaande configuratie in `/etc/ser2net.conf`:
```
4000:telnet:600:/dev/ttyUSB0:115200 8DATABITS NONE 1STOPBIT banner max-connections=3
```
Ser2net leest dan de slimme meter poort uit en publiceert het op de opgegeven poort, in dit geval poort 4000.

Dan kun je DSMR-reader die laten uitlezen, maar blokkeer je niet andere applicaties die je eventueel wilt gebruiken, mits die uiteraard `ser2net` poorten kunnen uitlezen. Het hangt er vooral vanaf wat je zelf wilt gebruiken, gezien er een hoop tools en dashboards zijn tegenwoordig. Net wat je voorkeur heeft!
