### ISSUE TITLE
The headers or library files could not be found for jpeg

### ISSUE THREAD

**Issue by RichieB2B** [dsmrreader/dsmr-reader#1612]
### Description

Tijdens de upgrade van v4.20.0 naar v5.1.0 kon bij de stap
```
pip3 install -r ~/dsmr-reader/dsmrreader/provisioning/requirements/base.txt
```
Pillow niet worden geïnstalleerd door deze foutmelding:
```
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
```
De oplossing was simpel:
```
apt-get install libjpeg-dev
```

### DSMR-reader version

5.1.0

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Werkte de `sudo apt-get install libopenjp2-7-dev` lib uit de [upgrade guide](https://dsmr-reader.readthedocs.io/en/v5/tutorial/upgrading/to-v5.html#upgrade-to-dsmr-reader-v5) niet?

Zo ja, welk OS met welke OS-versie gebruik je?

**Comment by RichieB2B** [comment]
Jawel, die deed het prima. Ik draai raspbian buster op Pi 3b.

**Comment by dennissiemensma** [comment]
Bedankt voor je aanvulling. Wellicht begrijp ik je verkeerd hoor, maar werkte alleen `libjpeg-dev` voor je en niet `libopenjp2-7-dev`? Of is de ene een alias van de andere?

**Comment by RichieB2B** [comment]
Ik heb `libopenjp2-7-dev` geïnstalleerd zoals in de instructies staat. Pillow heeft echter (ook?) `libjpeg-dev` nodig.

**Comment by dennissiemensma** [comment]
Hmm vreemd. Wat krijg je allemaal te zien bij deze:

```
sudo apt list --installed | grep jp
```

Ik heb ook Buster en blijkbaar werkend via deze:
```
libjpeg62-turbo/oldstable,now 1:1.5.2-2+deb10u1 armhf [installed,automatic]
libopenjp2-7-dev/oldstable,now 2.3.0-2+deb10u2 armhf [installed]
libopenjp2-7/oldstable,now 2.3.0-2+deb10u2 armhf [installed,automatic]
```

Staat er bij jou wat anders bij?

**Comment by dennissiemensma** [comment]
Ik heb overigens tot nu toe drie meldingen gehad, dus ik weet alleen wat er gemeld wordt en niet wat men zelf oplost.

-  `libopenjp2-7-dev` - #1590
-  `libopenjp2-7-dev` - #1577
- `libjpeg-dev` - jouw melding

**Comment by RichieB2B** [comment]
`ImportError: libopenjp2.so.7` lijkt me ongerelateerd aan `The headers or library files could not be found for jpeg` ?

**Comment by dennissiemensma** [comment]
Ja de melding wel, alleen kwamen die andere fouten ook uit Pillow en ze hebben beiden te maken met JPEG. Dus ik ben zoekende waarom het bij mij wel werkte of installeerde zonder die extra lib. Op hetzelfde OS.

**Comment by dennissiemensma** [comment]
Welke Python-versie draai je? Wellicht zit daar nog een (conditioneel) verschil in voor Pillow. Ik zit op Python 3.9.

**Comment by RichieB2B** [comment]
Buster heeft Python 3.7.3. Probeer dit eens:
```
docker run -it debian:buster /bin/bash
apt update
apt -y install git python3-dev python3-venv gcc libpq-dev zlib1g-dev
git clone --branch v5 https://github.com/dsmrreader/dsmr-reader.git
python3 -m venv ~/dsmr-reader/.venv/
source ~/dsmr-reader/.venv/bin/activate
cd dsmr-reader/
pip3 install -r dsmrreader/provisioning/requirements/base.txt
```
Dit geeft:
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kiheff18/Pillow/setup.py", line 1009, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
```
Het package `libjpeg-dev` is gewoon nodig voor Pillow op buster.

**Comment by RichieB2B** [comment]
> Welke Python-versie draai je? Wellicht zit daar nog een (conditioneel) verschil in voor Pillow. Ik zit op Python 3.9.

Installeert met Python 3.9 het Pillow package wellicht als `whl` of wordt hij ook van source gecompileerd? Want alleen dan heb je `libjpeg-dev` nodig natuurlijk.

**Comment by dennissiemensma** [comment]
Bedankt voor je aanvullingen! Ik heb hier nog wat dieper naar gekeken en ik kom er niet uit. 

Via mijn docker dev setup op Buster kan ik het niet reproduceren, maar wel met jouw stappen in Buster. Met dezelfde stappen werkt het wel weer zonder die fout op Bullseye.
Het kan best zijn dat het in Python 3.9 anders werkt of dat Pillow daar anders wordt geinstalleerd en daarom ook geen issue is bij mijn installatie en wellicht ook anderen die bijvoorbeeld al Debian Bullseye (of gewoon Docker) gebruiken. Overigens hint de upgrade-guide ook al op Python 3.9, dus wellicht nog een andere reden dat er niemand nog tegenaan is gelopen of gemeld heeft.

Ik zal voor de volgende release een heads up plaatsen, mocht iemand er ook tegenaan lopen bij Python 3.7.

**Comment by dennissiemensma** [comment]
Net gereleased via [v5.2](https://dsmr-reader.readthedocs.io/en/v5/reference/changelog.html#v5-2-0-2022-05-24)
