### ISSUE TITLE
🙋 Upgrade van 4.20 naar 5 failed (no module named 'django')

### ISSUE THREAD

**Issue by BurgerhoutJ** [dsmrreader/dsmr-reader#1614]
### Description

Ik heb netjes de manual gevolgd om van v4.20 naar v5 te upgraden en alles gaat goed tot dat ik commando `./deploy.sh` doe van stap 6.
Dan krijg ik de volgende melding:
![image](https://user-images.githubusercontent.com/25769575/162756534-de75ae82-d1c2-41ca-97b3-2342ededea3c.png)

Kan iemand bij helpen? Of moet ik nu helemaal opnieuw beginnen?

Admin portal is ook niet meer te bereiken.

### DSMR-reader version

4.20

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by BurgerhoutJ** [comment]
Heb geen idee wat er aan de hand was, maar nogmaals de upgrade uitgevoerd en nu doet ie het. Dus.... case closed.

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Ik vermoed dat het installeren van de dependencies (waaronder Django) niet helemaal lekker is gegaan. Hoe dan ook fijn dat het nu wel werkt!
