### ISSUE TITLE
Public internet access/indexing by crawlers prevention

### ISSUE THREAD

**Issue by ArNRDS** [dsmrreader/dsmr-reader#1615]
### Feature

Hi, 

With more and more people jumping aboard getting the data out of the P1, also some non security minded people might try it. I have noticed trying to learn about the tool that putting the right search into Google, will lead you to many public exposed instances of DSMR reader. Might be on purpose, might be not. 

Maybe there is a way to prevent / warn people about security risk, adding e.g. a short how-to on security, or notifications/warnings from within the tool, logging IP's hitting the pages, or even prevent indexing by Google (I do not know what is possible here, not a developer myself).

e.g. try searching: DSMR Number of voltage sags/dips in phase L1

PS: just into DSMR reader recently, great easy to use tool and most stable one I found yet.

**Comment by dennissiemensma** [comment]
Hi, thanks for the heads up! I've recently added a directive for web crawlers (or it will be included in the next release), which may reduce automated indexing in Google.

However, this requires users to upgrade as well, and some installations I've found are (quite) some versions behind. Also, there is a warning in the docs as well: https://dsmr-reader.readthedocs.io/en/latest/tutorial/setting-up.html#public-webinterface-warning
But only users who manually install are likely to read it. Docker-users may not even visit the docs at all.

Finally, there is an option in the DSMR-reader settings to have DSMR-reader at least require every visitor to be logged in as admin. But it's disabled by default, as enabling it by default would complicate stuff for new users. Maybe I'll create some kind of on-first-run-setup-guide for new installations in the future, but it will take some time and I'd really rather develop some new features instead. So for now I'll keep it as-is, maybe somewhere in the future I'll reconsider.
