### ISSUE TITLE
België : Laagtarief / Hoogtarief omgewisseld in DSMR GUI💡

### ISSUE THREAD

**Issue by verstrepeng** [dsmrreader/dsmr-reader#1622]
### Feature

Hernoemen van de naam van de tarieven. In Belgie is dit Dag/Nacht bijvoorbeeld.
Momenteel zijn laag en hoogtarief gewisseld.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek! Zie:

# #1396
