### ISSUE TITLE
Data verloren van 2 dagen🙋

### ISSUE THREAD

**Issue by Roel0412** [dsmrreader/dsmr-reader#1626]
### Description

In de nacht van vrijdag op zaterdag is er een storing ontstaan op mijn raspberry pi. Sindsdien heeft DSMR reader niets opgeslagen aan data. Na een herstart van de Raspberry Pi vandaag werkt alles weer, maar ben nu de data kwijt van zaterdag, zondag en de halve dag vandaag.

Kan dit nog ergens uitgelezen worden, zodat de data beschikbaar komt?

### DSMR-reader version

5.1

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Helaas is de data in dat geval weg. Als DSMR-reader niets heeft kunnen schrijven, staat het ook nergens.
Hier is ook vrij weinig aan te doen. Je kunt in theorie bijvoorbeeld monitoring toevoegen, maar dan moet je monitoring ook blijven werken. Etc, etc.

Ik denk overigens dat je van geluk mag spreken dat je er zo relatief snel achter bent gekomen ipv na enkele maanden.
