### ISSUE TITLE
'Day statistics are lagging behind' ook na het volgen van de How-to

### ISSUE THREAD

**Issue by ghost** [dsmrreader/dsmr-reader#1627]
### Description

Na het doorlopen van [de betreffende How-to](https://dsmr-reader.readthedocs.io/en/v5/how-to/troubleshooting/lagging-statistics.html) nog steeds last van 'Day statistics are lagging behind'. In mijn geval 'Day statistics are lagging behind   (1 day, 16 hours ago)'
En oplopende...

Ik heb naast de How-to opties en meermaals het genereren van de Day statistics geforceerd hebbende. Een dsmr-reader backup teruggezet op zowel de huidige alsmede een nieuwe PI installatie op een ander bordje met een verse software installatie. Dat laatste bordje draait overgens alweer 2 werk dagdelen. Beide geen soelaas. Het vreemde is dat ik in de debug logs geen errors tegen kom.

De actuele meet gegevens zijn correct. Ook als ik dit test met het inschakelen van een waterkoker en ineens veel energie vraag. Klopt het actuele verbruik. Dsmrreader lijkt echter de dag statistics niet bij te willen werken. Verder is er niets veranderd. Geen stroomstoring, slimme meter niet vervangen, niet van het Gas (iemand in de comments had soortgelijke problemen na afsluiten Gas) af.

Iemand een idee?

### DSMR-reader version

5.1

### DSMR-reader platform

Native (e.g. manual installation)

### Debug info dump

```shell
DSMR-READER
    App / Python / Database                                                        v5.1 / v3.9.2 / postgresql
    BE sleep / DL sleep / Retention / Override                                     1.0s / 5.0s / 672h / False
    Latest telegram version read / Parser settings                                                 "50" / "4"

DATA
    Telegrams total (est.)                                                                             199117
    Consumption records electricity / gas (est.)                                               193202 / 25303

UNRESOLVED ISSUES
    Day statistics are lagging behind                                                     1 day, 16 hours ago
```

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Als je geen fouten tegenkomt in de debug-logging, wat zie je dan wel als je zoekt op `Stats:`?

Als het goed is zie je in debug-mode juist wat er gebeurt, ook als er geen fouten zijn. Specifiek het deel voor de dagstatistieken zou je goed moeten kunnen zien waarom die geen dagstatistieken maakt. 

Zoals:
- https://github.com/dsmrreader/dsmr-reader/blob/v5.1.0/dsmr_stats/services.py#L64
- https://github.com/dsmrreader/dsmr-reader/blob/v5.1.0/dsmr_stats/services.py#L73
- https://github.com/dsmrreader/dsmr-reader/blob/v5.1.0/dsmr_stats/services.py#L82
- https://github.com/dsmrreader/dsmr-reader/blob/v5.1.0/dsmr_stats/services.py#L89
- https://github.com/dsmrreader/dsmr-reader/blob/v5.1.0/dsmr_stats/services.py#L101

**Comment by dennissiemensma** [comment]
@bertusdebruin ben je wat wijzer geworden met bovenstaande en debuglogging?

**Comment by ghost** [comment]
@dennissiemensma Nou ik heb er de eerst volgende dagen na melding,
geen aandacht aan kunnen besteden i.v.m. onverwachte drukte en omstandigheden op het werk. Excuses.

Toen ik het probleem een paar dagen later probeerde op te pakken was het probleem pardoes verdwenen toen ik wilde inloggen. Ik wilde het daarna nog eerst een paar dagen aanzien en de dsmr-reader rustig doorlaten pruttelen om te kijken of het stabiel blijft lopen. Voordat ik hier van alles ga roepen. Vandaar mijn late reactie. Maar het draait nog steeds stabiel. 

Achteraf vermoed ik het bijplaatsen van een nieuw transformatorhuisje in de nieuwe wijk, toevallig schuin tegenover mijn huis. 
Als het probleem. Ik ben hierover niet geinformeerd. En had het in eerste instantie ook helemaal niet door.

Je weet wel die grote grijze, metalen kisten. Dat zijn toch moderne transformatorhuisjes?
Blijkbaar is de stroom er meermaals kort afgeweest met vreemde en niet te herleiden storingen in mijn DSMR-reader systeem als gevolg. 

Het is een grote puinzooi hier in de wijk. De wijk is slechts een paar maanden terug opgeleverd. 
En nu liggen de net definitief (non bouw) aangelegde wegen alweer open om een glasvezelnetwerk aan te leggen (had dat dan meteen gedaan). 

Ook op het energienetwerk is blijkbaar een tekort aan capaciteit omdat iedereen in deze nieuwe wijk toevallig (not) overal zonnenpanelen installeert. Maar dat is een andere discussie. 

Nogmaals dank voor je tijd. Ik kom er op terug mocht ik een alsnog fouten krijgen.

**Comment by dennissiemensma** [comment]
Bedankt voor je zeer uitgebreide toelichting! 

In dat geval sluit ik het issue dan voor nu. Mocht het nogmaals voorkomen en niet te herleiden zijn, dan kunnen we hem ook weer net zo makkelijk heropenen.
