### ISSUE TITLE
Na meterwissel of verhuizing is jaarverbruik niet meer goed🚨

### ISSUE THREAD

**Issue by rtrinks** [dsmrreader/dsmr-reader#1632]
### Description

Er wordt aangegeven dat bij verhuizing of meterwissel, dat dit enkel de dag is waarop dat is uitgevoerd.
Maar op jaartotaal blijft dit een issue en heb ik een groot negatief getal wat dan logisch is.

Maar hoe lossen we dit op? Ik kan het nergens vinden en ook in de FAQ niet.

![Verbruik](https://user-images.githubusercontent.com/2185638/168465349-157316a8-f651-4cb8-8488-0982ef14fe5a.png)

### DSMR-reader version

DSMR-reader v4.18

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Heb je de betreffende wisseldag zelf al gecorrigeerd?

Zie https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/smart-meter-replacement.html

Als het goed is klopt alles daarna weer, omdat het de maand- en jaartotalen een optelsom zouden moeten zijn van alle individuele dagen.

**Comment by rtrinks** [comment]
Aangepast en staat nu in ieder geval weer helemaal goed. Bedankt.
