### ISSUE TITLE
🙋Upload to mindergas.nl failed

### ISSUE THREAD

**Issue by Flappiee** [dsmrreader/dsmr-reader#1634]
### Description

Ik heb eindelijk mijn historie van Domoticz overgezet in DSMR reader.

Ik gebruikte de API van Domoticz om de gasstand uit te lezen en te uploaden naar mindergas.nl.
Ik heb de API key nu ingegeven in DSMR Reader zodat DSMR Reader de upload naar mindergas.nl kan doen.
Echter werkt het niet en krijg ik deze melding:

May 18, 2022: Failed to export to MinderGas: Unexpected status code received

Het is toch alleen een kwestie van je API key invoeren?
Ik heb al een nieuwe API key aangevraagd maar blijf dit probleem houden.

### DSMR-reader version

5.1

### Debug info dump

```shell
DSMR-READER
    App / Python / Database                                                        v5.1 / v3.9.2 / postgresql
    BE sleep / DL sleep / Retention / Override                                     1.0s / 5.0s / 672h / False
    Latest telegram version read / Parser settings                                                 "42" / "4"

DATA
    Telegrams total (est.)                                                                              51188
    Consumption records electricity / gas (est.)                                                 11978 / 3894
```

**Comment by Flappiee** [comment]
never mind, al opgelost. Blijkbaar duurt het wisselen van de API keys even :)

**Comment by dennissiemensma** [comment]
@Flappiee bedankt voor je melding en update. Mocht je er weer tegenaan lopen, wellicht zie je in de logs de exacte fout(code).

Want de MinderGas API heeft wat diverse foutsituaties, zoals max 1 meterstand per dag en moet oplopend in de toekomst zijn, dus dat bijt soms wel eens bij overstappen tusen systemen. Of het was de API key zelf. Hoe dan ook mooi dat je het alweer werkend hebt!
