### ISSUE TITLE
🚨 Deleting a large amount of MQTT messages causes a 400 Reply

### ISSUE THREAD

**Issue by dekimpew** [dsmrreader/dsmr-reader#1643]
### Description

I'm trying to remove a huge amount of mqtt messages that are pending on dsmr because the mqtt broker is/was offline. When selecting all of them (5), the page returns a **Bad Request (400)** instead of deleting the messages.

Deleting messages in batch (100) works fine.

### DSMR-reader version

5.1

### DSMR-reader platform

Native (e.g. manual installation)

### Debug info dump

```shell
DSMR-READER
    App / Python / Database                                                        v5.1 / v3.9.2 / postgresql
    BE sleep / DL sleep / Retention / Override                                     1.0s / 5.0s / 672h / False
    Latest telegram version read / Parser settings                                             "None" / "101"

DATA
    Telegrams total (est.)                                                                            2343294
    Consumption records electricity / gas (est.)                                                46640 / 15179

UNRESOLVED ISSUES
    Too many outgoing MQTT messages queued for transit                                                    now

POSTGRESQL SIZE OF LARGEST TABLES (> 500 MB)
    public.dsmr_datalogger_dsmrreading                                                                 616 MB
```

**Comment by dennissiemensma** [comment]
Thanks for reporting. If the admin interface cannot handle thousands of messages, it's something I cannot fix, since it's related to Django framework. However, you can wipe them all in one command using the database. Do you still need support or did you finish purging manually already?

**Comment by dekimpew** [comment]
I have not. Having the command will be useful for future references also.

**Comment by dennissiemensma** [comment]
Try this:

```
sudo su - postgres
psql dsmrreader

delete from dsmr_mqtt_message;
```

It may take a few seconds, depending on the amount of data to delete (and hardware).

**Comment by dekimpew** [comment]
Thanks! That worked instantaneously. I assume this one can be closed then?

**Comment by dennissiemensma** [comment]
Great, sure!
