### ISSUE TITLE
mqtt bericht aanpassen / idx voor domoticz💡

### ISSUE THREAD

**Issue by jrosier** [dsmrreader/dsmr-reader#1647]
### Feature

Ik wil een aantal data via mqtt naar domoticz sturen. Domoticz heeft een idx veld nodig. Kan ik dat ergens toevoegen in het json bericht? Als ik het handmatig doe, gebeurt er niets:
[mapping]
electricity_delivered_1 = electricity_delivered_1
electricity_currently_returned = dsmr/reading/electricity_currently_returned

(Deze zou ik willen toevoegen)
1051=idx

**Comment by dennissiemensma** [comment]
Ik denk dat wat je zoekt niet mogelijk is. DSMR-reader kan alleen de velden mappen die beschikbaar zijn. Als het een vaste waarde moet zijn die je zelf bepaalt, dan kun je kijken naar iets ala Node Red. Ik lees dat dat vaak gebruikt wordt voor een dergelijke conversie.
