### ISSUE TITLE
🙋 DSMR maakt geen backups meer van data

### ISSUE THREAD

**Issue by Roel0412** [dsmrreader/dsmr-reader#1648]
### Description

Vorige week is mijn SD kaart kapot gegaan. Nu heb ik alles opnieuw weten te installeren op een SSD schijf.

Nu heb ik alleen het probleem dat er geen backups meer gemaakt worden van de database naar de USB stick.

![image](https://user-images.githubusercontent.com/63040431/174853451-aa997864-faef-4530-80eb-a8987afb7c68.png)

De laatste backup is van 15 juni.

Alles staat goed ingesteld. De USB stick is ook gemount en te benaderen. Ook heb ik de rechten er goed op staan. 

Heb je nog tips wat ik kan checken?

### DSMR-reader version

5.3

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
Je kunt in `/admin/dsmr_backend/scheduledprocess/` het `Create daily backup` proces aanklikken en **Today** + **Now** aanklikken en opslaan. Als het goed is maakt die dan een backup. Mogelijk zie je wat in de logs.

![Screenshot from 2022-06-21 19-59-34](https://user-images.githubusercontent.com/16581744/174867879-efc72c55-3401-4a73-ba6a-fb912db87f83.png)

![Screenshot from 2022-06-21 20-01-27](https://user-images.githubusercontent.com/16581744/174867882-02d1edee-6fea-4a87-8bef-3cd27696cb29.png)

----

Je kunt ook handmatig proberen:

```
sudo su - dsmr
./manage.py dsmr_backup_create --compact
```

Je krijgt dan iets als:
```
(.venv) dsmr@rpi4:~/dsmr-reader $ ./manage.py dsmr_backup_create --compact
Created partial backup: /home/dsmr/dsmr-reader/backups/manually/dsmrreader-postgresql-partial-backup-2022-06-21.sql.gz
```

Dan kun je iig zien of de rechten goed staan.

----

Een mogelijk oorzaak _kan_ zijn dat de client-versie van `psql` niet compatible is met je server `Posgres` versie. Mocht je daar wijzigingen in gedaan hebben.

**Comment by Roel0412** [comment]
De backup staat al aan in settings.

Ik heb hem handmatig proberen te draaien, maar krijg dan inderdaad dat ie
rechten mist:

![image](https://user-images.githubusercontent.com/63040431/174876354-ce8dbb81-4e60-476b-b43d-fddea4724179.png)


Ik krijg alleen de rechten niet goed. Hoe kan ik dat oplossen?

**Comment by dennissiemensma** [comment]
Bij die backup-settings kun je straks de backup herplannen naar "nu" om te simuleren wat die komende nacht gaat doen.

Voor de rechten kun je dit proberen als `pi` user:

```
sudo chown -R dsmr.dsmr /mnt/usb/backups/
```

**Comment by Roel0412** [comment]
Ik krijg op alle files in die map Operation not permitted:

![image](https://user-images.githubusercontent.com/63040431/174888741-7c46f55b-1261-4ddc-9e1d-4783d88d4b5e.png)

**Comment by dennissiemensma** [comment]
Je zult denk ik dan nog even wat moeten debuggen, gezien daar niet 1 oorzaak voor is: https://linuxpip.org/fix-chown-operation-not-permitted/

**Comment by Roel0412** [comment]
Is het een optie om de USB stick te formatteren en de backup weer aanzetten?
De data staat nu veilig op de SSD, de oude backups heb ik in principe niet meer nodig volgens mij.
Ik denk dat ie het niet doet, omdat ik het OS enz opnieuw moest installeren op een SSD i.p.v. de kapotte SD kaart.

**Comment by dennissiemensma** [comment]
Je kunt de backups ook gewoon op de SSD zelf zetten met de standaardinstellingen. Die slijt als het goed is lang niet zo snel als een SD-kaart.

Eventueel kun je je backups via Dropbox archiveren voor de zekerheid.

**Comment by Roel0412** [comment]
Thanks, ik ga d'r ff verder mee rommelen. Ben al wel wat verder gekomen. Heb de backups nu naar de SSD gezet en zal ff kijken voor Dropbox.
