### ISSUE TITLE
🙋onmogelijk database terug te zetten

### ISSUE THREAD

**Issue by newtech2015** [dsmrreader/dsmr-reader#1650]
### Description

na een mislukte upgrade van 4.x naar 5.x heb ik mijn sd-kaart image gerschreven met de versie van voor de upgrade.
helaas, start dsmr toch niet.  dsmr database stond op een externe hdd.

ik heb tijdens de mislukte update een database backup gemaakt, hoe moeilijk kan het zijn, om die terug te zetten.. zou je denken.
echter, wat ik ook probeer, lukt me met geen mogelijkheid.

supervisorctl stop all
sudo systemctl stop postgresql (stop de database)
sudo sudo -u postgres dropdb dsmrreader (verwijderen database)
sudo sudo -u postgres createdb -O dsmrreader dsmrreader (aanamken database zonder inhout)
zcat /home/dsmr/dsmr-reader/backups/dsmrreader-postgresql-backup-Thursday.sql.gz | sudo sudo -u postgres psql dsmrreader (vullen database met inhoud uit backup file)

    database verwijden - kan niet (kan ik me nog voorstellen)
    nieuwe aanmaken zonder inhoud - geen root rechten (???)
    verder kom ik niet

elke poging, gaat stuk op "dsmr password" (heb ik niet), of geen rechten

vb:
root@raspberrypi:~# sudo -u postgres createdb -O dsmrreader dsmrreader
could not change directory to "/root": Permission denied
createdb: could not connect to database template1: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

ik kom er niet meer verder mee
weet iemand iets?

### DSMR-reader version

4.20

**Comment by dennissiemensma** [comment]
Ik denk dat Postgres niet draait, zie #1649
