### ISSUE TITLE
🚨Bulk remove InfluxDB measurements

### ISSUE THREAD

**Issue by WatskeBart** [dsmrreader/dsmr-reader#1651]
### Description

I had a lot of stored InfluxDB measurements (~850). When I tried to delete them in one go the page returns a 504 error (gateway timeout error).
When selecting and deleting a single page of measurements (100), everything deletes ok. I tried again with 450 measurements, but still getting a 504 error.
Eventually I deleted all measurements one page at a time.

### DSMR-reader version

v5.3

### DSMR-reader platform

Docker (e.g. Xirixiz)

### Debug info dump

```shell
DSMR-READER
    App / Python / Database                                                       v5.3 / v3.10.5 / postgresql
    BE sleep / DL sleep / Retention / Override                                    1.0s / 5.0s / 2016h / False
    Latest telegram version read / Parser settings                                                 "50" / "4"

DATA
    Telegrams total (est.)                                                                             882061
    Consumption records electricity / gas (est.)                                                   123433 / -
```

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Je kunt dit het beste via de database doen.

```
sudo su - postgres
psql dsmrreader
delete from dsmr_influxdb_influxdbmeasurement;
```

De oorzaak is gelijk aan #1643 en kan ik niet in Django zelf oplossen.
