### ISSUE TITLE
Clonen van bestaand energiecontract💡

### ISSUE THREAD

**Issue by YLKersloot** [dsmrreader/dsmr-reader#1652]
### Feature

Met de maandelijkse tarieven ben ik elke maand een nieuw contract aan het maken voor een periode en moet ik even onthouden wat dal/normaal tarief is, naamgevingsconventie, etc. Het zou mij al helpen als er een 'clone' knop is, of een feature waarmee je al maandcontracten kan bijhouden (bijv. knop genereer nieuwe maand)

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik zal voor de volgende release `ModelAdmin.save_as` (https://docs.djangoproject.com/en/4.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.save_as) aanzetten.

Daarmee kun je een bestaand contract openen, de velden aanpassen en "opslaan als een nieuw contract". Ik dacht dat dat al aan stond, maar blijkbaar moest ik dat expliciet instellen.

## Nu
![nu](https://user-images.githubusercontent.com/16581744/176500171-83ea83cc-8f55-4b53-8388-2982ba2fa2e3.png)

----
## Straks

![straks](https://user-images.githubusercontent.com/16581744/176500177-004bbccc-ab90-4477-abd0-0530ed18ff14.png)

**Comment by dennissiemensma** [comment]
Release van v5.4 staat voor **morgenavond** op de planning, mits er niets uit de 24-uurstest komt.

**Comment by PhyxionNL** [comment]
Om hier even wat op in te haken, het zou handig zijn als DSMR dezelfde naamgeving gebruikt voor tarieven zoals iedereen dat doet, namelijk normaal- en daltarief in plaats van hoog en laag 🙂 Alle energiemaatschappijen hanteren ook de normaal- en daltarief naamgeving.

**Comment by dennissiemensma** [comment]
@PhyxionNL je kunt de namen van je tarieven instellen of wijzigen in `/admin/dsmr_frontend/frontendsettings/`

**Comment by PhyxionNL** [comment]
Bij energiecontracten heet het alsnog laagtarief en hoogtarief:

**N.B.: De betekening van elk tarief kan internationaal verschillen. Voor Nederlandse gebruikers: Tarief 1 is bekend als laagtarief en tarief 2 als hoogtarief.**

Die naamgeving vind je eigenlijk nergens in Nederland, iedereen noemt het normaal- en daltarief 🙂

**Comment by dennissiemensma** [comment]
Bedankt voor je aanvulling. Het was mij niet duidelijk dat je specifiek bij het invoeren bedoelde. Ik kan het wel een keertje aanpassen als het niets raakt en het niet duidelijk genoeg is.
Tot nu toe ben je nl de eerste, omdat het zelf kunnen wijzigen van de tariefnamen (sinds #750) de afgelopen jaren een hoop gedoe over de tariefnamen voor iedereen heeft opgelost.

**Comment by dennissiemensma** [comment]
Je kunt zelf de namen instellen van de tarieven. Er zijn diverse varianten dus iedereen is vrij om zelf wat te kiezen.
