### ISSUE TITLE
💡 Dashboard data via MQTT verzenden

### ISSUE THREAD

**Issue by Roukie686868** [dsmrreader/dsmr-reader#1653]
### Feature

Zou het mogelijk zijn om de data die te zien is in de dashboard pagina op gezette intervallen te publiceren via MQTT berichten. Het is dan mogelijk om deze data op externe displays te publiceren die naar deze MQTT-boodschappen luisteren. De mogelijkheid om de interval tijd te zetten zou geweldig zijn maar elke 10 second zou een goed start zijn.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Als het goed is kun je dit al deels via #685.

MQTT is overigens niet bedoeld om dezelfde data op bepaalde intervallen te verversen, alleen bij wijzigingen (push). DSMR-reader publiceert ook alle data met MQTT's **retain**, dus het zou uberhaupt niet nodig moeten zijn.

Als je op vaste intervallen een update wilt, is er meestal een koppeling met een API (pull) ipv MQTT. De DSMR-reader API heeft echter geen ondersteuning voor die data.
