### ISSUE TITLE
Tariefnamen rechttrekken

### ISSUE THREAD

**Issue by dennissiemensma** [dsmrreader/dsmr-reader#1666]
> "Om hier even wat op in te haken, het zou handig zijn als DSMR dezelfde naamgeving gebruikt voor tarieven zoals iedereen dat doet, namelijk normaal- en daltarief in plaats van hoog en laag 🙂 Alle energiemaatschappijen hanteren ook de normaal- en daltarief naamgeving."

_Originally posted by @PhyxionNL in https://github.com/dsmrreader/dsmr-reader/issues/1652#issuecomment-1179536503_

**Comment by dennissiemensma** [comment]
Aangepast voor v5.5

**Comment by PhyxionNL** [comment]
Super 👍

**Comment by dennissiemensma** [comment]
Uitgebracht in [v5.5](https://github.com/dsmrreader/dsmr-reader/releases/tag/v5.5.0)
