### ISSUE TITLE
De nieuwste python versie wordt niet gevonden🙋

### ISSUE THREAD

**Issue by ridderr** [dsmrreader/dsmr-reader#1667]
### Description

Er wordt ergens de verkeerde python versie controle uitgevoerd. Als ik op de cmdline check dan is 3.10.5 geinstalleerd maar deploy.sh geeft aan versie 3.9.2.
Ik zie wel in /dsmr-reader/.venv/bin verwijzingen staan naar python -> python3 -> python3.9. Ik denk dat het daardoor komt maar hoe moet ik dat aanpassen.
Onderstaande de check en en output van deploy.sh 

```
(.venv) dsmr@PI2:~/dsmr-reader $ **python -V
Python 3.10.5**
(.venv) dsmr@PI2:~/dsmr-reader $ ./deploy.sh

 --- You are currently running version:
5.4

 --- Checking Python version.
**Running Python 3.9.2** (default, Mar 12 2021, 04:06:34)
[GCC 10.2.1 20210110]
[WARNING] Your Python version can still be used with your current DSMR-reader version. However, Python 3.10.0 or higher is preferred. Consider using it for new installations in the future.


```

### DSMR-reader version

5,4

### DSMR-reader platform

Docker (e.g. Xirixiz)

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Gebruik je de Docker image? Want het lijkt juist op een native installatie.

In beide gevallen zou ik me er overigens niet te druk over maken, want je zult je virtualenv anders opnieuw moeten maken. Beide Python-versies werken verder prima voor DSMR-reader en de melding is vooral bedoeld dat gebruikers bij een herinstallatie een hogere versie proberen te installeren. Dat zorgt ervoor dat ze soms jaren niet Python hoeven te upgraden.

**Comment by ridderr** [comment]
Bedankt Dennis. Twee dingen geleerd. Draai dus niet docker en negeer de melding :-) (voorlopig?)

**Comment by dennissiemensma** [comment]
Ja, kun je voorlopig negeren.

----

Onderwater is DSMR-reader gebouwd met Django (versie 3) en Django versie 4 ondersteunt bijvoorbeeld **geen** < Python 3.7 meer:
- https://docs.djangoproject.com/en/4.0/releases/4.0/#python-compatibility

DSMR-reader ondersteunt echter nog **wel** Python 3.7 en er zullen gebruikers zijn die die Python versie nog hebben. Dus de volgende major release (DSMR-reader v5 -> v6) zal overgaan naar Django 4 en daarmee dus support voor Python 3.7 droppen.

Alle DSMR-reader gebruikers, inclusief jijzelf, die op Python 3.8 of hoger zitten, hoeven dan niet hun Python te upgraden om DSMR-reader v6.x te gebruiken. Vandaar dat ik ook aanstuur op een zo hoog mogelijke versie bij (her)installatie.

**Comment by dennissiemensma** [comment]
Daarbij komt overigens ook dat Python zelf uiteindelijk versies uitfaseert en Python 3.7 is (al) volgend jaar aan de beurt:
- https://endoflife.date/python

De versie die je nu draait heeft nog zeker 3 jaar support. Nog een pluspunt dus.
