### ISSUE TITLE
💡Meerdere bronnen

### ISSUE THREAD

**Issue by cmderks93** [dsmrreader/dsmr-reader#1668]
### Feature

Ik zit in de situatie (zakelijk) dat wij drie meters in gebruik krijgen.
2x een elektrameter, en 1x een gasmeter. 

In mijn situatie is de 2e elektrometer een dummy, welke enkel de gasmeterstand doorgeeft. Dit omdat de afstand naar de hoofdmeter te groot is. 

Daarnaast zal deze situatie vaker gaan voorkomen denk ik, gezien het tegenwoordig mogelijk is een 2e meter naast je eerste meter te plaatsen. Dit om bijvoorbeeld alleen terug te leveren via deze meter, en hier een gunstig contract voor af te sluiten. 

to the point: Zou het mogelijk gemaakt kunnen worden om een 2e bron te gebruiken?
Wellicht dat het dan aan te geven is welke gegevens van welke meter gebruikt moeten worden.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Helaas is het vrij complex om dit achteraf in DSMR-reader te bouwen, omdat daar eigenlijk alles van 1 meter of 1 bron uit gaat.
Dit is in het begin van dit project, jaren terug, ooit de consessie geweest voor relatief simpel en snel ontwikkelen. Het grote nadeel is dat meterwissels of meerdere meters daardoor niet native ondersteund worden. Echter is er van buitenaf wel omheen te werken.

Want wat je nog wel kan doen is met een scriptje zelf beide meters uitlezen (bijvoorbeeld met [dsmr_parser](https://github.com/ndokter/dsmr_parser)) en de data extraheren/samenvoegen.
Vervolgens kun je dan via de v2 REST API van DSMR-reader de meting aanmaken met de velden/data die je wilt. DSMR-reader pakt bij dat endpoint gewoon wat je stuurt. Je stuurt dan dus niet een telegram (dat is de v1 API) maar de losse velden en waardes die je wilt.

Laatstgenoemde is relatief simpel om te doen, mits je uiteraard wat handig bent met scripten.

**Comment by cmderks93** [comment]
Dankje. 
Ik zal eens kijken naar je voorbeeld. Ik gebruik de lezertjes van Marcel Zuidwijk.
