### ISSUE TITLE
🚨 Tabel meterstatistics blijft aangroeien in grootte

### ISSUE THREAD

**Issue by MathiasVDA** [dsmrreader/dsmr-reader#1670]
### Description

Hallo!

Ik heb gemerkt dat de tabel dsmr_datalogger_meterstatistics veel schijfruimte inneemt ondanks dat het maar 1 record bevat. Ik heb een vaccuum analyzed full gedaan en daarmee verminderde de grootte naar een normaal formaat:

Voor (>200MB):
![image](https://user-images.githubusercontent.com/15101339/179390429-e7367713-5819-4893-863b-b1c5e8b99f32.png)

Na: 
![image](https://user-images.githubusercontent.com/15101339/179390436-d42d8846-1cde-4b5c-88e4-9b865e6e9b78.png)

Is niet zo belangrijk want het zal nog wel even duren voordat het een groot probleem wordt. Maar ik dacht het alvast hier te melden. Bedankt!

### DSMR-reader version

5.5

**Comment by dennissiemensma** [comment]
Bedankt voor je melding! Ik wist niet dat zo'n tabel kon uitgroeien tot zoiets groots. Helemaal omdat Postgres ook automatisch enige vacuum zou moeten doen.

Voor nu laat ik het even voor wat het is. DSMR-reader geeft sowieso een melding als een tabel een bepaalde grootte heeft (ik dacht 1 GB).
