### ISSUE TITLE
🚨Blijft vastlopen

### ISSUE THREAD

**Issue by Rockvolleyball** [dsmrreader/dsmr-reader#1678]
### Description

Helaas terugkomend op #1672. Proces blijft vastlopen, ondanks een nieuwe Pi. Een herstart lost het wel op, maar dat is verre van werkbaar. 

Problemen beginnen bij versie 5.4. Jaren ervoor altijd prima gedraaid. 

### DSMR-reader version

5.5

### DSMR-reader platform

Other

**Comment by dennissiemensma** [comment]
Je kunt #1672 heropenen
