### ISSUE TITLE
50% teruglever vergoeding💡

### ISSUE THREAD

**Issue by abeltman** [dsmrreader/dsmr-reader#1692]
### Feature

Sinds 1 september is de terugleververgoeding van Budget Energie nog maar 50%. Dit geldt alleen voor de kWh die je netto teruglevert tijdens de gehele periode van een factuur jaar. De kWh die je teruglevert maar zelf in de wintermaanden weer gebruikt worden dus nog gewoon 1 op 1 verrekend.

Ik realiseer me dat het best complex is om dit in te bouwen zeker gezien het feit dat de prijzen maandelijks wijzigen (ik vraag me ook af hoe Budget Energie dit berekent) maar ik vroeg me af het misschien toch mogelijk is om een dergelijke regeling in te bouwen in DSMR-Reader.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. De korte versie is dat dit buiten de scope van DSMR-reader valt.

Voor meer toelichting zie oa:
- https://github.com/dsmrreader/dsmr-reader/issues/1493#issuecomment-933814538
- https://github.com/dsmrreader/dsmr-reader/issues/1578#issuecomment-1035333429
- https://github.com/dsmrreader/dsmr-reader/issues/1607#issuecomment-1078391049
- https://github.com/dsmrreader/dsmr-reader/issues/1444#issuecomment-907390458
