### ISSUE TITLE
Prijsberekening van kosten van teruglevering stroom boven verbruik💡

### ISSUE THREAD

**Issue by TimonTerBraak** [dsmrreader/dsmr-reader#1694]
### Feature

Momenteel gelden er versschillende prijszen voor de stroom die aan het net teruggeleverd wordt boven het eigen verbruik. Door de saldering voer ik nu in de energiecontracten in dat de prijs voor teruglevering hetzelfde is als de prijs voor de levering van stroom. Hierdoor denkt dsmr-reader dan ook dat het erg gunstig is om zoveel mogelijk stroom terug te leveren, wat in extremiteit nogal een verkeerde indruk geeft van de berekende energiekosten.

Ik ben dan ook benieuwd of het mogelijk is om een extra 'kostenpost' te defineren voor de overtollige teruglevering van stroom. Ik ben me er van bewust dat dit de berekening van kosten een stukje lastiger maakt, zeker omdat het (jaarlijkse) moment waarop het netto saldo van de levering/teruglevering bepaald wordt van invloed is.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Helaas valt dit buiten de scope van DSMR-reader.

Voor meer informatie zie: https://github.com/dsmrreader/dsmr-reader/issues/1692#issuecomment-1213440467
