### ISSUE TITLE
Buienradar temperatuur 

### ISSUE THREAD

**Issue by PascalBu** [dsmrreader/dsmr-reader#1695]
### Description

Sinds gisteren middag 15 uur blijft de temperatuur hangen:
![Screenshot_2022-08-24-09-08-33-83_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/47149320/186354038-f08b0070-8304-4d69-9f20-f602364f5cd9.jpg)

Overigens zie ik dit ook in home assistant, dus waarschijnlijk iets veranderd bij Buienradar?

### DSMR-reader version

5.6

**Comment by PascalBu** [comment]
Never mind, het lijkt alweer opgelost

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Het kan inderdaad zijn dat er even issues waren. Ik zie hetzelfde

![Screenshot from 2022-08-24 20-08-42](https://user-images.githubusercontent.com/16581744/186491736-7af90933-86fd-4426-a889-c132a6966e4d.png)
