### ISSUE TITLE
Dsmr docker container very large

### ISSUE THREAD

**Issue by hemant5400z** [dsmrreader/dsmr-reader#1696]
### Description

Hi,

just noticed when exporting my dsmrdb en dsmr container. I noticed dsmr container is almost 2.5 gb. I expect the dsmrdb container to be large bit not sure what is kept in dsmr. I also cleaner the backuo dirs. Moving to antoher machine so exporting the containers to keep all settings. Any ideas why and where the extra data is located?.

hemant

### DSMR-reader version

4.z

### DSMR-reader platform

Docker (e.g. Xirixiz)

**Comment by dennissiemensma** [comment]
I think Xirixiz can help you in this case, https://github.com/xirixiz/dsmr-reader-docker/issues
