### ISSUE TITLE
Systeem upgraden van ubuntu 20.04 naar 22.04

### ISSUE THREAD

**Issue by allureGOT** [dsmrreader/dsmr-reader#1704]
### Description

Ik wil graag mijn systemen allemaal upgraden naar ubuntu 22.04, gaat dit zonder meer problemen opleveren voor DSMR?

### DSMR-reader version

5.6

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
In principe kan dat, alleen kan het wel zijn dat je bijvoorbeeld de virtual env opnieuw moet aanmaken als die hem niet pakt. Houd er rekening mee dat je worst-case een herinstallatie moet doen, omdat dat vaak sneller is dan debuggen. Zorg dus voor een goede DB backup om evt terug te zetten.

**Comment by allureGOT** [comment]
Update van OS gelukt, in ubuntu 22.04 wordt postgres 12 "obsolete" en is versie 14 de default.
Postgres 12 gepurged en de DB in postgres 14 restored.

Alles werkt weer, thanks!

**Comment by dennissiemensma** [comment]
Top, fijn om te horen!
