### ISSUE TITLE
💡Energy Contract Details

### ISSUE THREAD

**Issue by darf53** [dsmrreader/dsmr-reader#1705]
### Feature

Putting in the details of my energy contract I'm missing following features (FYI - I'm still on version 4):

- We do not have different tarifs like "hoogtarief" and "laagtarief". Having this split on every dashboard is confusing. Also when we need to enter the contract details it is not clear to me if I need to add it or not and do I put same price plans in both fields.

- On the admin page, where you can add the contract details, there's no indication what data you need to provide apart from the fact it is in "€". But what metric is used. (m3 of kWh or what volume...) Different countries or providers might be using different ways to communicate the price to customers.  Would be nice to know we're adding the data in the right/same dimension. Gas is I think in m3 and Electricity in kWh.

**Comment by dennissiemensma** [comment]
Hi, you can have the tariffs merged into one. Somewhere in Frontend settings in admin. Just put the same price for all tariffs then. Prices are per M3 or kWh.

**Comment by dennissiemensma** [comment]
I will see if I can add the units to the help text some time.

**Comment by dennissiemensma** [comment]
In the next release, the units (e.g. €/kWh) will be displayed.

![Screenshot from 2022-09-23 21-11-07](https://user-images.githubusercontent.com/16581744/192040522-4a12801e-844d-46b5-a19a-761ce66287f5.png)
