### ISSUE TITLE
💡 timestamp offset instellen

### ISSUE THREAD

**Issue by hlugt** [dsmrreader/dsmr-reader#1712]
### Feature

Mijn meter is een Sagemcom t211. Deze meter wordt volgens mij inmiddels veelvuldig ingezet, omdat er een gebrek is aan slimme meters. In mijn geval (en ik vermoed bij meerderen) staat echter de lokale tijd van de Sagemcom verkeerd. Bij mijn meter is het op moment van schrijven 27 december 2021, 4 uur 20 's nachts.
Nu weet ik dat de config een optie heeft om de timestamp in het telegram te negeren. Dit is inderdaad nodig om de Sagemcom telegrammen uberhaupt verwerkt te krijgen.
Toch zou het prettig zijn de timestamps een rol te laten blijven spelen. In verband met buffering ed.

Daarom het volgende feature request:

De mogelijkheid een offset in seconden (plus en min) voor de timestamp instellen. Op deze manier kan de tijd (die ws vooral in het verleden ligt) gecorrigeerd worden naar de juiste tijd van produceren telegram, en igv buffering of opslag, nog naar juiste moment en volgorde gebracht worden.
Vermoed dat de ontvangen timestamp teruggebracht moet worden van timestamp naar unix time, offset toegepast en dan terug van unix time inclusief offset naar timestamp.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Hiervoor kun je het beste zelf je meter uitlezen, de data aanpassen naar wat je wilt en dan via de API van DSMR-reader invoeren. Je bent namelijk qua datainvoer via de REST API van DSMR-reader helemaal vrij in de waardes van alle velden.
Voor het parsen van de meterdata kun je iets als dsmr_parser gebruiken, een tool waar DSMR-reader ook gebruik van maakt. 

Overigens zou ik dit ook gewoon melden bij je netbeheerder, want het lijkt me niet wenselijk dat je meter zover achterloopt. De optie in DSMR-reader om tijdstippen te negeren is vooral bedoeld voor kleine afwijkingen, niet dit soort intervallen van bijna een jaar.
