### ISSUE TITLE
🙋Running Home Assistant OS - how do i upgrade to a newer version?

### ISSUE THREAD

**Issue by prmfeddema** [dsmrreader/dsmr-reader#1721]
### Description

Currently running 5.6 - would like to upgrade to 5.8 but instructions provided do not relate to home assistant os. When using SSH to my home assistant os i cannot set user dsmr 
Can anyone provide instructions on how to do an upgrade please?

### DSMR-reader version

5.6

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
You will need to get in touch with whoever made the setup you're currently using. This project is only for DSMR-reader. 

Did you possible use this one? 
- https://github.com/sanderdw/hassio-addons

**Comment by prmfeddema** [comment]
Good evening Dennis!Thanks for the quick response - indeed i used that one. Will contact the author.Kr,PascalVerstuurd vanaf mijn iPhoneOp 3 okt. 2022 om 22:39 heeft Dennis Siemensma ***@***.***> het volgende geschreven:﻿
You will need to get in touch with whoever made the setup you're currently using. This project is only for DSMR-reader.
Did you possible use this one?

https://github.com/sanderdw/hassio-addons
