### ISSUE TITLE
🙋How do i set "Saldering"?

### ISSUE THREAD

**Issue by prmfeddema** [dsmrreader/dsmr-reader#1726]
### Description

I see that the calculation for used and solar energy production is right, but i am missing the "saldering", i.e:

When solar production >= consumption the cost becomes revenue: (solar production - consumption) * solar tariff
When solar production < consumption the cost becomes revenue: (consumption - solar production) * Energy company tariff

Am i overlooking something or this is not implemented? If not implemented: please please please implement this functionality.

Thanks.

Pascal

### DSMR-reader version

latest

### DSMR-reader platform

Docker (e.g. Xirixiz)

**Comment by dennissiemensma** [comment]
Hi, thanks for asking. Unfortunately this feature is not available and will not be implemented either.

The main reason DSMR-reader being a tool to visualize your smart meter data. Any calculations regarding costs is just a shallow indication for a per-day basis, to compare between them.

Getting all the price calculations, rules, discounts, etc right could probably be a dedicated project on its own.
