### ISSUE TITLE
Nieuwe slimmemeter, 3-fase DSMR leest niet uitzichzelf uit

### ISSUE THREAD

**Issue by D1StrX** [dsmrreader/dsmr-reader#1727]
### Description

Vraagje betreft herconfigureren (denk bus snelheden) voor het uitlezen van de slimme meter.
Heb een 3-fase slimmemeter gekregen, waarvan de chineese leverancier op de website zegt dat de usb -> p1 kabel zou moeten werken. 
DSMR daarintegen leest mn nog niet uit. Hoe is dit het beste te testen/fixen?

### DSMR-reader version

v5.8

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by D1StrX** [comment]
ik zie onder configuration nu wel dat die de nieuwe meter al heeft herkend. Had een keer p1 seriele connectie opnieuw opgeslagen geklikt. Dus ik weet zeker dat de de hardware in orde is. Kan het in de database weggeschreven worden? 1-fase meter naar 3-fase meter overgang

**Comment by dennissiemensma** [comment]
Je kunt het beste "cu" installeren en buiten DSMR-reader om je meter proberen te lezen. Stop DSMR-reader wel even om gekke fouten te voorkomen. Zie deze specifieke stap: https://dsmr-reader.readthedocs.io/nl/v5/tutorial/installation/step-by-step.html#optional-your-first-reading

**Comment by D1StrX** [comment]
positieve is dat die goede reading laat zien. Maar dsmr laat nu al -140000 watt zien, dus moet ergens wat mis gegaan zijn. Prima als dat de teruglevering zou zijn.. 😅 
Wat kunnen we nog meer doen? (naast een backup terugzetten of clean install)

**Comment by dennissiemensma** [comment]
Als je meter verwisseld is, zul je een dag moeten wachten en daarna eenmalig met de hand herstellen. Zie https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/smart-meter-replacement.html

**Comment by D1StrX** [comment]
Het draait weer alsof er niets gebeurd is. De rest van de dag de p1 eruit (ge)laten, en daarna inderdaad handmatig fixen.  P1 er terug in, en alles werkte weer.
