### ISSUE TITLE
🚨 MQTT value electricity_tariff

### ISSUE THREAD

**Issue by vincedh** [dsmrreader/dsmr-reader#1728]
### Description

Hoi Dennis,
Het lijkt erop dat mqtt value 'electricity_tariff = dsmr/meter-stats/electricity_tariff' niet meer goed wordt doorgegeven. Alle waardes uit dsmr reader worden keurig weergegeven in home assistant, behalve deze.
Ik heb de hele [(Databron) Meterstatistieken: Gesplitst topic] al een keer uit en aangezet, zonder resultaat. Ook push ik sommige waardes uit dsmr door naar openhab via mqtt (waaronder electricity_tariff), maar ook daar komt hij niet meer aan.
Is daar onlangs iets in veranderd?
Ik hoor 't wel als ik iets kan proberen.
Bedankt alvast,
Vince

### DSMR-reader version

5.8

### Debug info dump

```shell
DSMR-READER
    App / Python / Database                                                       v5.8 / v3.8.10 / postgresql
    BE sleep / DL sleep / Retention / Override                                    1.0s / 0.5s / 4032h / False
    Latest telegram version read / Parser settings                                                 "50" / "4"

DATA
    Telegrams total (est.)                                                                           14581892
    Consumption records electricity / gas (est.)                                               292342 / 97705

UNRESOLVED ISSUES
    Database groeit gestaag: 5236 MB, overweeg dataopschoning (indien nog niet ingeschakeld)                                      nu

POSTGRESQL SIZE OF LARGEST TABLES (> 500 MB)
    public.dsmr_datalogger_dsmrreading                                                                4919 MB
```

**Comment by dennissiemensma** [comment]
Je kunt het beste DEBUG level logging tijdelijk aanzetten en in de logs van het backend proces kijken wat er gebeurt qua MQTT:
- https://github.com/dsmrreader/dsmr-reader/issues/1714#issuecomment-1261813560

Voor zover ik weet is er niets aan veranderd en het veld heet ook nog steeds `electricity_tariff` in de database.

**Comment by dennissiemensma** [comment]
@vincedh ben je nog wat wijzer geworden?

**Comment by vincedh** [comment]
Hoi Dennis,
Nee, helaas niet, ik heb ff in de database zelf gekeken en ook daar staat de waarde keurig in. Ook links bovenin het homescherm van DSMR reader zelf wordt het huidige tarief goed weergegeven. Alleen niet via MQTT dus... Ik zou niet weten wat ik verder nog kan doen en zo'n grote ramp is het ook weer niet. Dus mocht jij verder ook geen idee hebben laten we het hier bij. Toch bedankt voor je reactie.

**Comment by dennissiemensma** [comment]
Je kunt nog de logging bekijken https://github.com/dsmrreader/dsmr-reader/issues/1728#issuecomment-1277979777

**Comment by vincedh** [comment]
Hoi Dennis,
Ik ben een beetje bang dat het 'tarief bericht' alleen om 7u en 23u verstuurd wordt, daarna wordt het log vol gepropt met andere berichten, dus lastig om de juiste eruit te halen, heb jij een tip misschien?

**Comment by dennissiemensma** [comment]
In principe kun je in de logfiles zoeken naar `electricity_tariff`. Weet je trouwens zeker dat je ook de MQTT van de meterstatistieken hebt ingeschakeld?

- Zie `/admin/dsmr_mqtt/splittopicmeterstatisticsmqttsettings/`

Het is namelijk **geen** onderdeel van de telegram update uit DSMR-reader, maar van de losse statistieken ernaast (omdat het weinig verandert).

**Comment by vincedh** [comment]
Ik heb het gevonden! 'electricity_tariff = dsmr/meter-stats/electricity_tariff' stond 2x in de lijst, waardoor deze niet verzonden werd. Aangepast en alles wordt direct keurig doorgegeven. Dank voor je tijd en ondersteuning.

**Comment by dennissiemensma** [comment]
Top, fijn om te horen!
