### ISSUE TITLE
tibber integratie💡/ dynamische prijzen

### ISSUE THREAD

**Issue by bruijnes** [dsmrreader/dsmr-reader#1729]
### Feature

Tibber is een energieleverancier met dynamische prijzen, ik vroeg me af of deze mogelijkheid al wordt overwogen In de nieuwe versie? https://tibber.com/

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek! Helaas valt dat buiten de scope en is DSMR-reader er nooit voor ontworpen: #1607
Plus dat het echt een draak is om dat allemaal goed te krijgen en te houden, voor alle leveranciers.
