### ISSUE TITLE
Toevoegen dynamische uur en dag prijzen💡

### ISSUE THREAD

**Issue by tfranssen** [dsmrreader/dsmr-reader#1730]
### Feature

Steeds meer mensen kiezen voor een dynamisch energiecontract. Hierbij worden er per uur wisselende prijzen gehanteerd. De prijzen worden een dag eerder bekend gemaakt. Voor gas gelden er dagtarieven, dus niet per uur. Soms (vaak op een zonnige zondag) zijn de tarieven zelfs negatief.

De tarieven staan bijvoorbeeld hier: https://www.easyenergy.com/nl/energietarieven, https://energie.anwb.nl/actuele-tarieven

Het zou mooi zijn als deze prijzen ook in DSMR geladen kunnen worden!

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Helaas valt dit buiten de scope van het project. Zie ook alles qua prijzen in o.a.: #1729 #1723 #1607 #1694 #1692
