### ISSUE TITLE
💡Mogelijkheid om Authenticatie/Login volledig uit te schakelen

### ISSUE THREAD

**Issue by Saeverix** [dsmrreader/dsmr-reader#1732]
### Feature

Ik ben voor mijn homelab bezig om te kijken of ik Authelia of Authentik kan gaan gebruiken voor al mijn interne applicaties.
Met die software is het mogelijk om `Single Sign On` voor al je applicaties te zetten, en als extra beveiliging ook gebruik te maken van 2FA en zelfs een hardware key.

Het is mogelijk om dit voor DSMR te plaatsen, maar het gevolg is dat ik dan alsnog het login scherm van DSMR zelf krijg. Dubbele login dus.

Is het mogelijk om een optie in te bouwen waarbij de interne authenticatie/login volledig uit te schakelen is?

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Onderwater gebruikt DSMR-reader Django als framework en daar is wel wat te configureren: 

https://docs.djangoproject.com/en/3.2/topics/auth/customizing/

Echter is dat niet triviaal omdat daar waarschijnlijk custom code voor vereist is en het vooral een hele specifieke feature is om te maken. Dus ik heb helaas niet zo 1-2-3 een oplossing voor je.
