### ISSUE TITLE
💡Sluipverbruik meten ???

### ISSUE THREAD

**Issue by niekniek89** [dsmrreader/dsmr-reader#1744]
### Feature

Geen idee of onderstaande überhaupt mogelijk is, dus hierbij een open vraag:

Het is (wellicht) wel “vloeken in de kerk”, maar bij Eneco/Toon is er een mogelijkheid om je sluipverbruik te monitoren/weergeven.

Ik heb echter geen idee welke techniek/meting methode hierachter zit en hoe ze dit inzichtelijk brengen.

Daarom dus ook geen idee of dit met DSMR te achterhalen/uit te lepelen is.
Betreft daarom een open “issue”, en wellicht is het ook niet mogelijk.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. In principe is je sluipverbruik het constante verbruik op momenten dat je geen of amper verbruik verwacht. Je bent zelf de enige die kan beoordelen of dat klopt of niet. Het beste moment is vaak in de nacht, omdat je dan doorgaans alles uit hebt, behalve het noodzakelijke. Je kunt dan in de grafieken terugkijken hoeveel Watt en/of kWh je in de nacht/afwezigheid verbruikt hebt en of dat is wat je verwacht.

**Comment by dennissiemensma** [comment]
Bijvoorbeeld bij mezelf zit het wattage in de nacht rond de 40W, afgezien van een closein boiler die telkens kort aanslaat. En alles bij elkaar lijkt dan zo'n 0,7 kWh in de nacht te verbruiken. Dat is mijn sluipverbruik.
