### ISSUE TITLE
🙋Hi, having issues getting "stadsverwarming/warmtelink" data into DSMR-reader in Home Assistant

### ISSUE THREAD

**Issue by BSandman** [dsmrreader/dsmr-reader#1749]
### Description

I have installed a "P1 slimmemeter" (ethernet version) following the guidelines provided https://www.zuidwijk.com/using-esp-link/#home-assistant. 
I'm running DSMR-reader in Home Assistant. All latest versions.

Data is coming into Home Assistant, so that works, using recorder it's going to TimeScaleDB to, no problem. I'm getting a GJ value since it's  city heat, but nothing shows, having retraced my steps twice DSMR-reader keeps telling me there are no readings.
So I'm at a loss as to what to try to resolve this.

I'm using IPv$, DSMR version 4/5 (standard), the specified ip-adres and port are correct.

The only message other than "there's no data" are the rejected telegrams : 4.645, due to CRC checksum fail

### DSMR-reader version

5.8

### DSMR-reader platform

Other

### Debug info dump

```shell
SMR-READER
    App / Python / Database                                                       v5.8 / v3.10.7 / postgresql
    BE sleep / DL sleep / Retention / Override                                     1.0s / 5.0s / 672h / False
    Latest telegram version read / Parser settings                                               "None" / "4"

DATA
    Telegrams total (est.)                                                                                 -1
    Consumption records electricity / gas (est.)                                                      -1 / -1

UNRESOLVED ISSUES
    Geen dagstatistieken gevonden                                                                          nu
    Nog nooit een meting ontvangen                                                                         nu
```

**Comment by dennissiemensma** [comment]
There currently is no support yet for this feature. See #1286 for a workaround.
