### ISSUE TITLE
🚨Database-upgrade v5.8 -> v5.9 mislukt

### ISSUE THREAD

**Issue by mthmulders** [dsmrreader/dsmr-reader#1755]
### Description

Upgraden van v5.8 naar v5.9 mislukt. Het lijkt een beetje op wat ik eerder rapporteerde in #1663:

```
 --- Applying database migrations.
./post-deploy.sh: line 50: 20385 Killed                  ./manage.py migrate --noinput

 >>>>> [!] Executing database migrations failed! <<<<<
       [i] Trying to automatically resolve with 'dsmr_sqlsequencereset'.
./post-deploy.sh: line 69: 20389 Killed                  ./manage.py dsmr_sqlsequencereset
./post-deploy.sh: line 69: 20391 Killed                  ./manage.py migrate --noinput
>>>>> [!] Executing database migrations failed again! <<<<<
        - Running dsmr_sqlsequencereset did not resolve the problem.
        - Create an issue on GitHub and attach the exeception trace listed above.
[!] Halted. Post-deployment script exited with non-zero code
```

Destijds [suggereerde je](https://github.com/dsmrreader/dsmr-reader/issues/1663#issuecomment-1178579518):

> Je kunt nog proberen ze met de hand uit te voeren

Dat heb ik gedaan:

```
./manage.py migrate --noinput
Killed
```

En [je vroeg](https://github.com/dsmrreader/dsmr-reader/issues/1663#issuecomment-1178579518):

> Ik zie niet zo goed waarom de processen gekilled worden, duren ze erg lang?

Dat heb ik gemeten (voor referentie, het is een virtuele machine in de cloud met 1 GB RAM en dual-core 2GHz processor, op zich zou dat vlot zat moeten zijn toch?)

```
time ./manage.py migrate --noinput
Killed

real	0m26.549s
user	0m2.350s
sys	0m0.795s
```

### DSMR-reader version

5.8

### DSMR-reader platform

Native (e.g. manual installation)

### Debug info dump

```shell
DSMR-READER
    App / Python / Database                                                        v5.8 / v3.8.0 / postgresql
    BE sleep / DL sleep / Retention / Override                                    1.0s / 0.5s / 8064h / False
    Latest telegram version read / Parser settings                                               "None" / "3"
    (!) Database migrations pending                                                                     3 (!)

DATA
    Telegrams total (est.)                                                                            2922290
    Consumption records electricity / gas (est.)                                               513721 / 18880

UNRESOLVED ISSUES
    Database growing large: 1606 MB, consider data cleanup (if not already enabled)                                     now

POSTGRESQL SIZE OF LARGEST TABLES (> 500 MB)
    public.dsmr_datalogger_dsmrreading                                                                1123 MB
```

**Comment by dennissiemensma** [comment]
Staat er verder ook niets in de syslog? En loopt het geheugengebruik toevallig niet op, zodat die een out-of-memory kill triggert?

Je bent de enige die zoiets gemeld heeft, dus er is vast iets wat afwijkt, maar ik zou het niet weten. Ook omdat het de vorige keer zichzelf opgelost had.

Draai je trouwens nog steeds op 18.4 LTS? Wellicht dat een nieuwe LTS hier geen last van heeft, want het moet bijna wel iets in je OS zijn wat de kill doet.

**Comment by dennissiemensma** [comment]
Je zou nog iets als `watch -n 1 free -m` kunnen doen in een tabje tijdens uitvoeren. Om te kijken of je daar iets in ziet gebeuren tijdens het draaien.

**Comment by dennissiemensma** [comment]
En deze kan ook nog inzicht geven: https://askubuntu.com/a/709366

```
dmesg | less
```

Om te zien of die OOM was.

**Comment by mthmulders** [comment]
Ik snap er niks meer van... Zojuist nog eens `./manage.py migrate --noinput`, met in een tweede terminal `watch -n 1 free -m` - draait als een zonnetje. Gisteravond was er nog een kernel update waardoor de VM even herstart is geweest.

Enige wat ik me zou kunnen voorstellen - maar dat is echt een _wild guess_: de PostgreSQL database draait op dezelfde VM. Ik heb een vrij grote database (althans, dat zegt DSMR Reader...) en misschien dat het uitvoeren van de migraties zoveel geheugen kost voor PostgreSQL dat er iets in de soep loopt?

> Draai je trouwens nog steeds op 18.4 LTS? Wellicht dat een nieuwe LTS hier geen last van heeft, want het moet bijna wel iets in je OS zijn wat de kill doet.

Ja. Toen ik het pakket de eerste keer installeerde was 20.04 nog niet ondersteund, en ik heb de upgrade naar 20.04 om die reden tot nu toe steeds tegengehouden. Is 20.04 ondertussen ook een ondersteund OS?

**Comment by dennissiemensma** [comment]
De migratie van 5.8 naar de laatste versie raakt geen grote data. DSMR-reader ondersteunt niet specifieke OS'en, maar requirements qua Python enzo. Ik raad je aan om een keertje te kijken naar de Docker-versie van DSMR-reader door Xirixiz. Dan zit alles in een container en ben je niet afhankelijk van je OS. Vooral bij toekomstige upgrades scheelt dat. Nadeel is dat het wat abstracter is, echter is het installeren en hosten van DSMR-reader daarmee wel super makkelijk dus. En je kunt er ook voor kiezen om bijv je database op de normale manier te hosten en DSMR-reader applicatie via docker.

**Comment by mthmulders** [comment]
Bedankt voor het advies! Ik ken mijn weg in Docker vrij goed, dus daar ben ik niet zo bang voor. Dit issue kan in elk geval dicht.
