### ISSUE TITLE
Custom datum bereik in archive💡

### ISSUE THREAD

**Issue by mvaneijken** [dsmrreader/dsmr-reader#1762]
### Feature

In het archive scherm is het mogelijk om de totalen per dag, maand en jaar op te vragen. Omdat ik graag zicht wil houden op het verschil tussen wat is geconsumeerd van het net en wat daaraan is teruggeleverd, zou ik graag handmatig een start- en einddatum kunnen opgeven. Nu weet ik dat je zoiets ook zou kunnen bereiken dmv contracts, echter ik heb vanwege de BTW verlaging hetzelfde contract per 1 juli met een ander tarief actief gemaakt.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Wellicht dat ik zoiets in een toekomstige versie meeneem. Waarschijnlijk niet op korte termijn.

Voor nu kun je de gegevens ophalen via de database of een CSV-export. Ik denk dat laatstgenoemde het makkelijkste is, ook omdat je daar een range kan opgeven. 
Exporteren kan via de `/export` URL in DSMR-reader of onderaan de nieuwe Support-pagina daar.

**Comment by dennissiemensma** [comment]
Ik laat deze voor wat het is. Hoewel ik me helemaal kan vinden in de feature zelf, kom ik er simpelweg niet aan toe.
