### ISSUE TITLE
Ongeveer "None" metingen opgeslagen (MySQL)

### ISSUE THREAD

**Issue by andyesten** [dsmrreader/dsmr-reader#1767]
### Description

Na de upgrade naar 5.9 krijg ik in het ' over' scherm de volgende (fout) melding:

   Ongeveer None metingen opgeslagen, overweeg dataopschoning (indien nog niet ingeschakeld)   (nu)

Kan ik deze negeren? De dataopschoning staat op een maand.

Andy

### DSMR-reader version

5.9

### DSMR-reader platform

Docker (e.g. Xirixiz)

### Debug info dump

```shell
DSMR-READER
    App / Python / Database                                                            v5.9 / v3.11.1 / mysql
    BE sleep / DL sleep / Retention / Override                                     1.0s / 5.0s / 672h / False
    Latest telegram version read / Parser settings                                                 "50" / "4"

DATA
    Telegrams total (est.)                                                                        ??? (mysql)
    Consumption records electricity / gas (est.)                                    ??? (mysql) / ??? (mysql)

UNRESOLVED ISSUES
    Ongeveer None metingen opgeslagen, overweeg dataopschoning (indien nog niet ingeschakeld)                                      nu
```

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Werkt de rest verder wel? Zo ja, dan hoef je niets te doen.

Dit komt doordat je MySQL gebruikt. De kern van DSMR-reader zou overigens gewoon moeten werken, ook zonder PostgreSQL, maar dit is een onvoorzien bijeffect denk ik. Ik zal kijken of ik die specifieke check een keer wat kan verbeteren.

**Comment by andyesten** [comment]
Hi,

Dank voor de snelle reactie.

> Werkt de rest verder wel? 

Ja zeker! Alles werkt verder zonder problemen.

> Ik zal kijken of ik die specifieke check een keer wat kan verbeteren

Top.

**Comment by peternijssen** [comment]
Ik ervaar hetzelfde probleem, maar het doet inderdaad verder geen afbreuk aan de applicatie zelf :)

**Comment by dennissiemensma** [comment]
In de volgende release wordt de melding niet meer getoond als het geen postgresql engine is.
