### ISSUE TITLE
Github: The discussions tab doesn't have a button to start a discussion 

### ISSUE THREAD

**Issue by SenH** [dsmrreader/dsmr-reader#1785]
### Description

Is the discussions tab still active (or disabled for non contributors)?
![image](https://user-images.githubusercontent.com/168986/210765110-1b713ff3-d2cf-470d-a9ae-29058d3af9a9.png)

### DSMR-reader version

v5.9

### DSMR-reader platform

Docker (e.g. Xirixiz)

**Comment by dennissiemensma** [comment]
Only announcements _should_ be disabled for public, the other one I'd expect to work. But not sure...

----

![Screenshot from 2023-01-05 20-45-21](https://user-images.githubusercontent.com/16581744/210866970-af519de4-2dc1-4425-af2c-481b63f101a4.png)

---

> **Question / Answer**
> Enable your community to ask questions, suggest answers, and vote on the best suggested answer.
