### ISSUE TITLE
💡Mogelijkheid om dynamische tarieven te laden.

### ISSUE THREAD

**Issue by Simanias** [dsmrreader/dsmr-reader#1790]
### Feature

@dennissiemensma,

Aangezien er steeds meer aanbieders zijn met dynamische tarieven (zelf ben ik recentelijk overgestapt), was ik benieuwd of het mogelijk is om een de invoer voor het tarief vanuit een json-string te laten plaats vinden.
Eventueel zou ook een MQTT sensor vanuit Home Assistant met dit flexibele tarief een optie zijn (deze sensor is redelijk makkelijk te realiseren in Home Assistant).

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Zie de comments in #1783 en vooral de onderste daar voor wat meer context. 

_De TLD;DR is dat DSMR-reader niet als doel heeft zo ver te gaan qua prijzen. Ik denk dat prijsberekeningen (de complexere maar ook in het algemeen) in een HA je meer kunnen helpen, omdat dat meer een tool is "voor van alles en heel specifiek"._
