### ISSUE TITLE
Relative percentages in Compare

### ISSUE THREAD

**Issue by caskes** [dsmrreader/dsmr-reader#1798]
### Feature

Really like this tool and love the interface. A small feature I would like to suggest is the following.

Under Compare I sometimes like to compare the current month with the same month last year. E.g comparing Jan 2023 with Jan 2022. However when the month is still ongoing you can't do a like for like comparison as you do not have the same amount of datapoints. The percentage comparisons in the last column therefor make little sense - not until the month is almost complete. 

Would it be possible to calculate this percentage so that it also considers the number of datapoints the 2 metrics are based on. So on Jan 17 you would have 16 datapoints and thus correct the percentage by multiplying it with 16/31.

Cheers.

**Comment by dennissiemensma** [comment]
Thanks for your suggestion. I'll consider it in a future release one way or another. I might just plot all datapoint along each other when month level is selected, similar to the Archive changing graph hour/day/month levels depending on the level selected.

**Comment by dennissiemensma** [comment]
I'll leave this issue as-is, as I do not have the time to rework the interface, even though it was planned for overhaul.
