### ISSUE TITLE
Toevoegen van kwartier piek vermogen data gerapporteerd door Fluxis meters💡

### ISSUE THREAD

**Issue by roswennen** [dsmrreader/dsmr-reader#1807]
### Feature

Deze request is om de nieuwe waardes van de kwartier pieken die Fluxis meters nu uitsturen toe te voegen aan de MQTT lijst

Het betreft het actuele kwartier piek waarde van het lopende kwartier met volgend formaat
            1-0:1.4.0(00.078*kW)

Hoogste kwartier piek waarde en het eindtijdstip van dat betreffende kwartier wat wordt aangegeven in formaat yymmddhhmmss en W voor winter of S voor summer tijd
            1-0:1.6.0(230201020000W)(01.566*kW)

en de lijst van de laatste 13 kwartier piek waardes en maanden waarop ze betrekking hebben dus .  Deze groeit tot er 13 waardes zijn.  Idealiter zijn er dus 39 MQTT waardes
maand 1 piek, maand 1 maand (de maand waarin de piek was) en maand 1 time (end of quarter time), maand 2 piek ..... tot 13

            0-0:98.1.0(3)(1-0:1.6.0)(1-0:1.6.0)(200501000000S)(200423191500S)(03.695*kW)(200401000000S)(200305123000S)(05.980*kW)(200301000000S)(200210034500W)(04.318*kW)
De eerste waarde tussen haakjes geeft aan voor hoeveel van de 13 (x3) parameters er waarden in het telegram zitten.  Hier dus 3 en in mijn telegrams 1.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek! Deze staat al op de lijst via:

# #1764
