### ISSUE TITLE
Ik heb dsmr reader in docker geïnstalleerd op een RP 3en kom niet ingelogd.

### ISSUE THREAD

**Issue by Kakes** [dsmrreader/dsmr-reader#1815]
### Description

Wat mij opvalt is dat er in Container details altijd staat bij status Running for a few seconds.
[dsmr log.txt](https://github.com/dsmrreader/dsmr-reader/files/10842334/dsmr.log.txt)

### DSMR-reader version

v5.10.2

### DSMR-reader platform

None

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Voor issues met de docker-versie, specifiek bij de processen in de container (die niet over de werking van DSMR-reader zelf gaan), kun je het beste door (oude) issues bij deze kijken: 
- https://github.com/xirixiz/dsmr-reader-docker/issues

Ik denk dat je sowieso in de logs zelf mag kijken, want als er iets niet goed start dan staat er meestal wel een reden in de container logs.

**Comment by Kakes** [comment]
Sorry Dennis.
hartelijk dank voor je snelle reactie.
dit was mijn eerste post op github ik had te snel op enter gedrukt.
ik wilde nog melden dat de docker constant meldt  *Running for a few
seconds*
en zoals de log hieronder dat ook meldt.
Ook dat ik de volgende docker tag heb geinstalleerd docker pull
ualex73/dsmr-reader-docker

Vriendelijke groet Jan Kakes


2023-02-27 20:07:48 INFO: Start DSMR Reader - Mode=SERVER

2023-02-27 20:07:48 INFO: Executing '/usr/bin/pg_isready -h
192.168.2.25 -p 5432 -U dsmrreader -d dsmrreader -t 1'

...........................................................
2023-02-27 20:08:50

2023-02-27 20:08:50 INFO: Start DSMR Reader - Mode=SERVER

2023-02-27 20:08:50 INFO: Executing '/usr/bin/pg_isready -h
192.168.2.25 -p 5432 -U dsmrreader -d dsmrreader -t 1'

...........................................................
2023-02-27 20:09:52

2023-02-27 20:09:52 INFO: Start DSMR Reader - Mode=SERVER

2023-02-27 20:09:52 INFO: Executing '/usr/bin/pg_isready -h
192.168.2.25 -p 5432 -U dsmrreader -d dsmrreader -t 1'

...........................................................
2023-02-27 20:10:55

2023-02-27 20:10:55 INFO: Start DSMR Reader - Mode=SERVER

2023-02-27 20:10:55 INFO: Executing '/usr/bin/pg_isready -h
192.168.2.25 -p 5432 -U dsmrreader -d dsmrreader -t 1'

...........................................................
2023-02-27 20:11:57

2023-02-27 20:11:57 INFO: Start DSMR Reader - Mode=SERVER

2023-02-27 20:11:57 INFO: Executing '/usr/bin/pg_isready -h
192.168.2.25 -p 5432 -U dsmrreader -d dsmrreader -t 1'

...........................................................
2023-02-27 20:12:59

2023-02-27 20:12:59 INFO: Start DSMR Reader - Mode=SERVER

2023-02-27 20:12:59 INFO: Executing '/usr/bin/pg_isready -h
192.168.2.25 -p 5432 -U dsmrreader -d dsmrreader -t 1'



{
    "AppArmorProfile": "",
    "Args": [],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "/app/run.sh"
        ],
        "Domainname": "",
        "Entrypoint": null,
        "Env": [
            "DSMRREADER_ADMIN_PASSWORD=admin",
            "DJANGO_DATABASE_HOST=192.168.2.25",
            "DSMRREADER_ADMIN_USER=admin",
            "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "LANG=C.UTF-8",
            "GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D",
            "PYTHON_VERSION=3.11.1",
            "PYTHON_PIP_VERSION=22.3.1",
            "PYTHON_SETUPTOOLS_VERSION=65.5.1",
            "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/66030fa03382b4914d4c4d0896961a0bdeeeb274/public/get-pip.py",
            "PYTHON_GET_PIP_SHA256=1e501cf004eac1b7eb1f97266d28f995ae835d30250bec7f8850562703067dc6",
            "DSMR_READER_VERSION=v5.10.2",
            "DJANGO_DATABASE_ENGINE=django.db.backends.postgresql",
            "DJANGO_DATABASE_PORT=5432",
            "DJANGO_DATABASE_USER=dsmrreader",
            "DJANGO_DATABASE_PASSWORD=dsmrreader",
            "DJANGO_DATABASE_NAME=dsmrreader",
            "DSMRREADER_DATALOGGER_INPUT_METHOD=serial",
            "DSMRREADER_DATALOGGER_SERIAL_PORT=/dev/ttyUSB0",
            "DSMRREADER_DATALOGGER_SERIAL_BAUDRATE=115200",
            "DSMRREADER_DATALOGGER_NETWORK_HOST=127.0.0.1",
            "DSMRREADER_DATALOGGER_NETWORK_PORT=2000",
            "DSMR_MODE=SERVER"
        ],
        "ExposedPorts": {
            "443/tcp": {},
            "80/tcp": {}
        },
        "Hostname": "0037dd977ebf",
        "Image": "ualex73/dsmr-reader-docker:latest",
        "Labels": {},
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": {
            "/dev": {}
        },
        "WorkingDir": "/dsmr"
    },
    "Created": "2023-02-27T17:16:20.177497568Z",
    "Driver": "overlay2",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": {
            "LowerDir":
"/var/lib/docker/overlay2/5e044b004702777eed9bf703bac96a02c49244788a76337cf33d0fd0246de039-init/diff:/var/lib/docker/overlay2/0a569563abd4dbe7c8554fc835dce4ea807cbbeb876713a75d3f5177983ffdc3/diff:/var/lib/docker/overlay2/3db754c71510374d815f236f96da83088d54817f759a933bbc7a0054d2076210/diff:/var/lib/docker/overlay2/6f6371d770588ae6ce8760c22374e755e2a95a246bc5291779d6a63175d41811/diff:/var/lib/docker/overlay2/ad5b997e2b8821124bac7ed55b5ba72957a3e9618057c4a337cd4250241254d1/diff:/var/lib/docker/overlay2/54f8037b27ed7b274662b7d25ffef061bcc3d6e5b9eb842d3f2bf21da838aa69/diff:/var/lib/docker/overlay2/322a906a9d7ae138cfab9b67e54f76c55ed7ee3f1308d779e61e782d9298873e/diff:/var/lib/docker/overlay2/7c3ab535c0f255ce97e1bea3c2671dae4e34b9a5f647c8f834bfd10d5b8861a2/diff:/var/lib/docker/overlay2/c8e3700b82dd7a88185557a8dd2b1bc700354f6216f1811585d59a764f8673b8/diff:/var/lib/docker/overlay2/1cdece5531922bddd910464aafc4925a0992cad732f47c54e3f3c2b61efa34e2/diff:/var/lib/docker/overlay2/ca200e714ee08df55f97b3cfb8a024fe217b287e1e072ae773a22abebb7e57aa/diff",
            "MergedDir":
"/var/lib/docker/overlay2/5e044b004702777eed9bf703bac96a02c49244788a76337cf33d0fd0246de039/merged",
            "UpperDir":
"/var/lib/docker/overlay2/5e044b004702777eed9bf703bac96a02c49244788a76337cf33d0fd0246de039/diff",
            "WorkDir":
"/var/lib/docker/overlay2/5e044b004702777eed9bf703bac96a02c49244788a76337cf33d0fd0246de039/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "/dev:/dev"
        ],
        "BlkioDeviceReadBps": [],
        "BlkioDeviceReadIOps": [],
        "BlkioDeviceWriteBps": [],
        "BlkioDeviceWriteIOps": [],
        "BlkioWeight": 0,
        "BlkioWeightDevice": [],
        "CapAdd": [
            "AUDIT_WRITE",
            "CHOWN",
            "DAC_OVERRIDE",
            "FOWNER",
            "FSETID",
            "KILL",
            "MKNOD",
            "NET_BIND_SERVICE",
            "NET_RAW",
            "SETFCAP",
            "SETGID",
            "SETPCAP",
            "SETUID",
            "SYS_CHROOT"
        ],
        "CapDrop": [
            "AUDIT_CONTROL",
            "BLOCK_SUSPEND",
            "DAC_READ_SEARCH",
            "IPC_LOCK",
            "IPC_OWNER",
            "LEASE",
            "LINUX_IMMUTABLE",
            "MAC_ADMIN",
            "MAC_OVERRIDE",
            "NET_ADMIN",
            "NET_BROADCAST",
            "SYSLOG",
            "SYS_ADMIN",
            "SYS_BOOT",
            "SYS_MODULE",
            "SYS_NICE",
            "SYS_PACCT",
            "SYS_PTRACE",
            "SYS_RAWIO",
            "SYS_RESOURCE",
            "SYS_TIME",
            "SYS_TTY_CONFIG",
            "WAKE_ALARM"
        ],
        "Cgroup": "",
        "CgroupParent": "",
        "CgroupnsMode": "private",
        "ConsoleSize": [
            24,
            80
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": [
            {
                "CgroupPermissions": "rwm",
                "PathInContainer": "/dev/ttyUSB0",
                "PathOnHost": "/dev/ttyUSB0"
            }
        ],
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": [],
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "IpcMode": "private",
        "Isolation": "",
        "Links": null,
        "LogConfig": {
            "Config": {},
            "Type": "json-file"
        },
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "bridge",
        "OomKillDisable": null,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {
            "80/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8888"
                }
            ]
        },
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ],
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "unless-stopped"
        },
        "Runtime": "runc",
        "SecurityOpt": null,
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": null
    },
    "HostnamePath":
"/var/lib/docker/containers/9bbe26bd250ebcce793765aafb3ae69b62faa50c2f3f6b1fc75d2c2b1c1672f2/hostname",
    "HostsPath":
"/var/lib/docker/containers/9bbe26bd250ebcce793765aafb3ae69b62faa50c2f3f6b1fc75d2c2b1c1672f2/hosts",
    "Id": "9bbe26bd250ebcce793765aafb3ae69b62faa50c2f3f6b1fc75d2c2b1c1672f2",
    "Image": "sha256:dc7b6596afad5a45b66b876fccc2e2c0dd63a044b2d172eddb61041f4c5a462b",
    "LogPath": "/var/lib/docker/containers/9bbe26bd250ebcce793765aafb3ae69b62faa50c2f3f6b1fc75d2c2b1c1672f2/9bbe26bd250ebcce793765aafb3ae69b62faa50c2f3f6b1fc75d2c2b1c1672f2-json.log",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/dev",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/dev",
            "Type": "bind"
        }
    ],
    "Name": "/dsmr",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID":
"ccabeb91afbe1834b40c1267b66bb9678cf1768723937912abeb86ebe4db115a",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.3",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:03",
        "Networks": {
            "bridge": {
                "Aliases": null,
                "DriverOpts": null,
                "EndpointID":
"ccabeb91afbe1834b40c1267b66bb9678cf1768723937912abeb86ebe4db115a",
                "Gateway": "172.17.0.1",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": {},
                "IPAddress": "172.17.0.3",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "02:42:ac:11:00:03",
                "NetworkID":
"76c7402b4188e1db43f5bfc7821a3cc21110ccddc6c2a6565c3e5d815b2de13b"
            }
        },
        "Ports": {
            "443/tcp": null,
            "80/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8888"
                },
                {
                    "HostIp": "::",
                    "HostPort": "8888"
                }
            ]
        },
        "SandboxID":
"ffed463b1e19e79e72f97727ed7ac61b865247dbe06b29d2d8179dd101a12b65",
        "SandboxKey": "/var/run/docker/netns/ffed463b1e19",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "/app/run.sh",
    "Platform": "linux",
    "Portainer": {
        "ResourceControl": {
            "Id": 17,
            "ResourceId":
"9bbe26bd250ebcce793765aafb3ae69b62faa50c2f3f6b1fc75d2c2b1c1672f2",
            "SubResourceIds": [],
            "Type": 1,
            "UserAccesses": [],
            "TeamAccesses": [],
            "Public": false,
            "AdministratorsOnly": true,
            "System": false
        }
    },
    "ProcessLabel": "",
    "ResolvConfPath":
"/var/lib/docker/containers/9bbe26bd250ebcce793765aafb3ae69b62faa50c2f3f6b1fc75d2c2b1c1672f2/resolv.conf",
    "RestartCount": 1,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "2023-02-27T17:17:22.988972245Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 1228570,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2023-02-27T17:17:24.200332179Z",
        "Status": "running"
    }
}














Op ma 27 feb 2023 om 20:53 schreef Dennis Siemensma <
***@***.***>:

**Comment by dennissiemensma** [comment]
Je kunt anders het beste deze image proberen: https://github.com/xirixiz/dsmr-reader-docker

**Comment by Kakes** [comment]
Hoi Dennis
helaas een vergelijkbaar resultaat met de geadviseerde tag
alleen deze blijft al in de docker als oranje starting staan
hieronder staat de logging

Vriendelijke groet Jan Kakes

     nc: getaddrinfo: Name does not resolve


Testing database connectivity: 1 second(s) of 30 seconds...
Testing database connectivity: 2 second(s) of 30 seconds...
Testing database connectivity: 3 second(s) of 30 seconds...
Testing database connectivity: 4 second(s) of 30 seconds...
Testing database connectivity: 5 second(s) of 30 seconds...
Testing database connectivity: 6 second(s) of 30 seconds...
Testing database connectivity: 7 second(s) of 30 seconds...
Testing database connectivity: 8 second(s) of 30 seconds...
Testing database connectivity: 9 second(s) of 30 seconds...
Testing database connectivity: 10 second(s) of 30 seconds...
Testing database connectivity: 11 second(s) of 30 seconds...
Testing database connectivity: 12 second(s) of 30 seconds...
Testing database connectivity: 13 second(s) of 30 seconds...
Testing database connectivity: 14 second(s) of 30 seconds...
Testing database connectivity: 15 second(s) of 30 seconds...
Testing database connectivity: 16 second(s) of 30 seconds...
Testing database connectivity: 17 second(s) of 30 seconds...
Testing database connectivity: 18 second(s) of 30 seconds...
Testing database connectivity: 19 second(s) of 30 seconds...
Testing database connectivity: 20 second(s) of 30 seconds...
Testing database connectivity: 21 second(s) of 30 seconds...
Testing database connectivity: 22 second(s) of 30 seconds...
Testing database connectivity: 23 second(s) of 30 seconds...
Testing database connectivity: 24 second(s) of 30 seconds...
Testing database connectivity: 25 second(s) of 30 seconds...
Testing database connectivity: 26 second(s) of 30 seconds...
Testing database connectivity: 27 second(s) of 30 seconds...
Testing database connectivity: 28 second(s) of 30 seconds...
Testing database connectivity: 29 second(s) of 30 seconds...
Testing database connectivity: 30 second(s) of 30 seconds...[ FAIL ]
Database connectivity couldn't be verified! Please verify your
settings. Exiting...

[cont-init.d] 20-set-app-defaults: exited 1.

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 10-adduser: executing...

usermod: no changes

-------------------------

User UID: 803

User GID: 803

-------------------------

[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 20-set-app-defaults: executing...


[ INFO ] DSMR Reader Reader release: 5.10.3


[ INFO ] DSMR Reader Reader Docker release: 2023.02.01


[ INFO ] Ensure permissions...


[ INFO ] Setting architecture requirements...


[ INFO ] ARM Architecture


[ INFO ] Verifying if the DSMR Reader web credential variables have been set...


[ INFO ] Verifying database connectivity to host: dsmrdb with port: 5432...

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve


Testing database connectivity: 1 second(s) of 30 seconds...
Testing database connectivity: 2 second(s) of 30 seconds...
Testing database connectivity: 3 second(s) of 30 seconds...
Testing database connectivity: 4 second(s) of 30 seconds...
Testing database connectivity: 5 second(s) of 30 seconds...
Testing database connectivity: 6 second(s) of 30 seconds...
Testing database connectivity: 7 second(s) of 30 seconds...
Testing database connectivity: 8 second(s) of 30 seconds...
Testing database connectivity: 9 second(s) of 30 seconds...
Testing database connectivity: 10 second(s) of 30 seconds...
Testing database connectivity: 11 second(s) of 30 seconds...
Testing database connectivity: 12 second(s) of 30 seconds...
Testing database connectivity: 13 second(s) of 30 seconds...
Testing database connectivity: 14 second(s) of 30 seconds...
Testing database connectivity: 15 second(s) of 30 seconds...
Testing database connectivity: 16 second(s) of 30 seconds...
Testing database connectivity: 17 second(s) of 30 seconds...
Testing database connectivity: 18 second(s) of 30 seconds...
Testing database connectivity: 19 second(s) of 30 seconds...
Testing database connectivity: 20 second(s) of 30 seconds...
Testing database connectivity: 21 second(s) of 30 seconds...
Testing database connectivity: 22 second(s) of 30 seconds...
Testing database connectivity: 23 second(s) of 30 seconds...
Testing database connectivity: 24 second(s) of 30 seconds...
Testing database connectivity: 25 second(s) of 30 seconds...
Testing database connectivity: 26 second(s) of 30 seconds...
Testing database connectivity: 27 second(s) of 30 seconds...
Testing database connectivity: 28 second(s) of 30 seconds...
Testing database connectivity: 29 second(s) of 30 seconds...
Testing database connectivity: 30 second(s) of 30 seconds...[ FAIL ]
Database connectivity couldn't be verified! Please verify your
settings. Exiting...

[cont-init.d] 20-set-app-defaults: exited 1.

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 10-adduser: executing...

usermod: no changes

-------------------------

User UID: 803

User GID: 803

-------------------------

[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 20-set-app-defaults: executing...


[ INFO ] DSMR Reader Reader release: 5.10.3


[ INFO ] DSMR Reader Reader Docker release: 2023.02.01


[ INFO ] Ensure permissions...


[ INFO ] Setting architecture requirements...


[ INFO ] ARM Architecture


[ INFO ] Verifying if the DSMR Reader web credential variables have been set...


[ INFO ] Verifying database connectivity to host: dsmrdb with port: 5432...

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve

nc: getaddrinfo: Name does not resolve



Op ma 27 feb 2023 om 21:24 schreef Dennis Siemensma <
***@***.***>:

**Comment by dennissiemensma** [comment]
Het lijkt erop dat je database niet draait. 

Het alleen wisselen van een tag is niet afdoende, je zult echt de complete docker compose config moeten gebruiken van whatever je gebruikt:
- https://github.com/xirixiz/dsmr-reader-docker
- https://github.com/ualex73/dsmr-reader-docker

DSMR-reader heeft sowieso een database nodig en mogelijk nog andere images, afhankelijk van wat je gebruikt (influxdb, etc).

Voor inhoudelijke hulp kun je het beste bij bovenstaande projecten zelf aankloppen, maar linksom of rechtsom kun je het beste de voorbeelden daar gebruiken.

**Comment by Kakes** [comment]
Oke Dennis
ik ga het nog een keer proberen
Dankjewel voor de snelle reactie

Op di 28 feb 2023 om 18:57 schreef Dennis Siemensma <
***@***.***>:
