### ISSUE TITLE
🚨 	Teruglevering blijft op nul staan in live grafieken

### ISSUE THREAD

**Issue by bertus24** [dsmrreader/dsmr-reader#1816]
### Description

In het overzicht live grafieken blijft de terug levering op 0 staan. In het dashboard wordt het wel goed weergegeven. De grafieken zelf werken wel goed alleen het teruglever totaal blijft op 0 staan.

### DSMR-reader version

v5.10.3

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. 

- Is het een nieuwe installatie?
- Heb je een screenshot van het dashboard en grafieken? 
- Heb je een voorbeeldtelegram?

**Comment by bertus24** [comment]
Installatie heeft al verschillende upgrades gehad. Is dus niet nieuw.

![image](https://user-images.githubusercontent.com/61046339/221944338-3e67eec3-ed24-469c-9a76-b4469d2684ce.png)

Als je mij helpt met hoe ik een voorbeeld telegram kan toevoegen komt deze ook.

**Comment by dennissiemensma** [comment]
Bedankt voor je aanvulling.

Ik zie dat je die issue om 8:39 hebt aangemaakt en volgens je grafiek leek je op dat moment nog geen teruglevering te hebben. Doelde je daarop?
 
![Screenshot from 2023-02-28 19-27-48](https://user-images.githubusercontent.com/16581744/221945951-363f2a40-3c0e-4eaa-a37a-06ba025ee8b4.png)


Heb je ook een screenshot van het dashboard? Omdat het nu avond is, kun je dit wellicht het beste morgen doen zodra je weer meer opwekt dan verbruikt.

**Comment by dennissiemensma** [comment]
Idem voor het telegram, mocht het morgen op dat moment niet kloppen. Bij de pagina Support of Ondersteuning kun je onderaan de pagina je laatste telegram inzien.

**Comment by bertus24** [comment]
Vanwege mijn eigen stommiteit heb ik gewoon op het verkeerde moment gekeken. Sorry voor de tijd die dit je heeft gekost.

**Comment by dennissiemensma** [comment]
Bedankt voor je snelle update, het had mijzelf ook kunnen overkomen hoor 🤣
