### ISSUE TITLE
💡Hoe migreren naar een nieuwe server/vm 

### ISSUE THREAD

**Issue by Timdebruijn** [dsmrreader/dsmr-reader#1817]
### Feature

De huidige handleiding is heel erg compleet, echter ontbreekt het aan een "how to" om de bestaande data te migreren naar een nieuwe server/vm.
Stel een gebruiker wil van Debian 10 naar Debian 11 migreren of Ubuntu 20.04 naar 22.04. Ik gebruik dsmr nu al meer dan 2 jaar en zal dus ooit moeten migreren wil ik support van het OS behouden en ook dsmr zal uiteindelijk de ondersteuning voor oudere python versies laten vallen.

Ik heb zorgvuldig gezocht in de bestaande documentatie maar kon helaas niets vinden over migreren buiten dit:
https://dsmr-reader.readthedocs.io/en/v5/how-to/database/postgresql-migrate-day-hour-statistics.html

Het is mij onduidelijk of dit alle data bevat en in welke fase van de installatie dit moet worden gedaan.

Alvast heel erg bedankt!

**Comment by dennissiemensma** [comment]
In principe staat al je data in de database. Alleen het overzetten van de complete database is vereist en een stuk makkelijker. Deze kun je dumpen naar een gecomprimeerde SQL file met:

```
sudo su - dsmr
./manage.py dsmr_backup_create --full
```
In de output van het command staat waar de file staat. Backup die.

----

Vervolgens kun je een nieuwe installatie doen van DSMR-reader (dit moet wel dezelfde of een nieuwere versie zijn) en al vrij snel bij de installatie kun je dan die SQL file importeren:
- https://dsmr-reader.readthedocs.io/en/v5/how-to/installation/quick.html#optional-restore-a-database-backup
- https://dsmr-reader.readthedocs.io/en/v5/how-to/database/postgresql-restore-backup.html

Ik adviseer je dit een keertje te doen in een nieuwe VM, zonder de oude weg te gooien, om te zien of het lukt. Je kunt de nieuwe installatie (ter test) in principe gewoon draaien zonder die aan je meter te hangen. 

Als het importeren gelukt is zou je al je data moeten zien tot het moment van SQL dump hierboven. Je kunt dan kiezen die installatie te gebruiken of het nogmaals te doen "voor het echt".
