### ISSUE TITLE
🙋Geen teruglevering zichtbaar in live / dashboard

### ISSUE THREAD

**Issue by BjornB2** [dsmrreader/dsmr-reader#1839]
### Description

Sinds vanmiddag zonnepanelen (yay!) maar ik denk dat ik ergens een instelling in DSMR niet goed heb want ik zie de teruglevering niet terug in Live en dashboard. Ik zie de teruglevering wel in admin -> DSMR readings en in MQTT. Moet ik ergens iets aanzetten? Ik heb me rotgezocht maar nog niets kunnen vinden. 
<img width="783" alt="Scherm­afbeelding 2023-04-17 om 17 28 13" src="https://user-images.githubusercontent.com/3328086/232537990-c2f60117-42a9-4579-a4bb-1f41496ad620.png">
<img width="1139" alt="Scherm­afbeelding 2023-04-17 om 17 38 36" src="https://user-images.githubusercontent.com/3328086/232538112-75d43075-be27-4ee1-858d-dec11983bad6.png">
<img width="320" alt="Scherm­afbeelding 2023-04-17 om 17 39 41" src="https://user-images.githubusercontent.com/3328086/232538363-3317c982-125b-4e78-b36e-2cbb4a94a32e.png">

### DSMR-reader version

5.10 docker op Synology

### DSMR-reader platform

Docker (e.g. Xirixiz)

### Debug info dump

```shell
DSMR-READER
    App / Python / Database                                                    v5.10.3 / v3.11.2 / postgresql
    BE sleep / DL sleep / Retention / Override                                     1.0s / 0.5s / 672h / False
    Latest telegram version read / Parser settings                                                 "42" / "4"

DATA
    Telegrams total (est.)                                                                             310938
    Consumption records electricity / gas (est.)                                               112387 / 34639

UNRESOLVED ISSUES
    Proces loopt achter op schema: Calculate quarter hour electricity peaks                      52 minuten geleden
```

**Comment by dennissiemensma** [comment]
Je zou kunnen kijken in de admin in `/admin/dsmr_backend/backendsettings/` of daar het vinkje aanstaat om teruglevering geforceerd te verbergen.

**Comment by BjornB2** [comment]
Ahh dat was hem! Ik draai DSMR al eeuwen en zal dat ooit aangezet hebben. 

Thanks voor je snelle reactie en uiteraard ook voor DSMR Reader in het algemeen 😊

**Comment by dennissiemensma** [comment]
Top, fijn om te horen!
