### ISSUE TITLE
🚨Gasverbruik en Stroomverbruik in CSV-export (dag-totalen) kloppen niet

### ISSUE THREAD

**Issue by jcjdammers** [dsmrreader/dsmr-reader#1844]
Update

# Zie #1770 

-----

### Description

Ik maak elke maand een CSV-export met dagtotalen van stroom- en gasverbruik en tel die bij elkaar op voor de maandtotalen.
Echter de totalen van de CSV-export en ook het getoonde gasverbruik in het maand Archief scherm kloppen niet.
Het gasverbruik en stroomverbruik in de Home Assistant Energy Dashboard (maandtotalen) kloppen echter wel, met de gegevens van Oxxio en mijn eigen handmatige meteropname.

Zie de bijgevoegde bestanden:
dsmrreader-2023-03.xlsx ==> CSV-export van DSM-reader met dagtotalen van de maand Maart 2023.
oxxio-2023-03.xlsx 	==> CSV-export van Oxxio met dagtotalen van de maand Maart 2023.
DSM-reader Archief Maart 2023.png ==> DSM-reader Archief scherm van de maand Maart 2023.
HA-Stroom-Maart2023.jpg ==> HA energy dashboard met totaal stroomverbruik van Maart 2023.
HA-Gas-Maart2023.jpg ==> HA energy dashboard met totaal gasverbruik van Maart 2023.

Wat is er mis? Graag uw hulp.
Alvast bedankt.
NB. Ik heb DSM-reader geinstalleerd als add-on binnen HAOS.

<img width="1225" alt="DSM-reader Archief Maart 2023" src="https://user-images.githubusercontent.com/10573570/234633864-0ea52b9c-2847-432f-9f6b-13587dea9d0c.png">
[dsmrreader-2023-03.xlsx](https://github.com/dsmrreader/dsmr-reader/files/11334923/dsmrreader-2023-03.xlsx)
![HA-Gas-Maart2023](https://user-images.githubusercontent.com/10573570/234633878-d5d77419-e6d2-4ef2-8dc8-0bd95e23598d.jpg)
![HA-Stroom-Maart2023](https://user-images.githubusercontent.com/10573570/234633886-f2ba1140-c41e-4f3a-8a91-38e6ae304835.jpg)
[oxxio-2023-03.xlsx](https://github.com/dsmrreader/dsmr-reader/files/11334924/oxxio-2023-03.xlsx)

### DSMR-reader version

5.10.3

### DSMR-reader platform

Other

**Comment by dennissiemensma** [comment]
Vermoedelijk gerelateerd aan #1811 en #1770

**Comment by jcjdammers** [comment]
Ja daar lijkt het wel op.
Hopelijk kan dit worden opgelost.

**Comment by gctwnl** [comment]
Het viel mij op dat de maandtotalen van gas in DSMR niet klopten met die van Greenchoice. Nu ga ik er dan vanzelf van uit dat Greenchoice er naast zit (hopeloze IT daar), maar toen ik wat dieper ging graven begon ik daar toch aan te twijfelen.

Volgens DSMR v5.10.3:
- Was op 1/3/2023 00:00:00 de stand 1,082.161
- Was op 1/4/2023 00:00:00 de stand 1,205.788
Dat is een verbruik van 123.627 (wat vrijwel overeenkomt met wat Greenchoice mij aangeeft: 123)
Selecteer ik in Archive echter het maandniveau, dan zegt DSMR dat ik 112.811 heb verbruikt.

Ik zie dat er hier op github al een paar gerelateerde meldingen over die totalen zijn dus ik hoef er geen issue daar aan toe te voegen, maar wellicht is dit een ander datapunt dat interessant/nuttig is.

Ik heb overigens de hourly CSV data gedownload en eens een sommetje in excel gemaakt van maart en dan kom ik voor gas op 112.754. En toen snapte ik het niet meer. Het lijkt wel of die hourly metingen onvolledig zijn, terwijl de meterstanden in de daily CSV wel een juist beeld geven. Dus dan zou het toch een ander issue zijn. Kortom, ik ben de draad even kwijt.

**Comment by massis87** [comment]
ik sluit me aan bij gctwnl: Ik slaagde er maar niet in om mijn kosten te laten overeenkomen met de werkelijke facturen.
Tot bleek dat meterstand bij eind van de maand (2080.393) min meterstand bij eind vorige maand (2052.192) flink afwijkt, want het is werkelijk 28+m³, maar DSMR zegt een maandverbruik van 20m³. Dit is structureel elke maand flink ernaast, zowel in het Archive scherm op maandniveau, als in het Energy Contracts scherm waar mijn contracten per maand (maandelijks variabele prijs) in staan...

**Comment by dennissiemensma** [comment]
Dit is helaas een gevolg van https://github.com/dsmrreader/dsmr-reader/issues/1844#issuecomment-1523766555. Ik kom echter in de maanden buiten de winter om hier wat lastig aan toe, omdat het niet een kleine fix is.

**Comment by massis87** [comment]
> Dit is helaas een gevolg van [#1844 (comment)](https://github.com/dsmrreader/dsmr-reader/issues/1844#issuecomment-1523766555). Ik kom echter in de maanden buiten de winter om hier wat lastig aan toe, omdat het niet een kleine fix is.

Alle begrip daarvoor, ik wilde maar bevestigen dat het nog steeds speelt :-)

Ps: handig misschien om mee rekening te houden: in België wordt steeds de gas stand van 06:00 gebruikt door netbeheerder Fluvius als ze gaan rekenen, nooit dat van middernacht...

**Comment by dennissiemensma** [comment]
Ik sluit deze zodat alles via #1770 gaat.

# Zie #1770

**Comment by jcjdammers** [comment]
Hi Dennis,
Ik snap dat het meer tijd kost, maar ik hoop dat het later dit jaar kan worden opgelost. Het maken van dag/maand totalen is namelijk een belangrijke functie voor mij, en ik zou het jammer vinden als dit niet correct werkt in zo'n goed programma. Alvast bedankt.
