### ISSUE TITLE
🙋dsmr reader een poos niet aan toch data import mogelijkheid

### ISSUE THREAD

**Issue by alexswart** [dsmrreader/dsmr-reader#1850]
### Description

Helaas is mijn server met daarop DSMR reader gecrasht en heeft hierdoor dsmr-reader een aantal dagen niet kunnen draaien en heb een backup van Februari terug kunnen zetten, hellaas had ik geen recentere meer 
nu mis ik dus van een periode het verbruik, hier kan ik gelukkig mee leven, maar deze dagen zijn zoals het nu lijkt ook niet meegenomen met het totale verbruik van het afgelopen jaar kijkt hij niet naar het eerste en laatse bekende verbruik?
als ik nu een overzicht bekijk met wat ik afgelopen maand bijvoorbeeld heb verbruikt is dit verbruik veel te laag is er een mogelijkheid om dit te corrigeren? eventueel een extreem hoog verbruik op de dag dat DSMR reader weer ging draaien? 

### DSMR-reader version

5.10.3

### DSMR-reader platform

Other

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. 

Je kunt alle statistieken achteraf aanpassen via de admin URLs:
- `/admin/dsmr_stats/daystatistics/`
- `/admin/dsmr_stats/hourstatistics/`

De eerste is voor de totalen in het Archief, de andere voor de grafieken van een dag.
