### ISSUE TITLE
🙋data opschoning

### ISSUE THREAD

**Issue by style2k** [dsmrreader/dsmr-reader#1854]
### Description

![image](https://github.com/dsmrreader/dsmr-reader/assets/55606882/248052b8-0b20-4273-a19d-6771554ae4b0)

ik krijg deze melding en nu heb ik al een tijd geleden dataopschoning ingeschakeld maar deze melding blijft komen. 

### DSMR-reader version

5.10.3

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
https://github.com/dsmrreader/dsmr-reader/issues/1222#issuecomment-736754851
