### ISSUE TITLE
Postgesql error🙋

### ISSUE THREAD

**Issue by brugk000** [dsmrreader/dsmr-reader#1862]
### Description

Ik krijg deze foutmelding:
2023-05-31 09:02:36.815 CEST [73062] ERROR:  nextval: reached maximum value of sequence "dsmr_mqtt_message_id_seq" (2147483647)

### DSMR-reader version

docker tatest

### DSMR-reader platform

Docker (e.g. Xirixiz)

**Comment by brugk000** [comment]
Ik ben wat verder in de foutmeldingen gedoken en denk dat het te maken heeft met het MAXvalue van de in de fout genoemde sequence. Heb nu mijn mqtt verbinding uitgevinkt en kijk of dat misschien een oplossing biedt

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Je bent de eerste die hier tegenaan loopt en dat zou betekenen dat je al ruim 2 miljard MQTT berichten via DSMR-reader hebt verstuurd. Ik denk dat de fix voor nu is de tabel leeggooien en de sequence (ID teller) weer te resetten naar 1. Ik heb alleen niet zo 1-2-3 de betreffende queries bij de hand voor je. Daar zou ik thuis naar moeten zoeken en proberen.

**Comment by brugk000** [comment]
Is gelukt. pgAdmin4 gebruikt om de database te benaderen. Tabel leeggemaakt en de teller op 1 gezet.
Zal kijken of dit de oplossing is

**Comment by dennissiemensma** [comment]
Ik neem aan dat het gelukt is?

Gebruik je trouwens MQTT in DSMR-reader met een per-veld topic? Want dat zou wel deels verklaren dat je aan de limiet komt, al is 2+ miljard berichten echt heel heel veel

**Comment by brugk000** [comment]
De DSMR integratie in Home Assistant werkt met split mqtt topics. Dat zijn er idd veel

**Comment by dennissiemensma** [comment]
Wellicht dat ik dan DSMR-reader moet overzetten naar UUID's ipv numerieke ID's. Dat is wel meer best practice, maar helaas ook niet heel triviaal om "even" te doen. Wellicht ooit.

**Comment by brugk000** [comment]
Snap ik. Ik ken nu de oplossing dus ik kan weer verder. In ieder geval bedankt voor het meedenken en voor de ontwikkeling van dit mooie product.

**Comment by 786534786** [comment]
Ik heb nu ook dit issue. 
Het zou enorm helpen als iemand de queries heeft om de betreffende tabel leeg te maken en de sequence naar 1 te zetten. Bedankt alvast. 

Nevermind sql statement is volgens mij:

TRUNCATE dsmrreader.dsmr_mqtt_message RESTART IDENTITY;

**Comment by dennissiemensma** [comment]
Is het gelukt @786534786?

**Comment by 786534786** [comment]
> Is het gelukt @786534786?

Ja met statement zoals toegevoegd in mijn post. Wellicht heeft iemand anders er ook nog iets aan.

**Comment by brugk000** [comment]
Bedankt voor de query. Ik deed het nogal omslachtig via pgAdmin4.

**Comment by brugk000** [comment]
Terug van vakantie en de query geprobeerd in een sql window in pgAdmin4.
Deze moest in uitbreiden met het schema in de database: TRUNCATE dsmrreader.public.dsmr_mqtt_message RESTART IDENTITY;

**Comment by davidvf** [comment]
I just ran into this as well...
Below the oneliner i used to fix the error in a docker environment.

```
sudo docker exec -t <POSTGRES CONTAINER NAME> psql --host=127.0.0.1 --port=5432 --dbname=dsmrreader --username=dsmrreader -c 'TRUNCATE dsmrreader.public.dsmr_mqtt_message RESTART IDENTITY'
```

**Comment by roelbeun** [comment]
just had this issue, the query from David worked. Something to be resolved in a future version?

**Comment by dennissiemensma** [comment]
@Ruvetuve I could fix it, but it would mean that the change is backward-incompatible, as the integer ID field will be replacing by a (in JSON) string type UUID. 

I'll have a look and decide if I'll change it with DSMR-reader v6, which might be the best moment since it's incompatible anyway.

**Comment by dennissiemensma** [comment]
I think I'll just bump it to a [bigger field](https://docs.djangoproject.com/en/6.0/ref/models/fields/#bigautofield) instead, which would be a 64bit int, resulting in `9,223,372,036,854,775,807` values compared to `2,147,483,647` now. Should also make it less incompatible
