### ISSUE TITLE
💡Support dynamic energy pricing contracts

### ISSUE THREAD

**Issue by Moving4407** [dsmrreader/dsmr-reader#1863]
### Feature

Companies like Tibber offer dynamic energy pricing, support that would be valuable to add:
- Current cost per kWh (based on the hour of the day) 
- Cost per kWh per hour for the day
- Cost per kWh per hour in live graph
- Cost per kWh per hour in archive (this is not possible in the Tibber app so there's no way to check if the daily cost was calculated correctly)
- Monthly cost
Information can be retrieved from their API

**Comment by dennissiemensma** [comment]
#1783
