### ISSUE TITLE
💡API Endpoint voor maandelijks verbruik

### ISSUE THREAD

**Issue by wimhaanstra** [dsmrreader/dsmr-reader#1869]
### Feature

Binnen Home Assistant zou ik graag de maandelijkse verbruiken in een grafiek tonen. Nu ben ik door de API documentatie aan het bladeren, maar volgens mij wordt dit op dit moment nog niet ondersteund.

Wat ik zoek is een API call, welke per maand statistieken terug levert. Dus verbruik, teruglevering en eventueel gas verbruik.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. DSMR-reader registreert geen gegevens per maand, dus die zijn ook niet via de API op te vragen.

Je kunt kijken of #1291 je een alternatief biedt.

**Comment by wimhaanstra** [comment]
@dennissiemensma Thanks voor je reply, maar het ging me om het ontsluiten van de gegevens welke via de `Archive` pagina beschikbaar zijn.

**Comment by wimhaanstra** [comment]
Ah, het ziet er naar uit dat ik gewoon dit kan mis/gebruiken:

`https://<domain>/archive/xhr/graphs?date=2023-05-01&level=months`

**Comment by dennissiemensma** [comment]
Je kunt voorlopig die XHR-requests ervoor misbruiken, met de kanttekening dat ik die niet compatible houd in toekomstige releases. Echter zie ik dat niet op korte termijn gebeuren.
