### ISSUE TITLE
🙋dropbox

### ISSUE THREAD

**Issue by style2k** [dsmrreader/dsmr-reader#1871]
### Description

![image](https://github.com/dsmrreader/dsmr-reader/assets/55606882/8eca518f-daed-4e6b-8105-2103e25da2e1)

wat is dit ? waarom worden er geen backups meer gemaakt op dropbox?????

![image](https://github.com/dsmrreader/dsmr-reader/assets/55606882/7f92764b-808d-49b6-8586-a195f1971ab6)

en dit staat er ook al een hele tijd terwijl ik die optie aangepast heb ????????

### DSMR-reader version

 v5.10.3

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
Je kunt Dropbox opnieuw instellen als die ontkoppeld raakt

**Comment by dennissiemensma** [comment]
Voor dataopschoning zie https://github.com/dsmrreader/dsmr-reader/issues/1854#issuecomment-1546628664
