### ISSUE TITLE
🙋dsmr reader resetten

### ISSUE THREAD

**Issue by D3nn1zp** [dsmrreader/dsmr-reader#1881]
### Description

Goedemorgen,

Ik gebruik dsmr reader nu voor 2 maanden en het werkt echt top. bedankt daarvoor. 

afgelopen zaterdag is mijn nieuwe contract ingegaan voor 1 jaar. In dsmr kan je idd heel netjes een contract jaar aanmaken en hierop zie ik ook bij contract netjes dat die de dagen bij elkaar optelt. Maar ik wil alle waardes in dsmr resetten naar nul. Dit omdat ik in hoas een script heb die doormiddel van dsmr uit kan rekenen hoeveel ik per dag per maand en per jaar kwijt ben aan kosten en de zonnepanelen en verbruik van elkaar aftrekt.

Nu zit ik met nieuwe contract en die 2 maanden en dat is voor de berekening niet juist.

Is er niet ergens in dsmr een reset knop die zorgt dat ik vanaf begin opnieuw start. Mocht het er wel zijn. Ik kan het niet vinden.

Bedankt

Groeten, 

Dennis

### DSMR-reader version

5

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
Als je de contractprijzen op 0 zet, kun je dit daarna proberen: https://dsmr-reader.readthedocs.io/en/v5/how-to/troubleshooting/recalculate-prices.html

Zo niet, dan zal ik kijken hoe je dit via een query in de database kan doen.

**Comment by D3nn1zp** [comment]
Bedankt, Dat zou top zijn Dennis. Je addon werkt echt super goed. Heb je goed gedaan. 

Nu alleen nog even dat ik alles op 0 kan zetten en dan.

**Comment by dennissiemensma** [comment]
Werkt het command uit bovenstaande link dan niet? Als je de contractprijzen niet meer nodig hebt in DSMR-reader, zou ik ze gewoon allemaal verwijderen.

**Comment by D3nn1zp** [comment]
Ja ik heb die contract prijzen juist wel nodig. Het systeem werkt super. Heb het nu 2 maanden draaien. Maar afgelopen week ging me nieuwe contract jaar in en heb dus in dsmr een contract aangemaakt. Maar de waardes van die afgelopen 2 maanden blijven staan. Heb alleen een klein stukje waar die de kwh en gas laat zien die vallen binnen het contract wat ik ingevoerd heb. 
![Screenshot_20230719_230154_Home Assistant](https://github.com/dsmrreader/dsmr-reader/assets/34403768/31eb9bfa-8b6f-4017-8f36-35e7adc18a9a)

![Screenshot_20230719_230220_Home Assistant](https://github.com/dsmrreader/dsmr-reader/assets/34403768/2a641154-7e93-4914-b7aa-583c92e15716)

Zoals je ziet blijft die waardes van afgelopen 2 maanden doorlopen. Dat wil ik juist allemaal op nul. Want nu kan ik niet zien hoeveel geld het jaar daadwerkelijk kost. Kijk maar op de laatste regel voorschot stroom & gas realtime. Door verbruikte kosten huidig jaar van dsmr te gebruiken en die van de voorschot af te trekken. Zie ik altijd hoeveel voorschot er nog is door het jaar heen. 

Die wil ik nog verder uit bereiden met een voorspelling. Maar dat gaat niet omdat die bij het nieuwe contract datum niet op 0 gaat. Maar door loopt met de kuub en kwh.

**Comment by dennissiemensma** [comment]
Bedankt voor je aanvulling. Ik begrijp echter nog niet helemaal wat je wilt. Wil je de contractprijzen op nul of de dagprijzen (Archief + Energiecontracten) van de afgelopen maanden op nul of de dagprijzen (Archief + Energiecontracten) van de afgelopen maanden herberekenen of iets anders?

**Comment by D3nn1zp** [comment]
Het archief op nul. Echt het begin. Net zoals je dsmr voor de eerste keer heb geïnstalleerd. 

Wil schoon schip. Zodat mijn contract jaar klopt qua berekening wat ik dar jaar echt heb verbruikt. Nu zit de afgelopen 2 maanden erbij en dat wil ik verwijderen.

**Comment by dennissiemensma** [comment]
Zie de volgende link. Echter gooi je daar dus alle data mee weg, niet alleen de prijzen, ook de metingen en het archief!  https://github.com/dsmrreader/dsmr-reader/issues/809#issuecomment-568563028

**Comment by D3nn1zp** [comment]
Dat is juist de bedoeling voor deze keer. Factory reset zegmaar. 

Bedankt voor je reacties

**Comment by dennissiemensma** [comment]
Prima. Deze is zelfs nog wat recenter: https://github.com/dsmrreader/dsmr-reader/issues/1836#issuecomment-1510386355

**Comment by D3nn1zp** [comment]
Hoi Dennis,

Ik heb het geprobeert. Maar alles blijft gewoon erin staan. Heb zelf het stukje gedaan van jou handleiding waarbij staat warning hierdoor verwijder je alle data. Nou niet bij mij dus. In hoas blijft alle verbruikte kwh en gas kuub gewoon staan.

Data verwijderen is goed beveiligd.

**Comment by dennissiemensma** [comment]
DSMR-reader doet niets met Home Assistant. Als je de gegevens niet meer ziet in DSMR-reader maar wel in HA, dan zul je daar ook handmatig de gegevens moeten verwijderen.

**Comment by D3nn1zp** [comment]
Ja de pest is dat de waardes gewoon in dsmr blijven staan. Ik heb die sudo su script gedaan. Maar alles blijft staan. Ook in dsmr webpagina.

**Comment by dennissiemensma** [comment]
Welke output krijg je bij het uitvoeren van de delete queries?

**Comment by D3nn1zp** [comment]
Ik krijg dit te zien als ik het invoer. Ik doe iets verkeerd.


![psql](https://github.com/dsmrreader/dsmr-reader/assets/34403768/7253c41b-7b2e-4470-b5c2-6011342f86c9)

**Comment by dennissiemensma** [comment]
Die meldingen lijken goed. Wat zie je hier?

```
sudo su - postgres
psql dsmrreader

select count(id) from dsmr_datalogger_dsmrreading;
select count(id) from dsmr_consumption_electricityconsumption;
select count(id) from dsmr_consumption_gasconsumption;
select count(id) from dsmr_consumption_quarterhourpeakelectricityconsumption;
select count(id) from dsmr_datalogger_meterstatistics;
select count(id) from dsmr_stats_daystatistics;
select count(id) from dsmr_stats_electricitystatistics;
select count(id) from dsmr_stats_hourstatistics;
```

**Comment by D3nn1zp** [comment]
Als ik naar het ip adres ga en inlog met de inloggegevens. Dan krijg ik onderstaand te zien. Die zelfde link heb ik in home assistant als sidebar. Daar blijven de gegevens staan. 

Dat is toch raar. Het is toch de zelfde ip adres waar naar gekeken wordt. Wat moet ik nu doen? Dsmr reader verwijderen in home assistant en daarna weer installeren. 

Wat ik nu zie staan als ik naar het ip adres ga. Zoals de afbeelding. Daar gaat die nu ook niet meer opnieuw het stroom en gas berekenen. Dit blijft er staan.

![Screenshot_20230802_215249_Samsung Internet](https://github.com/dsmrreader/dsmr-reader/assets/34403768/1918af77-12e8-45e9-a683-3dd5e57d060a)

**Comment by dennissiemensma** [comment]
Wat krijg je uit bovenstaande queries? Als de gegevens weg zijn zou je wel tijdelijk de melding uit je screenshots moeten krijgen, dat is de beginstaat

**Comment by D3nn1zp** [comment]
als ik die queries doe dan krijgt ik dit:


 count
     0
(1 row)

Maar hij is al vanaf 0 aan het tellen. Heb in dsmr alles gereset. Rare is dat als ik naar het ip adres ga dan blijft die aangeven geen gegevens gevonden. Wat jij zegt de beginstaat. Maar in home assistant heb ik dsmr als sidebar staan en daar teld die wel vanaf 0 en geeft die data door.

Het is gelukt. Super bedankt voor je input.
