### ISSUE TITLE
Grafiek: Niet aanwezige metingen weergeven

### ISSUE THREAD

**Issue by jicho** [dsmrreader/dsmr-reader#1885]
### Feature

Wanneer je door een storing (langer dan 1 minuut) bij het ontvangen van telegrammen, herstart, database upgrade, of een andere oorzaak geen metingen binnen krijgt, dan zie je dit niet terug in de live grafieken. Alle meetpunten sluiten netjes aan alsof ze allemaal opvolgend zijn terwijl dat niet het geval is.

Zou het mogelijk zijn om in de live grafieken op uitval momenten wel de tijden neer te zetten, maar dan zonder meetpunten? Vanuit grafiek en overzichtsoogpunt lijkt me dat wat logischer.

Zelf zou ik aan een soortgelijke weergaven denken:

![image](https://github.com/dsmrreader/dsmr-reader/assets/610740/8d7b51dc-32b5-4675-9ee3-b059a7ef3811)

'k Kan niet een soort gelijke vraag vinden binnen de "issues", hopelijk is het geen dubbel verzoek 🤞 

Tot slot... dank voor al het werk dat je in DSMR-reader steekt!

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Je kunt het beste #1278 volgen, al zal die niet snel opgepakt worden.
