### ISSUE TITLE
Suggestie voor de style.css: 💡

### ISSUE THREAD

**Issue by heyudude** [dsmrreader/dsmr-reader#1893]
### Feature

Na aanpassing van de style sheet (style.css) ziet het helder groene teruglever label er wat beter leesbaar uit (vind ik tenminste): 
![image](https://github.com/dsmrreader/dsmr-reader/assets/102884/b0d01e14-42db-4bc1-acea-a489f997ddd0)

Is dat ook in de settings aan te passen net zoals de grafiek kleuren? Zo te zien niet.
Ik heb de 30% gepakt, iets donkerder met een wit font, in de witte en zwarte schema's:
![image](https://github.com/dsmrreader/dsmr-reader/assets/102884/0cd7772b-47f4-4f38-a1ba-d5aaddbdaf66)

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik denk dat je het beste een browser-plugin zoals Stylish kan gebruiken. Dat is veel makkelijker voor dit soort (persoonlijke) voorkeuren. Het instellen van de grafiekkleuren binnen DSMR-reader is vooral omdat er in sommige gevallen 6 lijnen in 1 grafiek kunnen komen. En dat was dan doorgetrokken...

**Comment by heyudude** [comment]
klopt het is subtiel en persoonlijk. Vandaar wellicht een setting in de configuratie als idee, een browser plugin is lastig met meerdere computers en laptops en een mobiele variant.
