### ISSUE TITLE
💡Is there a way to look at the live graph but for historical data?

### ISSUE THREAD

**Issue by jorkzijlstra** [dsmrreader/dsmr-reader#1910]
### Question

Sorry the create discussion button seems to be missing and can't ask it there.

I have never had the need to enable retention and still have all data available in the db. It curently contains alsmost 5 years of data and performance is no issue what so ever.

In the archive you calculate the hour / dayly stats etc for quick access for that particular use case. It only shows data at that granularity.

I have found myself a number of time to want to go back more than 24 hours in the "live graph" and was wondering if there is such an option to do so.

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Deze optie zit er niet in en gaat er waarschijnlijk ook niet komen, gezien het gros van de gebruikers de standaardretentie gebruikt. DSMR-reader is meer gemaakt voor globale indicaties en inzicht.

Wat je misschien wel kunt doen is kijken of je de data naar een andere timeseries database of iets kan exporteren en visualiseren. Dat is er ook wat meer geschikt voor qua performance en opslag en dan kun je doorgaans ook wat specifiekere vraagstukken beantwoorden of query'en. 
Nadeel is uiteraard wel dat je er zelf in zal moeten duiken, afhankelijk van je technische kennis. Al denk ik dat er wel meerdere gebruikers zijn die zoiets hebben gedaan. De data in de DSMR-reader-database qua metingen is verder vrij plat, dus zou goed te exporteren moet zijn.
