### ISSUE TITLE
Notities maken per maand/jaar

### ISSUE THREAD

**Issue by niekniek89** [dsmrreader/dsmr-reader#1925]
### Description

Goedemorgen,

Wellicht niet heel spannend (en geen idee of het iets toevoegt).
Ik zie nu dat je per dag een notitie kan maken in het archief van DSMR Reader.
Is het ook mogelijk om dit beschikbaar te maken voor de maanden/jaren?

PS: Is overigens geen BUG, maar krijg het label niet weg :).

### DSMR-reader version

v5.10.3

### DSMR-reader platform

Docker (e.g. Xirixiz)

**Comment by dennissiemensma** [comment]
Bedankt voor je suggestie. Ik denk dat het relatief veel werk is, gezien de notities ook qua opslag aan een datum hangen en niet perse aan een maand of periode. 
Het is opzich een leuk idee, alleen gezien alle andere prioriteiten denk ik niet dat het haalbaar is.

**Comment by niekniek89** [comment]
Dank voor je antwoord.
Ik kan zelf niet bepalen wat wel/niet veel werk is, maar begrijp de keuze zeker wel.
Mocht het ooit eens lukken, zou het inderdaad een leuke toevoeging zijn, maar niet noodzakelijk.

**Comment by dennissiemensma** [comment]
Ik sluit deze omdat ik weet dat ik er uiteindelijk niet aan toe ga komen.
