### ISSUE TITLE
🙋 Fresh install of data_logger (v5) gives module 'decouple' has no attribute 'Choices'

### ISSUE THREAD

**Issue by MrHappy** [dsmrreader/dsmr-reader#1933]
### Description

Yesterday installed data_logger v4 by accident, but worked fine (except for delivering data to home assistant).
I noticed I did not have the most recent version and followed these instructions.
Now I receive the notification (after enabling debug-logging) that decouple has no Choices-attribute.
What did I miss (or is missing from the installation instructions)?

### DSMR-reader version

5

### DSMR-reader platform

Native (e.g. manual installation)

### Debug info dump

```shell
[2023-12-08 12:38:25.585873] Starting...
Traceback (most recent call last):
  File "/home/dsmr/dsmr_datalogger_api_client.py", line 236, in <module>
    main()
  File "/home/dsmr/dsmr_datalogger_api_client.py", line 133, in main
    cast=decouple.Choices(["serial", "ipv4"]),
AttributeError: module 'decouple' has no attribute 'Choices'
```

**Comment by dennissiemensma** [comment]
De twee versies zijn niet compatible met elkaar qua config en/of dependencies. Je kunt het beste de v5-variant installeren:

https://dsmr-reader.readthedocs.io/en/v5/how-to/installation/remote-datalogger.html

**Comment by dennissiemensma** [comment]
Decouple is onderdeel van: https://dsmr-reader.readthedocs.io/en/v5/how-to/installation/remote-datalogger.html#remote-datalogger-device
