### ISSUE TITLE
not getting my plugin to run🙋

### ISSUE THREAD

**Issue by gfi63** [dsmrreader/dsmr-reader#1934]
### Description

I had DSMR running on my Pi but the Pi got some network errors, after fixing those, it seems I do not get my plugin (https://gist.github.com/steffjenl/31bd083eeb9d0be04375b7695b9f2eaf) not running anymore. If I try to execute the ./pst-deploy.sh, it starts screaming the following
 --- Checking whether '.venv' VirtualEnv is activated.
     [i] ----- Activating '.venv' VirtualEnv...
./post-deploy.sh: line 10: /root/dsmr-reader/.venv/bin/activate: No such file or directory

     [!] Aborting, failure switching to '.venv' VirtualEnv (is it installed properly?)

I deleted the container and pulled it again, but still the same problem.

Can anyone tell me what I am doing wrong?
PS I am running the latest version, DSMR-reader: v5.10.4

Thanks in advance for any help
Gerrit 

### DSMR-reader version

5,10,4

### DSMR-reader platform

Docker (e.g. Xirixiz)

### Debug info dump

```shell
DSMR-READER
    App / Python / Database                                                    v5.10.4 / v3.12.0 / postgresql
    BE sleep / DL sleep / Retention / Override                                    5.0s / 10.0s / 672h / False
    Latest telegram version read / Parser settings                                                 "50" / "4"

DATA
    Telegrams total (est.)                                                                             197230
    Consumption records electricity / gas (est.)                                                64617 / 39598
```

**Comment by dennissiemensma** [comment]
Plugins draaien in de virtualenv van DSMR-reader zelf. Ik denk dat je de plugins-map moet mounten als volume: https://github.com/xirixiz/dsmr-reader-docker#dsmr-reader---plugins

Het deploy-script werkt sowieso niet in Docker, omdat de container op een andere manier is ingericht (zou ook niet nodig moeten zijn). Zie bovenstaande link en dat zou dan afdoende moeten zijn met de envvars.

**Comment by gfi63** [comment]
Na veel zoeken en proberen, ben ik erachter gekomen dat het probleem niet zit in het laden van de plugin, maar in de connectie naar de ontvanger... ik heb nu de volgende regels in de logs gevonden:
dsmr_1    | 2023-12-12 08:21:30,036 ERROR    update_checker run                              18 | Update checker: Error HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/dsmrreader/dsmr-reader/releases (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x72f811f8>: Failed to establish a new connection: [Errno -3] Try again'))
dsmr_1    | ERROR:root:HTTPSConnectionPool(host='5f479bf7547cba0c68590b39.connect.athom.com', port=443): Max retries exceeded with url: /api/app/com.p1/update/dsmrreader (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x72f354b0>: Failed to establish a new connection: [Errno -3] Try again'))

Tja verder zoeken waar dit fout gaat. In ieder geval bedankt voor de hulp hier.
