### ISSUE TITLE
🚨Afwijking in maandtotalen gas

### ISSUE THREAD

**Issue by JohanvanLoon** [dsmrreader/dsmr-reader#1936]
### Description

Bedankt voor jullie geweldige dsmrreader. Ik gebruik dit al enkele jaren tot volle tevredenheid. Wat mij opvalt is ,dat het maandtotaal van de gasmeting telkens +/- 6- 8 m3  minder is, dan mijn eigen meting (meterstand aan einde maand- meterstand begin maand. Sinds kort heb ik DSMRreader middels MQTT gekoppeld aan Home Assistant. In HA worden de maandtotalen van de gasmeting wel correct weergegeven.  De meterstand van de gasmeter wordt in DMSRreader - statistieken wel correct weergegeven. 

### DSMR-reader version

5.10.4

### DSMR-reader platform

None

**Comment by dennissiemensma** [comment]
Bedankt voor je melding, dit is een bekende bug in #1770
