### ISSUE TITLE
🙋Verbinding tussen dsmrreader en database

### ISSUE THREAD

**Issue by mbouwm** [dsmrreader/dsmr-reader#1949]
### Description

Dag,
Het is me gelukt om zowel de dsmrreader en de dsmrdb een zelf gekozen ip adres te geven in een docker macvlan.
Omdat de dsmrreader zoekt naar het ip-adres van dsmrdb, heb ik deze ingegeven in mijn dns-server. En dat werkt.
In mijn dns server zie ik veel hits hiervan, en dat wil ik stoppen.
Dat kan door direct ergens in de dsmrreader het ip addres van de database te zetten, maar ik weet niet waar.
Andere optie is om de etc/hosts file van de dsmrreader aan te passen, en dat schijnt wel te werken.
Echter na een reboot is mijn aangepaste etc/hosts file overschreven.
Kun je mij aangeven hoe ik het beste kan oplossen?
Mvg,
Martien

### DSMR-reader version

5.10.4

### DSMR-reader platform

None

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Je kunt dit het beste bij het DSMR-reader Docker project vragen.

- https://github.com/xirixiz/dsmr-reader-docker/issues

Als het goed is hoef je met Docker Compose binnen hetzelfde container netwerk geen dingen te doen met hostfiles en zorgt die zelf voor die DNS resolutie. In theorie.
