### ISSUE TITLE
Getoonde waarde van Current Power Return L1 - L3 en Current Power Usage L1 - L3 1000x te groot.🚨

### ISSUE THREAD

**Issue by Hveen28** [dsmrreader/dsmr-reader#1952]
### Description

De getoonde waarde van Current Power Return L1, L2, L3 en van Current Power Usage L1, L2 en L3 zijn 1000x te groot. Bijvoorbeeld 48.000W is in werkelijkheid 48W

### DSMR-reader version

Ik heb DSMR-Reader gisteren geinstalleerd

### DSMR-reader platform

Other

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Zou je een telegram willen toevoegen? En een [debug info](https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/debug-info-dump.html)?
