### ISSUE TITLE
Installing DSMR on proxmox: restart of nginx failed

### ISSUE THREAD

**Issue by Koen568** [dsmrreader/dsmr-reader#1953]
### Description

Hallo, 
ik probeer DSMR te installeren op een bestaande NUC met proxmox.  Ik installeerde een nieuwe VPE de daar daarin Debian 12.
Ik heb weinig kennis van software en volgende de installatie DSMR-reader v5 alles verliep vlot tot de herstart van nginx.
Hier weet ik geen raad mee. Kan iemand me zeggen hoe ik tot de logs, oorzaak,... kom om dit op te lossen?  Alvast bedankt, Koen

### DSMR-reader version

DSMR V5 on Debian 12

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
https://dsmr-reader.readthedocs.io/en/v5/how-to/troubleshooting/logfiles.html

en

```
/var/log/nginx/*
```
