### ISSUE TITLE
MQTT messages are not published anymore🙋

### ISSUE THREAD

**Issue by RobvanHamersveld** [dsmrreader/dsmr-reader#1954]
### Description

I've setup mqtt messaging to integrate with Home Assistant. I'm using Telegram split topic. This setup worked for over 3 years and has now stopped. I've enabled debug logging and the following error is logged:

`publish_split_topic_meter_statistics() failed: nextval: reached maximum value of sequence "dsmr_mqtt_message_id_seq" (2147483647)` 

### DSMR-reader version

5.10.4

### DSMR-reader platform

Docker (e.g. Xirixiz)

### Debug info dump

```shell
DSMR-READER
    App / Python / Database                                                    v5.10.4 / v3.12.0 / postgresql
    BE sleep / DL sleep / Retention / Override                                    1.0s / 0.5s / 2016h / False
    Latest telegram version read / Parser settings                                                 "50" / "4"

DATA
    Telegrams total (est.)                                                                            7175572
    Consumption records electricity / gas (est.)                                               177944 / 79126

POSTGRESQL SIZE OF LARGEST TABLES (> 500 MB)
    public.dsmr_datalogger_dsmrreading                                                                5446 MB
```

**Comment by dennissiemensma** [comment]
https://github.com/dsmrreader/dsmr-reader/issues/1862#issuecomment-1584937503
