### ISSUE TITLE
DSMR-reader remote uitlezen (door domoticz)

### ISSUE THREAD

**Issue by githubbersky** [dsmrreader/dsmr-reader#1956]
### Communicatietaal / Language

🇳🇱 Nederlandstalig

### Help yourself

- [X] I've checked [the how-to guides](https://dsmr-reader.readthedocs.io/nl/v5/how-to/index.html)
- [X] I've checked previous [questions](https://github.com/dsmrreader/dsmr-reader/discussions)
- [X] I've checked (recent) [previous issues](https://github.com/dsmrreader/dsmr-reader/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc) and their solutions
- [X] I've checked the [logfiles](https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/logfiles.html) *(when applicable)*

### Inquiry

Feature or idea

### Description

Hoi! Prachtig programma, werd mij op gewezen omdat na reinstall ser2net net meer (goed) aan de praat te krijgen was.
In mijn setup leest DSMR-reader de P1 uit en dat gaat naar HA. Daarnaast draaien er nog twee Domoticz servers. Is er een mogelijkheid om de serieele info ook aan te bieden op een (TCP)poort? Of via de API? (die laatste vereist wel een studie hier)

### DSMR-reader version

v5.10.4

### DSMR-reader platform

Docker (e.g. Xirixiz's DSMR-reader Docker)

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Ik denk dat je het beste alsnog gebruik kan maken van `ser2net`, omdat erg low-level is, meerdere clients ondersteunt en makkelijk te installeren is. DSMR-reader kan die ook uitlezen.

Via de API kun je zoiets doen, maar je krijgt daar niet het originele telegram uit. Die slaat DSMR-reader niet op:
```
# Meest recente meting:
GET /api/v2/datalogger/dsmrreading?ordering=-timestamp&limit=1
```

**Comment by githubbersky** [comment]
Krijg ik dan geen interface conflict met DSMR-reader die dezelfde USB0 uitleest?
Bedankt voor je reply Dennis!

**Comment by dennissiemensma** [comment]
Je kunt dat als het goed is configureren in `/etc/ser2net.conf`

Bijvoorbeeld voor poort 4000 exposen met 3 max connecties. 
```
4000:telnet:600:/dev/ttyUSB0:115200 8DATABITS NONE 1STOPBIT banner max-connections=3
```

De banner kan eventueel ook nog uit dacht ik. Die wordt bij het eerste bericht eenmalig teruggegeven en "verpest" dat telegram. Maar de eerstvolgende daarna zou wel goed moeten zijn,


Zie https://manpages.debian.org/experimental/ser2net/ser2net.8.en.html `max-connections`

**Comment by githubbersky** [comment]
Ja precies, met SER2NET v3 ging dat wel, maar met versie 4 is het een yml config geworden, die syntax is nogal veranderd. Ik ga hier nog wel eens mee stoeien! Nogmaals dank Dennis! :D
