### ISSUE TITLE
API not working 404: not found

### ISSUE THREAD

**Issue by poelie83** [dsmrreader/dsmr-reader#1972]
### Communicatietaal / Language

🇳🇱 Nederlandstalig

### Help yourself

- [X] I've checked [the how-to guides](https://dsmr-reader.readthedocs.io/nl/v5/how-to/index.html)
- [X] I've checked previous [questions](https://github.com/dsmrreader/dsmr-reader/discussions)
- [X] I've checked (recent) [previous issues](https://github.com/dsmrreader/dsmr-reader/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc) and their solutions
- [X] I've checked the [logfiles](https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/logfiles.html) *(when applicable)*

### Inquiry

Help with installation or upgrade

### Description

Ik heb een nieuwe schone installatie van HAOS 2024.3.0.
hier draait TimescaleDB en vervolgens DMSR Reader op, alles draait probleemloos en DSMR Reader werkt naar behoren.

Ik wil oude data van Domoticz importeren via de API, API geactiveerd via de configuratie echter zonder succes.
Op geen enkele wijze krijg ik toegang tot de URL: http://192.168.0.150:8123/api/v2/datalogger/dsmrreading wat ik ook doe. 
Het IP adres klopt, het poortnummer klopt en zelfs de postman collection via de API documentatie pagina wordt wel geladen. 
ik krijg 404: Not Found

Add-on al een keer verwijderd en opnieuw geïnstalleerd zonder succes. 

### DSMR-reader version

v5.10.3

### DSMR-reader platform

Other (e.g. Home Assistant Plugin)

### Optional: Debug info dump (of DSMR-reader)

```shell-script
DSMR-READER
    App / Python / Database                                                    v5.10.3 / v3.11.3 / postgresql
    BE sleep / DL sleep / Retention / Override                                     1.0s / 5.0s / 672h / False
    Latest telegram version read / Parser settings                                                 "50" / "4"

DATA
    Telegrams total (est.)                                                                               1413
    Consumption records electricity / gas (est.)                                                     107 / -1

UNRESOLVED ISSUES
    Geen dagstatistieken gevonden                                                                          nu
```

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Als je hostnaam + poort klopt, zie ik niet zo 1-2-3 waar het aan ligt, gezien dat pad goed lijkt.

Je kunt nog evenpolsen bij de auteur van de HASS plugin of die nog een suggestie heeft: https://github.com/sanderdw/hassio-addons/issues

Je zou namelijk sowieso iets terug moeten krijgen als het goed werkt, zelfs via de browser:
```
{"detail":"Invalid auth key"}
```
