### ISSUE TITLE
Tijd van upload naar minder gas instelbaar maken

### ISSUE THREAD

**Issue by wderuijter** [dsmrreader/dsmr-reader#1978]
# Opgelost via https://github.com/dsmrreader/dsmr-reader/issues/1977#issuecomment-2016448156

----

### Communicatietaal / Language

🇳🇱 Nederlandstalig

### Help yourself

- [X] I've checked [the how-to guides](https://dsmr-reader.readthedocs.io/nl/v5/how-to/index.html)
- [X] I've checked previous [questions](https://github.com/dsmrreader/dsmr-reader/discussions)
- [X] I've checked (recent) [previous issues](https://github.com/dsmrreader/dsmr-reader/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc) and their solutions
- [X] I've checked the [logfiles](https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/logfiles.html) *(when applicable)*

### Inquiry

Feature or idea

### Description

Naar aanleiding van onderstaande email van mindergas.nl, is het mogelijk om het via configuratie mogelijk te maken om af te wijken van de 00.00 uur data upload?
Ik overzie niet wat de gevolgen hiervan zouden kunnen zijn.

> Beste MinderGas deelnemer,

> 
> Je maakt gebruik van de Meterstand API van MinderGas.nl om dagelijks je meterstand te uploaden.
> 
> Op dit moment posten veel gebruikers hun meterstand om precies 0.00 uur naar MinderGas (of vlak ervoor of vlak erna). De MinderGas.nl website is echter niet ontworpen om vele honderden verzoeken binnen een minuut te verwerken. Deze piekbelasting kan leiden tot response code 503 'Server unavailable'. De meterstand wordt in dat geval niet goed opgeslagen.
> 
> Indien je dit wilt voorkomen en je meterstand betrouwbaar wilt uploaden, doe dan de upload op een willekeurig gekozen moment tussen 0.05 en 1.00 uur (of op een ander tijdstip gedurende de dag). Je zult hiervoor je script moeten aanpassen.
> 
> Zie ook de [API documentatie](https://mindergas.nl/member/api).
> 
> Met vriendelijke groeten, David MinderGas.nl

### DSMR-reader version

v5.11

### DSMR-reader platform

Docker (e.g. Xirixiz's DSMR-reader Docker)

**Comment by dennissiemensma** [comment]
Zie ook:
- #1977
