### ISSUE TITLE
Database grootte waarschuwing

### ISSUE THREAD

**Issue by JaroNoor** [dsmrreader/dsmr-reader#1985]
### Language / Voertaal

🇳🇱 Nederlandstalig

### Help yourself

- [X] I've checked [the how-to guides](https://dsmr-reader.readthedocs.io/nl/v5/how-to/index.html)
- [X] I've checked previous [questions](https://github.com/dsmrreader/dsmr-reader/discussions)
- [X] I've checked (recent) [previous issues](https://github.com/dsmrreader/dsmr-reader/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc) and their solutions
- [X] I've checked the [logfiles](https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/logfiles.html) *(when applicable)*

### Inquiry

Feature or idea

### Description

Hi Dennis,

Ten eerste: ik gebruik DSMR-reader al 3 jaar bijna: top! Inmiddels heb ik dus de bekende database-grootte waarschuwing sinds die 950 MB is. Mijn Pi heeft een 64 GB-kaartje, ik maak mij hier dus totaal geen zorgen over.

Kan ik de waarschuwing disablen ergens?

### DSMR-reader version

v5.11

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
Ja, zie https://dsmr-reader.readthedocs.io/nl/v5/reference/env-settings.html#dsmrreader-suppress-storage-size-warnings
