### ISSUE TITLE
[vraag] nieuwe meter, alles gereset

### ISSUE THREAD

**Issue by remb0** [dsmrreader/dsmr-reader#2018]
### Language / Voertaal

🇳🇱 Nederlandstalig

### Help yourself

- [X] I've checked [the how-to guides](https://dsmr-reader.readthedocs.io/nl/v5/how-to/index.html)
- [X] I've checked previous [questions](https://github.com/dsmrreader/dsmr-reader/discussions)
- [X] I've checked (recent) [previous issues](https://github.com/dsmrreader/dsmr-reader/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc) and their solutions
- [X] I've checked the [logfiles](https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/logfiles.html) *(when applicable)*

### Inquiry

Help with installation or upgrade

### Description

Ik heb vandaag een nieuwe meter ontvangen, en de standen zijn naar 0 gereset.
dit betekend dat in dsmr reader nu staat: 

verbruikt: -17.077,963   enz

wat is the way to go om weer vanaf 0 te beginnen maar het wel correct te krijgen?

### DSMR-reader version

5

### DSMR-reader platform

Docker (e.g. Xirixiz's DSMR-reader Docker)

**Comment by dennissiemensma** [comment]
https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/smart-meter-replacement.html

**Comment by remb0** [comment]
thanks!
