### ISSUE TITLE
correctie op 1 dag nar nieuwe meter

### ISSUE THREAD

**Issue by remb0** [dsmrreader/dsmr-reader#2024]
### Language / Voertaal

🇳🇱 Nederlandstalig

### Help yourself

- [X] I've checked [the how-to guides](https://dsmr-reader.readthedocs.io/nl/v5/how-to/index.html)
- [X] I've checked previous [questions](https://github.com/dsmrreader/dsmr-reader/discussions)
- [X] I've checked (recent) [previous issues](https://github.com/dsmrreader/dsmr-reader/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc) and their solutions
- [X] I've checked the [logfiles](https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/logfiles.html) *(when applicable)*

### Inquiry

Help with installation or upgrade

### Description

op maandag 5 auguster heb ik een nieuwe beter gekregen.   
mijn dsmrreading veranderden maar nu krijg ik geen kloppende statistieken meer 

![image](https://github.com/user-attachments/assets/9198e29c-7f49-4e78-b471-ace9a9000fab)
![image](https://github.com/user-attachments/assets/00e28d50-2b4f-41bd-add2-acc63879300a)

Ik heb alleen geen enkel idee hoe en waar ik dit moet corrigeren om weer een kloppend maand/jaar totaal te kunnen zien.

### DSMR-reader version

v5.11

### DSMR-reader platform

Other (e.g. Home Assistant Plugin)

**Comment by dennissiemensma** [comment]
Zie https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/smart-meter-replacement.html

**Comment by remb0** [comment]
dank voor de link. Ik snap dat ik iets moet corrigeren. maar weet niet zeker wat.
de foutieve dag verwijderen?
![image](https://github.com/user-attachments/assets/f0a60af1-32b0-4246-a7c4-3f3136800a60)

of maak ik het dat erger?

**Comment by dennissiemensma** [comment]
Je kunt de foute dagtotalen van de dag van de wissel met de hand op 0 zetten. Of ze zelf uitrekenen voor die dag. Alles na die dag zou verder al goed moeten staan. En vervolgens ook automatisch alle maand en jaar totalen.

**Comment by spiralshapeturtle** [comment]
Ik kreeg vandaag in 2026 een nieuwe meter en heb inderdaad moeten wachten tot 00:00 om de dagtotalen te laten resetten. Daarna stonden heel veel waarden over de afgelopen maand ver in de min, ik heb daarna eergisteren naar vandaag gekopieerd (overtikken) en daarna was alles weer in orde.

https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/smart-meter-replacement.html Deze link zo net even 1 a 2 regels extra uitleg mogen krijgen zoals hierboven, gaan we van een 8 naar een 9 ;-)

**Comment by dennissiemensma** [comment]
@spiralshapeturtle bedankt voor je feedback. Kan het zijn dat je nog DSMR-reader v5 draait? Want dat zijn de oude docs.

De nieuwe staan hier: https://dsmr-reader.readthedocs.io/en/v6/troubleshooting/smart-meter-issues/#smart-meter-replacement

Maar daar heb je uiteraard weinig aan als je op v5 zit. _In v6 is het overigens nog steeds handwerk, dus geen reden om alleen daarvoor te upgraden._
