### ISSUE TITLE
scenario support for heatnet-p1 and electra-p1 and solar panels (via mqtt)?

### ISSUE THREAD

**Issue by pooh22** [dsmrreader/dsmr-reader#2040]
### Language / Voertaal

🇳🇱 Nederlandstalig

### Help yourself

- [X] I've checked [the how-to guides](https://dsmr-reader.readthedocs.io/nl/v5/how-to/index.html)
- [X] I've checked previous [questions](https://github.com/dsmrreader/dsmr-reader/discussions)
- [X] I've checked (recent) [previous issues](https://github.com/dsmrreader/dsmr-reader/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc) and their solutions
- [X] I've checked the [logfiles](https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/logfiles.html) *(when applicable)*

### Inquiry

Feature or idea

### Description

I was wondering if my scenario could be workable with dsmr-reader, but I guess not (https://github.com/dsmrreader/dsmr-reader/issues/429)

I have two "smart" meters with p1 ports (and perhaps in the future a third for water usage?), also I have solar panels.

I have some hacked together scripts that sort of combine this in various dashboards (icinga 1.x, which is old and unsupported, home assistant which doesn't work well together with my hacked scripts, but it sort of works).
Since december 2017 I keep track of my heat usage from the "warmtenet" meter, I have no gas at home. A few years ago the meter was replaced with a "smart" meter, which I can read out using another p1 cable in my pi that I was using already for the electricity.

I thought it would be nice if this could all work in one application that can also keep track of costs, but for that it would be good to incorporate the solar energy produced, in order to keep track of the actual usage, as well as the consumed/delivered power to the net. My SMA inverter is read out using bluetooth on another pi, which sends out mqtt telegrams when it works.

I think this, or similar scenario's, will become increasingly common, as more and more houses are converted to work without gas and also analog meters get replace with meters with p1 ports.

It seems for now this kind of scenario isn't supported, but I don't know of any other projects that would be more suitable to have this...

### DSMR-reader version

v0.0.0

### DSMR-reader platform

Native (e.g. manual installation)

**Comment by dennissiemensma** [comment]
Bedankt voor je suggestie. DSMR-reader beperkt zich tot de slimme meter. 

Voor andere databronnen hebben gebruikers vaak iets als InfluxDB + grafana, ook omdat je dan zelf dashboards kan plotten met whatever je wilt weten (ook zaken buiten de slimme meter, zoals temperatuur/zonnepanelen/etc).
