### ISSUE TITLE
Dag- en maanddata publiceren op MQTT

### ISSUE THREAD

**Issue by ThaStealth** [dsmrreader/dsmr-reader#685]
### Jouw omgeving
* DSMR-reader versie *(rechtsbovenin applicatie zichtbaar)*: `v2.3.3`

### Bug, wens of iets anders
Kun je de maand data (die op de dashboard page onder het knopje "display current month" verstopt is) ook via MQTT naar buiten sturen?

**Comment by dennissiemensma** [comment]
Bedankt voor je suggestie. Ik zet het op de backlog, maar het zal wel een tijd duren voordat ik hier aan toekom.

**Comment by skank01** [comment]
+1 
Per jaar zou ook welkom zijn !!
Beetje gelijkgaand ook met https://github.com/dsmrreader/dsmr-reader/issues/989

**Comment by dennissiemensma** [comment]
Dit issue is nu opgenomen in ##1291.

**Comment by dennissiemensma** [comment]
Dit gaat mee bij de aanstaande v4.13-release. Naast de gegevens via MQTT worden ze ook zichtbaar in het dashboard. Zie #1291 voor meer informatie en screenshots.
