### ISSUE TITLE
Hogere backend process sleep toestaan

### ISSUE THREAD

**Issue by SaturnusDJ** [dsmrreader/dsmr-reader#862]
v3.2

Webinterface - Backend configuration - Backend process sleep.
Een waarde met meer dan 2 decimalen geeft: 'Ensure that there are no more than 2 digits before the decimal point.'
Ik zou hier graag 180 invullen.

**Comment by dennissiemensma** [comment]
Ik heb het veld vergroot voor de volgende release.

**Comment by SaturnusDJ** [comment]
Top, dank.
