### ISSUE TITLE
Exchange of electricity and/or gas meeter.

### ISSUE THREAD

**Issue by Piet-PvdZ** [dsmrreader/dsmr-reader#863]
Recently my electricity meter was changed du to bad RF connections to the Stedin network.
The new meter starts at 00000 but DSMR dit not detect the 0000 value and calculated a huge negative value. The graphs are destroyed du to the large negative number.
A suggestion:
Check the meter serial number from the telegram data and if this is changed ignore the huge negative usage. Or check for negative results and handle accordingly.
Running now DSMR V3.1.0

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Dit is een bekend issue en er staat al een ticket voor om het ooit op te lossen: #507

Voor nu kun je het beste na afloop van de dag handmatig de dagtotalen bijwerken. Dit hoef je maar eenmalig te doen als het goed is. Zie bovenstaand issue voor meer info.

**Comment by Piet-PvdZ** [comment]
Dennis.Dank voor je reactie.Had het ticket #507 niet opgemerkt.Ik wacht een mogelijke oplossing wel af. Hoop dat Stedin niet nogeens komt voor vervanging.Groet.  Piet van der Zanden.
