### ISSUE TITLE
Actuele Amperes weergeven 

### ISSUE THREAD

**Issue by dgeest66** [dsmrreader/dsmr-reader#875]
Ik zou graag ook het actueel gebruik in Ampere per fase zien in dsmr-reader. En deze ook door kunnen zetten via mqtt. 

De applicatie die mijn laadpaal aanstuurt heeft   [https://github.com/snaptec/openWB](https://github.com/snaptec/openWB) deze gegevens nodig heeft. 
Het gaat om de volgende OBIS-codes:
```
1-0:31.7.0(001*A)
1-0:51.7.0(000*A)
1-0:71.7.0(000*A)
```

Kan ik deze zelf toevoegen, of kan de code aangepast worden?

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik zal er op termijn inhoudelijk naar kijken.

Je kunt ook nog overwegen om het zelf uit te lezen met [dsmr_parser](https://github.com/ndokter/dsmr_parser) en daarna direct door te geven aan die andere applicatie. Daar ben je wellicht wat sneller mee geholpen.

**Comment by DarkShadowNight** [comment]
Dit zou een zeer zinnige functionaliteit kunnen zijn, daar je aansluiting beperkt is op stroom en niet op vermogen.
Een kleine grafiek net zoals de spanning zou al een leuke toevoeging zijn.

**Comment by dennissiemensma** [comment]
@dgeest66 @DarkShadowNight ik heb een opzet klaar. Alleen ben ik er nog niet helemaal uit welke grafiekstijl het beste hiervoor is. Hebben jullie input? 

- Bij stacked staan de fasen altijd boven elkaar en kunnen ze elkaar nooit kruizen.
- Bij unstacks gaan ze door elkaar heen en kunnen ze elkaar kruizen wanneer ze wisselend hoger of lager dan elkaar zijn (zie voltages).

Zie de screenshots:

## Stacked bars
![Selection_004](https://user-images.githubusercontent.com/16581744/74971502-84af7780-5420-11ea-8aef-a599c59d4759.png)

## Stacked lines
![Selection_005](https://user-images.githubusercontent.com/16581744/74971504-84af7780-5420-11ea-8e93-476e5a870fc3.png)

## Unstacked lines
![Selection_006](https://user-images.githubusercontent.com/16581744/74971506-85480e00-5420-11ea-96b4-b8d3eacec773.png)

**Comment by dennissiemensma** [comment]
Voor nu in branch klaargezet met stacked bars als voorstel. Wacht op input.

**Comment by dgeest66** [comment]
@dennissiemensma dank, ik zal zsm terugkoppelen

**Comment by Ferryb** [comment]
Ik zou de Ampere's ook fijn vinden naar MQTT. Hopelijk snel een update. :)

**Comment by dgeest66** [comment]
Misschien domme vraag, maar welke stappen moet ik nemen om van de huidige versie naar deze branch te updaten?

**Comment by dennissiemensma** [comment]
Je kunt wisselen met:
```
sudo su - dsmr
git fetch
git checkout -b feature/875-power-current-graph wip/feature/875-power-current-graph
./deploy.sh
```

Zorg er wel voor dat je voor de zekerheid een recente database-backup achter de hand hebt.

**Comment by dennissiemensma** [comment]
Ik heb de branch alvast gemerged naar de release branch. Mocht het nog een ander type moeten worden, dan pas ik het tussendoor nog wel aan.

**Comment by dennissiemensma** [comment]
Uitgebracht in [v3.5](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v3.5.0)

**Comment by Ferryb** [comment]
Dennis, zijn de stoomwaardes nu ook via MQTT te versturen? via gesplitst topic? Ik zie ze er namelijk niet bij staan.

**Comment by dennissiemensma** [comment]
Ik heb daar niet bij stil gestaan. Echter gaat alles dynamisch, dus je kunt kijken of deze mapping voor je werkt:

## JSON
```
phase_power_current_l1 = phase_power_current_l1
phase_power_current_l2 = phase_power_current_l2
phase_power_current_l3 = phase_power_current_l3
```

## Split topic
```
phase_power_current_l1 = dsmr/reading/phase_power_current_l1
phase_power_current_l2 = dsmr/reading/phase_power_current_l2
phase_power_current_l3 = dsmr/reading/phase_power_current_l3
```

Ik zal de beschrijvingen met bovenstaande waardes bijwerken.

**Comment by Ferryb** [comment]
Ook deze werkt inderdaad. Alle waardes worden retained verstuurd.
Dank weer.

**Comment by dgeest66** [comment]
@dennissiemensma , dankjewel voor de toevoeging!

**Comment by dennissiemensma** [comment]
Bijgewerkt in [v3.6](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v3.6.0)

**Comment by RubenDijk** [comment]
Volgens mij zijn de waardes die hij over mqtt weg stuurt geen ampère maar wattage. (versie 3.9.1)

**Comment by RubenDijk** [comment]
![image](https://user-images.githubusercontent.com/18540436/82052397-dd0eb200-96bb-11ea-933b-8403cf382057.png)
![image](https://user-images.githubusercontent.com/18540436/82052441-eb5cce00-96bb-11ea-9dfe-4a5e797e018b.png)

**Comment by dennissiemensma** [comment]
@RubenDijk bedankt voor je melding. 

Kan het zijn dat je in de verkeerde grafiek kijkt? Er staat expliciet Ampere in als ik het hier test. 
Mocht je geen DSMR v5 meter hebben, dan zijn deze gegevens overigens niet beschikbaar.

![Selection_002](https://user-images.githubusercontent.com/16581744/82068021-c1aea180-96d1-11ea-919d-81fe0ed4698a.png)

**Comment by RubenDijk** [comment]
Hallo Dennis,

Ik zie wel Amperes in DSMR-Reader webpage. 
De waarde word niet door gestuurd naar ha (mqtt) De gestuurde waardes zijn wattage per fase
![image](https://user-images.githubusercontent.com/18540436/82074933-c6785300-96db-11ea-8ea8-4a3bc086ec2e.png)
![image](https://user-images.githubusercontent.com/18540436/82075089-fcb5d280-96db-11ea-9fca-984bbb45095d.png)

**Comment by dennissiemensma** [comment]
Als je DSMR-reader al gebruikte voordat v3.5 er was, zul je ze met de hand moeten toevoegen aan de MQTT config. Dat gaat niet automatisch: https://github.com/dennissiemensma/dsmr-reader/issues/875#issuecomment-594137011

**Comment by RubenDijk** [comment]
zo als hier boven zijn de regels toegevoegd.
Heb de supervisor reload en opnieuw opgestart.
De rpi gereboot, DSRM versie nr:5

**Comment by RubenDijk** [comment]
Dennis,

Zou het kunnen dat HA het niet ondersteund?
Mqtt explorer ziet hem wel
![image](https://user-images.githubusercontent.com/18540436/82077014-f5dc8f00-96de-11ea-844c-cbd0e3ad9210.png)

**Comment by dennissiemensma** [comment]
Dat zou kunnen. Ik gebruik zelf geen HA dus ik kan je op dat gebied niet helpen. Je kunt eventueel op het Tweakers forum om hulp vragen.
