### ISSUE TITLE
Huidig tarief aangeven op het dashboard

### ISSUE THREAD

**Issue by ghost** [dsmrreader/dsmr-reader#878]
Is het mogelijk, het huidige tarief aan te geven op het dashboard. Bijvoorbeeld boven rechts naast nu daltarief of piektarief. Of piek of dal, hetgeen op het moment van toepassing is?

**Comment by dennissiemensma** [comment]
Bedankt voor je suggestie, dat lijkt me een prima toevoeging.

**Comment by dennissiemensma** [comment]
Gemaakt voor v3.4

**Comment by dennissiemensma** [comment]
Uitgebracht in [v3.4](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v3.4.0)
