### ISSUE TITLE
Show electricity usage as stacked bar chart

### ISSUE THREAD

**Issue by DiedB** [dsmrreader/dsmr-reader#883]
I saw that that gas usage in the archive section was switched to a bar chart, which is a nice improvement. The bar chart suits the type of data much better.

I would like to see the electricity chart in the same way, but then as a stacked bar chart (to be able to differentiate between tariffs). The current chart is pretty much unreadable when comparing consumption data between different days/months/years.

![Schermafbeelding 2020-02-16 om 23 36 53](https://user-images.githubusercontent.com/7628001/74614117-7ce88e00-5115-11ea-92c4-586ce68ae1c8.png)

**Comment by dennissiemensma** [comment]
Thanks for the suggestion. I'll have a look for the possibilities.

**Comment by dennissiemensma** [comment]
@DiedB see the screenshot below:

![Selection_001](https://user-images.githubusercontent.com/16581744/74682983-d6a99080-51c7-11ea-97e3-b77e4ba1b815.png)

Would that suffice?

**Comment by DiedB** [comment]
Great, absolutely!

**Comment by dennissiemensma** [comment]
Added to v3.4 release.

**Comment by dennissiemensma** [comment]
Uitgebracht in [v3.4](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v3.4.0)

**Comment by Helloitsme** [comment]
thanks!

**Comment by Helloitsme** [comment]
1 klein puntje: bij mij gaat de uitlijning van de energie teruggeleverd grafiek niet goed (onder archive)
de staaf van de eerste dag overlapt de Y as

![afbeelding](https://user-images.githubusercontent.com/2877375/75089645-5d10fa00-555b-11ea-8511-373a09f61ac8.png)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding! Ik zag het zelf ook al en neem het mee voor de volgende release. 

Als je het handmatig wil fixen kun je dit doen:
```
vi /var/www/dsmrreader/static/dsmr_frontend/js/dsmr-reader/archive/electricity-returned.js
```

Rond regel 42 staat iets als:
```
        xAxis: [
            {
                type : 'category',
                boundaryGap: false,
                data : xhr_data.x
            }
        ],
```

Pas deze aan:
```
boundaryGap: false,
# wordt
boundaryGap: true,
```
Je wijziging wordt overigens automatisch overschreven bij de volgende DSMR-reader update die je doet.
