### ISSUE TITLE
Staafdiagram voor stroomverbruik

### ISSUE THREAD

**Issue by killabeenl** [dsmrreader/dsmr-reader#889]
Vanaf versie 3.3 is het mogelijk om gas verbruik in een staafdiagram weer te geven.
Zou dit ook mogelijk voor de stroomverbruik?
Dit is voor een maand of jaar overzicht namelijk mooier aflezen.

**Comment by dennissiemensma** [comment]
Dit komt in de volgende release. Zie #883
