### ISSUE TITLE
elektriciteit teruggaven zichtbaar ondanks niet fysiek aanwezig.

### ISSUE THREAD

**Issue by BlackDex** [dsmrreader/dsmr-reader#890]
* DSMR-reader versie: `v3.3`
* Hardware: `Raspberry Pi 2 Model B Rev 1.1`
* DSMR-protocol slimme meter: `v2/3`

Er worden elektriciteit teruggaven gemeten, maar die heb ik niet.
Is er een manier om dit uit te schakelen?
Hierdoor zie ik tegenwoordig een groen statistiek box welke nooit iets aan geeft.

Tevens is dit ook zichtbaar bij de archieven.

**Comment by dennissiemensma** [comment]
Je kunt dit geforceerd verbergen in de Backend-configuratie:

- `Disable electricity returned capability`

![Selection_002](https://user-images.githubusercontent.com/16581744/74865690-d2a97a00-5351-11ea-97bc-44fe1da3ed5c.png)

**Comment by BlackDex** [comment]
Mijn excuses voor deze vraag.
Ik heb die optie volledig over het hoofd gezien.

**Comment by dennissiemensma** [comment]
Geen probleem joh! Met het oerwoud aan opties en instellingen moet ik soms zelf ook even zoeken waar wat zit. :]
