### ISSUE TITLE
PVoutput wel verbruikte power geen opgeleverde power

### ISSUE THREAD

**Issue by GerbenKwakkel** [dsmrreader/dsmr-reader#896]
API koppeling ingesteld naar PVoutput.org. Het vreemde is dat ik daarin wel verbruikte energie zie (rood) maar geen opgeleverde energie (groen).

In dsmr-reader zie ik dit wel duidelijk terug.

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Het is goed om te weten dat DSMR-reader alleen je (netto) verbruik naar PVOutput stuurt.

Doorgaans is het namelijk de bedoeling dat de omvormer van je zonnepanelen direct de opbrengst doorgeeft aan PVOutput. Voor meer achtergrondinformatie, zie issue #9.
