### ISSUE TITLE
Check toevoegen op overlappende tarieven

### ISSUE THREAD

**Issue by spiralshapeturtle** [dsmrreader/dsmr-reader#897]
Native DSMR 3.4 op een Ubuntu VM met een losse Pi welke via API updates plaatst in de backend.

De energie calculaties staan op zwart (met een - erin) dat is sinds kort. Het energie tarief is correct en ook toegepast voor deze datum. Ik heb nog getracht de energiecalc een "start trigger" te geven door de eind datum een paar dagen te verschuiven.

**Comment by spiralshapeturtle** [comment]
![image](https://user-images.githubusercontent.com/16855935/75035463-cfc49b80-54af-11ea-806d-039bdafab51e.png)

**Comment by spiralshapeturtle** [comment]
![image](https://user-images.githubusercontent.com/16855935/75035561-07334800-54b0-11ea-9eca-0bc0db7c48d0.png)
16e nog in orde 

![image](https://user-images.githubusercontent.com/16855935/75035583-13b7a080-54b0-11ea-80fe-92f7e9c19749.png)

17e defect

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. 

- Zou je eens willen kijken of je de datums van je contract(en) goed staan?

Op je beide screenshots staat `Energy price` als leeg en dat betekent dat er geen prijs voor die datum is gevonden. Dat veld wordt namelijk live opgehaald bij het bekijken van het Archief.

De prijzen in `Cost` worden echter eenmalig berekend per dag. 

- Als je met terugwerkende kracht de prijzen goed instelt, kun je daarna dit uitvoeren om het te fixen:
```
sudo su - dsmr
./manage.py dsmr_stats_recalculate_prices
```

**Comment by spiralshapeturtle** [comment]
![6DCE3571-6722-473A-89CC-107D7E169AAC](https://user-images.githubusercontent.com/16855935/75094484-d1fc2800-558b-11ea-93c3-70cdfe77479a.jpeg)

Dennis. Ik had de prijzen gecontroleerd, maar alleen de eerste regel. Er blijkt overlap in te zitten na het aanpassen van de tarieven door de gewijzigde overheidsbelastingen op 1 Jan. 

Ik zal zo op de PC even e.a aanpassen. En het script runnen. 

Misschien goed om een check in te bouwen?

**Comment by spiralshapeturtle** [comment]
![3396F47E-E64B-475E-AFFC-C22D86E01ACD](https://user-images.githubusercontent.com/16855935/75096091-358e5180-559c-11ea-8a45-d6c01bc06dcd.jpeg)

Het is opgelost!

Wat voor mij nog iets is wat ik al eerder aan wilde geven. Het “today notitie knopje” dat zou voor mij een user selectable optie mogen worden. En die knop van de live grafieken valt er nu ook vrij lelijk overheen. 

Zou mooier zijn om dat allemaal te kunnen verbergen zodat je de data helder tot je kunt nemen zonder afleiding. Wat volgens mij in lijn is met het verplaatsen van de grafieken “overzicht houden”

**Comment by spiralshapeturtle** [comment]
Voor ik het vergeet; enorm veel dank voor al je ontwikkeling!

**Comment by dennissiemensma** [comment]
Bedankt voor je input. Ik zal kijken of het mogelijk is om er een check op te maken.

**Comment by dennissiemensma** [comment]
Wat betreft die knoppen. Ik moet toegeven dat ik het doorgaans alleen in de browser test op een normaal scherm en niet mobiel. Het schaalt wel automatisch mee, maar dat geeft dus niet altijd het goede resultaat. Ik zal er een keertje doorheen lopen om te kijken wat er anders kan.

**Comment by dennissiemensma** [comment]
@rodeho ik heb nu voor de volgende release ook de layout aangepast, zodat het (meeste) wat strakker en rustiger uitlijnt op telefoonschermen.

* Desktop screenshots: https://github.com/dennissiemensma/dsmr-reader/blob/wip/v3.5.0/docs/_static/screenshots/frontend/
* Mobiel:
----
![screencapture-rpi4-siemensma-net-2020-02-24-23_46_13](https://user-images.githubusercontent.com/16581744/75198058-058fab80-5760-11ea-9768-b2228bd804ec.png)
----
![screencapture-rpi4-siemensma-net-archive-2020-02-24-23_46_40](https://user-images.githubusercontent.com/16581744/75198060-06284200-5760-11ea-8ed6-c6a2b7aef9e1.png)
----
![screencapture-rpi4-siemensma-net-energy-contracts-2020-02-24-23_47_06](https://user-images.githubusercontent.com/16581744/75198061-06284200-5760-11ea-9c96-2178d2def7ee.png)
----
![screencapture-rpi4-siemensma-net-live-2020-02-24-23_46_27](https://user-images.githubusercontent.com/16581744/75198062-06c0d880-5760-11ea-8b2e-fb06ddcfe1a0.png)
----
![screencapture-rpi4-siemensma-net-statistics-2020-02-24-23_46_54](https://user-images.githubusercontent.com/16581744/75198063-07596f00-5760-11ea-8014-0450d5d9fc7a.png)

**Comment by spiralshapeturtle** [comment]
Goedemorgen @dennissiemensma het ziet er goed uit, een heel stuk rustiger! Volgens mij heb je tevens de uitdaging opgelost waarbij in het archive de tabel breder was dan de grafieken.

Ik ga geen beta draaien, maar ik wacht vol verrassing op de release van 3.5.

**Comment by dennissiemensma** [comment]
Ik heb gekeken naar de validatie voor overlappende contracten. Helaas krijg ik het niet sluitend wegens een tekortkoming in Django admin validatie.

**Comment by spiralshapeturtle** [comment]
Dennis 

Op de iPhone gaat het zwart nog buiten de kaders. Ik denk door het vrij forse woord “teruggeleverd”

Zou je daar nog eens naar willen kijken? Want links van de zwarte bolletjes is nog ruimte. 

![BB748036-A67C-4612-9D3D-B44E9956D5CF](https://user-images.githubusercontent.com/16855935/75630513-b0ceb380-5beb-11ea-82df-8866f7020d24.png)

**Comment by spiralshapeturtle** [comment]
@dennissiemensma ff een tag omdat hij al gesloten is.

**Comment by dennissiemensma** [comment]
Bedankt voor je terugkoppeling. Ik denk echter dat het vrij lastig wordt om dat op te lossen.

Er zijn namelijk zoveel formaten en resoluties, dat het onmogelijk is om alle varianten te proberen en te testen. Als ik het simuleer krijg ik bijvoorbeeld:

![screencapture-localhost-8000-2020-03-01-21_35_41](https://user-images.githubusercontent.com/16581744/75633407-c6040c00-5c04-11ea-8503-409438eb5e91.png)

En ik kan het woord wel iets inkorten, maar dan ziet het er weer vaag uit op Desktop. Wellicht dat ik die termen in de toekomst ook zelf-instelbaar maak. Dan kan iedereen zijn of haar eigen termen gebruiken en evt inkorten.
