### ISSUE TITLE
Staafgrafieken archief 

### ISSUE THREAD

**Issue by donnie-dominguez** [dsmrreader/dsmr-reader#898]
Ik ben blij met de staafgrafieken in het ' archief'. Erg overzichtelijk. Als je met de muis over een staaf van de grafiek ' hovert' dan is hoogtarief/laagtarief te zien. Wellicht is het mogelijk om in datzelfde pop-upje ook het totaalverbruik (laagtarief+hoogtarief) te zetten? Uiteraard is dat ook makkelijk zelf uit te rekenen, maar dit zou het nog overzichtelijker maken denk ik.

**Comment by dennissiemensma** [comment]
Ik zal kijken of dat mogelijk is met de library die ik gebruik voor de grafieken. Lijkt me goede toevoeging als dat kan.

**Comment by dennissiemensma** [comment]
Ik heb hiernaar gekeken, maar ik kreeg het helaas niet zo snel voor elkaar.

**Comment by donnie-dominguez** [comment]
Dat is jammer. Bedankt voor het kijken.
