### ISSUE TITLE
Verkeerde buiten temperatuur

### ISSUE THREAD

**Issue by Erik050572** [dsmrreader/dsmr-reader#900]
**Wat gebruik je?**
* DSMR-reader versie *(links- of rechtsbovenin applicatie zichtbaar)*: v3.4
* Hardware *(RaspberryPi 3, 4 of iets anders)*: RaspberryPi 3
* Native of Docker *(Native is de installatie direct op je RaspberryPi)*: both
* DSMR-protocol slimme meter *(v4 of v5)*: v5

Goedemiddag Dennis,

Ik weet niet of de bug in het programma zit of bij het "KNMI":
De grafiek voor de buitentemperatuur geeft sinds de upgrade naar V3.4 de hele tijd dezelfde waarde weer
Is dit op te lossen?

Mvg,
Erik

**Comment by x-real-ip** [comment]
Dit is bij mij ook het geval, heb een weerstation uit Arhem geselecteerd, in DSMR-Reader wordt een constante temperatuur van 5 graden celcius aangegeven en wijkt af van de werkelijke temperatuur. 

Zit ook op versie 3.4

**Comment by cranberryNL** [comment]
HIer idem (v3.4). Sinds de update naar 3.4 blijft de temperatuur hangen op 5.6 gr C. (Weerstation De Bilt)

**Comment by dennissiemensma** [comment]
Bedankt voor jullie melding. Ik zie hetzelfde bij mijzelf, maar kan alleen constateren dat dat de temperatuur is die Buienradar via haar API teruggeeft.

Arnhem:
![Selection_012](https://user-images.githubusercontent.com/16581744/75099422-c1ff3b00-55c1-11ea-8c6e-2d72e9c0a9c7.png)

Bilt:
![Selection_011](https://user-images.githubusercontent.com/16581744/75099398-7d739f80-55c1-11ea-99b0-e92253e0e4de.png)

https://data.buienradar.nl/2.0/feed/json

**Comment by dennissiemensma** [comment]
Wellicht morgen even kijken of het zichzelf dan oplost.

**Comment by kgroot** [comment]
Ik heb het probleem nog steeds. De Bilt is 5.6 graden constant. Ook de geschiedenis (van zaterdag) geeft 5.6 graden.

**Comment by kommer** [comment]
Hoi,

Ik zit nog op v3.3 en ik heb ook temperaturen die blijven hangen. Misschien
werkt de API van buienradar niet meer goed?

Groeten,
Kommer

**Comment by dennissiemensma** [comment]
Ik zie in de API nog steeds dezelfde waardes. Je kunt overwegen om even een berichtje te sturen naar Buienradar zelf.

**Comment by kommer** [comment]
Hoi Dennis en anderen,

Ik heb contact gehad met buienradar en ze hebben het volgens mij opgelost.
In mijn DSMR reader zie ik weer andere waarden!

**Comment by cranberryNL** [comment]
Is inderdaad opgelost, o.b.v. mijn grafiek hier ergens tussen 14:00 en 15:00.

**Comment by dennissiemensma** [comment]
Dank @kommer !
