### ISSUE TITLE
Volgorde grafieken zelf instellen

### ISSUE THREAD

**Issue by vincedh** [dsmrreader/dsmr-reader#903]
Hoi Dennis,

Is het misschien een idee om de volgorde van de live grafieken aan te (kunnen) passen?
Ik vind 'RECENT GASVERBRUIK' veel interessanter dan 'RECENTE DISTRIBUTIE ELEKTRICITEITSFASEN' of 'RECENTE VOLTAGES FASEN'

Hoor graag je reactie, bedankt!

**Comment by dennissiemensma** [comment]
Bedankt voor je input. Ik zal het overwegen, maar op de korte termijn laat ik het voor wat het is.

**Comment by vincedh** [comment]
Helemaal goed, dank voor je reactie.

**Comment by PhyxionNL** [comment]
Vind ik ook een goed idee, misschien als ze niet aan te passen zijn dan gas boven het voltage zetten, zoveel kan je daar namelijk niet mee.

**Comment by dennissiemensma** [comment]
Voor de toekomstige v4.3 release heb ik iets toegevoegd wat de volgorde van grafieken instelbaar maakt in de admin. Het is niet de meest mooie oplossing, maar het werkt en is wat mij betreft afdoende voor nu.

**Comment by dennissiemensma** [comment]
Uitgebracht in [v4.3](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v4.3.0).
