### ISSUE TITLE
Kleuren van grafieken omgewisseld

### ISSUE THREAD

**Issue by vincedh** [dsmrreader/dsmr-reader#904]
**Wat gebruik je?**
* DSMR-reader versie *(links- of rechtsbovenin applicatie zichtbaar)*: v3.4
* Hardware *(RaspberryPi 3, 4 of iets anders)*: RaspberryPi 3
* Native of Docker *(Native is de installatie direct op je RaspberryPi)*: native
* DSMR-protocol slimme meter *(v4 of v5)*: v5

Hoi Dennis,

Ik heb 2 verschillende kleuren voor hoog en laagtarief (zie afb 1).
Maar als ik bij afgelopen vrijdag kijk (een dag met verschillende tarieven), geeft hij in de laagperiode de rode kleur en bij hoog tarief de groene kleur (precies andersom dus), zie afb 2.

Op de pagina 'Trends' gaat het wel goed, zie afb 3.

Vriendelijke groet,
![afb 1](https://user-images.githubusercontent.com/17254729/75148655-769f7680-5700-11ea-96c0-ce932f13dad0.png)
![afb2](https://user-images.githubusercontent.com/17254729/75148658-77380d00-5700-11ea-93b8-a7c7810a6484.png)
![afb 3](https://user-images.githubusercontent.com/17254729/75148659-77380d00-5700-11ea-9c33-c439b522607c.png)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Dit lijkt er al heel lang in te zitten, maar het is tot nu toe nog niemand opgevallen. Ik fix het in de volgende release.

**Comment by dennissiemensma** [comment]
Uitgebracht in [v3.5](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v3.5.0)
