### ISSUE TITLE
Herstellen ontbrekende data

### ISSUE THREAD

**Issue by JohannesIV** [dsmrreader/dsmr-reader#906]
Hallo Dennis, 

Mijn upgrade van v2 naar v3 leverde een foutmelding op, waardoor ik nog niet v3 draaide, maar mijn v2 datalogger twee weken stil heeft gelegen (en data dus mist). Nu toont v3 alleen mijn actuele verbruik (sinds upgrade gelukt is en v3 online). 

Is er een manier om de 'gemiste' data te extrapoleren op basis van de ontvangen meterstanden, zodat voor februari wel het juiste totaal wordt geregistreerd?

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Je kunt in DSMR-reader handmatig (ontbrekende) dagen toevoegen. Dit kun je doen bij de admin-interface bij dagstatistieken (`/admin/dsmr_stats/daystatistics/`).

Je kunt dan het verbruikt van die twee gemiste weken dan bijvoorbeeld op 1 dag registreren, zodat het in het Archief bij het maand-/jaaroverzicht meetelt.
