### ISSUE TITLE
Inzoomen van jaar naar maand naar dag

### ISSUE THREAD

**Issue by Pendora** [dsmrreader/dsmr-reader#907]
Hallo,

Als ik in het archief zit zou ik het prettig vinden om te kunnen "inzoomen" naar een niveau lager. Dus je zit bijvoorbeeld bij "Jaren" te kijken en ik zou dan het detailniveau willen zien van een specifiek maand (of van maand naar dag) ik alleen maar op die "staaf" te kunnen klikken om naar het detailniveau te gaan van die maand. 
Ik hoop dat het zo duidelijk is.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik kan je niets beloven, maar ik zal kijken of ik er iets van een doorklik in kan maken.

**Comment by dennissiemensma** [comment]
Ik heb hier wat uurtjes ingestoken, maar ik krijg het helaas niet voor elkaar. 

Er moet dan visueel de dagen/maanden in de labels omgezet worden naar een veilig formaat dat automatisch ingelezen kan worden. Dat gaat ten koste van de leesbaarheid. Ik kon ook geen andere manier vinden om in de grafieken zelf verborgen data te integreren, zodat ik kan aflezen naar welke datum of maand doorgeklikt wordt.

Wel jammer, want ik had het een mooie toevoeging gevonden. Voor nu laat ik het voor wat het is.
