### ISSUE TITLE
Weer inzoomen in gas/temperatuur-grafieken

### ISSUE THREAD

**Issue by vincedh** [dsmrreader/dsmr-reader#911]
**Wat gebruik je?**
* DSMR-reader versie *(links- of rechtsbovenin applicatie zichtbaar)*: v3.5
* Hardware *(RaspberryPi 3, 4 of iets anders)*: RaspberryPi 3
* Native of Docker *(Native is de installatie direct op je RaspberryPi)*: native
* DSMR-protocol slimme meter *(v4 of v5)*: v5

Hoi Dennis,

Sinds de upgrade naar 3.5 mis ik de functie om 'in te kunnen zoomen' bij de live grafieken van recent gasverbruik & recente temperaturen. Bij de andere grafieken zit de functie er nog wel in.

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Ik had ze er bewust uitgehaald omdat de temperatuur maar maximaal 24 meetpunten per 24 uur heeft. En voor gas idem, maar ik besef me nu dat voor DSMR-v5 meters er meer meetpunten (kunnen) zijn.

Ik zal ze in de volgende release weer toevoegen.

**Comment by dennissiemensma** [comment]
Aangepast voor volgende release.

**Comment by dennissiemensma** [comment]
Uitgebracht in [v3.6](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v3.6.0)
