### ISSUE TITLE
Welk front-end gebruik je?

### ISSUE THREAD

**Issue by henkboonstra** [dsmrreader/dsmr-reader#914]
Welk front-end gebruik je voor DSMR Reader?
is dit een bestaande template of is deze zelf otwikkeld?

**Comment by dennissiemensma** [comment]
Hallo Henk. Zie https://dsmr-reader.readthedocs.io/en/latest/credits.html#software-used voor een wat uitgebreidere lijst van wat allemaal gebruikt wordt.

De template heb ik zeker niet zelf ontwikkeld en heette iets als "Director Responsive Admin template". 
- Het was (vijf jaar geleden) beschikbaar op http://web-apps.ninja/director-free-responsive-admin-template/, maar die lijkt inmiddels weg. 
- Cached op: https://web.archive.org/web/20150226203603/http://web-apps.ninja/director-free-responsive-admin-template/
