### ISSUE TITLE
Gecombineerd verbruik teruggeven in API's "Retrieve today's consumption"

### ISSUE THREAD

**Issue by braham2019** [dsmrreader/dsmr-reader#916]
Is het mogelijk om aan de API /api/v2/consumption/today twee velden toe te voegen ?
- een veld dat electricity1 en electricity2 opgeteld weergeeft
- een veld dat electricity1_returned en electricity2_returned opgeteld weergeeft 

Ik gebruik de API om de info op mijn DAKboard scherm te tonen van verbruik en teruggave, maar daar staan nu vier waarden (omwille van tarief 1 en 2); ik zou er liever twee hebben, als het zou kunnen. DAKboard laat niet toe dat ik die zelf optel alvorens ik ze weergeef :-(

Bedankt voor de nuttige toepassing!

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik zal t.z.t. kijken of ik dat kan toevoegen.

**Comment by dennissiemensma** [comment]
Ik heb even voor je gekeken en de data was al praktisch aanwezig. Echter verborg ik deze hardcoded, dus ik zal hem toevoegen en ook de docs bijwerken.

**Comment by dennissiemensma** [comment]
Gaat mee in de volgende release.

**Comment by dennissiemensma** [comment]
Uitgebracht in [v3.6](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v3.6.0)

**Comment by braham2019** [comment]
Prachtig, dankjewel !
