### ISSUE TITLE
Upgrade error and Fresh installation error 

### ISSUE THREAD

**Issue by jossie67** [dsmrreader/dsmr-reader#917]
Laaste versie 
Raspberry3 / Ubuntu
DSMR Protocol v4

Vandaag mijn dsmr-reader geupgrade, na de upgrade een error
```
"Server Error
Sorry, something unexpected happened.
Exception:
ProgrammingError: relation "dsmr_consumption_electricityconsumption" does not exist
LINE 1: SELECT (1) AS "a" FROM "dsmr_consumption_electricityconsumpt..."
```

Ik dacht ligt aan mij SD formateren, versie installatie , database restoren

Weer de zelfde foutmelding.....

Ik nu even een verse installatie op Ubuntu zonder restore...

En weer de zelfde foutmedling ..
Zit er een fout in de repository?

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Wat krijg je hier te zien?

```
sudo su - dsmr
python3 --version
```

En kun je daarna dit eens proberen:
```
sudo su - dsmr
./manage.py migrate
```

**Comment by jossie67** [comment]
Dennis,
Thanks for you replay, I checked and recheck, I found the issue.
Op de com-port /dev/ttyUSB0 was de " ir-schreib-lesekopf" aangesloten ivm de P1
Door de /dev/ttyUSB0  te veranderen in /dev/ttyUSB1 werkte alles weer.
Weer een leerpuntje

**Comment by dennissiemensma** [comment]
Top, bedankt voor je terugkoppeling.
