### ISSUE TITLE
Bijhouden van veranderingen meterstatistieken

### ISSUE THREAD

**Issue by neverstoppedaskingwhy** [dsmrreader/dsmr-reader#920]
Hi Dennis,

De meter statistics (number of voltage sags, number of voltage swells, ...) worden al weergegeven op de statistics pagina. Het zou fijn zijn, als er een melding komt met datum en tijd, wanneer herkent wordt, dat de waarde tegenover de vorig bekende waarde is veranderd. Eventueel kan elke verandering ook in het archief worden opgeslagen?

Groetjes,
Mark

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik zal kijken of ik zoiets kan opnemen in een toekomstige release.

**Comment by dennissiemensma** [comment]
Onderdeel van DSMR-reader v4.2 release.

**Comment by dennissiemensma** [comment]
Uitgebracht in [v4.2](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v4.2.0)
