### ISSUE TITLE
Suggestie: Live grafieken standaard laten uitzoomen naar laatste uur laten zien in plaats van de afgelopen minuut.

### ISSUE THREAD

**Issue by iMartien** [dsmrreader/dsmr-reader#926]
Het is denk ik overzichtelijker om de live grafieken standaard op het afgelopen uur in te stellen in plaats van de afgelopen minuut / laatste paar seconden.

Of misschien de mogelijkheid om de standaard zoom in te stellen?

**Comment by dennissiemensma** [comment]
Je kunt dit als het goed is wijzigen via `Interfaceconfiguratie` > `Dashboard grafiek breedte`. 

Daar kun je geen tijdspanne invoeren, maar wel het aantal punten dat zichtbaar is. Houd er rekening mee dat de performance in je browser wat minder kan zijn bij een hoog aantal datapunten.

**Comment by theelog** [comment]
Ik zou het zelf fijn vinden om in de live grafiek de mogelijkheid te hebben om met een dropdown de time range in te kunnen stellen. Zie hier een voorbeeld uit Grafana.

![image](https://user-images.githubusercontent.com/2011325/78063832-1c45a580-7391-11ea-8d17-e56d166e5859.png)

**Comment by dennissiemensma** [comment]
Bedankt voor je toevoeging. Toevallig is hier net #947 voor aangemaakt en had ik niet gezien dat het huidige ticket er (nog) was. Voor nu sluit ik deze en gaat het via #947.

**Comment by dennissiemensma** [comment]
In de volgende release kan je zelf de range instellen in uren, van 1 tot 168 (week).
