### ISSUE TITLE
Soms afrondingsfout in grafieken-tooltip

### ISSUE THREAD

**Issue by KobeBergmans** [dsmrreader/dsmr-reader#930]
Bij het bekijken van de live grafiek zijn er soms waarden van de teruggeleverde stroom niet goed afgerond. Zie afbeelding
![Screenshot_2](https://user-images.githubusercontent.com/55985776/77248809-b93f6a80-6c3c-11ea-9571-10f61848f2e4.png)

**Wat gebruik je?**
* DSMR-reader versie *(links- of rechtsbovenin applicatie zichtbaar)*: v3.7
* Hardware *(RaspberryPi 3, 4 of iets anders)*: RaspberryPi 3 Datalogger en Ubuntu backend en webserver.
* Native of Docker *(Native is de installatie direct op je RaspberryPi)*: Native
* DSMR-protocol slimme meter *(v4 of v5)*: vDSMR 5 (Belgie)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Het was me zelf nog niet opgevallen, maar ik zie het nu bij mijn eigen grafiek ook. Ik neem het mee voor de volgende release.

**Comment by dennissiemensma** [comment]
Het lijkt heel specifiek op te treden bij vaste getallen, zoals `1023`. Vermoedelijk doordat het een float is gemaakt en dat blijven altijd onbetrouwbare dingen. En bij nader inzien hoeven het ook geen floats te zijn, maar gewoon integers, gezien het over eenheden gaat zonder kommagetal.

**Comment by dennissiemensma** [comment]
Aangepast voor volgende release.

**Comment by dennissiemensma** [comment]
Uitgebracht in [v3.8](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v3.8.0)
