### ISSUE TITLE
Django-beheer naar hoofdpagina

### ISSUE THREAD

**Issue by PhyxionNL** [dsmrreader/dsmr-reader#935]
De Django-beheer link gaat momenteel naar de /admin/ pagina, maar dit is niet heel erg praktisch. Of je zit er al op en voegt het niks toe of je zit op een subpagina en dan kan je gewoonweg op 'voorpagina' drukken. Handiger zou zijn dat de link terug gaat naar de "normale" DSMR reader pagina / dashboard.

Volgens de Django docs moet dit toegevoegd kunnen worden aan https://github.com/dennissiemensma/dsmr-reader/blob/v3/dsmr_backend/admin.py
`admin.site.site_title = 'DSMR Reader'`
`admin.site.site_url = '/'`

**Comment by dennissiemensma** [comment]
Bedankt voor je suggestie. Ik heb de header aangepast, maar de link laat ik voor wat het is. Ik begrijp je punt, maar anderzijds zijn er waarschijnlijk aan hoop mensen al gewend aan de bestaande target.
