### ISSUE TITLE
Home Assistant Add-on DSMR Datalogger created

### ISSUE THREAD

**Issue by sanderdw** [dsmrreader/dsmr-reader#936]
Hi Dennis,

I created an Home Assistant add-on for the DSMR datalogger (https://github.com/sanderdw/hassio-addons). Do you mind if i use the logo's etc?

Currently it looks like this in Home Assistant:
![image](https://user-images.githubusercontent.com/19476345/77536535-c490d100-6e9c-11ea-833c-370795df72cb.png)

![image](https://user-images.githubusercontent.com/19476345/77536581-db372800-6e9c-11ea-90a9-81cbb13bde77.png)

![image](https://user-images.githubusercontent.com/19476345/77536902-703a2100-6e9d-11ea-994c-ffef6e87f466.png)

Any remarks or things i need to change, please let me know?

Love this project btw!

**Comment by dennissiemensma** [comment]
It looks pretty neat. You can use the logo, as it's not mine anyway (https://www.flaticon.com/free-icon/eco-energy_25013) and it's credited in the DSMR-reader docs so you should be fine.

The only remark I have is that HTTPS is not required or default for the `DSMR_API_URL`, so you might take that into account.

**Comment by dennissiemensma** [comment]
Let me know if you need anything else. For now I'll close this.
