### ISSUE TITLE
Dashboard €/uur houdt geen rekening met teruglevering

### ISSUE THREAD

**Issue by PhyxionNL** [dsmrreader/dsmr-reader#937]
**Wat gebruik je?**
* DSMR-reader versie: 3.7
* Hardware: RaspberryPi 3b
* Native of Docker: Docker
* DSMR-protocol slimme meter: v5

Screenshot ter verduidelijking:

![image](https://user-images.githubusercontent.com/7643972/77640675-1ef06700-6f5b-11ea-9092-0c9974edcfa6.png)

Waar het hoog- en laagtarief wel negatieve waardes weergeven bij de kosten (er wordt immers stroom opgeleverd), staat de €/uur berekening vast op 0,00.

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Ik ben wat terughoudend met het tonen en meenemen van opbrengsten van teruglevering, omdat die regels vrij complex zijn en ik dat een grijs gebied vind binnen dit project.

Echter, gezien het hier puur om een indicatie gaat op het dashboard, vind ik het (**voor nu**) prima om het ook daarin op te nemen.

**Comment by dennissiemensma** [comment]
Aangepast voor de volgende release.

**Comment by PhyxionNL** [comment]
Fijn, bedankt. Qua regels is het niet veel anders dan nu voor alleen de kosten toch? Het lijkt mij dat je gewoon dat wat je al hebt en dan - watt * terugleveringtarief kan doen? Dat het niet helemaal 100% klopt maakt ook niet heel veel uit, een indicatie is wel leuk in ieder geval. De energiecontracten / kosten zijn juist zo leuk om te bekijken ☺

**Comment by dennissiemensma** [comment]
Uitgebracht in [v3.8](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v3.8.0)
