### ISSUE TITLE
Verschillende kleuren op dashboard voor negatieve kosten / opbrengst

### ISSUE THREAD

**Issue by PhyxionNL** [dsmrreader/dsmr-reader#938]
Op het dashboard zijn zowel kosten als opbrengsten zwart. Door verschillende kleuren te gebruiken is het makkelijker om onderscheid te maken tussen de daadwerkelijke kosten en opbrengsten.

Ik heb hieronder bg-olive gebruikt als voorbeeld.

![image](https://user-images.githubusercontent.com/7643972/77643372-86101a80-6f5f-11ea-877e-88211c9da294.png)

**Comment by dennissiemensma** [comment]
Bedankt voor je idee. Ik begrijp je punt en kan me persoonlijk ook wel vinden in je suggestie. 

Echter wil ik voorkomen dat de interface een kleurplaat/regenboog wordt. Het palet en de variatie die nu in de meest recente versie zit, vind ik ook al op het randje. Ik denk eerder dat ik het op termijn zelfs nog wat rustiger maak, door bijvoorbeeld alleen de namen een kleur te geven. Maar dat laat ik voor nu nog voor wat het is. Het is nog te overzien.

**Comment by PhyxionNL** [comment]
Het wordt inderdaad ook wel wat een kleurplaat dan. Misschien in plaats van groen is een grijstint dan beter. Is het anders een idee om dit configureerbaar te maken? Net als de grafiek kleuren nu, dan kan iedereen kiezen wat ie zelf wil. Voor mij, persoonlijk, vind ik bijvoorbeeld het oranje van gas weinig toevoegen (zeker omdat de totalen ook gewoon rood zijn).

**Comment by dennissiemensma** [comment]
Het is aardig wat werk om ook al die dingen configureerbaar te maken. Ik zal ooit nog een andere matrix proberen, maar de huidige was degene die tot nu toe het duidelijkste was.
