### ISSUE TITLE
Column missing (3.6 > 3.7 upgrade) 

### ISSUE THREAD

**Issue by d0mmels** [dsmrreader/dsmr-reader#944]
**Wat gebruik je?**
* DSMR-reader versie *(links- of rechtsbovenin applicatie zichtbaar)*: v3.7
* Hardware *(RaspberryPi 3, 4 of iets anders)*: RaspberryPi 3B
* Native of Docker *(Native is de installatie direct op je RaspberryPi)*: Native
* DSMR-protocol slimme meter *(v4 of v5)*: v4

After updating 3.6 to 3.7 /status and /configuration are inaccesable 
Server error:
ProgrammingError: column dsmr_backup_backupsettings.compression_level does not exist

**Comment by dennissiemensma** [comment]
Thanks for reporting. Would you mind trying this:

```
sudo su - dsmr
./manage.py migrate
```

What's the output of the last command?

**Comment by d0mmels** [comment]
See attached file for the output:
[output.txt](https://github.com/dennissiemensma/dsmr-reader/files/4399100/output.txt)

**Comment by dennissiemensma** [comment]
Can you try this:

```
sudo su - dsmr
./manage.py dsmr_sqlsequencereset

# And then
./manage.py migrate
```

Let me know if that fixes the error from your logs:
```
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "django_migrations_pkey"
DETAIL:  Key (id)=(144) already exists.
```

**Comment by d0mmels** [comment]
Yes, output was ok without any errors this time and all issues seem to be gone.
Thank you!
