### ISSUE TITLE
Retention op 3 maanden kunnen zetten

### ISSUE THREAD

**Issue by Roel0412** [dsmrreader/dsmr-reader#954]
Is het mogelijk om naast 1 week, 1 maand, 6 maanden en 1 jaar de retentie ook op 3 maanden te zetten?

Ik merk dat in mijn geval 6 maanden net te lang is om te voorkomen dat het bij mij vast gaat lopen. En 1 maand is wat te kort.

![image](https://user-images.githubusercontent.com/63040431/78223841-d50e0080-74c7-11ea-8d16-2f5df604d830.png)

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Dat lijkt me een goede toevoeging. Ik heb bij deze de optie toegevoegd aan de volgende release.

**Comment by dennissiemensma** [comment]
Uitgebracht in [v3.8](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v3.8.0)
