### ISSUE TITLE
Resetten van meter statistieken

### ISSUE THREAD

**Issue by n9iels** [dsmrreader/dsmr-reader#955]
Ik denk dat het kunnen resetten van de meter statistieken en de _All time highs & lows_ een nuttige feature zou kunnen zijn. Momenteel staat mijn all time low allemaal op 1 Watt en heb ik er dus vrij weinig aan. Daarnaast kan het nuttig zijn als je eens een keer een soort nul-meting wilt doen om te kijken hoeveel energie je in e nacht verbruikt of iets dergelijks.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Het resetten van de meterstatistieken zou geen zin hebben, want die komen met elk telegram opnieuw binnen.

Wat betreft de highs en lows. Deze kun je nu ook al zien in `/admin/dsmr_stats/electricitystatistics/`, alleen zijn ze nog read-only. Ik zal ze bewerkbaar maken, zodat je ze zelf eventueel kan wijzigen voor een reset of nachtmeting.

Mocht je zonnepanelen hebben, dan zeggen die all-time lows niet zoveel omdat die dan vervuild raken door de opname en de slimme meter kan dat niet detecteren.

**Comment by dennissiemensma** [comment]
Toegevoegd aan volgende release.

**Comment by dennissiemensma** [comment]
Uitgebracht in [v3.8](https://github.com/dennissiemensma/dsmr-reader/releases/tag/v3.8.0)
