### ISSUE TITLE
Geen voltages in telegrammen

### ISSUE THREAD

**Issue by remyderuysscher** [dsmrreader/dsmr-reader#960]
Hi Dennis,

Ik heb een Landys + Gyr E350 DSMR 4.2 meter, ik krijg de P1 telegrammen door maar zie bij een ruwe telegram geen voltages klopt dit? Ligt dit aan de meter of wellicht aan een bug (of docker container van ualex73)?

Bedankt weer.

Remy

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Dat is inderdaad iets wat alleen in DSMR-5 meters mogelijk is.

Zie ook https://github.com/dennissiemensma/dsmr-reader/issues/518#issuecomment-417015266 en dan het verschil iets onder de lange dubbele regel in het midden.
