### ISSUE TITLE
[#937] Dashboard €/uur houdt geen rekening met teruglevering

### ISSUE THREAD

**Issue by niekniek89** [dsmrreader/dsmr-reader#962]
* DSMR-reader versie *(links- of rechtsbovenin applicatie zichtbaar)*: v3.8
* Hardware *(RaspberryPi 3, 4 of iets anders)*: Intel NUC
* Native of Docker *(Native is de installatie direct op je RaspberryPi)*: Docker
* DSMR-protocol slimme meter *(v4 of v5)*: v4

Goedemorgen,

ik heb zojuist de laatste versie van DSMR reader geinstalleerd.
Bij het terugleveren zie ik nu dat deze niet meer op 0.00 €/uur staat, maar oploopt, terwijl ik terug lever (zie screenshots). 

Terwijl ik terug lever, loopt het totaal bedrag wel op, terwijl deze eigenlijk stil moet blijven staan tijdens het terug leveren?

gaat er wellicht bij mijn DSMR reader iets niet goed?
![DSMR na](https://user-images.githubusercontent.com/48858098/78883138-5bdb5400-7a59-11ea-891e-146cd20e9d6b.PNG)
![DSMR voor](https://user-images.githubusercontent.com/48858098/78883141-5c73ea80-7a59-11ea-9668-7450a91fbe7b.PNG)

Ik ben nu terug gegaan naar versie 3.7, echter zie ik nog steeds dat tijdens het terugleveren de totale kosten voor het elektra blijven oplopen... terwijl dit gelijk zou moeten blijven tijdens het terugleveren?

**UPDATE:**

Zat een fout in mijn DSMR settings (qua tarieven leverancier).
Versie 3.8 draait prima, niks mis mee.
Excuus, was een foutje van mijzelf.

**Comment by niekniek89** [comment]
Zat een fout in mijn DSMR settings (qua tarieven leverancier).
Versie 3.8 draait prima, niks mis mee.
Excuus, was een foutje van mijzelf.

**Comment by dennissiemensma** [comment]
Bedankt voor je terugkoppeling. Fijn dat je het hebt kunnen oplossen.
