### ISSUE TITLE
Onverwerkte telegrammen

### ISSUE THREAD

**Issue by lukevredeveld** [dsmrreader/dsmr-reader#964]
Mijn DSMR-reader is vanmorgen rond een uurtje of 6 gestopt met het verwerken van Telegrammen. Omdat er een nieuwe versie klaar stond, heb ik eerst een update gedaan. Daarna liep het aantal telegrammen nog steeds op. Daarna heb ik alle processen nog een aantal malen herstart met `sudo supervisorctl restart all`

Als de processen opnieuw gestart zijn, dan werkt DSMR-reader gedurende enkele minuten een paar honderd van de 28.000 achterstallige telegrammen weg. Na een paar minuten loopt het aantal onverwerkte telegrammen echter weer op. Dit is de weergave van het log-file van het backend proces.

![image](https://user-images.githubusercontent.com/964895/79043209-2a4fbd80-7bfe-11ea-92b9-a95977a5a32f.png)

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Die foutmelding van PVoutput is vrij onschuldig en lost zichzelf op. Ik zou graag deze gegevens nog wat je willen weten:

**Wat gebruik je?**
* Hardware *(RaspberryPi 3, 4 of iets anders)*: RaspberryPi ...
* Native of Docker *(Native is de installatie direct op je RaspberryPi)*: ...
* DSMR-protocol slimme meter *(v4 of v5)*: v...

**Comment by dennissiemensma** [comment]
Verder kun je waarschijnlijk debug-logging aanzetten om te zien wat het systeem (de backend) precies doet: https://dsmr-reader.readthedocs.io/en/latest/troubleshooting.html#logging

**Comment by dennissiemensma** [comment]
Daarnaast kun je nog even topic #913 doorlezen voor aanwijzigingen. Zodra je meer informatie hebt kunnen we wat gerichter zoeken.

**Comment by lukevredeveld** [comment]
Oh sorry, was inderdaad een beetje te snel met mijn post. Had eerst alles gewist en was toen vergeten die gegevens die je vraagt toe te voegen :-)

Het is een pi 3b met native installatie. Ik kan ff niet vinden welke dsmr-protocol slimme meter ik gebruik.... waar kan ik dat zien?

Logging ga ik zometeen aanzetten als de pi klaar is met alle andere pakketten updaten en upgraden.

**Comment by dennissiemensma** [comment]
> Het is een pi 3b met native installatie. Ik kan ff niet vinden welke dsmr-protocol slimme meter ik gebruik.... waar kan ik dat zien?

Als je elke seconde een telegram krijgt heb je DSMR v5, als je elke 10 seconden een telegram krijgt heb je DSMR v4.

Dat kan namelijk van invloed zijn op de performance. Als je v5 hebt is mijn advies om sowieso de datalogger wat te laten vertragen, zodat je 5 of 10x minder telegrammen binnenkrijgt. Dat scheelt je performance en opslag, terwijl de dagtotalen er niet door beinvloed worden.

**Comment by lukevredeveld** [comment]
Dan heb ik v5 :-)

Overigens is deze PI dedicated voor DSMR met een 32Gb kaartje erin. Dus het kan wel wat hebben. Ik heb ook gecheckt en de kaart zit nog lang niet aan zijn max.

**Comment by dennissiemensma** [comment]
Het gaat niet alleen om de opslag, maar ook of de hardware het kan bijbenen qua verwerken.

Hoe dan ook kun je het beste de backend-log in debugging mode bekijken. Dan zie je precies wat die doet, waar die op wacht en wat er (relatief) lang duurt.

**Comment by lukevredeveld** [comment]
Yep. Ga ik zo aanzetten. Ik had blijkbaar een sh*tload aan achterstallige updates op die PI uit te voeren, want hij heeft net 788MB binnengehaald. Is nu op 3% update...

**Comment by lukevredeveld** [comment]
Oh... dit is niet goed. Ik heb de debug aangezet. Daarna alles dus opnieuw gestart, conform de handleiding. Toen ging DSMR-reader weer telegramme wegwerken. Maar nu dus dit (een geen GUI meer):

```
Server Error
Sorry, something unexpected happened.
Exception:

OperationalError: FATAL:  the database system is shutting down
FATAL:  the database system is shutting down
```

**Comment by dennissiemensma** [comment]
Het lijkt erop dat er iets met de database is. Je kunt het systeem een keer proberen te herstarten en anders even in de logs van postgresql kijken.

**Comment by lukevredeveld** [comment]
Na de update van de PI heb ik DSMR-reader een aantal keren herstart, waarna hij weer goed begon te lopen. Na een half uurtje waren alle telegrammen weer verwerkt. De rest van de dag / avond is hij goed blijven lopen. Vannacht is hij echter weer opeens gestopt met het verwerken van telegrammen. De LOG-file van de backend stopt ook gewoon op dat moment (zie hieronder). Kun je me aangeven hoe ik de datalogger kan vertragen? Misschien dat dat nog iets oplevert.

![image](https://user-images.githubusercontent.com/964895/79065550-7871c900-7cb1-11ea-8138-773772629920.png)

**Comment by dennissiemensma** [comment]
Als in je de admin-interface naar Backend configuratie gaat kun je daar de sleep instellen voor de backend. Die kun je op 5 seconden zetten.

Voor de datalogger sleep kun je in de admin naar Datalogger configuratie en daar de sleep instellen voor de datalogger. Je kunt daar ook eerst 5 seconden of meer proberen.

----

Alleen zou het systeem niet zomaar moeten stoppen, hooguit wat trager moeten zijn als die het niet aankan. Staan er in logfiles van `/var/log/supervisor/` verder fouten? Supervisor zou sowieso oneindig moet proberen de processen weer te starten.

**Comment by lukevredeveld** [comment]
De backend log op de locatie /var/log/supervisor laat ook gewoon een 'gat' zien op het moment dat het probleem zich voordoet (zie hieronder). 

Overigens heb ik de sleep voor de datalogger nu op 5 gezet (stond op 0.5). Sindsdien blijft het aantal onverwerkte telegrammen <10 staan. Dus so far, so good... wel vreemd van die logfiles?

Backendlog
![image](https://user-images.githubusercontent.com/964895/79118252-aaf0f400-7d8d-11ea-84f3-4977e232cda7.png)

Supervisor log
![image](https://user-images.githubusercontent.com/964895/79120007-09b86c80-7d92-11ea-8855-c939a64aa259.png)

**Comment by dennissiemensma** [comment]
Bedankt voor de terugkoppeling. Als het verder nu wel goed werkt zou ik het even aankijken of dat een paar dagen goed blijft gaan.

**Comment by lukevredeveld** [comment]
Het bleef inderdaad 4 dagen goed gaan... inmiddels wordt er weer geen telegram verwerkt en sta ik er alweer 22.000 achter.... nog ideeen?

**Comment by dennissiemensma** [comment]
Wat staat er in de logs? Loopt de achterstand wel in of wordt die alleen maar groter?

**Comment by dennissiemensma** [comment]
@lukevredeveld ben je hier nog verder mee gekomen?

**Comment by lukevredeveld** [comment]
Als hij stopt met verwerken dan start ik de boel opnieuw op en dan gaat hij weer inlopen. Hij gaat inmiddels al weer 10 dagen goed. Hopen dat het zo blijft

**Comment by dennissiemensma** [comment]
Prima. Ik ga er vanuit dat het verhogen van de sleep-tijden het wellicht heeft opgelost. En anders kun je er hier later nog op terugkomen.
