### ISSUE TITLE
Error: could not connect to server: Connection refused

### ISSUE THREAD

**Issue by Kludon** [dsmrreader/dsmr-reader#965]
**Wat gebruik je?**
* DSMR-reader versie *(links- of rechtsbovenin applicatie zichtbaar)*: v3.8
* Hardware *(RaspberryPi 3, 4 of iets anders)*: RaspberryPi 3
* Native of Docker *(Native is de installatie direct op je RaspberryPi)*: Native
* DSMR-protocol slimme meter *(v4 of v5)*: v4

Na de installatie van 3.8 werkte de applicatie. Daarna heb ik mijn pi geupdate en kreeg ik DSMR niet meer aan de praat met onderstaande meldingen. Hoe kan ik DSMR weer opstarten ? 

 --- Reloading running apps...

 * Reloading process: dsmr_webinterface (Gunicorn)   [OK]
 * Reloading process: dsmr_backend                   [??] PID file does not exist
 * Reloading process: dsmr_datalogger                [??] PID file does not exist
 * Reloading process: dsmr_mqtt                      [??] PID file does not exist

```
Server Error
Sorry, something unexpected happened.
Exception:
OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
```

**Comment by Kludon** [comment]
I had also changed my language settings to nl-nl. Changed it back to en-us and the app is running.
But at some point I now get 504 Gateway Time-out if I want to read my status or my dsmr readings.

It looks like my pi is hanging at the requests. I have raspberian with vnc running. Is that to much ?

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Het lijkt erop dat DSMR-reader niet meer bij de database kan.

- Wat is de output van deze twee commands?

```
lsb_release -a

sudo su - postgres
psql dsmrreader
```

- Staan er foutmeldingen in de log van PostgreSQL?
```
# Mogelijk heet je file iets anders als je een andere versie draait.
sudo view /var/log/postgresql/postgresql-11-main.log
```

**Comment by dennissiemensma** [comment]
Als de database wel goed werkt, kun je even in de logs kijken: https://dsmr-reader.readthedocs.io/en/latest/troubleshooting.html#supervisor

Staan daar fouten?

**Comment by Kludon** [comment]
Hoi Dennis, door het wisselen van de language settings kon hij niet meer bij de database. door het terugzetten kan hij er weer bij. De gateway time out komt denk ik doordat ik gee nretentie heb teogepast. Ik heb er nu 2 jaar aan data instaan. Ik heb de retentie nu gezet op een jaar om een eerste deel te verwijderden maar nu loopt de applicatie weer vast omdat dat natuurlijk veel werk is. Is er een command line commando dat ik kan uitvoeren voor de rententie zodat  ik het kan monitoren ? Of is het nu gewoon wachten ?

**Comment by dennissiemensma** [comment]
Bedankt voor je terugkoppeling. Dat is goed om te weten qua taalinstellingen, ik wist niet dat dat invloed had.

Wat betreft retentie, je kunt met debug-logging (https://dsmr-reader.readthedocs.io/en/latest/troubleshooting.html#logging) kijken hoever die is en wat die doet. Dat kun je dan zien in de log van de backend.

Verder zou je nog kunnen kijken of de indexes op de tabellen staan: https://github.com/dennissiemensma/dsmr-reader/issues/913#issuecomment-593137228

**Comment by dennissiemensma** [comment]
En als aanvulling op laatste comment, kun je deze tabel ook nog checken qua indexes:

```
\dS dsmr_consumption_electricityconsumption
```

Ter vergelijking
```
Indexes:
    "dsmr_consumption_electricityconsumption_pkey" PRIMARY KEY, btree (id)
    "dsmr_consumption_electricityconsumption_read_at_key" UNIQUE CONSTRAINT, btree (read_at)
    "dsmr_consumption_electrici_phase_power_current_l1_3d9fd70d" btree (phase_power_current_l1)
    "dsmr_consumption_electrici_phase_voltage_l1_72e3c8f8" btree (phase_voltage_l1)
    "dsmr_consumption_electrici_phase_voltage_l2_917726c7" btree (phase_voltage_l2)
    "dsmr_consumption_electrici_phase_voltage_l3_1a9d7c37" btree (phase_voltage_l3)
    "dsmr_consumption_electricityc_currently_delivered_5bf9be2d_uniq" btree (currently_delivered)
    "dsmr_consumption_electricityco_currently_returned_5f91fed7_uniq" btree (currently_returned)
    "dsmr_consumption_electricityconsumption_2241f8ee" btree (phase_currently_delivered_l2)
    "dsmr_consumption_electricityconsumption_5714c500" btree (phase_currently_delivered_l1)
    "dsmr_consumption_electricityconsumption_e90842a6" btree (phase_currently_delivered_l3)
```

**Comment by dennissiemensma** [comment]
@Kludon ben je hier nog verder mee gekomen?
