### ISSUE TITLE
Het opnemen van watergebruik

### ISSUE THREAD

**Issue by allureGOT** [dsmrreader/dsmr-reader#967]
Is het een idee om het verbruik van water op te nemen?
Dit is volgens mij goed te doen met een pulsmeter.
https://www.bol.com/nl/p/sensus-pulssensor-hri-voor-watermeters/9200000124224648/

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Hoewel ik kan begrijpen dat dit heel handig is, beperkt dit project zich tot het uitlezen van het DSMR-protocol. 
Mocht het daarin opgenomen worden (de specificaties van Netbeheer NL houden er wel rekening mee), dan zal ik het zeker toevoegen.

**Comment by markminnoye** [comment]
Mijn Digitale meter geeft naast electriciteit en gas ook het waterverbruik door via DSMR. (België)
Ik merk op dat de HA plugin "DSMR Smart Meter" van netbeheer Nederland deze waarden _wel_ doorgeeft.
zou deze toegevoegd kunnen worden ?

![Image](https://github.com/user-attachments/assets/16d08226-f2ce-469e-88cb-29239410c45d)

![Image](https://github.com/user-attachments/assets/0bf17c9c-ed60-41a3-a59c-d745b0623dfc)

Groeten,
Mark

**Comment by dennissiemensma** [comment]
Zie #1813
