### ISSUE TITLE
In- en uitknijpen van de grafieken werkt niet meer

### ISSUE THREAD

**Issue by vincentweeda** [dsmrreader/dsmr-reader#969]
**Wat gebruik je?**
* DSMR-reader versie: v3.8
* Hardware: RaspberryPi 3B+
* Native of Docker *:  Native
* DSMR-protocol slimme meter *(v4 of v5)*: v5

Sinds de laatste versie werkt het in en uitknijpen van de grafieken op de "Live graphs" niet meer op mijn Oneplus 5 (Android 9) toestel.

Ik heb het ook geprobeerd op de iPad iOS 13 maar daar functioneert het ook niet in Safari. 
Nog even getest, en gewoon op de PC (touchscreen) zoemt hij enkel het gehele scherm in en uit.

**Comment by ezweistra** [comment]
Ik heb deze bug inderdaad ook gemerkt op mijn Android toestellen (Samsung Galaxy Tab S3 en Samsung Galaxy S8, beide ook op Android 9). Werkte altijd perfect tot deze update.

**Comment by dennissiemensma** [comment]
Bedankt voor jullie melding. Ik zal dan de library voor de grafieken in de volgende release weer downgraden. Wellicht zit er in die update iets wat niet lekker is.

**Comment by dennissiemensma** [comment]
Opgelost voor volgende release
