### ISSUE TITLE
Dag rapporten worden niet meer gegenereerd

### ISSUE THREAD

**Issue by geforceFXguy** [dsmrreader/dsmr-reader#974]
DSMR-reader versie (links- of rechtsbovenin applicatie zichtbaar): v3.8
Hardware (RaspberryPi 3, 4 of iets anders): RaspberryPi 3
Native of Docker (Native is de installatie direct op je RaspberryPi): Native
DSMR-protocol slimme meter (v4 of v5): v2/3

Sinds 4 april worden mijn dag reports niet meer gemaakt. Nu heb ik de logging aangezet en dan kom hij met de melding dat er geen gegevens zijn voor 5 april. Nu heb ik gekeken en in de database staat toch echt gegevens in. 

Zit op V3.8
<img width="960" alt="Status" src="https://user-images.githubusercontent.com/64011120/79743342-b8b1f680-8304-11ea-83cf-258b220205a0.png">

<img width="615" alt="Log" src="https://user-images.githubusercontent.com/64011120/79743077-3d504500-8304-11ea-8dfc-504a0d77927a.PNG">

<img width="901" alt="Mysql_results" src="https://user-images.githubusercontent.com/64011120/79743078-3d504500-8304-11ea-9510-2159de34cb82.PNG">

<img width="1421" alt="dsmr_consumption_electricityconsumption" src="https://user-images.githubusercontent.com/64011120/79743073-3b868180-8304-11ea-8c34-cfd57cde0c3e.PNG">

<img width="1406" alt="dsrm_dsmrlogger_dsmrreadings" src="https://user-images.githubusercontent.com/64011120/79743075-3cb7ae80-8304-11ea-99e0-3e44df724d18.PNG">

**Comment by dennissiemensma** [comment]
Bedankt voor je melding en de uitgebreide info. Gebruik je toevallig MySQL als database-opslag? (#909)

**Comment by geforceFXguy** [comment]
ik gebruik:
MySQL 5.7.25 deze draait op een Windows 2016 machine

**Comment by dennissiemensma** [comment]
Dan vermoed ik dat het mogelijk ligt aan missende tijdzone definities. Deze staan standaard niet aan in MySQL en zorgen voor vage bugs. 

Zie ook het topic dat ik hierboven al heb gelinked: https://github.com/dennissiemensma/dsmr-reader/issues/909#issuecomment-594081194

Ik verwacht dat dat de problemen oplost.

**Comment by geforceFXguy** [comment]
Het lijkt nu weer te werken. Apart dat het van vanaf 2017 al gewerkt heeft :)

**Comment by dennissiemensma** [comment]
Fijn om te horen. Het kan zijn dat er in recentere versies een edge-case is dit veroorzaakt. Hoe dan ook wordt dit project niet gemaakt en getest zonder tijdzone-support, dus vandaar dat de gerelateerde issues daaruit vaak wat vaag zijn.
