### ISSUE TITLE
sorting en filtering lijkt niet goed te werken.

### ISSUE THREAD

**Issue by casperleenheer** [dsmrreader/dsmr-reader#976]
Alle laatste versies

http://192.168.x.x/api/v2/consumption/electricity?ordering=-read_at?limit=1

Geeft 25 records en in de normale tijdorder en niet het laatste record.

?limit=5&offset=5&ordering=-read_at&read_at__gte=2020-01-14

geeft resultaten van 2019...

**Comment by dennissiemensma** [comment]
Bedankt voor je melding. Ik kan het helaas niet reproduceren als ik het hier even probeer. Werkt het ook niet als je de voorgedefinieerde Postman-collectie gebruikt?
