### ISSUE TITLE
Publish current month total consumption on MQTT Topic

### ISSUE THREAD

**Issue by hiscorebob** [dsmrreader/dsmr-reader#983]
Hello,
I have not found a way to publish current month consumption to a MQTT Topic. Is there a way to achieve this? Like the same way current day consumption is already available, including costs and total kWh.

Thank you!

**Comment by dennissiemensma** [comment]
Thanks for your request. At this time there is no such MQTT topic available. I might add it later, but I can't promise it though.

**Comment by dennissiemensma** [comment]
Duplicated by #685
