### ISSUE TITLE
MQTT bericht voor overcapaciteit zonnepanelen

### ISSUE THREAD

**Issue by MORD0R** [dsmrreader/dsmr-reader#985]
Het zou handig zijn als je meer stroom opwekt dan je gebruikt. Dat hier een apart mqtt bericht van is.

Dit kan handig zijn als de saldering stopt in Nederland. Als je teveel opwerkt zou je de wasmachine bijvoorbeeld kunnen laten aangaan.

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik denk dat je dit nu ook al zelf kunt detecteren met de huidige MQTT-waardes.

Een telegram heeft de velden `electricity_currently_delivered` en `electricity_currently_returned`. Wanneer de eerste 0 is en de tweede groter dan nul, ben je aan het terugleveren en kun je aan de hand daarvan een melding of iets anders triggeren.

**Comment by MORD0R** [comment]
Dankje ik ga het proberen sry voor de late reactie.
