### ISSUE TITLE
Dag standen

### ISSUE THREAD

**Issue by Dennux** [dsmrreader/dsmr-reader#986]
Is het ook mogelijk om eenvoudig de 00:00:00 standen per dag te zien (Electricity delivered 1). 
dit zodat je de standen van de leverancier kunt controleren die ze gebruiken voor jaar afrekening bv.

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Ik zal kijken of daar iets voor mogelijk is op termijn.

**Comment by dennissiemensma** [comment]
Ik heb zojuist in #997, voor de volgende release, iets gemaakt waarmee je kunt zoeken naar een dag in de admin interface.
