### ISSUE TITLE
Bot telegram status opvragen

### ISSUE THREAD

**Issue by aroe0546** [dsmrreader/dsmr-reader#987]
Als eerst wil ik je bedanken voor het mooie stukje software die je hebt geschreven en het werkt naar alle tevredenheid. 

Ik vraag me alleen 1 ding af is het mogelijk om via telegram een commando te geven om de status op te vragen van de meter. Met bijvoorbeeld /status En dan een bericht zoals je bij notificaties krijgt

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik vind het een leuk idee alleen denk ik dat het net buiten de scope van het project valt. 
Het project ondersteunt het ophalen van data via een API en het pushen van data via MQTT. Om het behapbaar te houden, denk ik dat het beter is om het voor nu bij deze twee opties te houden. 

Ik zou het dan eerder zoeken bij iemand die er een telegram-bot voor kan maken, die simpelweg de API van DSMR-reader gebruikt om te antwoorden op queries/commands.
