### ISSUE TITLE
Feature request - Alerts genereren obv energie verbruik

### ISSUE THREAD

**Issue by ph0real** [dsmrreader/dsmr-reader#990]
Hoi Dennis,

Al een flinke tijd gelukkige gebruiker van DSMR; waarvoor dank.
Ik vroeg me vanochtend af, hoe interessant het zou zijn als er een feature bestond om een gebruiker te waarschuwen bij een bepaald energie verbruik op een gegeven moment. Een voorbeeld; ik weet dat ik na 23:00 xx energie verbruik en niet veel meer. Maar ik heb een apparaat aan laten staan en het verbruik ligt dus hoger. Met deze feature zou ik dmv triggers en alerts op de hoogte gesteld kunnen worden dat ik iets vergeten ben uit te zetten in het huis. 

Ik weet niet of je deze kant op wil met de datalogger, maar dacht, vraag het toch even.

Gr. Dennis

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik denk dat inderdaad wat te specifiek is voor dit project zelf.

Ik denk dat er al voldoende tools zijn binnen het project. Je kunt via MQTT een push krijgen van het huidige verbruik en daar een alert op maken. Of je kunt de API gebruiken en op vaste intervallen opvragen wat het verbruik is en dan een alert maken.

**Comment by ph0real** [comment]
Ah ik wist niet dat t kon met deze alternatieven. Ik zal er es induiken!
