### ISSUE TITLE
Back-up terugzetten lukt niet

### ISSUE THREAD

**Issue by Gercovo** [dsmrreader/dsmr-reader#993]
Ik heb een clean-install op mijn Raspberry Pi3 uitgevoerd en ik wil graag een backup terugzetten, maar ik krijg de melding "invalid command \N" en uiteindelijk "out of memory". Ik had altijd een back-up lopen via Dropbox. Het bestand is ingepakt wel 353MB groot.

**Comment by Eggenhuizen** [comment]
wellicht overbodig maar.. 

@Gercovo ben je je ervan bewust dat je jouw persoonlijke energie verbruiksdata nu publiekelijk beschikbaar stelt?

**Comment by Gercovo** [comment]
Ik ben mij er van bewust, maar indien het niet nodig is om deze te delen dan liever niet natuurlijk. Dus ik heb het maar even (tijdelijk) verwijderd.

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Ik denk dat je backup simpelweg te groot is geworden voor je Pi. Ik gok dat die 350 MB uitgepakt vele GB's zijn en dat die daar tegenaan loopt. 
Ik kan je sowieso aanraden om straks retentie in te stellen zodat de dataset wat kleiner is, helemaal omdat je vermoedelijk DSMR-v5 meter hebt.

Ben je in de gelegenheid om de backup zelf ergens anders uit te pakken?

**Comment by Gercovo** [comment]
Uitgepakt is het circa 2,5GB. Ik kan de back-up zeker zelf even uitpakken. Dit zal ik nu even doen.

**Comment by dennissiemensma** [comment]
Ooh dat valt me eerlijk gezegd wel mee qua grootte. In dat geval kun je het eens proberen om de import te doen met het uitgepakte bestand, met de onderste variant: https://dsmr-reader.readthedocs.io/en/latest/installation/restore.html

**Comment by Gercovo** [comment]
Helaas komt hij dan op een gegeven moment weer met "out of memory" .

**Comment by dennissiemensma** [comment]
Bedoel je bij het uitpakken of bij het importeren?

**Comment by Gercovo** [comment]
Excuus, het importeren.

**Comment by dennissiemensma** [comment]
Ik ben daar helaas zelf nog niet tegenaan gelopen en zie op Google een hoop verschillende oorzaken en oplossingen daarover. Je kunt daar nog wat van proberen, maar ik heb geen gegarandeerde fix voor je.

Het enige wat ik zelf kan bedenken is dat je de dump ergens anders probeert in te lezen waar mee geheugen beschikbaar is en DSMR-reader er dan retentie op laat toepassen. Ik kan het eventueel ook voor je proberen, maar bij voorkeur doe je het natuurlijk zelf.

**Comment by dennissiemensma** [comment]
@Gercovo ben je hier nog verder mee gekomen?

**Comment by Gercovo** [comment]
Excuus voor de late reactie. Helaas is het mij nog niet gelukt. De oplossing die jij aandraagt is daar een uitleg van te vinden?

**Comment by dennissiemensma** [comment]
Je zult daarvoor eerst een PC of laptop of server moeten hebben waar je de database op kan importeren. En anders kan ik het eventueel hier op mn PC voor je proberen.

**Comment by Gercovo** [comment]
Dat idee had ik al, is dat https://www.postgresql.org/ downloaden en installeren?

Gister dacht ik laat ik het nog eerst een keer proberen, nu kreeg ik niet de melding "out of memory", maar aan het einde gewoon "killed". Wanneer ik nu naar het dashboard ga en dan naar archief ga staat er "Geen gegevens gevonden".

**Comment by dennissiemensma** [comment]
Wat je kunt doen is de dataset verkleinen. Je kunt daarvoor ofwel de backup ergens anders inladen en dan handmatig oude metingen (niet de dagtotalen) verwijderen. 
Ofwel je kunt de backup ergens anders inladen en dan vervolgens DSMR-reader er (tijdelijk) tegen laten praten en die de opschoning laten doen. Het voordeel van de laatste is dat DSMR-reader altijd van elk uur twee metingen bewaart. Maar als je daar geen waarde aan hecht is het eerste makkelijker.

Als dat gedaan is kun je een nieuwe DB-export doen daar. Je hebt dan een veel kleinere DB-backup. Deze kun je dan naar verwachting zonder issues inladen op je Pi.
