### ISSUE TITLE
tarieven teruglevering

### ISSUE THREAD

**Issue by alexswart** [dsmrreader/dsmr-reader#995]
ik weet niet of het technisch mogelijk is maar zou het ook kunnen om bij de tarieven dubbele tarieven voor teruglevering in te vullen?
op dit moment kunnen we in Nederland nog salderen dus tot je huidige afname bij de netbeheerder kan je voor hetzelfde tarief terugleveren.
kom je met je levering boven je huidige verbruik dan krijg je nog maar een cent of 8 terug per kW

ik heb nu bij het tarief de teruglevering vergoeding gelijk aan de afname vergoeding maar zodra ik meer terug ga leveren dan klopt het bedrag niet meer

**Comment by dennissiemensma** [comment]
Bedankt voor je verzoek. Ik heb hier eerder naar gekeken, maar het bleek vrij complex om het naadloos te maken. 
Er zijn aantal factoren zoals de begin-/einddatum van het contract (vermoed ik?) en dat het verbruik dus over meer dan 1 dag gesaldeerd kan worden. Dat maakt berekeningen erg lastig, gezien je je verbruik met terugwerkende kracht kan salderen. Als je vandaag een overschot hebt, kun je je verbruik van gisteren daarmee wegsalderen. 
Dit project berekent dagelijks het verbruik en schrijft dat weg als 'definitieve' waarde, dus dat zit al in de weg. De prijzen binnen DSMR-reader warenoverigens  ooit bedoeld als grove een indicatie voor jezelf zodat je een gevoel hebt wat een dag 'kost' (of oplevert).
Mocht de salderingsregeling ooit versimpelen, dan kan ik er wel opnieuw naar kijken.
